<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Wed, 18 Mar 2015 14:50:10 +0000
// --------------------------------------------------------------------------------

$l['nav_announcements'] = 'Fórum közlemény';
$l['announcements'] = 'Közlemény';
$l['forum_announcement'] = 'Fórum közlemény: {1}';
$l['error_invalidannouncement'] = 'A közlemény érvénytelen.';
$l['announcement_edit'] = 'Közlemény szerkesztése';
$l['announcement_qdelete'] = 'Közlemény törlése';
$l['announcement_quickdelete_confirm'] = 'Biztos vagy benne, hogy szeretnéd törölni ezt a közleményt?';
