<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://community.mybb.com/mods.php?action=view&pid=441
// Compatible version of MyBB : 1807 Béta
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 13 Mar 2016 09:56:57 +0000
// --------------------------------------------------------------------------------

$l['archive_fullversion'] = 'Teljes verzió:';
$l['archive_replies'] = 'Válaszok';
$l['archive_reply'] = 'Válasz';
$l['archive_pages'] = 'Oldalak:';
$l['archive_note'] = 'Jelenleg könnyített verzióban tekinted meg a fórumot. <a href="{1}">Megtekintés teljes verzióban</a> teljes formázással és grafikai elemekkel.';
$l['archive_nopermission'] = 'Nincs engedélyed ehhez a területhez.';
$l['error_nothreads'] = 'Jelenleg nincs téma ebben a fórumban.';
$l['error_unapproved_thread'] = 'Ez a téma nem lett elfogadva. Kérlek, <a href="{1}">tekintsd meg teljes verzióban</a>, hogy megnézd ennek a témának a tartalmát.';
$l['archive_not_found'] = '<h1>404 Nem található</h1><p>A keresett dokumentum nem található a szerveren.</p>';
$l['error_mustlogin'] = 'A fórum használatához be kell jelentkezni.';
$l['error_nopermission'] = 'Nincs engedélyed megtekinteni a témákat ebben a fórumban.';
