<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 15 Mar 2015 13:31:19 +0000
// --------------------------------------------------------------------------------

$l['contact'] = 'Kapcsolat.';
$l['contact_no_message'] = 'Nem adtad meg a küldendő üzenet szövegét.';
$l['contact_no_subject'] = 'Töltsd ki a tárgy mezőt.';
$l['contact_no_email'] = 'Egy érvényes email címet kell megadnod.';
$l['contact_success_message'] = 'Az üzeneted sikeresen elküldve az Adminisztrátornak.';
$l['contact_subject'] = 'Tárgy';
$l['contact_subject_desc'] = 'Az üzeneted témája röviden megfogalmazva.';
$l['contact_message'] = 'Üzenet';
$l['contact_message_desc'] = 'Ide írhatod le az észrevételedet vagy problémádat részletesen.';
$l['contact_email'] = 'Email';
$l['contact_email_desc'] = 'Add meg az email címedet, hogy fel tudjuk venni veled a kapcsolatot.';
$l['contact_send'] = 'Küld';
$l['image_verification'] = 'Kép ellenőrzés';
$l['verification_note'] = 'Írd be a képen látható szöveget az alább lévő szöveg mezőbe. Ez megakadályozza az automatikus vagy véletlen üzenetküldést.';
$l['verification_subnote'] = '(kis- és nagybetű érzéketlen)';
$l['invalid_captcha'] = 'A beírt képi ellenőrző kód hibás volt. Kérlek add meg a kódot pontosan, ahogyan az a képen látszik.';
$l['subject_too_long'] = 'A tárgy túl hosszú. A tárgynak rövidebbnek kell lennie, mint {1} karakter (jelenleg beírt {2}).';
$l['message_too_short'] = 'Az üzenet túl rövid. Az üzenetnek hosszabbnak kell lennie, mint {1} karakter (jelenleg beírt {2}).';
$l['message_too_long'] = 'Az üzenet túl hosszú. Az üzenetnek rövidebbnek kell lennie, mint {1} karakter (jelenleg beírt {2}).';
$l['error_stop_forum_spam_spammer'] = 'Elnézést kérünk, {1}  egyezik egy ismert spammerrel, ezért a kapcsolati űrlapod benyújtása  blokkolva lett.';
$l['error_stop_forum_spam_fetching'] = 'Elnézést kérünk, valamilyen hiba történt az üzeneted ellenőrzésekor a spammer adatbázisban. Valószínűleg az adatbázis nem elérhető. Kérlek próbáld meg később.';
