<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sat, 07 Mar 2015 12:43:11 +0000
// --------------------------------------------------------------------------------

$l['warnings_reached_max_warnings_day'] = 'Nem tudsz figyelmeztetni senkit, mivel elérted az egy nap kiosztható figyelmeztetési limitedet.<br /><br />Általad maximálisan kiosztható figyelmeztetések száma naponta {1}"';
$l['warnings_error_invalid_user'] = 'A kiválasztott felhasználó nem létezik.';
$l['warnings_error_invalid_post'] = 'A kiválasztott hozzászólás nem létezik.';
$l['warnings_error_cannot_warn_self'] = 'Nem adhatsz magadnak saját figyelmeztetési szintet.';
$l['warnings_error_user_reached_max_warning'] = 'Ez a felhasználó nem figyelmeztethető, mivel már elérte a maximális figyelmeztetési szintet.';
$l['warnings_error_no_note'] = 'Nem adhatsz semmilyen adminisztratív megjegyzéseket ehhez a figyelmeztetéshez.';
$l['warnings_error_invalid_type'] = 'Érvénytelen figyelmeztetési típust választottál.';
$l['warnings_error_cant_custom_warn'] = 'Nincs engedélyed egyéni figyelmeztetések adni a felhasználókhoz.';
$l['warnings_error_no_custom_reason'] = 'Nem adtad meg az egyéni figyelmeztetésed okát.';
$l['warnings_error_invalid_custom_points'] = 'Nem megfelelő pontszámot adtál meg ehhez a felhasználói figyelmeztetési szinthez. Egy szám értéket kell megadnod, amely nagyobb mint 0, de nem lehet nagyobb mint {1}.';
$l['warnings_error_invalid_expires_period'] = 'Érvénytelen lejárati típust adtál meg.';
