<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian (Magyar)
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://community.mybb.com/mods.php?action=view&pid=441
// Compatible version of MyBB : 1810 Béta
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sat, 14 Jan 2017 09:01:49 +0000
// --------------------------------------------------------------------------------

$l['userdata_missing_username'] = 'Nem adtál meg felhasználónevet. Kérlek válassz egyet.';
$l['userdata_banned_username'] = 'Az általad megadott felhasználónév nem megfelelő. Kérlek adj meg egy másikat.';
$l['userdata_bad_characters_username'] = 'A megadott felhasználónév tiltott karaktert tartalmaz. Kérlek adj meg egy másikat.';
$l['userdata_invalid_username_length'] = 'A megadott felhasználónév nem megfelelő hosszúságú. Kérlek adj meg egy nevet {1} és {2} karakter közt.';
$l['userdata_invalid_usertitle_length'] = 'A megadott becenév nem megfelelő hosszúságú. Kérlek adj meg egy nevet, amely nem hosszabb, mint {1} karakter.';
$l['userdata_username_exists'] = 'A megadott felhasználónév már foglalt. Kérlek válassz egy másikat.';
$l['userdata_invalid_password_length'] = 'A megadott jelszó nem megfelelő hosszúságú. Kérlek adj meg egy jelszót {1} és {2} karakter közt.';
$l['userdata_no_complex_characters'] = 'Az általad megadott jelszó nem megfelelő bonyolultságú. Kérlek adj meg egy legalább {1} karakter hosszú, nagybetűt, kisbetűt és számot is tartalmazó jelszót.';
$l['userdata_passwords_dont_match'] = 'A megerősítésként megadott jelszó nem egyezik az eredetivel. Kérlek javítsd ki a hibát.';
$l['userdata_bad_password_security'] = 'A jelszó amit megadtál ugyanaz mint a felhasználóneved vagy az email címed. Kérlek adj meg egy erősebb/biztonságosabb jelszót.';
$l['userdata_missing_email'] = 'Nem adtál meg email címet. Adj meg egyet.';
$l['userdata_invalid_email_format'] = 'A megadott email cím nem valós. Kérlek valós email címet adj meg.';
$l['userdata_emails_dont_match'] = 'A megerősítésként megadott email cím nem egyezik meg az eredetivel. Kérlek javítsd ki a hibát.';
$l['userdata_banned_email'] = 'Az általad megadott email cím tiltott. Kérlek adj meg másik email címet.';
$l['userdata_email_already_in_use'] = 'A megadott email címet már használja egy tagunk. Kérlek adj meg egy másik email címet.';
$l['userdata_dob_required'] = 'Nem választottad ki a születési dátumodat. A folytatáshoz kérlek add meg a születési idődet. (Később a születésnapodat el tudod rejteni más felhasználók elől.)';
$l['userdata_invalid_website'] = 'A megadott weboldal nem létezik. Kérlek valós weboldalt adj meg, vagy hagyd üresen a mezőt.';
$l['userdata_invalid_icq_number'] = 'A megadott ICQ szám nem megfelelő. Kérlek valós ICQ címet adj meg, vagy hagyd üresen a mezőt.';
$l['userdata_invalid_birthday'] = 'A megadott születésnap nem megfelelő. Kérlek valós születésnapot adj meg, vagy hagyd üresen a mezőt.';
$l['userdata_invalid_birthday_coppa'] = 'Hogy igazold a korodat, kérlek add meg az évet, amiben születtél. Elrejtheted a korodat és a születésnapodat a profil opcióknál.';
$l['userdata_invalid_birthday_coppa2'] = 'Legalább 13 évesnek kell lenned, hogy tag legyél. Kérlek lépj kapcsolatba az Adminisztrátorral.';
$l['userdata_invalid_birthday_privacy'] = 'Válassz egy érvényes születésnap adatvédelmi opciót.';
$l['userdata_invalid_referrer'] = 'A megadott ajánló nem megfelelő. Kérlek valós ajánlót adj meg, vagy hagyd üresen a mezőt.';
$l['userdata_invalid_language'] = 'A kiválasztott nyelv nem létezik. Kérlek valós nyelvet adj meg.';
$l['userdata_missing_returndate'] = 'A visszatérés dátuma nem megfelelő. Minden mezőt kitöltöttél?';
$l['userdata_missing_required_profile_field'] = 'Nem adtál meg "{1}" mezőt. Kérlek töltsd ki a mezőket vagy válassz megfelelő értéket.';
$l['userdata_bad_profile_field_value'] = 'Nem történt érvényes kiválasztás "{1}" mezőben. Kérlek javítsd ki.';
$l['userdata_bad_profile_field_values'] = 'Nem választottál érvényes opciót a "{1}" mezőből. Kérlek válassz egyet a felsorolt lehetőségekből.';
$l['userdata_max_limit_reached'] = 'Érvénytelen karakterszám megadás "{1}" mezőben. Töltsd ki ezt a mezőt több mint {2} karakterrel.';
$l['userdata_invalid_checkfield'] = 'A fórum úgy érzékelte, hogy ez az űrlap egy spam által lett elküldve. Ha ez mégsem így volt, kérlek lépj kapcsolatba egy adminisztrátorral.';
$l['userdata_invalid_postnum'] = 'A hozzászólás száma érvénytelen. Kérlek írj be egy érvényes hozzászólás számot, vagy hagyd üresen a mezőt.';
$l['userdata_invalid_threadnum'] = 'A téma szám(olás) amit megadtál érvénytelen. Kérlek adj meg egy érvényes téma számot vagy hagyd üresen a mezőt.';
$l['userdata_invalid_style'] = 'A kiválasztott stílus érvénytelen. Kérlek válassz egy érvényes stílust.';
$l['userdata_too_many_sig_images'] = 'Sajnáljuk, nem tudjuk frissíteni az aláírásodat, mert túl sok képet tartalmaz. Kérlek távolíts el néhányat az aláírásodból a folytatáshoz.';
$l['userdata_too_many_sig_images2'] = '<strong>Megjegyzés:</strong> A képek maximális megengedett száma az aláírásokban {1}. ';
$l['userdata_sig_too_long'] = 'Nem tudod frissíteni az aláírásodat, mert túl hosszú. Az aláírások maximális {1} karakter.';
$l['userdata_sig_remove_chars_plural'] = 'Kérlek törölj {1} karkatert és próbáld újra.';
$l['userdata_sig_remove_chars_singular'] = 'Kérlek törölj 1 karkatert és próbáld újra.';
