<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 15 Mar 2015 13:33:45 +0000
// --------------------------------------------------------------------------------

$l['eventdata_missing_name'] = 'Az esemény neve hiányzik. Kérlek add meg az esemény nevét.';
$l['eventdata_missing_description'] = 'Az esemény leírása hiányzik. Kérlek adj leírást az eseményhez.';
$l['eventdata_invalid_start_date'] = 'Az esemény kezdetének dátuma érvénytelen. Győződj meg róla, hogy a napot, hónapot, és az évet helyesen tüntetted-e fel.';
$l['eventdata_invalid_start_year'] = 'Eseményeket csak az elkövetkezendő 5 évre lehet létrehozni. Válassz egy ésszerűbb kezdőévet a listából.';
$l['eventdata_invalid_start_month'] = 'A kezdő hónap nem érvényes. Adj meg egy érvényes kezdő hónapot.';
$l['eventdata_invalid_end_date'] = 'Az esemény záró dátuma érvénytelen. Győződj meg róla, hogy a napot, hónapot, és az évet helyesen tüntetted-e fel.';
$l['eventdata_invalid_end_year'] = 'Eseményeket csak az elkövetkezendő 5 évre lehet létrehozni. Válassz egy ésszerűbb záróévet a listából.';
$l['eventdata_invalid_end_month'] = 'A záró hónap nem érvényes. Válassz egy érvényes hónapot.';
$l['eventdata_invalid_end_day'] = 'A záró nap nem érvényes. Valószínűleg a választott nap nagyobb mint a hónap napjai.';
$l['eventdata_cant_specify_one_time'] = 'Ha az eseményhez megadsz egy kezdő időpontot, akkor egy záró időpontot is meg kell adnod.';
$l['eventdata_start_time_invalid'] = 'A kezdő időpont érvénytelen. Példák érvényes időpontokra: 12am, 12:01am, 00:01.';
$l['eventdata_end_time_invalid'] = 'A záró időpont érvénytelen. Példák érvényes időpontokra: 12am, 12:01am, 00:01.';
$l['eventdata_invalid_timezone'] = 'A választott időzóna érvénytelen.';
$l['eventdata_end_in_past'] = 'A záró dátumot vagy időpontot az esemény kezdete elé helyezted.';
$l['eventdata_only_ranged_events_repeat'] = 'Csak időszakos események (események kezdő és záró időponttal) ismétlődhetnek.';
$l['eventdata_invalid_repeat_day_interval'] = 'Érvénytelen naponkénti ismétlődés intervallumot adtál meg.';
$l['eventdata_invalid_repeat_week_interval'] = 'Érvénytelen hetenkénti ismétlődés intervallumot adtál meg.';
$l['eventdata_invalid_repeat_weekly_days'] = 'Nem választottál napot az esemény megjelenésére.';
$l['eventdata_invalid_repeat_month_interval'] = 'Érvénytelen havonkénti ismétlődés intervallumot adtál meg.';
$l['eventdata_invalid_repeat_year_interval'] = 'Érvénytelen évenkénti ismétlődés intervallumot adtál meg.';
$l['eventdata_event_wont_occur'] = 'Az előbb megadott beállítások alapján ez az esemény nem fog megjelenni.';
$l['eventdata_no_permission_private_event'] = 'Nem rendelkezel jogosultsággal privát esemény hozzáadásához.';
