<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sat, 07 Mar 2015 12:42:03 +0000
// --------------------------------------------------------------------------------

$l['logindata_invalidpwordusername'] = 'Érvénytelen felhasználónév/jelszó kombinációt adtál meg. <br /><br />Ha elfelejtetted a jelszavadat <a href="member.php?action=lostpw">itt</a> kérhetsz egy másikat.';
$l['logindata_invalidpwordusernameemail'] = 'Érvénytelen email/jelszó kombinációt adtál meg. <br /><br />Ha elfelejtetted a jelszavadat <a href="member.php?action=lostpw">itt</a> kérhetsz egy másikat.';
$l['logindata_invalidpwordusernamecombo'] = 'Érvénytelen felhasználónév/jelszó vagy email/jelszó kombinációt adtál meg. <br /><br />Ha elfelejtetted a jelszavadat <a href="member.php?action=lostpw">itt</a>  kérhetsz egy másikat.';
$l['logindata_regimageinvalid'] = 'A képi ellenőrző kód, amelyet megadtál érvénytelen/helytelen volt. Kérlek add meg a kódot pontosan, ahogyan az a képen látszik.';
$l['logindata_regimagerequired'] = 'A belépés folytatásához töltsd ki a képi ellenőrző kódot. Kérlek add meg a kódot pontosan, ahogyan az a képen látszik.';
