<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sat, 07 Mar 2015 12:42:42 +0000
// --------------------------------------------------------------------------------

$l['pmdata_too_long_subject'] = 'Az üzenet tárgya túl hosszú. Kérlek módosítsd.';
$l['pmdata_code_no_subject'] = '[nincs tárgy]';
$l['pmdata_missing_subject'] = 'Nem adtad meg az üzeneted tárgyát.';
$l['pmdata_missing_message'] = 'Nem írtál üzenetet. Kérlek írd meg.';
$l['pmdata_invalid_recipients'] = 'Egy vagy több általad megadott címzett nem létezik. Érvénytelen címzettek: {1}';
$l['pmdata_no_recipients'] = 'Nem adtál meg címzettet. Legalább egy felhasználó nevét meg kell adnod.';
$l['pmdata_too_many_recipients'] = 'Egyszerre csak {1} felhasználónak küldhetsz privát üzenetet.';
$l['pmdata_recipient_is_ignoring'] = '{1} számára nem küldhetsz üzenetet, mert a mellőzött listáján vagy.';
$l['pmdata_recipient_has_buddy_only'] = 'Nem küldhetsz üzenetet {1} felhasználónak, mert nem vagy rajta a barátok listáján.';
$l['pmdata_recipient_pms_disabled'] = '{1} kikapcsolta a privát üzenet küldőjét. Ennek a felhasználónak nem küldhetsz privát üzenetet.';
$l['pmdata_recipient_reached_quota'] = 'Az üzenetet nem sikerült elküldeni, mert {1} postafiókja megtelt.';
$l['pmdata_pm_flooding'] = 'Túl gyorsan próbálsz üzenetet küldeni. Kérlek várj {1} másodpercet.';
$l['pmdata_pm_flooding_one_second'] = 'Túl gyorsan próbálsz üzenetet küldeni. Kérlek várj 1 másodpercet.';
