<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sat, 07 Mar 2015 12:42:58 +0000
// --------------------------------------------------------------------------------

$l['postdata_invalid_user_id'] = 'A felhasználó nem létezik. Valós felhasználót adj meg.';
$l['postdata_firstpost_no_subject'] = 'Nem lett megadva a téma tárgya. Kérlek adj meg tárgyat.';
$l['postdata_missing_subject'] = 'Hiányzik a tárgy. Kérlek add meg.';
$l['postdata_missing_message'] = 'Hiányzik az üzenet. Kérlek add meg.';
$l['postdata_message_too_long'] = 'Az üzenet túl hosszú. Kérlek írj {1} karakternél rövidebb üzenetet. (jelenleg {2})';
$l['postdata_message_too_short'] = 'Az üzenet túl rövid. Kérlek írj {1} karakternél hosszabb üzenetet.';
$l['postdata_subject_too_long'] = 'A tárgy túl hosszú. Kérlek írj 85 karakternél rövidebb tárgyat (jelenleg {1}).';
$l['postdata_banned_username'] = 'A megadott felhasználónév nem regisztrálható. Válassz másikat.';
$l['postdata_bad_characters_username'] = 'A megadott felhasználónév nem megengedett karaktereket tartalmaz. Válassz másikat.';
$l['postdata_invalid_username_length'] = 'A megadott felhasználónév hossza nem megfelelő. {1} és {2} karakter között kell lennie a hosszának.';
$l['postdata_username_exists'] = 'A felhasználónév amit megadtál már létezik. Kérlek adj meg egy másik felhasználónevet.';
$l['postdata_post_flooding'] = 'Túl rövid idő telt el az előző üzenetedtől. Kérlek várj {1} másodpercet.';
$l['postdata_post_flooding_one_second'] = 'Túl rövid idő telt el az előző üzenetedtől. Kérlek várj néhány másodpercet.';
$l['postdata_too_many_images'] = 'Az üzeneted {1} képet tartalmaz, de csak {2} kép engedélyezett egy üzenetben. Kérlek módosítsd az üzeneted.';
$l['postdata_too_many_videos'] = 'Az üzeneted {1} videót tartalmaz, de csak {2} videó engedélyezett egy üzenetben. Kérlek módosítsd az üzeneted.';
$l['postdata_invalid_prefix'] = 'A választott előtag érvénytelen. Válassz egy érvényes előtagot.';
$l['postdata_require_prefix'] = 'Ehhez a fórumhoz szükséges beállítani egy előtagot. Kérlek válassz egy érvényes előtagot.';
$l['thread_closed'] = 'Téma lezárva';
$l['thread_opened'] = 'téma megnyitva';
$l['thread_stuck'] = 'Téma kiemelve';
$l['thread_unstuck'] = 'Téma kiemelés megszüntetése';
