<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sat, 07 Mar 2015 12:43:19 +0000
// --------------------------------------------------------------------------------

$l['nav_editpost'] = 'Üzenet módosítása';
$l['edit_post'] = 'Ennek az üzenetnek a módosítása';
$l['delete_post'] = 'Üzenet törlése';
$l['delete_q'] = 'Töröl?';
$l['delete_1'] = 'Az üzenet törléséhez rakj pipát a \'Töröl?\' elé és jobb oldalon kattints a törlés gombra.';
$l['delete_2'] = '<b>Megjegyzés:</b> Ha ez az üzenet az első a témában az egész téma törlődni fog az üzenet törlésével.';
$l['subject'] = 'Tárgy';
$l['your_message'] = 'Üzeneted';
$l['post_options'] = 'Üzenet beállítások:';
$l['editreason'] = 'Szerkesztés oka:';
$l['options_sig'] = '<b>Aláírás:</b> beillesztheted aláírásod. (csak regisztrált felhasználók)';
$l['options_emailnotify'] = '<strong>Email értesítés</strong>: ha válasz érkezik, e-mailban kérek értesítést. (csak regisztrált felhasználók)';
$l['options_disablesmilies'] = '<b>Hangulatjelek tiltása</b>: megtiltod az üzenetben a hangulatjelek megjelenését.';
$l['preview_post'] = 'Előnézet';
$l['update_post'] = 'Frissít';
$l['poll'] = 'Szavazás:';
$l['poll_desc'] = 'Szavazást csatolhatsz a témához.';
$l['poll_check'] = 'Szavazást csatolok';
$l['num_options'] = 'Válasz lehetőségek száma:';
$l['max_options'] = '(Maximum: {1})';
$l['delete_now'] = 'Törlés';
$l['edit_time_limit'] = 'Elnézést, de nem módosíthatod az üzenetet. Az Adminisztrátor azt állította be, hogy az üzeneteket csak {1} percig lehet módosítani.';
$l['no_prefix'] = 'Nincs előtag';
$l['redirect_nodelete'] = 'A hozzászólás nem lett törölve, mert nem erősítetted meg a törlést.';
$l['redirect_norestore'] = 'a hozzászólás nem lett visszaállítva, mert nem lett bejelölve a "Visszaállítás" jelölőnégyzet.';
$l['redirect_postedited'] = 'A hozzászólás szerkesztve.<br />';
$l['redirect_postedited_redirect'] = 'Visszairányítunk a témához.';
$l['redirect_postedited_poll'] = 'A hozzászólás szerkesztve.<br />Mivel bejelölted a szavazás létrehozását, ezért átirányítunk a szavazás létrehozása oldalra.';
$l['error_invalidpost'] = 'Elnézést, érvénytelen címet adtál meg. Győződj meg róla, hogy a hozzászólás létezik és próbáld újra.';
$l['redirect_threaddeleted'] = 'A téma törölve.<br />Visszairányítunk a fórumhoz.';
$l['redirect_postdeleted'] = 'A hozzászólás törölve.<br />Visszairányítunk a témához.';
$l['redirect_threadrestored'] = 'Köszönjük, a téma visszaállítva.<br />Most visszairányítunk a fórumra.';
$l['redirect_postrestored'] = 'Köszönjük, a hozzászólás visszaállítva.<br />Most visszairányítunk a fórumra.';
$l['redirect_threadclosed'] = 'Nem módosíthatod a hozzászólásokat ebben a témában, mert azt egy moderátor lezárta.';
$l['redirect_post_moderation'] = 'Minden hozzászólás módosítást először egy adminisztrátornak jóvá kell hagynia. Most visszairányítunk a témához.';
$l['redirect_thread_moderation'] = 'Minden téma módosítást először egy adminisztrátornak jóvá kell hagynia. Most visszairányítunk a fórum kezdőlaphoz.';
$l['error_already_delete'] = 'Sajnáljuk, de ezt a hozzászólást már törölték.';
$l['thread_deleted'] = 'Véglegesen törölt téma';
$l['post_deleted'] = 'Véglegesen törölt üzenet';
$l['thread_soft_deleted'] = 'Ideiglenesen törölt téma';
$l['post_soft_deleted'] = 'Ideiglenesen törölt hozzászólás';
$l['thread_restored'] = 'Visszaállított téma';
$l['post_restored'] = 'Visszaállított hozzászólás';
$l['error_already_deleted'] = 'A kiválasztott hozzászólást már törölték.';
