<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian (Magyar)
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://community.mybb.com/mods.php?action=view&pid=441
// Compatible version of MyBB : 1810 Béta
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sat, 14 Jan 2017 09:03:11 +0000
// --------------------------------------------------------------------------------

$l['post_thread'] = 'Új téma';
$l['moderated_by'] = 'Moderátor:';
$l['nothreads'] = 'Elnézést, de jelenleg nincs téma ebben a fórumban a megadott dátum és idő korlátozás opciókkal.';
$l['search_forum'] = 'Keresés ebben a fórumban:';
$l['thread'] = 'Téma';
$l['author'] = 'Szerző';
$l['replies'] = 'Válaszok';
$l['views'] = 'Megtekintések';
$l['lastpost'] = 'Utolsó üzenet';
$l['rating'] = 'Értékelés';
$l['prefix'] = 'Előtag:';
$l['prefix_all'] = 'Előtag: Bármelyik/Nincs előtag';
$l['prefix_any'] = 'Előtag: Bármelyik előtag';
$l['prefix_none'] = 'Előtag: Nincs előtag';
$l['markforum_read'] = 'Megjelölés olvasottként';
$l['subscribe_forum'] = 'Feliratkozás a fórumra';
$l['unsubscribe_forum'] = 'Leiratkozás a fórumról';
$l['clear_stored_password'] = 'Tárolt fórum jelszó törlése';
$l['sort_by_subject'] = 'Rendezés: Téma szerint';
$l['sort_by_lastpost'] = 'Rendezés: Utolsó hozzászólás szerint';
$l['sort_by_starter'] = 'Rendezés: Szerző szerint';
$l['sort_by_started'] = 'Rendezés: Létrehozás ideje szerint';
$l['sort_by_rating'] = 'Rendezés: Értékelés szerint';
$l['sort_by_replies'] = 'Rendezés: Válaszok szerint';
$l['sort_by_views'] = 'Rendezés: Megtekintések száma szerint';
$l['sort_order_asc'] = 'Sorrend: Növekvő';
$l['sort_order_desc'] = 'Sorrend: Csökkenő';
$l['datelimit_1day'] = 'mától';
$l['datelimit_5days'] = 'utolsó 5 nap';
$l['datelimit_10days'] = 'utolsó 10 nap';
$l['datelimit_20days'] = 'utolsó 20 nap';
$l['datelimit_50days'] = 'utolsó 50 nap';
$l['datelimit_75days'] = 'utolsó 75 nap';
$l['datelimit_100days'] = 'utolsó 100 nap';
$l['datelimit_lastyear'] = 'utolsó 1 év';
$l['datelimit_beginning'] = 'bármikor';
$l['new_thread'] = 'Új üzenetek';
$l['new_hot_thread'] = 'Kedvelt téma (Új)';
$l['posts_by_you'] = 'A te üzeneted tartalmazza';
$l['no_new_thread'] = 'Nincsenek új üzenetek';
$l['hot_thread'] = 'Kedvelt téma (Nincs új)';
$l['locked_thread'] = 'Lezárt téma';
$l['goto_first_unread'] = 'Menjünk az első olvasatlan üzenetre';
$l['pages'] = 'Oldalak:';
$l['pages_last'] = 'utolsó';
$l['users_browsing_forum'] = 'Jelenlevő felhasználó(k) ebben a fórumban:';
$l['users_browsing_forum_guests'] = '{1} Vendég';
$l['users_browsing_forum_invis'] = '{1} Rejtett felhasználó';
$l['delayed_moderation'] = 'Késleltetett moderáció';
$l['inline_thread_moderation'] = 'Moderáció:';
$l['close_threads'] = 'Témák lezárása';
$l['open_threads'] = 'Témák megnyitása';
$l['stick_threads'] = 'Témák kiemelése';
$l['unstick_threads'] = 'Témák kiemelésének megszüntetése';
$l['soft_delete_threads'] = 'Témák ideiglenes törlése';
$l['restore_threads'] = 'Témák visszaállítás';
$l['delete_threads'] = 'Témák törlése';
$l['move_threads'] = 'Témák áthelyezése';
$l['approve_threads'] = 'Témák jóváhagyása';
$l['unapprove_threads'] = 'Témák elutasítása';
$l['inline_go'] = 'Tovább';
$l['clear'] = 'Mégse';
$l['sub_forums_in'] = '\'{1}\' kategória fórumai';
$l['forum_rules'] = '{1} - Szabályzat';
$l['subforums'] = '<strong>Alfórum(ok):</strong>';
$l['asc'] = 'növekvő';
$l['desc'] = 'csökkenő';
$l['forum_announcements'] = 'Közlemények';
$l['sticky_threads'] = 'Kiemelt témák';
$l['normal_threads'] = 'Normál témák';
$l['icon_dot'] = 'A téma a te hozzászólásaidat is tartalmazza. ';
$l['icon_no_new'] = 'Nincsenek új hozzászólások.';
$l['icon_new'] = 'Új hozzászólások.';
$l['icon_hot'] = 'Népszerű téma.';
$l['icon_lock'] = 'Lezárt téma.';
$l['attachment_count'] = 'Ez a téma 1 csatolást tartalmaz.';
$l['attachment_count_multiple'] = 'Ez a téma {1} csatolást tartalmaz.';
$l['rss_discovery_forum'] = 'Legfrissebb témák itt: {1}';
$l['forum_unapproved_posts_count'] = 'Ebben a fórumban jelenleg {1} hozzászólás várakozik jóváhagyásra.';
$l['forum_unapproved_post_count'] = 'Ebben a fórumban jelenleg 1 hozzászólás várakozik jóváhagyásra.';
$l['forum_unapproved_threads_count'] = 'Ebben a fórumban jelenleg {1} téma várakozik jóváhagyásra.';
$l['forum_unapproved_thread_count'] = 'Ebben a fórumban jelenleg 1 téma várakozik jóváhagyásra.';
$l['thread_unapproved_posts_count'] = 'Ebben a témában jelenleg {1} hozzászólás várakozik jóváhagyásra.';
$l['thread_unapproved_post_count'] = 'Ebben a témában jelenleg 1 hozzászólás várakozik jóváhagyásra.';
$l['page_selected'] = 'Összes, <strong>{1}</strong> téma a lapon kiválasztva.';
$l['all_selected'] = 'Összes, <strong>{1}</strong> téma a lapon kiválasztva.';
$l['select_all'] = 'Összes, <strong>{1}</strong> téma kiválasztása ebben a fórumban.';
$l['clear_selection'] = 'Kiválasztás törlése.';
$l['error_containsnoforums'] = 'Elnézést, de az általad jelenleg nézett téma nem tartalmaz szülőfórumokat.';
$l['inline_edit_description'] = '(Kattints és tartsd lenyomva a szerkesztéshez)';
$l['nopermission'] = 'Elnézést, de nincs engedélyed megtekinteni a témákat ebben a fórumban.';
$l['deleted_thread'] = 'Téma törlése';
