<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sat, 07 Mar 2015 12:59:17 +0000
// --------------------------------------------------------------------------------

$l['hello'] = 'Helló Világ!';
$l['hello_add'] = 'Hozzáadás';
$l['hello_add_message'] = 'Üzenet hozzáadása';
$l['hello_empty'] = 'Nem találhatóak üzenetek.';
$l['hello_message_empty'] = 'Az üzenet nem lehet üres.';
$l['hello_done'] = 'Az új üzenet sikeresen hozzáadva.';
