<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Wed, 11 Mar 2015 17:24:21 +0000
// --------------------------------------------------------------------------------

$l['s1_name'] = 'Felhasználó funkciók';
$l['s1_desc'] = 'Alapvető információk a fórum használatához.';
$l['s2_name'] = 'Üzenetek';
$l['s2_desc'] = 'Üzenetek, válaszok, és alapvető fórum funkciók.';
