<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Wed, 11 Mar 2015 17:25:00 +0000
// --------------------------------------------------------------------------------

$l['boardstats'] = 'Statisztika';
$l['new_posts'] = 'A fórumban új üzenetek vannak';
$l['no_new_posts'] = 'A fórumban nincsenek új üzenetek';
$l['forum_locked'] = 'A fórum lezárva';
$l['forum_unapproved_posts_count'] = 'Jelenleg {1} jóváhagyásra váró hozzászólás van a fórumon.';
$l['forum_unapproved_post_count'] = 'Jelenleg 1 jóváhagyásra váró hozzászólás van a fórumon.';
$l['forum_unapproved_threads_count'] = 'Jelenleg {1} jóváhagyásra váró téma van a fórumon.';
$l['forum_unapproved_thread_count'] = 'Jelenleg 1 jóváhagyásra váró téma van a fórumon.';
$l['markread'] = 'Fórumok megjelölése olvasottként';
$l['forumteam'] = 'Fórum üzemeltetői';
$l['forumstats'] = 'Fórum statisztika';
$l['todays_birthdays'] = 'Mai születésnaposak';
$l['birthdayhidden'] = 'Rejtett';
$l['quick_login'] = 'Gyors belépés:';
$l['index_logout'] = 'Kilépés';
$l['private_messages'] = 'Privát üzenetek';
$l['pms_new'] = '{1} új üzeneted van az utolsó bejelentkezésed óta.';
$l['pms_unread_total'] = '({1} olvasatlan üzeneted és {2} üzeneted van a mappáidban.)';
$l['stats_posts_threads'] = 'Felhasználóink eddig összesen {1} üzenetet írtak {2} témában.';
$l['stats_numusers'] = 'Jelenleg összesen {1} regisztrált felhasználónk van.';
$l['stats_newestuser'] = 'Legújabb tagunk: <b>{1}</b>';
$l['stats_mostonline'] = 'Legtöbb tagunk egyszerre jelen {1} fő, {2} {3}-kor volt itt.';
$l['whos_online'] = 'Ki van jelen';
$l['complete_list'] = 'Teljes lista';
$l['online_online_plural'] = 'felhasználó';
$l['online_online_singular'] = 'felhasználó';
$l['online_member_plural'] = 'tag';
$l['online_member_singular'] = 'tag';
$l['online_anon_plural'] = ' '; /*1 felhasználó volt aktív az utolsó 15 percben (1 tag, ebből 0 $l['online_anon_plural'] = ' ' rejtett, és 0 vendég).
*/
$l['online_anon_singular'] = ' is';
$l['online_guest_plural'] = 'vendég';
$l['online_guest_singular'] = 'vendég';
$l['online_note'] = '{1} {2} volt aktív az utolsó {3} percben ({4} {5}, ebből {6} {7} rejtett, és {8} {9}).';
$l['subforums'] = '<strong>Alfórumok:</strong>';
