<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Wed, 11 Mar 2015 17:35:08 +0000
// --------------------------------------------------------------------------------

$l['error_no_connection'] = 'Hiba lépett fel a szerverhez történő kapcsolódáskor: ';
$l['error_no_message'] = 'Nem volt üzenet megadva.';
$l['error_no_subject'] = 'Nem volt tárgy megadva.';
$l['error_no_recipient'] = 'Nem volt címzett megadva.';
$l['error_not_sent'] = 'Hiba lépett fel a php mail függvénnyel az email elküldésekor.';
$l['error_status_missmatch'] = 'Az állapot a szerverről eltér az elvárt eredménytől, visszairányítás: ';
$l['error_data_not_sent'] = 'Az adat elküldése a szervernek nem sikerült: ';
$l['error_occurred'] = 'Egy vagy több hiba lépett fel. Kérlek javítsd az alábbi hibákat, mielőtt tovább lépnél.<br />';
