<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Wed, 11 Mar 2015 17:36:05 +0000
// --------------------------------------------------------------------------------

$l['nav_group_management'] = '{1} csoport kezelés';
$l['nav_join_requests'] = 'Regisztráció kell';
$l['nav_group_memberships'] = 'Csoport tagság';
$l['not_leader_of_this_group'] = 'Elnézést, de te nem vagy vezetője a csoportnak.';
$l['invalid_group'] = 'Ez a csoport nem létezik.';
$l['pending_requests'] = 'Függőben lévő csatlakozási kérelmek';
$l['num_requests_pending'] = 'Neked jelenleg <strong>{1}</strong> függőben lévő csatlakozási kérelmed van.';
$l['group_management'] = 'Csoport kezelés';
$l['members_of'] = 'Tagok ebben a csoportban: "{1}"';
$l['user_name'] = 'Felhasználónév';
$l['contact'] = 'Kapcsolat';
$l['reg_date'] = 'Regisztrált';
$l['post_count'] = 'Üzenetek';
$l['remove_selected'] = 'Kiválasztott felhasználó törlése a csoportból';
$l['add_member'] = 'Felhasználó hozzáadása: "{1}"';
$l['add_member_submit'] = 'Felhasználó hozzáadás a csoporthoz';
$l['invite_member'] = 'Tag meghívása "{1}" csoportba';
$l['invite_member_submit'] = 'Tag meghívása csoportba';
$l['join_requests'] = 'Csatlakozási kérelem';
$l['join_requests_title'] = 'Csatlakozási kérelem a "{1}" csoporthoz';
$l['leader'] = '(Vezető)';
$l['reason'] = 'Ok';
$l['accept'] = 'Elfogad';
$l['ignore'] = 'Nem fogad el';
$l['decline'] = 'Később';
$l['action_requests'] = 'Tevékenység kérés';
$l['join_requests_moderated'] = 'A regisztráció kérés moderált.<br />Most visszairányítunk a listához.';
$l['no_requests'] = 'Nincs függőben lévő csatlakozási kérelem a csoportba.';
$l['no_users'] = 'Nincsenek felhasználók a csoportban.';
$l['user_added'] = 'A felhasználó hozzáadva a csoporthoz.';
$l['users_removed'] = 'A kiválasztott felhasználó törölve a csoportból.';
$l['group_no_members'] = 'Jelenleg nincs felhasználó a csoportban.<br />Ahhoz, hogy visszatérj a csoport kezelés oldalra, kattints <a href="usercp.php?action=usergroups">ide</a>.';
$l['group_public_moderated'] = 'Ez a csoport nyitott, ahová bárki jelentkezhet. Az összes jelentkezést a csoport moderátor bírálja el.';
$l['group_public_not_moderated'] = 'Ez a csoport nyitott, ide bárki szabadon jelentkezhet.';
$l['group_public_invite'] = 'Ez a csoport nyitott, ide a csoportvezető meghívása szükséges a csatlakozáshoz.';
$l['group_private'] = 'Ez egy privát csoport.  A csoportba nem lehet jelentkezni, a csoport tagjai kérik fel tagnak azt, akit maguk közt szeretnének látni.';
$l['group_default'] = 'Ez a csoport egy törzs csoport.';
$l['group_leaders'] = 'Csoport vezetői';
$l['search_user'] = 'Felhasználó keresése';
$l['no_users_selected'] = 'Nincs eltávolításra kijelölt tag.<br /> Lépj vissza és válaszd ki azokat a felhasználókat, akiket el szeretnél távolítani ebből a csoportból.';
$l['error_alreadyingroup'] = 'A megadott felhasználó már tagja a csoportnak.';
$l['error_alreadyinvited'] = 'A megadott felhasználó már meg lett hívva.';
$l['user_invited'] = 'A felhasználót meghívták, hogy  csatlakozzon a felhasználói csoporthoz.';
$l['invite_pm_subject'] = 'Meghívást kaptál, hogy csatlakoz a "{1}" felhasználói csoporthoz';
$l['invite_pm_message'] = 'Meghívást kaptál, hogy csatlakoz a "{1}" felhasználói csoporthoz.

A csatlakozáshoz kérlek látogasd meg a [url={2}/usercp.php?action=usergroups]Csoport tagságok[/url] oldaladat és kattints a \'Meghívás elfogadása\'-ra.

Ez a meghívás nem fog lejárni.';
$l['invite_pm_message_expires'] = 'Meghívást kaptál, hogy csatlakoz a felhasználói csoporthoz "{1}".

A csatlakozáshoz kérlek látogasd meg a [url={2}/usercp.php?action=usergroups]Csoport tagságok[/url] oldaladat és kattints a \'Meghívás elfogadása\'-ra.

A meghívás {3} napon belül le fog járni .';
