<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sat, 14 Mar 2015 12:21:43 +0000
// --------------------------------------------------------------------------------

$l['nav_memberlist'] = 'Tagok listája';
$l['memberlist_disabled'] = 'Ez a funkció tiltott.';
$l['member_list'] = 'Tagok listája';
$l['avatar'] = 'Avatar';
$l['username'] = 'Felhasználónév:';
$l['joined'] = 'Regisztrált:';
$l['lastvisit'] = 'Utolsó látogatás';
$l['posts'] = 'Hozzászólások';
$l['threads'] = 'Téma számláló';
$l['referrals'] = 'Meghívottak';
$l['search_members'] = 'Keresés a tagok között';
$l['website'] = 'Weboldal';
$l['sort_by'] = 'Rendezési elv';
$l['contains'] = 'Tartalmazza:';
$l['sort_by_username'] = 'Rendezés: felhasználónév szerint';
$l['sort_by_regdate'] = 'Rendezés: regisztráció időpontja szerint';
$l['sort_by_lastvisit'] = 'Rendezés: utolsó látogatás szerint';
$l['sort_by_posts'] = 'Rendezés: hozzászólásszám szerint';
$l['sort_by_threads'] = 'Rendezés: témaszám szerint';
$l['sort_by_referrals'] = 'Rendezés: meghívások száma szerint';
$l['order_asc'] = 'növekvő';
$l['order_desc'] = 'csökkenő';
$l['asc'] = 'növekvő';
$l['desc'] = 'csökkenő';
$l['forumteam'] = 'Fórum vezetők megjelenítése';
$l['advanced_search'] = 'Részletes keresés';
$l['nav_memberlist_search'] = 'Keresés';
$l['search_member_list'] = 'Keresés a tagok között';
$l['search_criteria'] = 'Keresési kritériumok';
$l['begins_with'] = 'ezzel kezdődik';
$l['username_contains'] = 'tartalmazza';
$l['search_website'] = 'Weboldal URL';
$l['search_aim'] = 'AIM cím';
$l['search_skype'] = 'Skype cím';
$l['search_google'] = 'Google Talk cím';
$l['search_yahoo'] = 'Yahoo! Messenger azonosító';
$l['search_icq'] = 'ICQ azonosító';
$l['search_options'] = 'Keresési opciók';
$l['per_page'] = 'Eredmények száma egy oldalon';
$l['search'] = 'Keresés';
$l['search_user'] = 'Felhasználó keresése';
$l['error_no_members'] = '<p>Nem találtunk felhasználót a megadott kritériumok alapján.</p><p>Kérlek adj meg egy másik keresési kritériumot.</p>';
$l['a'] = 'A';
$l['b'] = 'B';
$l['c'] = 'C';
$l['d'] = 'D';
$l['e'] = 'E';
$l['f'] = 'F';
$l['g'] = 'G';
$l['h'] = 'H';
$l['i'] = 'I';
$l['j'] = 'J';
$l['k'] = 'K';
$l['l'] = 'L';
$l['m'] = 'M';
$l['n'] = 'N';
$l['o'] = 'O';
$l['p'] = 'P';
$l['q'] = 'Q';
$l['r'] = 'R';
$l['s'] = 'S';
$l['t'] = 'T';
$l['u'] = 'U';
$l['v'] = 'V';
$l['w'] = 'W';
$l['x'] = 'X';
$l['y'] = 'Y';
$l['z'] = 'Z';
