<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian (Magyar)
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://community.mybb.com/mods.php?action=view&pid=441
// Compatible version of MyBB : 1813 Béta
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 10 Dec 2017 09:41:23 +0000
// --------------------------------------------------------------------------------

$l['nav_register'] = 'Regisztráció';
$l['nav_activate'] = 'Aktivál';
$l['nav_resendactivation'] = 'Aktiváló email újraküldése';
$l['nav_lostpw'] = 'Elfelejtett jelszó visszaállítás';
$l['nav_resetpassword'] = 'Jelszó törlése';
$l['nav_login'] = 'Belépés';
$l['nav_emailuser'] = 'Email a felhasználónak';
$l['nav_profile'] = '{1} profilja';
$l['tpp_option'] = 'Mutass {1} témát oldalanként';
$l['ppp_option'] = 'Mutass {1} üzenetet oldalanként';
$l['account_activation'] = 'Fiók aktiválás';
$l['activate_account'] = 'Fiók aktiválva';
$l['activation_code'] = 'Aktiváló kód';
$l['email_user'] = 'Email küldés a {1} felhasználónak';
$l['email_subject'] = 'Email tárgya';
$l['email_message'] = 'Email üzenet';
$l['send_email'] = 'Küldés';
$l['error_hideemail'] = 'A címzett azt választotta, hogy elrejti az email címét más felhasználók elől, így nem tudsz e-mailt küldeni neki.';
$l['error_no_email_subject'] = 'Meg kell adnod az email tárgyát';
$l['error_no_email_message'] = 'Meg kell adnod az üzenetet';
$l['login'] = 'Belépés';
$l['pw_note'] = 'Kérlek figyelj a jelszó beírásnál, a jelszó karakter érzékeny.';
$l['lostpw_note'] = 'Elfelejtetted a jelszavad?';
$l['lost_pw'] = 'Elfelejtett fiók jelszó';
$l['lost_pw_form'] = 'Elfelejtett jelszó visszaállítás';
$l['email_address'] = 'Email címed:';
$l['request_user_pass'] = 'Belépési adatok lekérése';
$l['profile'] = '{1} profilja';
$l['registration_date'] = 'Regisztráció dátuma:';
$l['date_of_birth'] = 'Születési idő:';
$l['birthdayhidden'] = 'Rejtett';
$l['birthday'] = 'Születésnap:';
$l['local_time'] = 'Helyi idő:';
$l['local_time_format'] = '{1} {2}';
$l['users_forum_info'] = '{1} fórum információi';
$l['joined'] = 'Regisztrált:';
$l['lastvisit'] = 'Utolsó látogatás:';
$l['total_posts'] = 'Összes hozzászólás:';
$l['ppd_percent_total'] = '{1} üzenet naponta | {2} % az összes üzenethez viszonyítva';
$l['total_threads'] = 'Összes téma:';
$l['tpd_percent_total'] = '{1} témák naponta | {2} % az összes témához viszonyítva';
$l['find_posts'] = 'Összes hozzászólás keresése';
$l['find_threads'] = 'Összes téma keresése';
$l['members_referred'] = 'Meghívott felhasználók száma:';
$l['rating'] = 'Értékelés:';
$l['users_contact_details'] = '{1} kapcsolatfelvételi adatai';
$l['homepage'] = 'Honlap:';
$l['pm'] = 'Privát üzenet:';
$l['send_pm'] = 'Privát üzenet küldése a {1} felhasználónak.';
$l['icq_number'] = 'ICQ szám:';
$l['aim_screenname'] = 'AIM belépési név:';
$l['yahoo_id'] = 'Yahoo ID:';
$l['skype_id'] = 'Skype ID:';
$l['google_id'] = 'Google Talk ID:';
$l['avatar'] = 'Avatar:';
$l['warning_level'] = 'Figyelmeztetési szint:';
$l['warn'] = 'Figyelmeztetés';
$l['away_note'] = '{1} jelenleg nem elérhető.';
$l['away_reason'] = 'Távollét oka:';
$l['away_since'] = 'Távol van (-tól):';
$l['away_returns'] = 'Visszatérés ideje:';
$l['away_no_reason'] = 'Nincs megadva.';
$l['ban_note'] = 'Ez a fórum felhasználó jelenleg ki van tiltva.';
$l['ban_by'] = 'Kitiltotta';
$l['ban_length'] = 'Kitiltás időtartama';
$l['ban_remaining'] = 'megmaradó/hátralévő';
$l['users_additional_info'] = '{1} egyéb információi';
$l['email'] = 'Email cím:';
$l['send_user_email'] = 'Email küldése a {1} felhasználónak.';
$l['users_signature'] = '{1} aláírása';
$l['agreement'] = 'Regisztrációs feltételek';
$l['agreement_1'] = 'Noha az Adminisztrátor, és a Moderátorok mindent megtesznek, hogy minél hamarabb eltávolítsák a Fórumból az általánosan kifogásolható anyagokat, lehetetlen, hogy minden egyes hozzászólást átnézzenek. Ebből adódóan elfogadom, hogy a Fórumon található összes hozzászólás a szerző nézeteit tükrözi, és nem az Adminisztrátorok, Moderátorok, vagy a webmester álláspontját - így ők nem vállalnak felelősséget a hozzászólások tartalmáért.';
$l['agreement_2'] = 'Beleegyezek, hogy nem küldök sértegető, obszcén, vulgáris, rágalmazó, gyűlöletkeltő, támadó, vagy bármely más olyan tartalmat, illetve anyagot, mely törvényt sért. Mivel ez egy nyilvános fórum, ezért olyan anyagot sem küldök, mely ellentétes az általános közízléssel. A fentiek megsértése azonnali és végleges törlést von maga után. Elfogadom, hogy a Fórum webmesterének, az Adminisztrátornak és bármely Moderátornak jogában áll eltávolítani, szerkeszteni a hozzászólásaimat, vagy lezárni az általam nyitott témákat, amennyiben úgy ítélik meg hogy ez szükséges.';
$l['agreement_3'] = 'Mint felhasználó, elfogadom, hogy néhány, általam megadott adat tárolásra kerül a Fórum adatbázisában, többek között minden bejegyzéshez eltárolódik az IP címed is. Ezek az információk semmilyen módon nem kerülnek ki egy harmadik félhez ( kivételt képez ez alól a törvényben foglalt adatközlési kötelezettség ), de sem az Adminisztrátor sem a Moderátorok nem tudnak felelősséget vállalni az adatokért egy esetleges -hacker-támadás- esetén. A portálhoz történő hozzáféréssel a Felhasználó tudomásul veszi és beleegyezik abba, hogy az oldal sütik-küldést eszközöl a számítógépére vagy egyéb hozzáférési eszközére annak érdekében, hogy a portálon tett látogatásait megszemélyesítse, és/vagy többet tudjon meg a használati és böngészési szokásairól. A süti tartalmazhat a Felhasználóról szóló személyes információt és lehet állandó, vagy egyszeri süti. A portál használata során a háttérben futó szoftver folyamatosan adatokat gyűjt a látogatói szokások elemzésének elősegítésére. A statisztikák alapjául szolgáló adatokat nem egyénre/látogatásra lebontva, hanem kizárólag összesítetten tároljuk, így azokból sem lehetőségünk, sem célunk egyéni látogatásokra vonatkozó információkat nyerni. A portálszoftver védelmi programrészeket is tartalmaz. Ezen programrészek állandóan működésben vannak. Ha ezek a programrészek szerverünk illetve szoftverünk elleni támadási kísérletet észlelnek, akkor az internetes technológia használatából adódóan rendelkezésre álló összes lehetséges adatot begyűjtjük, amelyet felhasználhatunk arra, hogy felderítsük, valóban támadási kísérletről volt-e szó. Ha feltevésünk beigazolódik, és szükségesnek látjuk, akkor a hatályos törvények, jogszabályok, rendeletek alapján járunk el.';
$l['agreement_4'] = 'A felhasználó a regisztrációval elismeri, hogy elolvasta, elismeri és magára nézve kötelező érvényűen elfogadja a Fórum - Működési Szabályait - mely megtalálható a fórum Fórumunkról/Működési Szabályzat témakörben. ';
$l['agreement_5'] = 'A REGISZTRÁCÓ gombra történő kattintással elismered, hogy a fenti feltételek elolvastad és kötelező érvényűen elfogadod! Tudomásul veszed, hogy az Adminisztrátoroknak és a Moderátoroknak jogában áll bárkit az oldalról indoklás nélkül azonnali hatállyal eltávolítani és örökre kitiltani, amennyiben az adott helyzetet úgy ítélik meg.';
$l['registration'] = 'Regisztráció';
$l['required_fields'] = 'Kötelezően kitöltendő';
$l['complex_password'] = '<acronym title="Egy jelszó, amely legalább {1} karakter hosszú és nagybetűket, kisbetűket és számokat tartalmaz.">Összetett</acronym> Jelszó:';
$l['confirm_email'] = 'Email cím még egyszer:';
$l['optional_fields'] = 'Megadható adatok';
$l['website_url'] = 'Weboldalad URL-je:';
$l['birthdate'] = 'Születésnap:';
$l['additional_info'] = 'Egyéb információk';
$l['required_info'] = 'Szükséges információ';
$l['i_agree'] = 'Elfogadom';
$l['account_details'] = 'Fiókod adatai';
$l['account_prefs'] = 'Fiókod tulajdonságai:';
$l['invisible_mode'] = 'Jelenlétem maradjon rejtve más felhasználók elől.';
$l['allow_notices'] = 'Az adminisztrátorok közérdekű üzeneteinek fogadása.';
$l['hide_email'] = 'Az email címem maradjon rejtve más felhasználók elől.';
$l['email_notify'] = 'Automatikusan feliratkozom azokra a témákra, melyekbe üzenetet írok.';
$l['receive_pms'] = 'Privát üzenetek fogadása más felhasználóktól.';
$l['pm_notice'] = 'Figyelmeztessen, ha privát üzenetem érkezett.';
$l['email_notify_newpm'] = 'Küldjön email értesítést ha privát üzenetem érkezik.';
$l['time_offset'] = 'Időzóna beállítások: (<acronym title="Daylight Savings Time">DST</acronym> korrekcióval):';
$l['time_offset_desc'] = 'Amennyiben az időzónád eltér a GMT-től, itt állíthatod be a megfelelő időt.';
$l['dst_correction'] = 'Nyári/téli időszámítás:';
$l['dst_correction_auto'] = 'DST beállítások automatikus észlelése';
$l['dst_correction_enabled'] = 'Mindig használja a DST korrekciót';
$l['dst_correction_disabled'] = 'Ne használja a DST korrekciót';
$l['redirect_registered_coppa_activate'] = 'Köszönjük a regisztrációdat a(z) {1} oldalunkon, {2}. A felhasználói fiókodat sikeresen létrehoztuk, azonban a frumot csak akkor fogod tudni használni, ha egy szülő/gondviselő engedélyezte azt, és ezt írásban jelezte felénk.<br /><br />A szülő/gondviselő-nek le kell töltenie a következő formanyomtatványt és kitöltve eljuttatni azt hozzánk: <a href="member.php?action=coppa_form">COPPA teljesítés és engedély űrlap</a>.<br /><br />Mihelyst megkapjuk a kitöltött nyomtatványt a fiókadat azonnal aktiváljuk.';
$l['coppa_compliance'] = 'COPPA teljesítés (COPPA irányelvek betartása)';
$l['coppa_desc'] = 'A <a href="http://coppa.org/" title="A gyermekek személyiségi jogainak online védelméről szóló törvény" target="_blank">COPPA</a> útmutatását követve, mielőtt regisztrálnál a fórumon, kérlek add meg a korodat. <br /><br />A regisztráció előtt minden 13 éven aluli felhasználónak engedélyt kell először kérnie a szülőtől / gondviselőtől, hogy a fórum regisztrált tagja lehessen. A szülő / gondviselőnek le kell töltenie a <a href="member.php?action=coppa_form" target="_blank">COPPA teljesítés és engedély űrlap</a>-ot és kitöltve, aláírva el kell azt juttatnia hozzánk.';
$l['hide_dob'] = 'Ezt az információt el tudod rejteni a többi felhasználó elől a regisztráció után.';
$l['signature'] = 'Aláírás:';
$l['continue_registration'] = 'Tovább';
$l['birthdayprivacy'] = 'Születési idő adatvédelem:';
$l['birthdayprivacyall'] = 'Életkor és születési idő megjelenítése';
$l['birthdayprivacynone'] = 'Életkor és születési idő elrejtése';
$l['birthdayprivacyage'] = 'Életkor megjelenítése';
$l['leave_this_field_empty'] = 'Hagyd üresen ezt a mezőt:';
$l['error_need_to_be_thirteen'] = '13 évesnek vagy ennél idősebbnek kell lenned, hogy regisztrálhass a fórumon.';
$l['coppa_registration'] = 'COPPA regisztrációs űrlap';
$l['coppa_form_instructions'] = 'Kérlek nyomtasd ki ezt az űrlapot, töltsd ki, és faxold el vagy küld el emailben a részünkre.';
$l['fax_number'] = 'Fax szám:';
$l['mailing_address'] = 'Levelezési cím:';
$l['account_information'] = 'Fiók információ';
$l['parent_details'] = 'Szülő / Gondviselő adatai';
$l['full_name'] = 'Teljes név:';
$l['relation'] = 'Kapcsolat:';
$l['phone_no'] = 'Telefon #:';
$l['coppa_parent_agreement'] = 'Elismerem, hogy az általam szolgáltatott információk a valóságnak megfelelnek.';
$l['coppa_agreement_1'] = 'A 13 év alatti felhasználóknak a {1} fórumra való regisztráláshoz először engedélyt kell kérniük a szüleiktől / gondviselőjüktől.';
$l['coppa_agreement_2'] = 'A szülő / gondviselőnek le kell töltenie a <a href="member.php?action=coppa_form" target="_blank">COPPA teljesítés és engedély űrlap</a>-ot és kitöltve, aláírva el kell azt juttatnia hozzánk.';
$l['coppa_agreement_3'] = 'Most tovább léphetsz a regisztrációhoz, de amíg nem kapjuk meg az aláírt nyomtatványt a szülődtől / nevelődtől, addig nem tudsz hozzászólni ezen a fórumon.';
$l['error_invalid_birthday'] = 'A megadott születési idő érvénytelen. Érvényes születési időt adj meg.';
$l['error_awaitingcoppa'] = 'Még nem használhatod a fórumot, mert a COPPA engedélyed nem érkezett meg.';
$l['lang_select'] = 'Nyelvi beállítások:';
$l['lang_select_desc'] = 'Amennyiben azt szeretnéd, hogy a fórum nyelve eltérjen az alapértelmezéstől itt változtathatsz nyelvet.';
$l['lang_select_default'] = 'Alapértelmezés';
$l['submit_registration'] = 'Regisztráció!';
$l['confirm_password'] = 'Jelszavad még egyszer:';
$l['referrer'] = 'Ajánló:';
$l['referrer_desc'] = 'Amennyiben neked valamely felhasználónk ajánlotta a fórumot itt megadhatod a nevét. Ha ilyen nincs hagyd üresen a mezőt.';
$l['search_user'] = 'Felhasználó keresése';
$l['resend_activation'] = 'Fiók aktiváció újra küldése';
$l['request_activation'] = 'Kötelező aktivációs kód';
$l['ppp'] = 'Üzenetek oldalanként:';
$l['ppp_desc'] = 'Itt adhatod meg, hogy hány üzenet jelenjen meg oldalanként.';
$l['tpp'] = 'Téma oldalanként:';
$l['tpp_desc'] = 'Itt adhatod meg, hogy oldalanként hány téma jelenjen meg.';
$l['reset_password'] = 'Jelszó törlése';
$l['send_password'] = 'Új jelszó küldése!';
$l['image_verification'] = 'Kép ellenőrzés';
$l['verification_note'] = 'Kérlek írd be a szövegmezőbe az itt található képen látott karaktersorozatot. Ez a művelet megelőzi az automatizált folyamatokat (kiszűri a robot tevékenységet).';
$l['verification_subnote'] = '(kis- és nagybetű érzéketlen)';
$l['registration_errors'] = 'A következő hiba lépett fel a regisztráció során:';
$l['timeonline'] = 'Online eltöltött idő:';
$l['timeonline_hidden'] = '(Rejtett)';
$l['registrations_disabled'] = 'Elnézést kérünk, jelenleg a regisztrációkat az Adminisztrátor felfüggesztette.';
$l['error_username_length'] = 'A felhasználónév nem megfelelő. A felhasználónévnek {1} és {2} karakter közt kell lennie.';
$l['error_stop_forum_spam_spammer'] = 'Elnézést, de a {1}-(d) egyezik egy ismert spammerrel. Ha úgy érzed, hogy ez tévedés kérlek lépj kapcsolatba egy adminisztrátorral.';
$l['error_stop_forum_spam_fetching'] = 'Elnézést, de egy hiba lépett fel a fiókod spammer adatbázisban történő ellenőrzésekor. Legvalószínűbb, hogy az adatbázis nem hozzáférhető. Kérlek próbáld meg később.';
$l['none_registered'] = 'A regisztráció nincs megerősítve';
$l['not_specified'] = 'Nincs megadva';
$l['membdayage'] = '({1} éves)';
$l['mod_options'] = 'Moderátor opciók';
$l['edit_in_mcp'] = 'Felhasználó szerkesztése a moderációs vezérlőpultban';
$l['ban_in_mcp'] = 'Felhasználó kitiltása a a moderációs vezérlőpultban';
$l['purgespammer'] = 'Spammer tisztítás';
$l['edit_usernotes'] = 'Felhasználó feljegyzések szerkesztése a a moderációs vezérlőpultban';
$l['no_usernotes'] = 'Jelenleg ehhez a felhasználóhoz nincsenek feljegyzések.';
$l['view_all_notes'] = 'Összes feljegyzés megtekintése';
$l['view_notes_for'] = '{1} feljegyzésének megtekintése???';
$l['reputation'] = 'Értékelés:';
$l['reputation_vote'] = 'Szavaz';
$l['reputation_details'] = 'Részletek';
$l['already_logged_in'] = 'Figyelem: már be vagy jelentkezve, mint: {1}.';
$l['admin_edit_in_acp'] = 'Felhasználó szerkesztése az adminisztrátori vezérlőpultban';
$l['admin_ban_in_acp'] = 'Felhasználó kizárása az adminisztrátori vezérlőpultban';
$l['admin_options'] = 'Admin opciók';
$l['redirect_registered_activation'] = 'Köszönjük, hogy regisztráltál fórumunkon: {1}, {2}.<p>A regisztráció befejezéséhez kérlek ellenőrizd az email postafiókodat és kövesd az aktivációs utasításokat. Amíg a regisztrációd nincs aktiválva nem fogsz tudni hozzászólásokat írni a fórumon. ';
$l['redirect_emailupdated'] = 'Az email címedet sikeresen megváltoztattuk.<br />Visszairányítunk a főoldalra.';
$l['redirect_accountactivated'] = 'A regisztrációd aktiválva.<br />Visszairányítunk a főoldalra.';
$l['redirect_accountactivated_admin'] = 'Az email címed sikeresen jóváhagyva.<br />A regisztrációdat most már egy adminisztrátor fogja aktiválni. Addig nem tudsz hozzászólni a fórumokhoz.<br />Most visszairányítunk a főoldalra.';
$l['redirect_registered'] = 'Köszönjük, hogy regisztráltál fórumunkon:  {1}, {2}.<br />Visszairányítunk a főoldalra.';
$l['redirect_registered_admin_activate'] = 'Köszönjük, hogy regisztráltál fórumunkon:  {1}, {2}.<br />A regisztrációdat egy adminisztrátor egyedileg fogja ellenőrizni.  Amíg a regisztrációd nem kerül megerősítésre addig nem biztos, hogy fogsz tudni hozzászólást írni a fórumon.';
$l['redirect_loggedout'] = 'Sikeres kijelentkezés.<br />Átirányítunk a fórum főoldalára.';
$l['redirect_alreadyloggedout'] = 'Már kijelentkeztél vagy be sem voltál jelentkezve.<br />Visszairányítunk a fórum főoldalára.';
$l['redirect_lostpwsent'] = 'Köszönjük, egy emailt elküldtünk a megadott címre instrukciókkal, hogy hogyan szerezheted vissza a jelszavad.<br /><br />Visszairányítunk a fórum főoldalára.';
$l['redirect_activationresent'] = 'Aktivációs email elküldve.';
$l['redirect_passwordreset'] = 'Köszönjük, a jelszavadat sikeresen megváltoztattuk. Az új jelszót elküldtük a regisztrációkor megadott email címre.';
$l['redirect_memberrated'] = 'A felhasználó értékelése megtörtént.';
$l['redirect_registered_passwordsent'] = 'Az új jelszót elküldtük a megadott email címre. Kérlek ellenőrizd le a postafiókodat.';
$l['redirect_validated'] = 'A regisztrációd érvényesítése megtörtént.<br />Visszairányítunk a fórum főoldalára.';
$l['error_activated_by_admin'] = 'Nem küldheted újra az aktivációs emailt, mivel minden regisztrációt az adminisztrátor egyedileg ellenőriz.';
$l['error_alreadyregistered'] = 'Úgy tűnik, már regisztráltál erre a fórumra, és a többszörös regisztráció nem engedélyezett.';
$l['error_alreadyregisteredtime'] = 'Nem tudjuk végrehajtani a regisztrációt, mert {1} új regisztráció történt erről az IP címről az elmúlt {2} órában. Kérlek próbálkozz később.';
$l['error_badlostpwcode'] = 'Úgy tűnik, hogy érvénytelen jelszó helyreállító kódot adtál meg. Kérlek olvasd el újra a levelet amit küldtünk, vagy lépj kapcsolatba az adminisztrátorral.';
$l['error_badactivationcode'] = 'Érvénytelen aktivációs kódot adtál meg. Az aktivációs email újraküldéséhez, kérlek <a href="member.php?action=resendactivation">katt ide</a>.';
$l['error_alreadyactivated'] = 'Úgy tűnik, hogy a regisztrációd aktiválása már megtörtént, vagy nincs szükség email aktivációra.';
$l['error_alreadyvalidated'] = 'Az emailed már jóvá lett hagyva.';
$l['error_nothreadurl'] = 'Az üzeneted nem tartalmazza a téma URL-ét. Kérlek használd a "Téma küldése barátnak" opciót arra, ami a célja.';
$l['error_bannedusername'] = 'Kitiltott felhasználónevet adtál meg. Kérlek válassz egy másikat.';
$l['error_notloggedout'] = 'Az azonosítódat nem sikerült megerősíteni a kijelentkezés során. Elképzelhető, hogy egy JavaScript program próbált automatikusan kijelentkeztetni. Ha te akartál kijelentkezni, kérlek kattints a Kijelentkezés gombra a menüben.';
$l['error_regimageinvalid'] = 'Hibás képellenőrző kódot adtál meg. Pontosan úgy add meg a kódot, ahogyan az a képen megjelenik.';
$l['error_regimagerequired'] = 'Kérlek add meg a kép megerősítő kódot a folytatáshoz. Pontosan úgy add meg a kódot, ahogyan az a képen megjelenik.';
$l['error_spam_deny'] = 'A rendszerünk szerint spammer vagy, ezért a regisztrációdat letiltottuk. Ha úgy érzed, hogy ez téves, lépj kapcsolatba az adminisztrátorral.';
$l['error_spam_deny_time'] = 'A rendszerünk szerint spammer vagy, ezért a regisztrációdat letiltottuk. A regisztrációnál várni kell min. {1} másodpercet, hogy megelőzze az automatikus feliratkozásokat, Te {2} másodpercen belül regisztráltál.??? Ha úgy érzed, hogy ez téves, lépj kapcsolatba az adminisztrátorral.';
$l['js_validator_no_username'] = 'Meg kell adnod egy felhasználónevet.';
$l['js_validator_invalid_email'] = 'Meg kell adnod egy érvényes email címet.';
$l['js_validator_email_match'] = 'Meg kell adnod az email címet újra.';
$l['js_validator_no_image_text'] = 'Meg kell adnod a képen látható szöveget.';
$l['js_validator_no_security_question'] = 'Meg kell adnod a fentebb feltett kérdésre a választ';
$l['js_validator_password_matches'] = 'A két jelszónak egyeznie kell.';
$l['js_validator_password_complexity'] = 'A jelszó túl egyszerű.';
$l['js_validator_password_length'] = 'A jelszavadnak {1} vagy több karakter hosszúnak kell lennie.';
$l['js_validator_not_empty'] = 'Meg kell adnod vagy választanod egy értéket ehhez a mezőhöz.';
$l['js_validator_checking_username'] = 'Felhasználónév foglaltságának ellenőrzése';
$l['js_validator_username_length'] = 'Felhasználónévnek {1} és {2} karakter között kell lennie.';
$l['js_validator_checking_referrer'] = 'Az ajánló felhasználónevének ellenőrzése.';
$l['js_validator_captcha_valid'] = 'Kép ellenőrző kód helyességének ellenőrzése.';
$l['security_question'] = 'Biztonsági kérdés';
$l['question_note'] = 'Kérlek válaszolj a feltett kérdésre. Ezt a folyamat az automatizált folyamatok megelőzésére használják.';
$l['error_question_wrong'] = 'A válasz, amit a biztonsági kérdésre adtál helytelen. Kérlek próbáld meg újra.';
$l['subscription_method'] = 'Alapértelmezett téma feliratkozási mód:';
$l['no_auto_subscribe'] = 'Nincs feliratkozás';
$l['no_subscribe'] = 'Nincs értesítés';
$l['instant_email_subscribe'] = 'Azonnali email értesítés';
$l['instant_pm_subscribe'] = 'Azonnali PÜ értesítés';
$l['remove_from_buddy_list'] = 'Eltávolítás a Barátok listájáról';
$l['add_to_buddy_list'] = 'Hozzáadás a Barátok listájához';
$l['remove_from_ignore_list'] = 'Eltávolítás a Tiltólistáról';
$l['add_to_ignore_list'] = 'Tiltólistához adás';
$l['report_user'] = 'Felhasználó jelentése';
$l['newregistration_subject'] = 'Új regisztráció at {1}';
$l['newregistration_message'] = '{1},



Egy új felhasználó van a(z) {2} fórumon akinek a függőben van az admin aktivációja.



Felhasználónév: {3}



Köszönettel,

{2} Csapata';
$l['registration_ip'] = 'Regisztrált IP:';
$l['last_known_ip'] = 'Utolsó ismert IP:';
$l['js_validator_bad_password_security'] = 'A jelszó, amit megadtál hasonlít a felhasználó nevedhez vagy e-mail címedhez.
Kérelek, adj meg erősebb jelszót.';
