<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian (Magyar)
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://community.mybb.com/mods.php?action=view&pid=441
// Compatible version of MyBB : 1810 Béta
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sat, 14 Jan 2017 09:11:40 +0000
// --------------------------------------------------------------------------------

$l['click_no_wait'] = 'Kattints ide, ha nem akarsz várni a betöltődésre.';
$l['redirect_return_forum'] = '<br /><br />Vagy <a href="{1}">kattints ide</a>, hogy visszatérj a fórumba.';
$l['redirect_emailsent'] = 'Email sikeresen elküldve.';
$l['redirect_loggedin'] = 'Sikeres bejelentkezés.<br />Átirányítunk a fórum főoldalára.';
$l['error_invalidpworusername'] = 'Érvénytelen felhasználónév/jelszó. <br /><br />Ha elfelejtetted a jelszavad, <a href="member.php?action=lostpw">kérj újat</a>.';
$l['error_invalidpworusername1'] = 'Érvénytelen email/jelszó. <br /><br />Ha elfelejtetted a jelszavad, <a href="member.php?action=lostpw">kérj újat</a>.';
$l['error_invalidpworusername2'] = 'Érvénytelen felhasználónév/jelszó vagy email/jelszó. <br /><br />Ha elfelejtetted a jelszavad, <a href="member.php?action=lostpw">kérj újat</a>.';
$l['error_incompletefields'] = 'Egy vagy több kötelezően kitöltendő mezőt üresen hagytál. Lépj vissza és töltsd ki a szükséges mezőket.';
$l['error_alreadyuploaded'] = 'A hozzászólás már tartalmaz egy csatolást ezzel a névvel. Nevezd át a fájlt, és töltsd fel újra. Másik lehetőség a "Csatolás frissítése".';
$l['error_alreadyuploaded_perm'] = 'A hozzászólás már tartalmaz egy csatolást ezzel a névvel. Töröld a meglévő fájlt, vagy nevezd át az új fájlt, és töltsd fel újra.';
$l['error_nomessage'] = 'Elnézést, de a folyamatot nem lehet elkezdeni, mert nem adtál meg valós üzeneteket. Lépj vissza és kezd újra.';
$l['error_invalidemail'] = 'Az általad megadott email cím nem valós.';
$l['error_nomember'] = 'A megadott felhasználó nem létezik.';
$l['error_maxposts'] = 'Nagyon sajnálom, de a napi üzenet limitet elérted. Kérlek várj holnapig az üzenettel, vagy vedd fel a kapcsolatot az Adminnal.<br /><br />A maximum üzenet melyet egy nap elküldhetsz: {1}';
$l['error_nohostname'] = 'Nem található hosztnév a megadott IP címhez.';
$l['error_invalidthread'] = 'A megadott téma nem létezik.';
$l['error_invalidpost'] = 'A megadott üzenet nem létezik.';
$l['error_invalidannouncement'] = 'A megadott közlemény nem létezik.';
$l['error_invalidattachment'] = 'A megadott csatolás nem létezik.';
$l['error_invalidforum'] = 'Nem megfelelő fórum';
$l['error_closedinvalidforum'] = 'Nem tudsz üzenetet írni ebbe a fórumba mert a fórum vagy a kategória le lett zárva.';
$l['error_attachtype'] = 'A csatolandó fájltípus nem engedélyezett. Kérlek válassz másfajta fájltípust.';
$l['error_attachsize'] = 'A csatolt fájl túl nagy. A max. fájlméret {1} kilobyte.';
$l['error_uploadempty'] = 'A megadott fájl üres.';
$l['error_uploadsize'] = 'A feltöltendő fájl túl nagy.';
$l['error_uploadfailed'] = 'A fájl feltöltés nem sikerült. Kérlek válassz valós fájlt. ';
$l['error_uploadfailed_detail'] = 'Részletek: ';
$l['error_uploadfailed_php1'] = 'PHP hiba: A feltöltött fájl mérete meghaladja a php.ini-ben engedélyezettet. Kérlek egyeztess az adminisztrátorral a hibáról.';
$l['error_uploadfailed_php2'] = 'A feltöltött fájl mérete meghaladta az engedélyezettet.';
$l['error_uploadfailed_php3'] = 'Csak a fájl egy része lett feltöltve.';
$l['error_uploadfailed_php4'] = 'Sikertelen feltöltés.';
$l['error_uploadfailed_php6'] = 'PHP hiba: Hiányzó ideiglenes mappa. Kérlek egyeztess az adminisztrátorral a hibáról.';
$l['error_uploadfailed_php7'] = 'PHP hiba: a fájl írása sikertelen. Kérlek egyeztess az adminisztrátorral a hibáról.';
$l['error_uploadfailed_phpx'] = 'PHP hibakód: {1}.  Kérlek egyeztess az adminisztrátorral a hibáról.';
$l['error_uploadfailed_nothingtomove'] = 'A megadott fájl nem engedélyezett.';
$l['error_uploadfailed_movefailed'] = 'probléma lépett fel a fájl áthelyezésekor.';
$l['error_uploadfailed_lost'] = 'A csatolás nem található a szerveren.';
$l['error_emailmismatch'] = 'A megadott email cím nemlétezik. Lépj vissza és próbáld újra.';
$l['error_nopassword'] = 'A megadott jelszó nem megfelelő.';
$l['error_usernametaken'] = 'A választott felhasználónév már használatban van. Ha te regisztráltad, kérlek <a href="member.php?action=login">lépj be</a>';
$l['error_nousername'] = 'Nem adtál meg felhasználónevet.';
$l['error_invalidusername'] = 'A megadott felhasználónév nem megfelelő.';
$l['error_invalidpassword'] = 'A megadott jelszó nem megfelelő. Ha elfelejtetted a jelszavad, kattints <a href="member.php?action=lostpw">ide</a>. Ha újra akarsz próbálkozni fordulj vissza.';
$l['error_postflooding'] = 'Nagyon sajnáljuk, de nem tudjuk az üzeneted elfogadni. Az adminisztrátor beállítása szerint csak {1} percenként lehet üzenetet írni.';
$l['error_nopermission_guest_1'] = 'Nem rendelkezel megfelelő jogosultsággal az oldal megtekintéséhez. Az indok a következő:';
$l['error_nopermission_guest_2'] = 'Nem léptél be, vagy nem vagy regisztrált felhasználó. Amennyiben regisztrált felhasználó vagy lépj be, ha még nem vagy felhasználónk regisztrálj.';
$l['error_nopermission_guest_3'] = 'Nem rendelkezel megfelelő jogosultsággal az oldal megtekintéséhez. Adminisztratív oldalra, vagy védett területre akarsz belépni?  Ellenőrizd a fórum Szabályzatát vagy kérdezz rá az Adminisztrátornál.';
$l['error_nopermission_guest_4'] = 'A fiókodat az Adminisztrátor letiltotta, vagy még a fiókod nincs aktiválva.';
$l['error_nopermission_guest_5'] = 'Közvetlenül érted el ezt az oldalt a helyett, hogy a megfelelő űrlapokon, vagy linkeken keresztül jutottál volna ide.';
$l['login'] = 'Belépés';
$l['need_reg'] = 'Szeretnél regisztrálni?';
$l['forgot_password'] = 'Elfelejtetted a jelszavad?';
$l['error_nopermission_user_1'] = 'Neked nincs engedélyed az oldal megtekintésére. Az indok a következő:';
$l['error_nopermission_user_ajax'] = 'Nem rendelkezel megfelelő jogosultsággal az oldal megtekintéséhez.';
$l['error_nopermission_user_2'] = 'A fiókodat valamilyen oknál fogva felfüggesztették vagy kitiltottak az oldalról.';
$l['error_nopermission_user_3'] = 'Nem rendelkezel megfelelő jogosultsággal az oldal megtekintéséhez. Lehet, hogy adminisztrációs vagy védett oldalra szeretnél belépni? Ellenőrizd a fórum Szabályzatát vagy kérdezz rá az Adminisztrátornál.';
$l['error_nopermission_user_4'] = 'A fiókod aktiválásra vár vagy moderálás alatt van.';
$l['error_nopermission_user_5'] = 'Az oldalt közvetlenül érted el a megfelelő űrlapok vagy link helyett.';
$l['error_nopermission_user_resendactivation'] = 'Aktivációs kód újraküldése';
$l['error_nopermission_user_username'] = 'Jelenleg be vagy jelentkezve mint: \'{1}\'';
$l['logged_in_user'] = 'Felhasználó belépés';
$l['error_too_many_images'] = 'Túl sok a kép.';
$l['error_too_many_images2'] = 'Sajnáljuk, de a kérést nem tudjuk végrehajtani, mivel túl sok a kép. Törölj néhány képet az üzenetedből, úgy próbáld újra.';
$l['error_too_many_images3'] = '<b>Megjegyzés:</b> Az üzenetekben max. felhasználható képek száma';
$l['error_attach_file'] = 'Fájl csatolási hiba';
$l['please_correct_errors'] = 'Kérlek javítsd ki a következő hibákat, mielőtt folytatnád:';
$l['error_reachedattachquota'] = 'Elnézést, de nem csatolhatod a fájlt mert nagyobb az engedélyezett {1} méretnél';
$l['error_maxattachpost'] = 'Elnézést, de nem csatolhatod a fájlt, mert túllépted az egy hozzászóláshoz engedélyezett {1} csatolást';
$l['error_invaliduser'] = 'A választott felhasználó nem valós.';
$l['error_invalidaction'] = 'Helytelen művelet';
$l['error_messagelength'] = 'Elnézést, az üzeneted túl hosszú. Kérlek rövidíts rajta és úgy próbáld újra.';
$l['error_message_too_short'] = 'Az üzeneted túl rövid.';
$l['failed_login_wait'] = 'Többszöri kísérletre sem sikerült belépned. Várnod kell {1} óra {2} perc {3} másodpercet a következő próbálkozásig.';
$l['failed_login_again'] = '<br/>Már csak <strong>{1}</strong> lehetőséged maradt.';
$l['error_max_emails_day'] = 'Nem használhatod a \'Téma küldése barátnak\' vagy \'Email küldése a felhasználónak\' opciókat mert már elhasználtad a 24 órán belül küldhető e-mailek mennyiségét, ami: {1}.';
$l['attachments_disabled'] = 'Nem használhatod a fájl csatolást, amelyet az Adminisztrátor letiltott.';
$l['emailsubject_lostpw'] = 'Jelszó törlés - {1}';
$l['emailsubject_passwordreset'] = 'Új jelszó - {1}';
$l['emailsubject_subscription'] = 'Új válasz a(z) {1} témában';
$l['emailsubject_randompassword'] = 'Jelszavad {1}';
$l['emailsubject_activateaccount'] = 'Fiók aktiváció - {1}';
$l['emailsubject_forumsubscription'] = 'Új téma: {1}';
$l['emailsubject_reportpost'] = 'Jelentett üzenet {1}-nál';
$l['emailsubject_reachedpmquota'] = 'PÜ limithányad elérés - {1}';
$l['emailsubject_changeemail'] = 'Email cím csere - {1}';
$l['emailsubject_newpm'] = 'Új PÜ érkezett {1} - {2}';
$l['emailsubject_newjoinrequest'] = 'Új csatlakozási kérelem {1}-nál';
$l['emailsubject_sendtofriend'] = 'Talán érdekelhet ez az oldal: {1}';
$l['emailsubject_changepassword'] = 'Jelszócsere {1}-nál';
$l['emailbit_viewthread'] = '... (a téma tovább olvasása..)';
$l['email_lostpw'] = '{1},



Jelszó emlékeztetést kértél a(z) {2} oldalon. Kattints a következő linkre:



{3}/member.php?action=resetpassword&uid={4}&code={5}



Ha ezt a linket nem sikerül betölteni, menj a következő oldalra:



{3}/member.php?action=resetpassword



Ott add meg az alábbi adatokat:

Felhasználónév: {1}

Aktiváló kód: {5}



Köszönettel,

{2} adminisztrátora';
$l['email_lostpw1'] = '{1},



A jelszavad cseréjének befejezéséhez {2} oldalon, kattints a következő linkre:



{3}/member.php?action=resetpassword&uid={4}&code={5}



Ha ezt a linket nem sikerül betölteni, menj a következő oldalra:



{3}/member.php?action=resetpassword



Ott add meg az alábbi adatokat:

Email címed

Aktiváló kód: {5}



Köszönettel,

{2} adminisztrátora';
$l['email_lostpw2'] = '{1},



A jelszavad cseréjének befejezéséhez {2} oldalon, kattints a következő linkre:



{3}/member.php?action=resetpassword&uid={4}&code={5}



Ha ezt a linket nem sikerül betölteni, menj a következő oldalra:



{3}/member.php?action=resetpassword

Ott add meg az alábbi adatokat:

Felhasználónév: {1} (vagy az email címed)

Aktiváló kód: {5}



Köszönettel,

{2} adminisztrátora';
$l['email_randompassword'] = '{1},



Köszönjük, hogy regisztráltál oldalunkon amely a {2}. Itt találod a felhasználóneved és a létrehozott jelszót. Jelentkezz be {2}, hogy profilod beállíthasd.



Felhasználónév: {3}

Jelszó: {4}



Ajánlott már az első bejelentkezéskor a jelszavad megváltoztatni. Ahhoz, hogy jelszavad megváltoztasd bejelentkezés után a Felhasználói vezérlőpulton(Vezérlőpult) keresd meg a Jelszó módosítás funkciót.



{2} admin';
$l['email_randompassword1'] = '{1},



Köszönjük regisztrációdat a(z) {2} oldalon. A belépéshez a felhasználónevedre és a véletlenszerűen generált jelszavadra van szükség.

A {2} oldalra való belépéshez a következőkre lesz szükséged: 





Email címed

Jelszó: {4}



Ajánlott már az első bejelentkezéskor a jelszavad megváltoztatni. Ahhoz, hogy jelszavad megváltoztasd bejelentkezés után a Felhasználói vezérlőpulton(Vezérlőpult) keresd meg a Jelszó módosítás funkciót.





Köszönettel,

{2} admin';
$l['email_randompassword2'] = '{1},



Köszönjük regisztrációdat a(z) {2} oldalon. A belépéshez a felhasználónevedre és a véletlenszerűen generált jelszavadra van szükség.

A {2} oldalra való belépéshez a következőkre lesz szükséged:





Felhasználónév: {3} (vagy az email címed)

Jelszó: {4}



Ajánlott már az első bejelentkezéskor a jelszavad megváltoztatni. Ahhoz, hogy jelszavad megváltoztasd bejelentkezés után a Felhasználói vezérlőpulton(Vezérlőpult) keresd meg a Jelszó módosítás funkciót.





Köszönettel,

{2} admin';
$l['email_reportpost'] = '{1} itt: {2} jelentette ezt a hozzászólást:



{3}

{4}/{5}



A beküldő felhasználó ezt az indoklást adta a jelentéshez:

{7}



Ezt az üzenetet elküldtük az összes moderátornak a fórumban, vagy minden adminisztrátornak és szuper moderátornak, ha nincsenek moderátorok.



Kérem ellenőrizzék ezt az üzenetet, amilyen hamar csak lehetséges.';
$l['email_passwordreset'] = 'Kedves {1},



A régi jelszavadat a(z) {2} oldalán töröltük.



Az új jelszavad: {3}



Ezzel a jelszóval bejelentkezhetsz a fórumba, de célszerű az első bejelentkezéskor a Felhasználói vezérlőpulton(Vezérlőpult) megváltoztatni.





{2} admin';
$l['email_sendtofriend'] = 'Szia,



{1} a(z) {2} fórumról úgy gondolta, hogy érdekelhet a következő oldal:



{3}



{1} a következő üzenetet küldte:

------------------------------------------

{4}

------------------------------------------





{2} admin';
$l['email_forumsubscription'] = '{1},



{2} új témát indított a(z) {3} fórumban. Feliratkoztál erre a fórumra a következő oldalon: {4}.



A téma címe: {5}



Kivonat az üzenetből:

--

{6}

--



Megtekintheted a témát itt:

{7}/{8}



Itt lehet, hogy találsz újabb témákat és hozzászólásokat amik érdekelnek. Addig nem kapsz újabb üzenetet, amíg el nem látogatsz az oldalra.



Köszönettel,

{4} admin



------------------------------------------

Leiratkozási Információk:



Ha nem szeretnél tovább értesítéseket kapni az új témákról a fórumban, látogasd meg a következő URL-t:

{7}/usercp2.php?action=removesubscription&type=forum&fid={9}&my_post_key={10}



------------------------------------------';
$l['email_activateaccount'] = '{1},



Regisztrációd befejezéséhez a(z) {2} oldalán, látogass el a következő címre:



{3}/member.php?action=activate&uid={4}&code={5}



Ha a linket valamiért nem tudod megtekinteni, menj a következő oldalra:



{3}/member.php?action=activate



Az oldalon add meg az alábbi adatokat:



Felhasználónév: {1}

Aktivációs kód: {5}





{2} admin';
$l['email_activateaccount1'] = '{1},



Regisztrációd befejezéséhez a(z) {2} oldalán, látogass el a következő címre:



{3}/member.php?action=activate&uid={4}&code={5}



Ha a linket valamiért nem tudod megtekinteni, menj a következő oldalra:



{3}/member.php?action=activate



Az oldalon add meg az alábbi adatokat:



Email címed



Aktivációs kód: {5}





{2} admin';
$l['email_activateaccount2'] = '{1},



Regisztrációd befejezéséhez a(z) {2} oldalán, látogass el a következő címre:



{3}/member.php?action=activate&uid={4}&code={5}



Ha a linket valamiért nem tudod megtekinteni, menj a következő oldalra:



{3}/member.php?action=activate



Az oldalon add meg az alábbi adatokat:



Felhasználónév: {1} (vagy az email címed)



Aktivációs kód: {5}







{2} admin';
$l['email_subscription'] = 'Kedves {1},

{2} új választ írt egy témában, amelyre feliratkoztál a(z) {3} fórumon.

A téma címe: {4}.

Részlet az üzenetből:
------------------------------------------
{5}
------------------------------------------

Ahhoz, hogy megtekintsd a témát, látogasd meg a következő URL-t:
{6}/{7}

Itt lehet, hogy találsz újabb témákat és hozzászólásokat, melyek érdekelhetnek. Addig nem kapsz újabb üzenetet amíg el nem látogatsz az oldalra.

Köszönettel,
{3} admin

------------------------------------------
Leiratkozási Információk:

Ha nem szeretnél további értesítéseket kapni az új témákról a fórumban, kattints a következő URL-re:
{6}/usercp2.php?action=removesubscription&tid={8}&my_post_key={9}



------------------------------------------';
$l['email_reachedpmquota'] = '{1},



Ez egy automatikusan generált levél. {2} privát üzenetek beérkezett mappája elérte a maximális méretet.



Egy vagy több felhasználó megpróbált Üzenetet küldeni számodra de ez nem sikerült, mivel nincs hely a beérkezett üzenetek mappádban.



Kérlek törölj a tárolt üzenetekből, ne felejtsd el a törölt üzeneteket a \'Szemetes\'-ből is eltávolítani.





Köszönöm,

{2} Adminisztrátor

{3}';
$l['email_changeemail'] = '{1},



Az email cím módosítási kérelmed {2} elfogadásra került (részleteket lásd lent).



Régi email cím: {3}

Új email cím: {4}



Ha ez a változtatás megfelelő, a módosítás aktiválásához {2} látogasd meg a következő URL-t.



{5}/member.php?action=activate&uid={8}&code={6}



Ha ezt a linket valamilyen oknál fogva nem tudod meglátogatni, menj a következő oldalra



{5}/member.php?action=activate



Itt add meg ezeket az adatokat:

Felhasználónév: {7}

Aktiváló kód: {6}



Amennyiben az új email cím aktiválását nem végzed el, úgy a régi email címed marad érvényben.







Köszönöm,

{2} admin

{5}';
$l['email_newpm'] = '{1},



Egy új privát üzenetet kaptál {3} fórumon {2} nevű felhasználótól:



------------------------------------------

{5}

------------------------------------------



A következő linken tudod megnézni, továbbítani vagy válaszolni erre az üzenetre:



{4}/private.php



Jegyezd meg, hogy nem fogsz kapni további új üzenet értesítéseket amíg nem látogatod meg {3}.



Le tudod tiltani az új üzenet értesítéseket a felhasználói fiókod beállításánál, amit a következő linkre kattintva érhetsz el:



{4}/usercp.php?action=options



Köszönettel,

{3} A csapat

{4}';
$l['email_emailuser'] = '{1},



{2} a(z) {3} fórumról a következő üzenetet küldte:

------------------------------------------

{5}

------------------------------------------







Köszönöm,

{3} admin

{4}



------------------------------------------

Nem szeretnél email üzeneteket kapni más felhasználóktól?



Ha nem szeretnéd, hogy más felhasználók email üzenetet küldjenek neked, a vezérlőpultodon kapcsold be az \'Email cím elrejtése\' funkciót:

{4}/usercp.php?action=options



------------------------------------------';
$l['email_changeemail_noactivation'] = '{1},



Kaptunk egy kérelmet a {2} fórumon, hogy megváltoztattad az email címed(részleteket lásd lentebb).



Régi email cím: {3}

Új email cím: {4}



Ez a változás automatikusan feldolgozásra került. Ha nem te kérted ezt a változtatást, kérlek lépj kapcsolatba egy Adminisztrátorral.



Köszönettel,

{2} A csapat

{5}';
$l['email_changepassword'] = '{1},



Azért kapod ezt az emailt mert te vagy valaki hozzáfért a jelszavadhoz és nemrég megváltoztatta a fiókod jelszavát.



Felhasználónév: {1}

Email cím: {2}



Ha nem te kérted ezt a változtatást, kérlek lépj kapcsolatba egy Adminisztrátorral.



Köszönettel,

{3} A csapat

{4}';
$l['email_groupleader_joinrequest'] = '{1},



{2} csatlakozási kérelmet küldött, hogy csatlakoz a {3} a {4} fórumon (lásd alább).



Ok: {5}



A következő linkre kattintva elfogadhatod vagy visszautasíthatod ezt a kérést:



{6}/managegroup.php?gid={7}



Köszönettel,

{4} A csapat';
$l['email_contact_subject'] = 'Kapcsolat: {1}';
$l['email_contact'] = 'Email: {1}

Fórum profil: {2}

IP cím: {3}

Üzenet:

{4}';
$l['pmsubject_subscription'] = 'Új válasz {1}-nak/-nek';
$l['pm_subscription'] = '{1},

{2} éppen most válaszolt a témára, amelyre feliratkoztál. A téma címe: {3}.

Íme egy részlet az üzenetből:
------------------------------------------
{4}
------------------------------------------

A téma megtekintéséhez látogasd meg a következő URL-t:
[url]{5}/{6}[/url]

Lehetnek más hozzászólások is a témához, de addig nem fogsz értesítéseket kapni, amíg nem látogatod meg újra a témát.

------------------------------------------
Leiratkozási információk:

Ha nem szeretnél több értesítést kapni a hozzászólásokról ebben a témában, akkor látogasd meg a következő linket:
[url]{5}/usercp2.php?action=removesubscription&tid={7}&my_post_key={8}[/url]
------------------------------------------';
$l['emailsubject_reportprofile'] = 'Jelentett felhazsnáló {1}-nál';
$l['emailsubject_reportreputation'] = 'Jelentett hírnév {1}-nál';
$l['email_reportprofile'] = '{1} jelentette {2}-ból/-ből a következő felhasználót:

{3}
{4}/{5}

Az ok amiért ez a felhasználó jelentette ezt a felhasználót:
{6}

Ez az üzenet el lett küldve ennek a fórum összes moderátorának vagy az összes adminisztrátornak és szuper moderátornak, ha ennek a fórumnak nincsenek moderátorai.

Amint lehetséges, kérlek ellenőrizd ezt a felhasználót.';
$l['email_reportreputation'] = '{1} jelentette {2}-ból/-ből a következő hírnevet:

{3}
{4}/{5}

Az ok amiért ez a felhasználó jelentette ezt a hírnevet:
{6}

Ez az üzenet el lett küldve ennek a fórum összes moderátorának vagy az összes adminisztrátornak és szuper moderátornak, ha ennek a fórumnak nincsenek moderátorai.

Amint lehetséges, kérlek ellenőrizd ezt a hírnevet.';
$l['email_broken_task_subject'] = '???MyBB feladat hiba a következőnél: {1}';
$l['email_broken_task'] = '???A MyBB verziód a {1} ({2}) futtatása közben hibát észlelt .........

Hiányzó feladat fájl a következőhöz: {3}

A feladat letiltottuk a probléma megoldásáig.';
$l['email_report_comment_extra'] = '{1}: {2}';
