<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian (Magyar)
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://community.mybb.com/mods.php?action=view&pid=441
// Compatible version of MyBB : 1810 Béta
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sat, 14 Jan 2017 09:12:51 +0000
// --------------------------------------------------------------------------------

$l['nav_helpdocs'] = 'Súgó dokumentumok';
$l['nav_smilies'] = 'Hangulatjelek lista';
$l['nav_syndication'] = 'Legfrissebb téma hírforrás (RSS)';
$l['aol_im'] = 'AOL IM';
$l['skype'] = 'Skype';
$l['yahoo_im'] = 'Yahoo IM';
$l['skype_center'] = 'Skype központ';
$l['skype_status'] = 'Skype állapot';
$l['chat_on_skype'] = 'Chatelés {1}-val/vel Skypeon';
$l['call_on_skype'] = '{1} felhívása Skypeon';
$l['yahoo_center'] = 'Yahoo! Központ';
$l['send_y_message'] = 'Küldj {1} részére egy Yahoo! üzenetet.';
$l['view_y_profile'] = '{1} Yahoo! profiljának megtekintése.';
$l['aim_center'] = 'AOL IM Központ';
$l['download_aim'] = 'AIM letöltése';
$l['aim_remote'] = 'AIM Remote';
$l['send_me_instant'] = 'Küldj nekem egy üzenetet';
$l['add_me_buddy_list'] = 'Adj hozzá a barátok listádhoz';
$l['add_remote_to_page'] = 'Remote hozzáadása az oldaladhoz';
$l['download_aol_im'] = 'AOL Instant Messenger letöltése';
$l['buddy_list'] = 'Barátok listája';
$l['online'] = 'Jelen van';
$l['online_none'] = '<em>Nincs \'Elérhető\' barátok</em>';
$l['offline'] = 'Nincs itt';
$l['offline_none'] = '<em>Nincs \'Nem elérhető\' barátok</em>';
$l['delete_buddy'] = 'X';
$l['pm_buddy'] = 'PÜ küldése';
$l['last_active'] = '<strong>Utoljára aktív:</strong> {1}';
$l['close'] = 'Bezár';
$l['no_buddies'] = '<em>A barátlistád jelenleg üres. Használd a Vezérlőpultot, vagy látogass meg egy felhasználói profilt barátok hozzáadásához.</em>';
$l['help_docs'] = 'Súgó dokumentumok';
$l['search_help_documents'] = 'Keresés a súgó dokumentumokban';
$l['search_by_name'] = 'Keresés név alapján';
$l['search_by_document'] = 'Keresés dokumentum alapján';
$l['enter_keywords'] = 'Keresendő szavak megadása';
$l['search'] = 'Keresés - Angol szavak alapján';
$l['redirect_searchresults'] = 'Köszönjük, keresésed sikerrel járt, most visszairányítunk az eredmények listájához.';
$l['search_results'] = 'Keresési eredmények';
$l['help_doc_results'] = 'Súgó dokumentum eredmények';
$l['document'] = 'Dokumentum';
$l['error_nosearchresults'] = 'Elnézést, de a keresett információ nem található. Kérlek próbáld újra egy másik szóval vagy kifejezéssel.';
$l['no_help_results'] = 'Elnézését, de keresett információ nem található.';
$l['error_helpsearchdisabled'] = 'A súgó dokumentumokban való keresés lehetőségét az Adminisztrátor letiltotta.';
$l['smilies_listing'] = 'Hangulatjelek Lisája';
$l['name'] = 'Név';
$l['abbreviation'] = 'Rövidítés';
$l['click_to_add'] = 'Kattints a hangulatjelre az üzenetben való elhelyezéshez.';
$l['close_window'] = 'ablak bezárás';
$l['who_posted'] = 'Ki üzent?';
$l['total_posts'] = 'Összes üzenet:';
$l['user'] = 'Felhasználó';
$l['num_posts'] = '# üzenet';
$l['forum_rules'] = '{1} - Szabályok';
$l['error_invalid_limit'] = 'Az adat érvénytelen.';
$l['syndication'] = 'Legfrissebb téma hírforrás';
$l['syndication_generated_url'] = 'A számodra generált Hírforrás URL:';
$l['syndication_note'] = 'Itt tudsz speciálisan a saját részedre generált RSS hírforrás linket készíteni. A linket generálhatod az összes fórumról, valamely fórumról, vagy speciálisan bizonyos számú fórumokról. Ha a linket beilleszted egy bármilyen RSS hírolvasó programba közvetlenűl olvashatod a kiválasztott fórumok legújabb hozzászólásait, ilyen például a <a href="http://www.sharpreader.net/">SharpReader</a>. <i><a href="http://www.xml.com/pub/a/2002/12/18/dive-into-xml.html">Mi az-az RSS?</a></i>';
$l['syndication_forum'] = 'Fórumból hírforrás:';
$l['syndication_forum_desc'] = 'Válaszd ki a számodra megfelelő fórumot. A CTRL billentyű lenyomásával több fórumot is választhatsz.';
$l['syndication_version'] = 'Feed verzió:';
$l['syndication_version_desc'] = 'Kérlek válaszd ki a számodra megfelelő feed verziót.';
$l['syndication_version_atom1'] = 'Atom 1.0';
$l['syndication_version_rss2'] = 'RSS 2.00 (Alapértelmezett)';
$l['syndication_generate'] = 'Hírforrás URL generálás';
$l['syndication_limit'] = 'Limit:';
$l['syndication_limit_desc'] = 'Kérlek válaszd ki, hogy a hírolvasó egyszerre hány hozzászólást töltsön le. Nem ajánlott 50-nél több.';
$l['syndication_threads_time'] = 'hozzászólás egyszerre';
$l['syndicate_all_forums'] = 'Hírforrás minden fórumról';
$l['redirect_markforumread'] = 'A kiválasztott fórum megjelölve olvasottként.';
$l['redirect_markforumsread'] = 'Összes fórum megjelölve olvasottként.';
$l['redirect_forumpasscleared'] = 'A tárolt jelszavak törölve.';
$l['redirect_cookiescleared'] = 'Sütik törölve.';
$l['error_invalidimtype'] = 'Ennek a felhasználónak nincs ilyen üzenetküldő(messenger) típus meghatározva a profiljában.';
$l['error_invalidhelpdoc'] = 'Nincs ilyen súgó dokumentum.';
$l['dst_settings_updated'] = 'Téli-nyári időszámítás automatikusan beállítva.<br /><br />Visszairányítunk a fórum főoldalára.';
$l['error_invalidforum'] = 'Nem létező/érvénytelen fórum';
$l['error_invalidsearch'] = 'Hibásan megadott keresi feltételek. Kérlek lépj vissza és próbáld újra.';
$l['error_no_search_support'] = 'Ez az adatbázis motor nem támogatja a keresést.';
$l['error_searchflooding'] = 'Elnézést, de {1} másodpercen belül csak egy keresést indíthatsz. Kérlek várj {2} másodpercet a következő keresésed indításáig.  ';
$l['error_searchflooding_1'] = 'Elnézést, de {1} másodpercen belül csak egy keresést indíthatsz. Kérlek várj 1 másodpercet a következő keresésed indításáig.  ';
$l['no_smilies'] = 'Jelenleg nincsenek elérhető hangulatjelek.';
