<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 15 Mar 2015 06:31:13 +0000
// --------------------------------------------------------------------------------

$l['nav_newreply'] = 'Válasz';
$l['post_reply_to'] = 'Az üzenetre válaszolt {1}';
$l['post_new_reply'] = 'Új válasz';
$l['reply_to'] = 'Válasz erre a témára: {1}';
$l['post_subject'] = 'Üzenet tárgya:';
$l['your_message'] = 'Üzeneted:';
$l['post_options'] = 'Üzenet beállítások:';
$l['options_sig'] = '<b>Aláírás</b>: aláírás beillesztése. (csak regisztrált felhasználók)';
$l['options_emailnotify'] = '<b>Email értesítés</b>: értesítsen emailben ha válasz érkezik az üzenetre. (csak regisztrált felhasználók)';
$l['options_disablesmilies'] = '<b>Hangulatjelek tiltása</b>: a hangulatjelek tiltása az üzenetben.';
$l['post_reply'] = 'Küld';
$l['preview_post'] = 'Előnézet';
$l['mod_options'] = 'Moderátor beállítások:';
$l['close_thread'] = '<b>Téma lezárás</b>: nem lehet a témába új üzeneteket írni.';
$l['stick_thread'] = '<b>Téma címkézés:</b> ennek a témának a hozzáadása a kedvenc fórumokhoz.';
$l['forum_rules'] = '{1} - Szabályok';
$l['thread_review'] = 'Téma áttekintés (újabbak elöl)';
$l['thread_review_more'] = 'Ebben a témában jelenleg {1} válasz van. <a href="{2}">A teljes téma olvasása.</a>';
$l['posted_by'] = 'Szerző';
$l['draft_saved'] = 'A téma sikeresen mentve és elküldve.<br />Most visszairányítunk a fórum témákhoz.';
$l['image_verification'] = 'Kép ellenőrzés';
$l['verification_note'] = 'Kérlek írd be a képen látható szöveget.';
$l['verification_subnote'] = '(kis- és nagybetű érzéketlen)';
$l['invalid_captcha'] = 'Az ellenőrzőkód, amelyet megadtál helytelen. Kérlek add meg a helyes kódot, ahogyan az a képen látható.';
$l['error_post_already_submitted'] = 'A hozzászólás már el lett küldve.';
$l['multiquote_external_one'] = 'Egy témán kívüli hozzászólást is kijelölést.';
$l['multiquote_external'] = 'Kijelöltél {1} hozzászólást a témán kívül.';
$l['multiquote_external_one_deselect'] = 'kijelölés visszavonása';
$l['multiquote_external_deselect'] = 'kijelölések visszavonása';
$l['multiquote_external_one_quote'] = 'Idézze ezt a hozzászólást is';
$l['multiquote_external_quote'] = 'Idézze ezeket a hozzászólásokat is';
$l['redirect_newreply'] = 'Köszönjük, hozzászólásod elküldésre került.';
$l['redirect_newreply_moderation'] = '<br />Minden új hozzászólást az adminisztrátor egyedileg hagy jóvá. Most visszairányítunk a témához.';
$l['redirect_newreply_post'] = '<br />Visszairányítunk a hozzászólásodhoz.';
$l['redirect_newreplyerror'] = 'HIBA: A hozzászólásod túl kevés karaktert tartalmaz. Kérlek írj többet. <br />Visszairányítunk a témához.';
$l['redirect_threadclosed'] = 'Nem írhatsz hozzászólást mert a téma le lett zárva.';
$l['error_post_noperms'] = 'Nincs jogosultságod ezt a vázlatot szerkeszteni.';
$l['error_stop_forum_spam_spammer'] = 'Elnézést, de a {1} vagy IP címed megegyezik egy ismert spammerrel. Ha úgy érzed, hogy ez tévedés, kérlek lépj kapcsolatba egy adminisztrátorral.';
$l['error_stop_forum_spam_fetching'] = 'Elnézést, de hiba történet a válaszod spammer adatbázisban történő ellenőrzése közben. Legvalószínűbb, hogy az adatbázis nem hozzáférhető. Kérlek próbáld meg később.';
$l['error_suspendedposting'] = 'Hozzászólási engedélyedet jelenleg felfüggesztették {1}.<br /><br />



Felfüggesztés dátuma: {2}';
$l['error_suspendedposting_temporal'] = '{1} -ig';
$l['error_suspendedposting_permanent'] = 'véglegesen';
