<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://community.mybb.com/mods.php?action=view&pid=441
// Compatible version of MyBB : 1807 Béta
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 13 Mar 2016 10:09:40 +0000
// --------------------------------------------------------------------------------

$l['nav_newthread'] = 'Új téma';
$l['newthread_in'] = 'Új téma itt: {1}';
$l['post_new_thread'] = 'Új téma indítása';
$l['thread_subject'] = 'Téma tárgya';
$l['your_message'] = 'Üzeneted:';
$l['post_options'] = 'Üzenet beállítások:';
$l['options_sig'] = '<b>Aláírás</b>: aláírás beillesztése. (csak regisztrált felhasználók)';
$l['options_emailnotify'] = '<b>Email értesítés</b>: értesítsen emailban ha válasz érkezik a témába. (csak regisztrált felhasználók)';
$l['options_disablesmilies'] = '<b>Hangulatjelek tiltása</b>: a hangulatjelek tiltása a hozzászólásokban.';
$l['post_thread'] = 'Küld';
$l['preview_post'] = 'Előnézet';
$l['poll'] = 'Szavazás';
$l['poll_desc'] = 'Szavazás csatolása ehhez a témához.';
$l['poll_check'] = 'Az üzenethez szavazást csatolok';
$l['num_options'] = 'Lehetséges válaszok száma:';
$l['max_options'] = '(Maximum: {1})';
$l['mod_options'] = 'Moderátor beállítások:';
$l['close_thread'] = '<b>Téma lezárás</b>: nem lehet a témába új üzeneteket írni.';
$l['stick_thread'] = '<b>Téma kiemelés:</b> ennek a témának a hozzáadása a kedvenc fórumokhoz.';
$l['draft_saved'] = 'A téma sikeresen mentve és elküldve.<br />Most visszairányítunk a fórum témákhoz.';
$l['image_verification'] = 'Kép ellenőrzés';
$l['verification_note'] = 'Kérlek írd be a képen látható szöveget.';
$l['verification_subnote'] = '(kis- és nagybetű érzéketlen)';
$l['invalid_captcha'] = 'Hibásan adtad meg a képellenőrző kódot. Kérlek add meg a kódot helyesen.';
$l['error_post_already_submitted'] = 'Már egyszer elküldted ezt a témát ebben a fórumban.';
$l['no_prefix'] = 'Nincs előtag';
$l['forum_rules'] = '{1} - Szabályzat';
$l['multiquote_external_one'] = 'Egy hozzászólást egy másik témából választottál.';
$l['multiquote_external'] = '{1} hozzászólást másik témából választottál.';
$l['multiquote_external_one_deselect'] = 'kijelölés megszüntetése';
$l['multiquote_external_deselect'] = 'kijelölés megszüntetése';
$l['multiquote_external_one_quote'] = 'Idézze ezt a hozzászólást is';
$l['multiquote_external_quote'] = 'Idézze ezeket a hozzászólásokat is';
$l['redirect_newthread'] = 'Az új téma elküldésre került.';
$l['redirect_newthread_poll'] = '<br />Átirányítunk a szavazás oldalra.';
$l['redirect_newthread_moderation'] = '<br />Az új témát egy adminisztrátornak jóvá kell hagynia. Átirányítunk a téma listázáshoz.';
$l['redirect_newthread_thread'] = '<br />Átirányítunk az új témához.';
$l['invalidthread'] = 'A megadott vázlat nem létezik, vagy nincs jogosultságod a megtekintéséhez.';
$l['error_stop_forum_spam_spammer'] = 'Elnézést, de a {1} vagy IP címed spammerként van nyilvántartva. Ha úgy érzed, hogy ez tévedés akkor lépj kapcsolatba egy adminisztrátorral';
$l['error_stop_forum_spam_fetching'] = 'Elnézést, de hiba történet a témád spammer adatbázisban történő ellenőrzése közben. Legvalószínűbb, hogy az adatbázis nem hozzáférhető. Kérlek próbáld meg később..';
$l['error_suspendedposting'] = 'Az üzenetküldési jogod pillanatnyilag fel van függesztve {1}.<br /><br />



Felfüggesztés dátuma: {2}';
$l['error_suspendedposting_temporal'] = '{1} -ig';
$l['error_suspendedposting_permanent'] = 'véglegesen';
$l['redirect_newthread_unviewable'] = '<br />Nincs engedélyed megtekinteni a témákat ebben a fórumban. Most visszairányítunk.';
