<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1801
// Last edited in MyBB Editor by : Sz.Gabor
// Last edited date : Thu, 05 Mar 2015 15:28:14 +0000
// --------------------------------------------------------------------------------

$l['nav_online'] = 'Ki van jelen?';
$l['nav_onlinetoday'] = 'Kik voltak ma itt';
$l['viewing_announcements'] = 'Ezt a közleményt olvassa: <a href="{1}">{2}</a>';
$l['viewing_announcements2'] = 'Közleményt olvas';
$l['viewing_attachment'] = 'A csatolások panelt nézi';
$l['viewing_attachment2'] = 'A <a href="attachment.php?aid={1}">csatolásokat</a> nézi a következő témában: <a href="{3}">{2}</a>';
$l['viewing_calendar'] = 'A <a href="calendar.php">Naptárat</a> tekinti meg';
$l['viewing_event'] = 'Az események panelt tekinti meg';
$l['viewing_event2'] = 'A/az <a href="{1}">{2}</a> eseményt tekinti meg';
$l['adding_event'] = '<a href="calendar.php?action=addevent">Esemény hozzáadás</a>';
$l['editing_event'] = 'Esemény módosítás';
$l['viewing_contact_us'] = 'Nézi a <a href="contact.php">Kapcsolat</a>-ot';
$l['editing_post'] = 'Üzenet módosítás';
$l['viewing_forum'] = 'Fórum megtekintés';
$l['viewing_forum2'] = 'Olvassa a <a href="{1}">{2}</a> fórumot';
$l['forum_redirect_to'] = 'Visszairányításra kerül ide: <a href="{1}">{2}</a>';
$l['viewing_index'] = '{1} <a href="index.php">Kezdőlap</a>';
$l['activating_account'] = 'Fiók aktiválás';
$l['viewing_profile'] = 'Profil megtekintés';
$l['viewing_profile2'] = 'Nézi <a href="{1}">{2}</a> profilját';
$l['registering'] = '<a href="member.php?action=register">Regisztráció</a>';
$l['logging_in'] = '<a href="member.php?action=login">Bejelentkezés</a>';
$l['logging_in_plain'] = 'Bejelentkezés';
$l['logging_out'] = 'Kilépés';
$l['emailing_user'] = 'Email küldés a felhasználónak';
$l['rating_user'] = 'Felhasználó értékelés';
$l['viewing_memberlist'] = 'A <a href="memberlist.php">tagok listáját</a> olvassa.';
$l['viewing_whoposted'] = 'Olvassa az új üzeneteket';
$l['viewing_whoposted2'] = 'Olvassa az új üzeneteket a <a href="{1}">{2}</a> témában';
$l['marking_read'] = '<a href="misc.php?action=markread&amp;my_post_key={1}">Fórumok megjelölése olvasottként</a>';
$l['viewing_helpdocs'] = 'Olvassa a <a href="misc.php?action=help">súgót</a>';
$l['viewing_buddylist'] = 'Nézi a <a href="misc.php?action=buddypopup">barátok listáját</a>';
$l['viewing_smilies'] = 'Megtekinti a <a href="misc.php?action=smilies">hangulatjelek listáját</a>';
$l['viewing_syndication'] = 'Nézi az <a href="misc.php?action=syndication">RSS hírforrás</a> oldalt.';
$l['replying_thread'] = 'Téma választ ír';
$l['replying_thread2'] = 'Választ ír a <a href="{1}">{2}</a> témában';
$l['posting_thread'] = 'Új témát ír';
$l['posting_thread2'] = 'Új témát ír a <a href="{1}">{2}</a> fórumban.';
$l['viewing_wol'] = 'Megtekinti a <a href="online.php">Ki van jelen?</a> listát.';
$l['viewing_woltoday'] = 'Nézi a <a href="online.php?action=today">Ki volt jelen ma</a> listát.';
$l['creating_poll'] = 'Új szavazást készít';
$l['editing_poll'] = 'Szavazást módosít';
$l['viewing_pollresults'] = 'A szavazás eredményét nézi';
$l['voting_poll'] = 'Szavazást értékel';
$l['using_modtools'] = 'Moderátor funkciót végez';
$l['sending_pm'] = 'Privát üzenetet küld';
$l['reading_pm'] = 'Privát üzenetet olvas';
$l['editing_pmfolders'] = 'PÜ mappát módosít';
$l['using_pmsystem'] = 'A PÜ rendszerben van';
$l['reporting_post'] = 'Hozzászólásról jelentést ír';
$l['searching_forum'] = '<a href="search.php">Keres</a> {1}';
$l['reading_thread'] = 'Témát olvas';
$l['reading_thread2'] = 'A <a href="{1}">{2}</a> {3} témát olvassa.';
$l['viewing_team'] = 'A Fórum üzemeltetők listáját nézi';
$l['viewing_stats'] = 'A fórum statisztikát olvassa';
$l['updating_profile'] = '<a href="usercp.php?action=profile">Profilt frissít</a>';
$l['updating_options'] = '<a href="usercp.php?action=options">Beállításokat frissít</a>';
$l['editing_signature'] = '<a href="usercp.php?action=editsig">Aláírást módosít</a>';
$l['changing_avatar'] = '<a href="usercp.php?action=avatar">Avatart választ</a>';
$l['viewing_subscriptions'] = 'Olvassa a <a href="usercp.php?action=subscriptions">téma feliratkozásokat</a>';
$l['viewing_favorites'] = 'Olvassa a <a href="usercp.php?action=favorites">kedvenc témákat</a>';
$l['editing_pad'] = 'Ír a <a href="usercp.php?action=notepad">személyes jegyzettömbbe</a>';
$l['editing_password'] = '<a href="usercp.php?action=password">Jelszót</a> módosít';
$l['user_cp'] = 'Megtekinti a <a href="usercp.php">felhasználó kezelőpultot</a>';
$l['viewing_portal'] = 'A <a href="portal.php">portál</a> oldalon van';
$l['viewing_noperms'] = 'Megtekinti a nem engedélyezett oldalt';
$l['unknown_location'] = '<a href="{1}">Ismeretlen helyen van</a>';
$l['giving_reputation'] = 'Értékelést ad: <a href="{1}">{2}</a>';
$l['viewing_reputation_report'] = '<a href="{1}">{2} értékelését nézi</a>';
$l['viewing_reputation_report2'] = 'Értékelést néz';
$l['member_resendactivation'] = 'Fiók aktiváló e-mail újraküldése';
$l['member_lostpw'] = ' <a href="member.php?action=lostpw">Jelszó visszaállítás</a>';
$l['sending_thread'] = 'Téma elküldése egy barátnak.';
$l['guest'] = 'Vendég';
$l['page'] = 'Oldal';
$l['users_online'] = 'Ki van jelen';
$l['on_username'] = 'Felhasználónév';
$l['time'] = 'Idő';
$l['location'] = 'Tartózkodási hely';
$l['online_today'] = 'Kik voltak itt ma';
$l['refresh_page'] = 'Oldal frissítése';
$l['online_online_plural'] = 'felhasználók';
$l['online_online_singular'] = 'felhasználó';
$l['online_member_plural'] = 'tagok';
$l['online_member_singular'] = 'tag';
$l['online_anon_plural'] = ' '; /*1 felhasználó volt aktív az utolsó 15 percben (1 tag, ebből 0 $l['online_anon_plural'] = ' ' rejtett, és 0 vendég).
*/
$l['online_anon_singular'] = 'is???';
$l['online_guest_plural'] = 'vendégek';
$l['online_guest_singular'] = 'vendég';
$l['online_count'] = '{1} {2} volt aktív az utolsó {3} percben ({4} {5}, {6} ebből {7} rejtve, és {8} {9}).';
$l['ip'] = 'IP:';
$l['resolves_to'] = 'Felold:';
$l['if_resolvable'] = '(ha feloldva)';
$l['admin_options'] = 'Admin beállítások:';
$l['search_regip_users'] = 'Felhasználók keresése, akik erről az IP-ről regisztráltak';
$l['search_postip_users'] = 'Felhasználók keresése, akik erről az IP-ről írtak üzenetet';
$l['lookup'] = '[kikeresés]';
$l['member_online_today'] = '<strong>1</strong> felhasználó volt ma itt';
$l['members_were_online_today'] = '<strong>{1}</strong> felhasználó volt ma itt';
$l['member_online_hidden'] = ' ({1} felhasználó volt nem látható)';
$l['members_online_hidden'] = ' ({1} felhasználó volt nem látható)';
$l['rating_thread'] = 'Téma értékelés';
$l['viewing_imcenter'] = 'IM központ megtekintése';
$l['managing_favorites'] = 'Kedvenc témák kezelése';
$l['managing_subscriptions'] = 'Feliratkozások kezelése';
$l['managing_group'] = 'Felhasználói csoport kezelése';
$l['viewing_modcp'] = 'Moderációs vezérlőpult megtekintése';
$l['viewing_modlogs'] = 'Moderátor naplók megtekintése';
$l['managing_announcements'] = 'Közlemények kezelése';
$l['search_for_user'] = 'Felhasználók keresése';
$l['managing_warninglogs'] = 'Figyelmeztetés naplók kezelése';
$l['searching_ips'] = 'IP címek keresése';
$l['viewing_reports'] = 'Jelentések megtekintése';
$l['adding_announcement'] = 'Közlemény hozzáadása';
$l['deleting_announcement'] = 'Közlemény törlése';
$l['editing_announcement'] = 'Közlemény szerkesztése';
$l['managing_modqueue'] = 'Moderációs sor kezelése';
$l['editing_user_profiles'] = 'Felhasználói profil szerkesztése';
$l['managing_bans'] = 'Kitiltások kezelése';
$l['revoking_warning'] = 'Kitiltás visszavonása';
$l['warning_user'] = 'Felhasználó figyelmeztetése';
$l['viewing_warning'] = 'Nézi a figyelmeztetést ???';
$l['managing_warnings'] = 'Figyelmeztetések kezelése';
$l['changing_dst'] = 'DST kapcsoló megváltoztatása';
$l['printing_thread'] = 'Téma nyomtatása';
$l['printing_thread2'] = 'Téma nyomtatása: <a href="{1}">{2}</a>';
$l['managing_buddyignorelist'] = 'Barátok-mellőzöttek listájának kezelése';
