<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://community.mybb.com/mods.php?action=view&pid=441
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 20 Sep 2015 07:13:24 +0000
// --------------------------------------------------------------------------------

$l['nav_postpoll'] = 'Üzenet szavazás';
$l['nav_editpoll'] = 'Szavazás módosítás';
$l['nav_pollresults'] = 'Szavazás eredmények';
$l['edit_poll'] = 'Szavazás módosítás';
$l['delete_poll'] = 'Szavazás törlése';
$l['delete_q'] = 'Törlöd?';
$l['delete_note'] = 'Ahhoz, hogy töröld a szavazást, rakj egy pipát a baloldali négyzetbe és nyomd meg a gombot a jobboldalon.';
$l['delete_note2'] = '<b>Megjegyzés:</b> Ha a szavazást törölted, többé nem lehet visszaállítani.';
$l['question'] = 'Kérdés:';
$l['num_options'] = 'Válasz beállítások:';
$l['max_options'] = 'Maximum:';
$l['poll_options'] = 'Szavazás beállítások:';
$l['update_options'] = 'Beállítások frissítése';
$l['poll_options_note'] = 'A szavazás feltétele, hogy a feltett kérdésre lehessen válaszolni.';
$l['options'] = 'Beállítások:';
$l['option_multiple'] = '<b>Többszörös szavazás engedélyezése:</b> A felhasználók többször is szavazhatnak.';
$l['option_multiple_maxoptions'] = 'Maximum opciók száma felhasználókként (0 nincs korlát):';
$l['option_public'] = '<b>Publikus szavazás:</b> A felhasználók láthatják, hogy ki mire szavazott.';
$l['option_closed'] = '<b>Szavazás lezárva:</b> Ha ide pipát teszel lezárod a szavazást.';
$l['poll_timeout'] = 'Szavazás lezárul:';
$l['timeout_note'] = 'A napok száma ameddig a felhasználók leadhatják szavazatukat.<br />(Ha az érték itt 0 a szavazás soha nem zárul le.)';
$l['days_after'] = 'hátralévő napok száma:';
$l['update_poll'] = 'Szavazás frissítése';
$l['option'] = 'Válasz';
$l['votes'] = 'Szavazat:';
$l['post_new_poll'] = 'Új szavazás indítása';
$l['days'] = 'napok';
$l['poll_results'] = 'Szavazás eredményei';
$l['poll_total'] = 'Összes:';
$l['poll_votes'] = 'szavazat';
$l['redirect_pollposted'] = 'A szavazás létrehozva.<br />Visszairányítunk a témához.';
$l['redirect_pollpostedmoderated'] = 'A szavazásodat létrehoztuk, de a témád még moderálásra vár.<br />Visszairányítunk a fórumhoz.';
$l['redirect_pollupdated'] = 'A szavazás sikeresen frissítve.<br />Visszairányítunk a témához.';
$l['redirect_votethanks'] = 'Köszönjük, hogy szavaztál.<br />Visszairányítunk a témához.';
$l['redirect_unvoted'] = 'A szavazatod/szavazataid eltávolítva ebből a témából.<br />Visszairányítunk a témához.';
$l['redirect_polldeleted'] = 'A szavazás sikeresen eltávolítva a témából.<br />Visszairányítunk a témához.';
$l['error_polloptiontoolong'] = 'Egy vagy több válasz amelyet megadtál túl hosszú. Kérlek menj vissza és rövidítsd le.';
$l['error_noquestionoptions'] = 'Vagy nem adtál meg kérdést a szavazáshoz, vagy túl kevés válasz lehetőséged van. A minimum megadandó válasz: 2.<br />Kérlek menj vissza és javítsd ezt a hibát.';
$l['error_pollalready'] = 'A témában már van egy szavazás!';
$l['error_nopolloptions'] = 'A megadott válasz érvénytelen vagy nem létezik.';
$l['error_maxpolloptions'] = 'Túl sok opcióra szavaztál. A szavazásnál megengedett opciók száma {1}.<br />Lépj vissza és próbáld újra.';
$l['error_alreadyvoted'] = 'Már szavaztál ebben a témában.';
$l['error_notvoted'] = 'Nem szavaztál még itt.';
$l['error_invalidpoll'] = 'A szavazás érvénytelen vagy nem létezik.';
$l['error_pollclosed'] = 'Nem szavazhatsz! A szavazás lezárva.';
$l['poll_time_limit'] = 'Elnézést, de nem tudsz szavazást hozzáadni a témádhoz. Az adminisztrátor beállította, hogy {1} órával a hozzászólás után lehet hozzáadni a szavazást.';
$l['poll_deleted'] = 'Törölt szavazás';
$l['poll_edited'] = 'Szerkesztett szavazás';
$l['error_polloptionsequence'] = 'A következő sorozat, amelyet egy vagy több szavazat beállításnál megadtál nem használható: <strong>||~|~||</strong>. Kérlek menj vissza és töröld ezt. ';
