<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 15 Mar 2015 06:42:07 +0000
// --------------------------------------------------------------------------------

$l['nav_portal'] = 'Portál';
$l['posted_by'] = 'Szerző:';
$l['forum'] = 'Fórum:';
$l['replies'] = 'Válaszok';
$l['no_replies'] = 'Nincsenek válaszok';
$l['latest_threads'] = 'Legfrissebb üzenetek';
$l['latest_threads_replies'] = 'Válaszok:';
$l['latest_threads_views'] = 'Megtekintések:';
$l['latest_threads_lastpost'] = 'Utolsó üzenet szerzője:';
$l['private_messages'] = 'Privát üzenetek';
$l['pms_received_new'] = '{1}, <b>{2}</b> új üzeneted van az utolsó látogatásod óta.';
$l['pms_unread'] = 'Olvasatlan üzenetek';
$l['pms_total'] = 'Összes üzenet';
$l['search_forums'] = 'Keresés';
$l['advanced_search'] = 'Bővített keresés';
$l['forum_stats'] = 'Fórum statisztikák';
$l['num_members'] = 'Tagok:';
$l['latest_member'] = 'Legújabb tag:';
$l['num_threads'] = 'Fórum témák:';
$l['num_posts'] = 'Fórum üzenetek:';
$l['full_stats'] = 'Teljes Statisztika';
$l['welcome'] = 'Üdvözöllek, {1}';
$l['guest'] = 'Vendég';
$l['guest_welcome_registration'] = '<a href="{1}">Regisztrálnod</a> kell, hogy üzenetet írhass a fórumba.';
$l['username'] = 'Felhasználónév';
$l['password'] = 'Jelszó';
$l['login'] = 'Belépés!';
$l['member_welcome_lastvisit'] = 'Utolsó látogatás:';
$l['since_then'] = 'Mióta itt vagy készült:';
$l['new_announcements'] = '{1} új közlemény';
$l['new_announcement'] = '1 új közlemény';
$l['new_threads'] = '{1} új téma';
$l['new_thread'] = '1 új téma';
$l['new_posts'] = '{1} új üzenet';
$l['new_post'] = '1 új üzenet';
$l['view_new'] = 'Új üzenetek megtekintése';
$l['view_todays'] = 'Mai üzenetek megtekintése';
$l['online'] = 'Jelenlévő felhasználók';
$l['online_user'] = 'Jelenleg 1 felhasználó van online';
$l['online_users'] = 'Jelenleg <b>{1}</b> felhasználó van itt.';
$l['online_counts'] = '<b>{1}</b> Tag | <b>{2}</b> Vendég';
$l['print_this_item'] = 'Nyomtatás';
$l['send_to_friend'] = 'Elküldés egy barátnak';
$l['latest_announcements'] = 'Legutolsó közlemény(ek)';
$l['portal_disabled'] = 'Nem tudod használni a portál funkcióit, mert az Admin letiltotta azt.';
