<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 15 Mar 2015 06:43:24 +0000
// --------------------------------------------------------------------------------

$l['nav_pms'] = 'Privát üzenetek';
$l['nav_send'] = 'Új üzenet írása';
$l['nav_tracking'] = 'Üzenet követés';
$l['nav_folders'] = 'Mappa kezelés';
$l['nav_empty'] = 'Mappák ürítése';
$l['nav_export'] = 'Üzenetek exportálása';
$l['nav_search'] = 'Keresés';
$l['nav_results'] = 'Találatok';
$l['new_pm'] = 'Új üzenet';
$l['old_pm'] = 'Régi üzenet';
$l['reply_pm'] = 'Válaszolva';
$l['fwd_pm'] = 'Továbbított üzenet';
$l['pms_disabled'] = 'Nem használhatod a privát üzenet küldőt, mert tiltott.';
$l['private_messaging'] = 'Privát üzenetek';
$l['inbox'] = 'Beérkezett';
$l['compose_message2'] = 'Új írása';
$l['manage_folders'] = 'Mappák kezelése';
$l['pm_search_results'] = 'Privát üzenet keresési eredmények';
$l['message_title'] = 'Üzenet neve';
$l['sender'] = 'Feladó';
$l['sentto'] = 'Címzett';
$l['date_sent'] = 'Küldési dátum/idő';
$l['desc'] = 'csökkenő';
$l['asc'] = 'növekvő';
$l['delete_pm'] = 'Töröl';
$l['move_to'] = 'Áthelyez';
$l['or'] = 'vagy';
$l['selected_messages'] = 'a kiválasztott üzenetek';
$l['go'] = 'Mehet';
$l['pmspaceused'] = 'PÜ által használt hely.';
$l['jump_folder'] = 'Ugrás a mappához:';
$l['archive_messages'] = 'Exportálás';
$l['archive_note'] = 'Az itt található eszközzel letöltheted az általad kiválasztott mappákat a saját számítógépedre.';
$l['folders'] = 'Mappák:';
$l['all_folders'] = 'Minden mappa';
$l['date_limit'] = 'Dátum limitálás:';
$l['date_limit_older'] = 'Üzenetek exportálása, amelyek öregebbek, mint';
$l['date_limit_newer'] = 'Üzenetek exportálása, amelyek újabbak, mint';
$l['date_limit_disregard'] = 'Dátum figyelmen kívül hagyása';
$l['date_limit_days'] = 'nap';
$l['export_unread'] = 'Olvasatlan üzenetek exportálása?';
$l['delete_archived'] = 'Törlöd az exportált üzeneteket?';
$l['delete_archived_note'] = 'Akarod törölni a mappáidból azokat az üzeneteket, melyeket már egyszer exportáltál?';
$l['export_format'] = 'Exportálás fájlformátuma';
$l['export_format_note'] = 'Kérlek választ fájltípust a letöltéshez.';
$l['export_html'] = 'HTML fájl (.html)';
$l['export_txt'] = 'Szövegfájl (.txt)';
$l['export_csv'] = 'Importált MS Excel fájl (.csv)';
$l['private_messages_for'] = 'Privát üzenetek: {1}';
$l['exported_date'] = 'Exportálva: {1}, {2}';
$l['subject'] = 'Tárgy:';
$l['to'] = 'Címzett:';
$l['from'] = 'Feladó:';
$l['sent'] = 'Elküldve:';
$l['export_messages2'] = 'Üzenetek letöltése';
$l['empty_folders'] = 'Privát üzenet mappák ürítése';
$l['empty_folders2'] = 'Mappák ürítése';
$l['empty_note'] = 'Tényleg törlöd az üzeneteket a kiválasztott mappákból? Egyszerűen válaszd ki a mappát, melyet szeretnél kiűriteni és kattints a \'Törlés\' gombra. Ez a művelet nem vonható vissza.<br /><b>Megjegyzés:</b> Ha egy üzenetet törölsz, többé nem lehet vissza állítani.';
$l['num_messages'] = 'Üzenetek száma:';
$l['empty_q'] = 'Ürít?';
$l['keep_unread'] = 'Olvasatlan üzenetek megtartása';
$l['pm_folders'] = 'Privát üzenet mappák';
$l['existing_folders'] = 'Létező mappák';
$l['edit_folder_note'] = 'Itt tudod módosítani a meglévő mappáidat, és újakat létrehozni. Ha egy mappát törölni akarsz, egyszerűen töröld ki a nevét. Bizonyos mappákat ne törölj, mert szükségesek a működéshez.<br /><b>Megjegyzés:</b> Ha egy mappát törölsz, törlődnek a benne lévő üzenetek is.';
$l['new_folders'] = 'Új mappa készítés';
$l['add_folders_note'] = 'Itt tudsz új mappákat készíteni. Nem szükséges minden mezőt kitölteni.';
$l['update_folders'] = 'Mappák frissítése';
$l['cannot_be_removed'] = 'Ne töröld ezt a mappát';
$l['reached_warning'] = 'Figyelmeztetés. Elérted a maximális üzenetek határát.';
$l['reached_warning2'] = 'Ahhoz hogy üzeneteket fogadhass helyet kell felszabadítanod.';
$l['deny_receipt'] = '[nyugta tiltása]';
$l['viewing_pm'] = 'Nézett PÜ:';
$l['reply'] = 'Válasz';
$l['reply_to_all'] = 'Válasz az összesre';
$l['forward'] = 'Továbbít';
$l['compose_pm'] = 'Új írása';
$l['compose_to'] = 'Címzett:';
$l['compose_bcc'] = 'Másolat (BCC):';
$l['compose_bcc_show'] = 'BCC';
$l['compose_bcc_show_title'] = 'A BCC mező kitöltésével az üzenetet egyszerre több felhasználónak is eltudod küldeni.';
$l['separate_names'] = 'Több felhasználónevet vesszővel válassz el.';
$l['max_recipients'] = '<br />Az üzenetet egyszerre maximum <strong>{1}</strong> felhasználónak küldheted el.';
$l['compose_subject'] = 'Tárgy:';
$l['compose_message'] = 'Üzenet:';
$l['compose_options'] = 'Beállítások:';
$l['message_icon'] = 'Üzenet ikon:';
$l['options_sig'] = '<b>Aláírás:</b> aláírás csatolása az üzenethez.';
$l['options_disable_smilies'] = '<b>Hangulatjelek tiltása:</b> az üzenetben a megjelenő hangulatjelek tiltása.';
$l['options_save_copy'] = '<b>Másolat mentése:</b> másolat mentése a KÜLDÖTT üzenetek mappába.';
$l['options_read_receipt'] = '<b>Olvasási visszaigazolás:</b> olvasási visszaigazolás kérése.';
$l['send_message'] = 'Üzenet küldése';
$l['save_draft'] = 'Mentés piszkozatként';
$l['preview'] = 'Előnézet';
$l['select_buddy'] = 'Vagy barát kiválasztás:';
$l['pm_tracking'] = 'Privát üzenet követés';
$l['read_messages'] = 'Olvasott üzenetek';
$l['unread_messages'] = 'Olvasatlan üzenetek';
$l['q'] = '?';
$l['dateread'] = 'Olvasási dátum';
$l['stop_tracking'] = 'Követés leállítás';
$l['datesent'] = 'Küldés dátum';
$l['cancel'] = 'Mégse';
$l['export_date_sent'] = 'Dátum';
$l['export_folder'] = 'Mappa';
$l['export_subject'] = 'Tárgy';
$l['export_to'] = 'Címzett';
$l['export_from'] = 'Feladó';
$l['export_message'] = 'Üzenet';
$l['not_sent'] = 'N/A (nem küldött)';
$l['at'] = 'idő:';
$l['nomessages'] = 'Nincsenek üzenetek ebben a mappában.';
$l['details'] = 'Részletek';
$l['message'] = 'Üzenet';
$l['buddy_list'] = 'Barátlista';
$l['multiple_recipients'] = '<em>Több címzett</em>';
$l['bcc'] = 'BCC:';
$l['reply_title'] = 'Válasz az üzenetre';
$l['forward_title'] = 'Üzenet továbbítása';
$l['delete_title'] = 'Üzenet törlése';
$l['you_replied_on'] = 'Üzenetre a válasz elküldve: {1}';
$l['you_forwarded_on'] = 'Üzenet továbbítva: {1}';
$l['you_replied'] = 'Válaszoltál az üzenetre {1}';
$l['you_forwarded'] = 'Továbbítottad az üzenetet {1}';
$l['select_from_buddies'] = 'Választás a barát listáról';
$l['no_readmessages'] = 'Jelenleg nincs olvasott üzeneted követve.';
$l['no_unreadmessages'] = 'Jelenleg nincs olvasatlan üzeneted követve.';
$l['stop_tracking_all'] = 'Az össze üzenet követésének leállítása';
$l['enter_keywords'] = 'Írd be a kulcsszavakat';
$l['advanced_search'] = 'Részletes keresés';
$l['search_pms'] = 'PÜ-k keresése';
$l['advanced_private_message_search'] = 'Részletes privát üzenet keresés';
$l['search_criteria'] = 'Keresési kritérium';
$l['find_users'] = "Felhasználó keresése";
$l['keywords'] = 'Kulcsszavak';
$l['search_in_subject'] = 'Keresés üzenet tárgya alapján';
$l['search_in_message'] = 'Keresés az üzenetekben';
$l['message_status'] = 'Üzenet állapota';
$l['message_status_new'] = 'Új';
$l['message_status_replied_to'] = 'Megválaszolt';
$l['message_status_forwarded'] = 'Átirányított';
$l['message_status_read'] = 'Olvas';
$l['folder'] = 'Mappa';
$l['search_options'] = 'Keresési opciók';
$l['sort_by'] = 'Rendezés';
$l['sort_by_subject'] = 'Rendezés: Tárgy szerint';
$l['sort_by_sender'] = 'Rendezés: Feladó szerint';
$l['sort_by_date'] = 'Rendezés: Dátum szerint';
$l['ascending_order'] = 'Növekvő sorrend';
$l['descending_order'] = 'Csökkenő sorrend';
$l['search_private_messages'] = 'Privát üzenetek keresése';
$l['check_all'] = 'Összes kijelölése';
$l['search_user'] = 'Felhasználó keresése';
$l['error_nopmsarchive'] = 'Nem találtunk privát üzenetet a megadott kritériumok alapján.';
$l['error_invalidpmfoldername'] = 'A mappa nevében nem engedélyezett karakterek szerepelnek.';
$l['error_emptypmfoldername'] = 'A név amelyet a mappának adtál nem tartalmaz szöveget. Kérlek adj egy nevet a mappának, vagy hagyd üresen a mappa törléséhez.';
$l['error_invalidpmrecipient'] = 'A címzett nevét helytelenül adtad meg, vagy nem létezik az adatbázisunkban. Kérlek lépj vissza, és add meg a helyes adatokat.';
$l['error_invalidpm'] = 'Érvénytelen PÜ';
$l['error_pmrecipientreachedquota'] = 'Nem küldhetsz PÜ-t a következő felhasználónak: {1}.<br /> A felhasználónak megtelt a postafiókja. Erről a felhasználó email üzenetet kapott. Kérlek próbálj meg üzenetet küldeni később.';
$l['error_recipientpmturnedoff'] = '{1} azt választotta, hogy nem fogad PÜ-t vagy nincs engedélyezve a számára a PÜ használata. Ezért nem tudsz PÜ-t küldeni neki.';
$l['error_pmsturnedoff'] = 'Jelenleg a PÜ küldése opció ki van kapcsolva a profilodban.<br />PÜ küldéséhez ezt előbb engedélyezned kell.';
$l['error_recipientignoring'] = 'Elnézést, de az üzenetedet nem tudjuk elküldeni a következő felhasználónak: {1}. Nem rendelkezel megfelelő jogosultsággal a művelet végrehajtásához.';
$l['error_pm_already_submitted'] = 'Az elmúlt 5 órában már elküldted ugyanezt az üzenetet ugyanennek a címzettnek.';
$l['error_nopms'] = 'Egy vagy több privát üzenet szükséges ennek a funkciónak a használatához.';
$l['error_minsearchlength'] = 'Egy vagy több megadott keresési feltétel rövidebb, mint a minimum megadható hosszúság. A minimálisan megadható keresési feltétel karaktereinek száma: {1} karakter.<br /><br />Ha egy konkrét kifejezést keresel, akkor kettős idézőjelek közé írd. Például "The quick brown fox jumps over the lazy dog".';
$l['error_nosearchresults'] = 'Nincs találat! Kérlek próbáld újra egy másik szóval vagy kifejezéssel.';
$l['error_no_search_support'] = 'Ez az adatbázis típus nem támogatja a kereséseket.';
$l['error_nosearchterms'] = 'Nem adtál meg semmilyen adatot a kereséshez!';
$l['error_searchflooding_1'] = 'Minden {1}. másodperc után hajtható végre egy keresés. Várj még 1 másodpercet, mielőtt megpróbálnád a keresést megint. ';
$l['error_searchflooding'] = 'Minden {1}. másodperc után hajtható végre egy keresés. Várj még {2} másodpercet, mielőtt megpróbálnád a keresést megint. ';
$l['error_invalidsearch'] = 'Érvénytelen keresés. Lépj vissza és próbáld meg újra.';
$l['redirect_pmsaved'] = 'Az üzenet elmentve a "Piszkozatok" mappába.';
$l['redirect_pmstrackingstopped'] = 'A kiválasztott PÜ-k követése megszüntetve.';
$l['redirect_pmstrackingcanceled'] = 'Az olvasatlan üzenetek törölve.';
$l['redirect_allpmstrackingstopped'] = 'Az összes  olvasott PÜ követése megszüntetve.';
$l['redirect_pmsmoved'] = 'A kiválasztott PÜ-k áthelyezve.';
$l['redirect_pmsdeleted'] = 'A kijelölt üzeneteket töröltük.<br />Visszairányítunk a bejövő üzenetekhez.';
$l['redirect_pmsent'] = 'Az üzeneted sikeresen elküldve.<br />Visszairányítunk a bejövő üzenetekhez.';
$l['redirect_pmfoldersupdated'] = 'A mappák sikeresen frissítve.<br />Visszairányítunk a bejövő üzenetekhez.';
$l['redirect_pmfoldersemptied'] = 'A mappa tartalma törölve.<br />Visszairányítunk a bejövő üzenetekhez.';
$l['redirect_searchresults'] = 'A keresés befejeződött, azonnal továbbítunk az eredményekhez.';
$l['quick_reply'] = 'Gyors válasz';
$l['message_note'] = 'Itt válaszolhatsz erre az üzenetre.';
$l['send_reply'] = 'Válasz küldése';
$l['quickreply_signature'] = 'Aláírás';
$l['quickreply_disable_smilies'] = 'Hangulatjelek tiltása';
$l['quickreply_save_copy'] = 'Másolat mentése';
$l['quickreply_read_receipt'] = '<strong>Olvasási visszaigazolás</strong>';
