<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 15 Mar 2015 06:44:44 +0000
// --------------------------------------------------------------------------------

$l['redirect_threadrated'] = 'Köszönjük, sikeresen értékelted a témát. Most visszairányítunk a témához.';
$l['error_invalidrating'] = 'Nem megfelelő értékelést adtál meg. Kérlek lépj vissza és próbáld újra.';
$l['error_alreadyratedthread'] = 'Elnézést, de már értékelted ezt a témát.';
$l['error_cannotrateownthread'] = 'Elnézést, de nem értékelheted a saját témádat.';
$l['rating_votes_average'] = '{1} Szavazat - {2} / 5 átlagban';
$l['one_star'] = '1 / 5';
$l['two_stars'] = '2 / 5';
$l['three_stars'] = '3 / 5';
$l['four_stars'] = '4 / 5';
$l['five_stars'] = '5 / 5';
$l['rating_added'] = 'Az értékelésed hozzáadva!';
