<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian (Magyar)
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://community.mybb.com/mods.php?action=view&pid=441
// Compatible version of MyBB : 1810 Béta
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sat, 14 Jan 2017 10:55:32 +0000
// --------------------------------------------------------------------------------

$l['report_reason'] = 'Jelentés oka:';
$l['report_to_mod'] = 'Jelentés küldése erről az üzenetről a moderátornak';
$l['close_window'] = 'Ablak bezárása';
$l['report_content'] = 'Tartalom jelentése';
$l['report_reason_post'] = 'Üzenet jelentése';
$l['report_reason_profile'] = 'Profil jelentése';
$l['report_reason_reputation'] = 'Hírnév jelentése???';
$l['report_reason_bad'] = 'Helytelen tartalom';
$l['report_reason_spam'] = 'Spam tartalom';
$l['report_reason_rules'] = 'Fórum szabályának megszegése';
$l['report_reason_wrong'] = 'Rossz fórum';
$l['report_reason_other'] = 'Egyéb';
$l['success_report_voted'] = 'Köszönjük, hogy jelentetted ezt a tartalmat.<br />A fórum csapata hamarosan ellenőrzi a jelentésedet.';
$l['error_report_length'] = 'Kérlek részletezd a jelentésed okát.???';
$l['error_invalid_report'] = 'Ez a tartalom egyike sem létezik vagy nem tudod jelenteni.???';
$l['error_report_duplicate'] = 'Ez a tartalmat már jelentette egy másik tag.<br />Ennek ellenére Te is jelentheted.???';
$l['report_reason_other_description'] = 'Ha az \'Egyéb\' lehetőséget választottad kérlek indokold meg miért jelentetted ezt a tartalmat.';
$l['error_invalid_report_reason'] = 'A kiválasztott ok érvénytelen.';
$l['error_comment_required'] = 'További megjegyzés  szükséges a kiválasztott okhoz.';
