<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 15 Mar 2015 06:54:52 +0000
// --------------------------------------------------------------------------------

$l['nav_reputation'] = 'Értékelés riport';
$l['nav_profile'] = '{1} profilja';
$l['reputation_disabled'] = 'Az Admin letiltotta az értékelés rendszert.';
$l['reputation'] = 'Értékelés';
$l['error'] = 'Hiba';
$l['add_no_uid'] = 'Nem határoztál meg felhasználót.';
$l['add_no_permission'] = 'Nincs jogosultságod értékelés hozzáadásához.';
$l['add_disabled'] = 'Ehhez a csoporthoz tartozó felhasználóknak nem adhatsz értékelést.';
$l['add_yours'] = 'Nem értékelheted saját magad.';
$l['add_invalidpower'] = 'Érvénytelen értéket választottál.';
$l['add_maxperday'] = 'Túllépted az egy napra megengedett adható értékelések számát.';
$l['add_maxperuser'] = 'Túllépted az egy főre adható értékelések napi számát.';
$l['add_maxperthread'] = 'Túllépted az egy főre egy témán belül adható értékelések napi számát.';
$l['add_no_comment'] = 'Meg kell adnod az okát amiért a felhasználónak értékelést adsz.';
$l['add_toolong'] = 'Adj meg egy okot, ami nem hosszabb, mint {1} karakter.';
$l['add_negative_disabled'] = 'Az adminisztrátor letiltotta a negatív értékeléseket.';
$l['add_neutral_disabled'] = 'Az adminisztrátor letiltotta a semleges értékeléseket.';
$l['add_positive_disabled'] = 'Az adminisztrátor letiltotta a pozitív értékeléseket.';
$l['add_all_rep_disabled'] = 'Az adminisztrátor letiltotta az értékeléseket. Nem értékelheted a felhasználót.';
$l['reputation_report'] = 'Értékelés jelentés {1} felhasználóról';
$l['reputation_members'] = 'Értékelés tagoktól:';
$l['reputation_posts'] = 'Értékelések hozzászólásonként:';
$l['summary'] = 'Összegzés';
$l['total_reputation'] = 'Összesített értékelés';
$l['post_reputation'] = 'Értékelés elküldése';
$l['positive_count'] = 'Pozitív';
$l['neutral_count'] = 'Semleges';
$l['negative_count'] = 'Negatív';
$l['last_week'] = 'Utolsó hét';
$l['last_month'] = 'Utolsó hónap';
$l['last_6months'] = 'Utolsó 6 hónap';
$l['all_time'] = 'Összes';
$l['comments'] = 'Megjegyzések';
$l['close_window'] = 'Ablak bezárása';
$l['add_reputation_vote'] = 'Hírnév szavazat adása: {1}';
$l['add_reputation_to_post'] = 'Ez a hírnév {1} felhasználó hozzászólásáért lett adva.<br />';
$l['neg_rep_disabled'] = '<span class="smalltext">* - <em>A negatív hírnév jelenleg le van tiltva</em></span>';
$l['pos_rep_disabled'] = '<span class="smalltext">* - <em>A pozitív hírnév jelenleg le van tiltva</em></span>';
$l['neu_rep_disabled'] = '<span class="smalltext">* - <em>A semleges hírnév jelenleg le van tiltva</em></span>';
$l['no_comment_needed'] = 'A felhasználó hozzászólásáért adsz hírnevet, amely linkelve lesz a profiljában is. Komment nem szükséges, de ha szeretnél hagyni, akkor itt megteheted.<br />';
$l['no_comment'] = '[Nincs hozzászólás]';
$l['vote_added'] = 'Értékelés hozzáadva';
$l['vote_updated'] = 'Értékelés frissítve';
$l['vote_deleted'] = 'Értékelés törölve';
$l['vote_added_message'] = 'A hírnév értékelésed sikeresen rögzítettük a felhasználónak.';
$l['vote_updated_message'] = 'A hírnév értékelésed sikeresen frissítésre került.';
$l['vote_deleted_message'] = 'Az értékelést töröltük.';
$l['update_reputation_vote'] = 'Hírnév értékelésed frissítése: {1}';
$l['positive'] = 'Pozitív';
$l['negative'] = 'Negatív';
$l['neutral'] = 'Semleges';
$l['user_comments'] = 'Hozzászólásod {1} értékeléséhez:';
$l['add_vote'] = 'Értékelés hozzáadása';
$l['update_vote'] = 'Értékelés frissítése';
$l['delete_vote'] = 'Töröl';
$l['report_vote'] = 'Jelent';
$l['power_positive'] = 'Pozitív ({1})';
$l['power_neutral'] = 'Semleges';
$l['power_negative'] = 'Negatív ({1})';
$l['show_all'] = 'Mutassa: Összes';
$l['show_positive'] = 'Mutassa: Pozitív';
$l['show_neutral'] = 'Mutassa: Semleges';
$l['show_negative'] = 'Mutassa: Negatív';
$l['sort_updated'] = 'Felsorolás: Utolsó frissítés';
$l['sort_username'] = 'Szortírozás: Felhasználónév';
$l['last_updated'] = 'Utoljára frissítve {1}';
$l['postrep_given'] = 'Értékelést kapott <a href="{1}">{2} hozzászólása</a> a {3}<br />';
$l['postrep_given_nolink'] = "Értékelést kapott a {1} hozzászólásért<br />";
$l['postrep_given_thread'] = '<a href="{1}">{2}</a> témában';
$l['no_reputation_votes'] = 'Ez a felhasználó jelenleg nem rendelkezik a kritériumoknak megfelelő értékeléssel.';
$l['delete_reputation_confirm'] = 'Tényleg törlöd az értékelést?';
$l['delete_reputation_log'] = 'Az értékelést eltávolította: {1} (UID: {2})';
$l['reputations_disabled_group'] = 'Az értékelés rendszer tiltva van ennél a csoportnál.';
$l['rate_user'] = 'A felhasználó értékelése';
