<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://community.mybb.com/mods.php?action=view&pid=441
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 20 Sep 2015 07:15:35 +0000
// --------------------------------------------------------------------------------

$l['nav_search'] = 'Keresés';
$l['nav_results'] = 'Eredmények';
$l['pages_last'] = 'utolsó';
$l['search'] = 'Keresés';
$l['search_keyword'] = 'Keresés kulcsszavak alapján';
$l['search_username'] = 'Keresés a felhasználónevekben';
$l['search_entire_post'] = 'keresés az üzenetek szövegében';
$l['search_titles_only'] = 'keresés csak a címekben';
$l['match_username'] = 'csak pontos felhasználónév';
$l['search_forums'] = 'Keresés az alábbi fórum(ok)-ban';
$l['search_all_forums'] = 'Keresés minden nyitott fórumban';
$l['search_options'] = 'Keresés beállítások';
$l['threads_at_least'] = 'Keresés azokban a témákban ahol legalább';
$l['threads_at_most'] = 'Keresés azokban a témákban ahol legfeljebb';
$l['find_anydate'] = 'Keresés bármilyen dátumú témákban';
$l['find_yesterday'] = 'Keresés a mai üzenetekben';
$l['find_lastweek'] = 'Keresés a héten íródott üzenetekben';
$l['find_2weeks'] = 'Keresés a max. 2 hete íródott üzenetekben';
$l['find_month'] = 'Keresés a max. 1 hónapja íródott üzenetekben';
$l['find_3months'] = 'Keresés a max. 3 hónapja íródott üzenetekben';
$l['find_6months'] = 'Keresés a max. 6 hónapja íródott üzenetekben';
$l['find_year'] = 'Keresés a max. 2 éve íródott üzenetekben';
$l['and_newer'] = 'és újabbakban';
$l['and_older'] = 'és régebbiekben';
$l['sorting_options'] = 'Eredmény felsorolás beállítások';
$l['sort_lastpost'] = 'A dátuma szerint';
$l['sort_author'] = 'A szerző neve szerint';
$l['sort_forum'] = 'A fórum szerint';
$l['sort_in'] = 'in???';
$l['sort_asc'] = 'növekvő';
$l['sort_desc'] = 'csökkenő';
$l['sort_order'] = 'sorrendbe';
$l['asc'] = 'növekvő';
$l['desc'] = 'csökkenő';
$l['display_options'] = 'Eredmények megjelenítés beállítások';
$l['show_results_as'] = 'Eredmény megjelenítése';
$l['show_results_threads'] = 'témánként';
$l['show_results_posts'] = 'üzenetenként';
$l['search_results'] = 'Keresési eredmények';
$l['post'] = 'Üzenetek';
$l['author'] = 'Szerző';
$l['forum'] = 'Fórum';
$l['replies'] = 'Válaszok';
$l['views'] = 'Megtekintések';
$l['posted'] = 'Beküldve';
$l['thread'] = 'Téma';
$l['lastpost'] = 'Utolsó üzenet';
$l['post_thread'] = 'Téma:';
$l['post_subject'] = 'Üzenet:';
$l['replies2'] = 'válasz van';
$l['selectall'] = 'Kiválasztod az összes további eredményt?';
$l['any_prefix'] = 'Témák keresése előtagokkal';
$l['no_prefix'] = 'Nincs előtag';
$l['inline_thread_moderation'] = 'Moderáció:';
$l['close_threads'] = 'Témák lezárása';
$l['open_threads'] = 'Témák megnyitása';
$l['stick_threads'] = 'Témák kiemelése';
$l['unstick_threads'] = 'Kiemelés megszüntetése';
$l['delete_threads'] = 'Témák végleges törlése';
$l['move_threads'] = 'Témák mozgatása';
$l['approve_threads'] = 'Témák jóváhagyása';
$l['unapprove_threads'] = 'Témák elutasítása';
$l['inline_soft_delete_posts'] = 'Üzenetek ideiglenes törlése';
$l['inline_restore_posts'] = 'Üzenetek visszaállítása';
$l['inline_delete_posts'] = 'Üzenetek végleges törlése';
$l['inline_merge_posts'] = 'Üzenetek összeillesztése';
$l['inline_split_posts'] = 'Üzenetek szétválasztása';
$l['inline_approve_posts'] = 'Üzenetek jóváhagyása';
$l['inline_unapprove_posts'] = 'Üzenetek elutasítása';
$l['inline_post_moderation'] = 'Moderáció:';
$l['inline_go'] = 'Tovább';
$l['clear'] = 'Mégse';
$l['icon_dot'] = 'A hozzászólásaidat tartalmazza. ';
$l['icon_no_new'] = 'Nincs új hozzászólás.';
$l['icon_new'] = 'Új hozzászólás.';
$l['icon_hot'] = 'Népszerű téma.';
$l['icon_lock'] = 'Lezárt téma.';
$l['attachment_count'] = 'Ez a téma 1 csatolást tartalmaz.';
$l['attachment_count_multiple'] = 'Ez a téma {1} csatolást tartalmaz.';
$l['goto_first_unread'] = 'Ugrás az első olvasatlan üzenethez';
$l['page_selected'] = '<strong>{1}</strong> találat kiválasztva ezen az oldalon.';
$l['all_selected'] = '<strong>{1}</strong> találat kiválasztva.';
$l['select_all'] = '<strong>{1}</strong> találat kiválasztása.';
$l['clear_selection'] = 'Kiválasztás törlése.';
$l['search_user'] = 'Felhasználó keresése';
$l['results'] = 'eredmény';
$l['mod_options'] = 'Moderátor opciók';
$l['display_all'] = 'Mindet listáz';
$l['display_only_approved'] = 'Engedélyezettek listázása';
$l['display_only_unapproved'] = 'Jóvá nem hagyottak listázása';
$l['display_only_softdeleted'] = 'Ideiglenesen töröltek listázása';
$l['redirect_searchresults'] = 'A keresés befejeződött, azonnal továbbítunk az eredményekhez.';
$l['error_minsearchlength'] = 'A keresendő kulcsszó vagy kifejezés túl kevés karaktert tartalmaz. Minimum {1} karaktert kell megadnod.<br /><br />Ha egy kifejezésre szeretnél rákeresni használj idézőjeleket a következőképpen: "The quick brown fox jumps over the lazy dog".';
$l['error_nosearchresults'] = 'Nincs találat! Kérlek próbáld újra egy másik szóval vagy kifejezéssel.';
$l['error_no_search_support'] = 'Az adatbázis nem támogatja a keresést.';
$l['error_nosearchterms'] = 'Nem adtál meg semmilyen adatot a kereséshez!';
$l['error_searchflooding_1'] = 'Elnézést, két keresés között el kell telnie {1} másodpercnek. Kérlek várj 1 másodpercet a következő keresésig.';
$l['error_searchflooding'] = 'Elnézést, két keresés között el kell telnie {1} másodpercnek. Kérlek várj {2} másodpercet a következő keresésig.';
$l['error_invalidsearch'] = 'Érvénytelen adatot adtál meg. Kérlek próbáld újra.';
$l['soft_delete_threads'] = 'Témák ideiglenes törlése';
$l['restore_threads'] = 'Témák visszaállítása';
$l['inline_move_posts'] = 'Üzenetek áthelyezése';
