<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 15 Mar 2015 06:57:28 +0000
// --------------------------------------------------------------------------------

$l['nav_sendthread'] = 'Téma elküldése egy barátnak';
$l['send_thread'] = 'Küldés barátnak';
$l['recipient'] = 'Barátod:';
$l['recipient_note'] = 'Add meg a barátod email címét.';
$l['subject'] = 'Tárgy:';
$l['message'] = 'Üzeneted:';
$l['image_verification'] = 'Kép ellenőrzés';
$l['verification_subnote'] = '(kis- és nagybetű érzéketlen)';
$l['verification_note'] = 'Kérlek add meg a képen látható szöveget az alább lévő szöveg mezőbe. Ez az eljárás megakadályozza az automatizált folyamatokat.';
$l['error_nosubject'] = 'Meg kell adnod az üzenet tárgyát.';
$l['error_nomessage'] = 'Írnod kell egy rövid üzenetet.';
