<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 15 Mar 2015 06:58:00 +0000
// --------------------------------------------------------------------------------

$l['nav_showteam'] = 'Fórum üzemeltetői';
$l['forum_team'] = 'Fórum üzemeltetői';
$l['moderators'] = 'Moderátorok';
$l['username'] = 'Felhasználónév';
$l['lastvisit'] = 'Utolsó látogatás';
$l['email'] = 'Email';
$l['pm'] = 'PÜ';
$l['mod_forums'] = 'Fórum(ok)';
$l['online'] = 'Elérhető';
$l['offline'] = 'Nem elérhető';
$l['away'] = "Távol van";
$l['group_leaders'] = 'Vezető(k)';
$l['group_members'] = 'Felhasználó(k)';
$l['no_members'] = 'Nincsenek felhasználók ebben a csoportban.';
$l['error_noteamstoshow'] = 'Nincs megjeleníthető vezető.';
