<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian (Magyar)
// Author of the language pack : Sz.Gábor
// Language pack translators website : https://community.mybb.com/mods.php?action=download&pid=441
// Compatible version of MyBB : 1815 Béta
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Fri, 30 Mar 2018 07:32:45 +0000
// --------------------------------------------------------------------------------

$l['delete_poll'] = 'Szavazás törlése';
$l['close_thread'] = 'Téma lezárás';
$l['stick_thread'] = 'Téma kiemelés';
$l['author'] = 'Szerző';
$l['message'] = 'Üzenet';
$l['threaded'] = 'Rétegezett';
$l['linear'] = 'Lineáris';
$l['thread_modes'] = 'Rétegzési módok';
$l['next_oldest'] = 'Következő régebbi';
$l['next_newest'] = 'Következő újabb';
$l['view_printable'] = 'Megtekintés nyomtatható verzióban';
$l['send_thread'] = 'A téma küldése egy barátnak';
$l['subscribe_thread'] = 'Feliratkozás a témára';
$l['unsubscribe_thread'] = 'Leiratkozás a témáról';
$l['add_poll_to_thread'] = 'Szavazás hozzáadása ehhez a témához';
$l['moderation_options'] = 'Moderátor beállítások:';
$l['delayed_moderation'] = 'Késleltetett moderáció';
$l['thread_notes'] = 'Módosít / Téma jegyzet';
$l['open_close_thread'] = 'Témát nyit / zár';
$l['approve_thread'] = 'Téma elfogadása';
$l['unapprove_thread'] = 'Téma elutasítása';
$l['soft_delete_thread'] = 'Téma ideiglenes törlése';
$l['restore_thread'] = 'Téma visszaállítása';
$l['delete_thread'] = 'Téma végleges törlése';
$l['delete_posts'] = 'Kiválasztott üzenet törlése';
$l['move_thread'] = 'Téma áthelyezése / másolása';
$l['stick_unstick_thread'] = 'Téma kiemelése / Kiemelés megszüntetése';
$l['split_thread'] = 'Téma szétválasztása';
$l['merge_threads'] = 'Témák egyesítése';
$l['remove_redirects'] = 'Átirányítás törlése';
$l['remove_subscriptions'] = 'Feliratkozások eltávolítása';
$l['poll'] = 'Szavazás:';
$l['show_results'] = 'Eredmények';
$l['edit_poll'] = 'Szavazás módosítás';
$l['public_note'] = '<b>Megjegyzés:</b> Ez egy nyitott szavazás, más felhasználók is látni fogják, hogy mire szavaztál.';
$l['total'] = 'Összes';
$l['vote'] = 'Szavaz!';
$l['total_votes'] = '{1} szavazat';
$l['you_voted'] = '* Már szavaztál erre az elemre.';
$l['poll_closed'] = 'A szavazás lezárva.';
$l['poll_closes'] = 'Ez a szavazás zárul: {1}';
$l['already_voted'] = 'Szavazhatsz ebben a témában.';
$l['undo_vote'] = 'Szavazás visszavonása';
$l['quick_reply'] = 'Gyors válasz';
$l['message_note'] = 'Az üzenetre a válaszod írd ide.';
$l['signature'] = 'Aláírás';
$l['email_notify'] = 'Email értesítés';
$l['disable_smilies'] = 'Hangulatjelek tiltása';
$l['post_reply'] = 'Elküld';
$l['post_reply_img'] = 'Új válasz';
$l['new_reply'] = 'Új válasz';
$l['search_button'] = 'Keresés';
$l['post_thread'] = 'Új téma';
$l['preview_post'] = 'Előnézet';
$l['rating_average'] = '{1} szavazat - átlag {2}';
$l['rate_thread'] = 'A téma értékelése:';
$l['thread_rating'] = 'A téma értékelése:';
$l['similar_threads'] = 'Hasonló témák...';
$l['thread'] = 'Téma:';
$l['replies'] = 'Válaszok:';
$l['views'] = 'Megtekintések:';
$l['lastpost'] = 'Utolsó üzenet';
$l['messages_in_thread'] = 'Üzenetek ebben a témában';
$l['users_browsing_thread'] = 'Jelenlevő felhasználók ebben a témában:';
$l['users_browsing_thread_guests'] = '{1} Vendég';
$l['users_browsing_thread_invis'] = '{1} Rejtett felhasználó';
$l['users_browsing_thread_reading'] = 'Olvasás...';
$l['inline_soft_delete_posts'] = 'Üzenetek ideiglenes törlése';
$l['inline_restore_posts'] = 'Üzenetek visszaállítása';
$l['inline_delete_posts'] = 'Üzenetek végleges törlése';
$l['inline_merge_posts'] = 'Üzenetek egyesítése';
$l['inline_split_posts'] = 'Üzenetek szétválasztása';
$l['inline_move_posts'] = 'Üzenetek áthelyezése';
$l['inline_approve_posts'] = 'Üzenetek engedélyezése';
$l['inline_unapprove_posts'] = 'Üzenetek tiltása';
$l['inline_post_moderation'] = 'Moderáció:';
$l['inline_go'] = 'Tovább';
$l['clear'] = 'Mégse';
$l['thread_closed'] = 'Téma lezárva';
$l['no_subject'] = 'Nincs tárgy';
$l['error_nonextnewest'] = 'Nincs újabb lap.';
$l['error_nonextoldest'] = 'Nincs régebbi lap.';
$l['quickreply_multiquote_selected'] = 'Egy vagy több hozzászólást választottál idézésre.';
$l['quickreply_multiquote_now'] = 'Hozzászólások idézése';
$l['or'] = 'vagy';
$l['quickreply_multiquote_deselect'] = 'kijelölés megszüntetése';
$l['search_thread'] = 'Keresés';
$l['enter_keywords'] = 'Kulcsszavak';
$l['image_verification'] = 'Biztonsági ellenőrzés';
$l['verification_note'] = 'Kérlek írd be a szövegmezőbe az itt található képen látott karaktersorozatot. Ez a művelet megelőzi az automatizált belépéseket (kiszűri a robot tevékenységet).';
$l['verification_subnote'] = '(kis-nagybetű érzékeny)';
$l['view_thread_notes'] = 'Téma feljegyzések';
$l['view_all_notes'] = 'Összes feljegyzés megtekintése';
$l['save_changes'] = 'Változások mentése';
$l['cancel_edit'] = 'Szerkesztés visszavonása';
$l['quick_edit_update_error'] = 'Hiba lépett fel a válaszod szerkesztése közben:';
$l['quick_reply_post_error'] = 'Hiba lépett fel a válaszod elküldése közben:';
$l['quick_delete_error'] = 'Hiba lépett fel a válaszod törlése közben:';
$l['quick_delete_success'] = 'Az üzenet sikeresen törölve.';
$l['quick_delete_thread_success'] = 'A téma sikeresen törölve.';
$l['quick_restore_error'] = 'Hiba lépet fel a válaszod visszaállítása közben:';
$l['quick_restore_success'] = 'Az üzenet sikeresen visszaállítva.';
$l['no_voting_permission'] = 'Nincs engedélyed szavazni ebben a témában.';
