<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 15 Mar 2015 07:02:28 +0000
// --------------------------------------------------------------------------------

$l['nav_stats'] = 'Oldal statisztikák';
$l['stats_disabled'] = 'Nem tudod megnézni a statisztikai oldalt, mert az Adminisztrátor letiltotta.';
$l['board_stats'] = 'Oldal statisztikák';
$l['none'] = 'Nincs';
$l['totals'] = 'Összesen';
$l['averages'] = 'Átlagos';
$l['posts'] = 'Üzenetek:';
$l['threads'] = 'Témák:';
$l['members'] = 'Tagok:';
$l['ppd'] = 'Üzenetek naponta:';
$l['tpd'] = 'Témák naponta:';
$l['mpd'] = 'Tagok naponta:';
$l['ppm'] = 'Üzenetek felhasználónként:';
$l['tpm'] = 'Témák felhasználónként:';
$l['rpt'] = 'Válaszok a témákra:';
$l['no_posts'] = 'Nem/Nincsenek üzenetek';
$l['general'] = 'Alapvető';
$l['newest_member'] = 'Legújabb tag:';
$l['members_posted'] = 'Üzenő tagok:';
$l['todays_top_poster'] = 'Mai legtöbb üzenet: <b>{1}</b> (<b>{2}</b> üzenet)';
$l['popular_forum'] = 'Jelenleg a legkedveltebb fórum: <b>{1}</b> (<b>{2}</b> üzenet, <b>{3}</b> témában)';
$l['most_popular'] = 'Jelenleg kedvelt...';
$l['most_replied_threads'] = 'Legújabb válasz a témában';
$l['most_viewed_threads'] = 'Utoljára megtekintett téma';
$l['not_enough_info_stats'] = 'Jelenleg a fórum nem tartalmaz elegendő információt a statisztika létrehozásához. Ahhoz, hogy statisztikát létre lehessen hozni, szükség van legalább 1 felhasználóra és egy témára.';
$l['replies'] = 'válaszok';
$l['views'] = 'megtekintések';
$l['top_referrer'] = 'Legjobb ajánló: <strong>{1}</strong> (<strong>{2}</strong> ajánlás)';
