<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 15 Mar 2015 07:02:48 +0000
// --------------------------------------------------------------------------------

$l['all_forums'] = 'Minden fórum';
$l['forum'] = 'Fórum:';
$l['posted_by'] = 'Az üzenet szerzője:';
$l['on'] = 'bekapcsolva';
$l['portal'] = 'Portál';
