<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 15 Mar 2015 07:11:44 +0000
// --------------------------------------------------------------------------------

$l['ucp_nav_width'] = '220';
$l['ucp_nav_menu'] = 'Menü';
$l['ucp_nav_messenger'] = 'Üzenetküldő';
$l['ucp_nav_compose'] = 'Új üzenet';
$l['ucp_nav_tracking'] = 'Követés';
$l['ucp_nav_edit_folders'] = 'Mappák módosítása';
$l['ucp_nav_profile'] = 'Profilod';
$l['ucp_nav_edit_profile'] = 'Profil módosítás';
$l['ucp_nav_edit_options'] = 'Beállítások módosítása';
$l['ucp_nav_change_email'] = 'Email módosítás';
$l['ucp_nav_change_pass'] = 'Jelszó módosítás';
$l['ucp_nav_change_username'] = 'Felhasználónév módosítás';
$l['ucp_nav_edit_sig'] = 'Aláírás módosítás';
$l['ucp_nav_change_avatar'] = 'Avatar módosítás';
$l['ucp_nav_misc'] = 'Egyéb';
$l['ucp_nav_editlists'] = 'Barátok - mellőzöttek';
$l['ucp_nav_favorite_threads'] = 'Kedvenc témák';
$l['ucp_nav_subscribed_threads'] = 'Téma feliratkozások';
$l['ucp_nav_forum_subscriptions'] = 'Fórum feliratkozások';
$l['ucp_nav_drafts'] = 'Mentett üzenetek';
$l['ucp_nav_drafts_active'] = '<strong>Mentett üzenetek ({1})</strong>';
$l['ucp_nav_notepad'] = 'Jegyzettömb';
$l['ucp_nav_view_profile'] = 'Profil megtekintés';
$l['ucp_nav_home'] = 'Kezelőpult kezdőlap';
$l['ucp_nav_usergroups'] = 'Csoport tagságok';
$l['ucp_nav_attachments'] = 'Csatolások kezelése';
