<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 15 Mar 2015 07:14:19 +0000
// --------------------------------------------------------------------------------

$l['nav_profile'] = '{1} profilja';
$l['nav_warning_log'] = 'Figyelmeztetés napló';
$l['nav_add_warning'] = 'Felhasználó figyelmeztetése';
$l['nav_view_warning'] = 'Figyelmeztetés részletei';
$l['warning_for_post'] = '.. Hozzászólás:';
$l['already_expired'] = 'Lejárt';
$l['details_username'] = 'Felhasználónév';
$l['warning_active'] = 'Aktív';
$l['warning_revoked'] = 'Visszavonva';
$l['warning_log'] = 'Figyelmeztetés napló';
$l['warning'] = 'Figyelmeztetés';
$l['issued_by'] = 'Adta';
$l['date_issued'] = 'Dátum';
$l['expiry_date'] = 'Lejár';
$l['active_warnings'] = 'Aktív figyelmeztetések';
$l['expired_warnings'] = 'Lejárt figyelmeztetések';
$l['warning_points'] = '({1} pont)';
$l['no_warnings'] = 'A felhasználó még nem részesült figyelmeztetésben, vagy azok már korábban vissza lettek vonva.';
$l['warn_user'] = 'Felhasználó figyelmeztetése';
$l['post'] = 'Hozzászólás:';
$l['warning_note'] = 'Megjegyzés:';
$l['details_warning_note'] = 'Megjegyzés';
$l['warning_type'] = 'Figyelmeztetés típus:';
$l['custom'] = 'Egyedi ok';
$l['reason'] = 'Oka:';
$l['points'] = 'Pont:';
$l['details_reason'] = 'Ok';
$l['warn_user_desc'] = 'Itt tudod növelni a felhasználó figyelmeztetési szintjét, ha az megszegte a fórum szabályzatát.';
$l['send_pm'] = 'Felhasználó értesítése:';
$l['send_user_warning_pm'] = 'PÜ értesítés a felhasználónak a figyelmeztetésről.';
$l['send_pm_subject'] = 'Tárgy:';
$l['warning_pm_subject'] = 'Figyelmeztetést kaptál.';
$l['send_pm_message'] = 'Üzenet:';
$l['warning_pm_message'] = 'Kedves {1}



{2} figyelmeztetésben részesített.

--



--';
$l['send_pm_options'] = 'Beállítások:';
$l['send_pm_options_anonymous'] = '<strong>Névtelen PÜ</strong>: üzenet küldése mint névtelen felhasználó.';
$l['expiration_never'] = 'véglegesen';
$l['expiration_hours'] = 'óra';
$l['expiration_days'] = 'nap';
$l['expiration_weeks'] = 'hét';
$l['expiration_months'] = 'hónap';
$l['redirect_warned_banned'] = 'A felhasználó át lett helyezve a következő csoportba: {1} Oka: {2}.';
$l['redirect_warned_suspended'] = 'A felhasználó hozzászólás írási joga fel lett függesztve. Oka: {1}.';
$l['redirect_warned_moderate'] = '<br /><br />Ennek a felhasználónak az összes hozzászólása moderálva lesz {1}.';
$l['redirect_warned_pmerror'] = '<br /><br />Figyelem, a PÜ nem lett elküldve.';
$l['redirect_warned'] = '{1} figyelmeztetési szintje növelve lett {2}%.{3}<br /><br />Most visszairányítunk az előző oldalra.';
$l['error_warning_system_disabled'] = 'Nem tudod használni a figyelmeztető rendszert mert az deaktiválva lett.';
$l['error_cant_warn_group'] = 'Nincs jogosultságod, hogy ezen csoport tagjait figyelmeztetésben részesítsd.';
$l['error_invalid_user'] = 'A kiválasztott felhasználó nem létezik.';
$l['details'] = 'Részletek';
$l['view'] = 'Megtekint';
$l['current_warning_level'] = 'Jelenlegi figyelmeztetési szint: <strong>{1}%</strong> ({2}/{3})';
$l['warning_details'] = 'Figyelmeztetés részletei';
$l['revoke_warning'] = 'Figyelmeztetés visszavonása';
$l['revoke_warning_desc'] = 'Írd be a visszavonás okát. Ez nem lesz hatással kitiltásokra és egyéb felfüggesztésekre.';
$l['warning_is_revoked'] = 'A figyelmeztetés visszavonva.';
$l['revoked_by'] = 'Visszavonta:';
$l['date_revoked'] = 'Dátum:';
$l['warning_already_revoked'] = 'A figyelmeztetés már vissza lett vonva.';
$l['no_revoke_reason'] = 'Nem adtad meg a visszavonás okát.';
$l['redirect_warning_revoked'] = 'A figyelmeztetés sikeresen visszavonva, és a felhasználó figyelmeztetési pontjai csökkentve.<br /><br />Most visszairányítunk ahol előzőleg voltál.';
$l['result'] = 'Eredmény:';
$l['result_banned'] = 'A felhasználó átmozgatásra kerül a kitiltott csoportba: ({1}) {2}';
$l['result_suspended'] = 'Hozzászólás írás jogok felfüggesztve: {1}';
$l['result_moderated'] = 'Hozzászólások moderálásra kerülnek: {1}';
$l['result_period'] = '{1} {2}';
$l['result_period_perm'] = 'véglegesen';
$l['hour_or_hours'] = 'Óra';
$l['day_or_days'] = 'Nap';
$l['week_or_weeks'] = 'Hét';
$l['month_or_months'] = 'Hónap';
$l['expires'] = 'Lejár:';
$l['new_warning_level'] = 'Új figyelmeztetési szint:';
$l['error_cant_warn_user'] = 'Nem rendelkezel megfelelő jogosultsággal, hogy figyelmeztethesd ezt a felhasználót.';
$l['existing_post_warnings'] = 'A hozzászóláshoz tartozó figyelmeztetések';
