<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 15 Mar 2015 07:19:25 +0000
// --------------------------------------------------------------------------------

$l['no_new_subject'] = 'Nem adtad meg az új témát.';
$l['post_moderation'] = 'A hozzászólásod moderáció alatt áll.';
$l['thread_moderation'] = 'A témád moderáció alatt áll.';
$l['post_doesnt_exist'] = 'A megadott hozzászólás nem létezik.';
$l['thread_doesnt_exist'] = 'A megadott téma nem létezik.';
$l['thread_closed_edit_subjects'] = 'A téma le van zárva, ezért nem módosíthatod.';
$l['no_permission_edit_subject'] = 'Nincs engedélyed a téma tárgyának módosításához.';
$l['thread_closed_edit_message'] = 'A téma le van zárva ezért nem módosíthatod a hozzászólást.';
$l['no_permission_edit_post'] = 'Nincs engedélyed a módosításhoz.';
$l['edit_time_limit'] = 'A módosításra csak az elkövetkező {1} percben van lehetőséged.';
$l['postbit_edited'] = 'A hozzászólás utolsó módosítás ideje: {1} Szerkesztette:';
$l['postbit_editreason'] = 'Szerkesztés';
$l['save_changes'] = 'Változtatások mentése';
$l['cancel_edit'] = 'Mégse';
$l['answer_valid_not_exists'] = 'A kérdés nem létezik.';
$l['captcha_not_exists'] = 'A biztonsági kép, melyet frissíteni próbálsz, nem létezik.';
$l['captcha_valid_not_exists'] = 'A biztonsági kép nem létezik.';
$l['captcha_does_not_match'] = 'A megadott kép ellenőrző kód hibás. Kérlek add meg a helyes kódot.';
$l['captcha_matches'] = 'A megadott képellenőrző kód érvényes.';
$l['answer_does_not_match'] = 'A megadott válasz helytelen.';
$l['banned_username'] = 'A megadott felhasználónév nem engedélyezett.';
$l['banned_characters_username'] = 'A felhasználónév érvénytelen karaktereket tartalmaz.';
$l['complex_password_fails'] = 'A jelszónak tartalmaznia kell nagybetűt, kisbetűt és számot.';
$l['username_taken'] = '{1} felhasználónév már regisztrálva van egy másik felhasználó által.';
$l['username_available'] = '{1} elérhető';
$l['invalid_username'] = '{1} nem felhasználóneve egyetlen regisztrált tagunknak sem.';
$l['valid_username'] = '{1} valós ajánló.';
$l['buddylist_error'] = 'Úgy tűnik, hogy nincs név a Barátok listádon. A funkció használatához először hozzá kell adnod néhányat.';
$l['close'] = 'Bezár';
$l['select_buddies'] = 'Barát választása';
$l['select_buddies_desc'] = 'Barátaid hozzáadásához válaszd ki őket.';
$l['selected_recipients'] = 'Kijelölt címzettek';
$l['ok'] = 'OK';
$l['cancel'] = 'Töröl';
$l['online'] = 'Elérhető';
$l['offline'] = 'Nem elérhető';
$l['edited_post'] = 'Szerkesztett hozzászólás';
$l['usergroup'] = 'Felhasználói csoport';
