<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Wed, 18 Mar 2015 15:09:53 +0000
// --------------------------------------------------------------------------------

$l['plugins'] = 'Bővítmények';
$l['plugins_desc'] = 'Ez az opció lehetővé teszi, hogy aktiváld, deaktiváld, vagy szerkeszd a fórumodra feltöltött bővítményeket. A bővítmények a fórumod <strong>inc/plugins</strong> mappájában találhatóak. Ha kiszeretnél kapcsolni egy bővítményt, de nem szeretnéd, hogy az adatai elvesszenek klikkelj a \'Deaktivál\' linkre.';
$l['plugin_updates'] = 'Bővítmény frissítések';
$l['plugin_updates_desc'] = 'Ez az opció lehetővé teszi, hogy frissítéseket keress a telepített bővítményekhez.';
$l['browse_plugins'] = 'Bővítmények böngészése';
$l['browse_plugins_desc'] = 'A fórum verzióddal kompatibilis hivatalos MyBB bővítmények között böngészhetsz.';
$l['browse_all_plugins'] = 'Összes bővítmény böngészése';
$l['plugin'] = 'Bővítmény';
$l['active_plugin'] = 'Bővítmény(ek) aktiválása';
$l['inactive_plugin'] = 'Bővítmény(ek) inaktiválása';
$l['your_version'] = 'A te verziód';
$l['latest_version'] = 'legfrissebb verzió';
$l['download'] = 'Letölt';
$l['deactivate'] = 'Deaktivál';
$l['activate'] = 'Aktivál';
$l['install_and_activate'] = 'Telepítés és aktiválás';
$l['uninstall'] = 'Eltávolítás';
$l['created_by'] = 'Készítette:';
$l['no_plugins'] = 'Jelenleg nem találhatóak bővítmények a fórumodon.';
$l['no_active_plugins'] = 'Nincs(enek) aktivált bővítmény(ek) a fórumodban.';
$l['no_inactive_plugins'] = 'Nincs(enek) elérhető inaktivált bővítmény(ek).';
$l['plugin_incompatible'] = 'Ez a bővítmény nem kompatibilis a MyBB {1} verzióval';
$l['recommended_plugins_for_mybb'] = 'Ajánlott bővítmények a MyBB {1} verziójához';
$l['browse_results_for_mybb'] = 'Találati eredmények böngészése. MyBB {1}';
$l['search_for_plugins'] = 'Bővítmények keresése';
$l['search'] = 'Keresés';
$l['error_vcheck_no_supported_plugins'] = 'Egyik telepített bővítmény sem támogatja a verzió ellenőrzést.';
$l['error_vcheck_communications_problem'] = 'Hiba lépett fel a mod serverrel való kapcsolatba lépéskor. Kérlek próbáld újra később.';
$l['error_vcheck_vulnerable'] = '[Sebezhető/Támadható bővítmény]:';
$l['error_vcheck_vulnerable_notes'] = 'Ez a submission jelenleg sebezhetőként van megjelölve a MyBB fejlesztők által. Az ajánljuk, hogy teljesen távolítsd el ezt a módosítást. Kérlek nézd meg az alábbi leírást/feljegyzést: ';
$l['error_no_input'] = 'Hiba kód 1: Hiányzó adat(ok).';
$l['error_no_pids'] = 'Hiba kód 2: Nincs megadva bővítmény azonosító.';
$l['error_communication_problem'] = 'Hiba lépett fel a mod szerverrel való kapcsolatba lépéskor.';
$l['error_invalid_plugin'] = 'Nincs ilyen bővítmény.';
$l['error_no_results_found'] = 'Nincs találat a megadott kulcsszavakra.';
$l['success_plugins_up_to_date'] = 'Gratulálunk, minden bővítményed naprakész.';
$l['success_plugin_activated'] = 'A kiválasztott bővítmény sikeresen aktiválva.';
$l['success_plugin_deactivated'] = 'A kiválasztott bővítmény sikeresen deaktiválva.';
$l['success_plugin_installed'] = 'A kiválasztott bővítmény sikeresen telepítve és aktiválva.';
$l['success_plugin_uninstalled'] = 'A kiválasztott bővítmény sikeresen eltávolítva.';
