<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sat, 21 Mar 2015 11:25:23 +0000
// --------------------------------------------------------------------------------

$l['warning_system'] = 'Figyelmeztető rendszer';
$l['warning_types'] = 'Figyelmeztetési típusok';
$l['warning_types_desc'] = 'Itt tudod kezelni a létrehozott figyelmeztetés típusokat, melyek kioszthatóak a felhasználóknak.';
$l['add_warning_type'] = 'Új figyelmeztetési típus hozzáadása';
$l['add_warning_type_desc'] = 'Itt tudsz létrehozni új figyelmeztetés típusokat. A figyelmeztetés típusok választhatóak, valamint meghatározhatod a figyelmeztető pontok számát és a figyelmeztetés időtartamát is.';
$l['edit_warning_type'] = 'Figyelmeztetés típus szerkesztése';
$l['edit_warning_type_desc'] = 'Itt tudod szerkeszteni ezt a típust. A figyelmeztetés típusok választhatóak, valamint meghatározhatod a figyelmeztető pontok számát és a figyelmeztetés időtartamát is.';
$l['warning_levels'] = 'Figyelmeztetési szintek';
$l['warning_levels_desc'] = 'Ez az opció meghatározza, hogy mi történik a felhasználóval, ha az elért egy bizonyos szintet (figyelmeztető pontok bizonyos százaléka). Kitilthatod a felhasználót vagy felfüggesztheted a jogosultságait.';
$l['add_warning_level'] = 'Új figyelmeztetési szint hozzáadása';
$l['add_warning_level_desc'] = 'Itt tudsz létrehozni új figyelmeztetési szinteket.';
$l['edit_warning_level'] = 'Figyelmeztetési szint szerkesztése';
$l['edit_warning_level_desc'] = 'A figyelmeztetési szint meghatározza, hogy mi történik a felhasználóval, ha az elért egy bizonyos szintet.';
$l['percentage'] = 'Százalék';
$l['action_to_take'] = 'Eljárás';
$l['move_banned_group'] = 'Átmozgatva a kitiltott csoportba ({1}) a következő időtartamra: {2} {3}';
$l['move_banned_group_permanent'] = '({1}) áthelyezve véglegesen a kitiltott csoportba';
$l['suspend_posting'] = 'Jogosultságok felfüggesztése {1} {2} időtartamra';
$l['suspend_posting_permanent'] = 'Jogosultságok felfüggesztése véglegesen';
$l['moderate_new_posts'] = 'Új hozzászólás moderálása {1} {2} időtartamra';
$l['moderate_new_posts_permanent'] = 'Új hozzászólás moderálása véglegesen';
$l['no_warning_levels'] = 'Jelenleg nincsenek figyelmeztetési szintek létrehozva a fórumon.';
$l['warning_type'] = 'Figyelmeztetés típus';
$l['points'] = 'Pont(ok)';
$l['expires_after'] = 'Lejárat';
$l['no_warning_types'] = 'Jelenleg nincsenek figyelmeztetési típusok létrehozva a fórumon.';
$l['warning_points_percentage'] = 'Figyelmeztetési pontok maximum százaléka';
$l['warning_points_percentage_desc'] = 'Kérlek adj meg egy numerikus értéket 1 és 100 között.';
$l['action_to_be_taken'] = 'Eljárás';
$l['action_to_be_taken_desc'] = 'Válaszd ki, hogy mi történjen a felhasználóval ha eléri a fent megadott értéket.';
$l['ban_user'] = 'Felhasználó kitiltása';
$l['banned_group'] = 'Kitiltott csoport:';
$l['ban_length'] = 'Kitiltás időtartama:';
$l['suspend_posting_privileges'] = 'Hozzászólás írás jogosultságának felfüggesztése';
$l['suspension_length'] = 'Felfüggesztés időtartama:';
$l['moderate_posts'] = 'Hozzászólás moderálása';
$l['moderation_length'] = 'Moderáció időtartama:';
$l['save_warning_level'] = 'Figyelmeztetési szint mentése';
$l['title'] = 'Cím';
$l['points_to_add'] = 'Figyelmeztetési pont';
$l['points_to_add_desc'] = 'a pontok száma a figyelmeztetési szinthez.';
$l['warning_expiry'] = 'Figyelmeztetés lejárata';
$l['warning_expiry_desc'] = 'Mikor járjon le a figyelmeztetés?';
$l['save_warning_type'] = 'Figyelmeztetési típus mentése';
$l['expiration_hours'] = 'óra';
$l['expiration_days'] = 'nap';
$l['expiration_weeks'] = 'hét';
$l['expiration_months'] = 'hónap';
$l['expiration_never'] = 'Soha nem jár le';
$l['expiration_permanent'] = 'Végleges';
$l['error_invalid_warning_level'] = 'A megadott figyelmeztetési szint nem létezik.';
$l['error_invalid_warning_percentage'] = 'Nem adtál meg megfelelő % értéket a figyelmeztetési szintnek. A % értéknek 1 és 100 között kell lennie.';
$l['error_invalid_warning_type'] = 'Nincs ilyen figyelmeztetési típus.';
$l['error_missing_action_type'] = 'Kérlek válassz egy eljárást az új figyelmeztetési szinthez.';
$l['error_missing_type_title'] = 'Nem adtad meg ennek a figyelmeztetési típusnak a címét.';
$l['error_missing_type_points'] = 'Nem adtál meg érvényes pontszámot. Meg kell adnod egy számot, amely nagyobb mint 0 de kevesebb mint {1}';
$l['success_warning_level_created'] = 'A figyelmeztetési szint sikeresen létrehozva.';
$l['success_warning_level_updated'] = 'A figyelmeztetési szint sikeresen frissítve.';
$l['success_warning_level_deleted'] = 'A kiválasztott figyelmeztetési szint sikeresen törölve.';
$l['success_warning_type_created'] = 'A figyelmeztetési típus sikeresen létrehozva.';
$l['success_warning_type_updated'] = 'A figyelmeztetési típus sikeresen frissítve.';
$l['success_warning_type_deleted'] = 'A kiválasztott figyelmeztetési típus sikeresen törölve.';
$l['confirm_warning_level_deletion'] = 'Biztos, hogy törölni szeretnéd ezt a figyelmeztetési szintet?';
$l['confirm_warning_type_deletion'] = 'Biztos, hogy törölni szeretnéd ezt a figyelmeztetési típust?';
