<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 15 Mar 2015 07:24:13 +0000
// --------------------------------------------------------------------------------

$l['languages'] = 'Nyelvek';
$l['languages_desc'] = 'Alább találhatóak a telepített nyelvi csomagok. Választhatod a nyelvi fájl szerkesztését, a fájl szerkesztését egy másik nyelvvel, vagy pedig a nyelvi fájl tulajdonságainak szerkesztését.';
$l['find_language_packs'] = 'Nyelvi csomagok keresése';
$l['language_files'] = 'Nyelvi fájlok';
$l['language_files_desc'] = 'Alább találhatóak a választott nyelv fájljai. A file-ok magukban foglalják mind a front-end és az adminisztráció szövegét is. A file szerkesztéséhez kattints a mellette lévő linkre.';
$l['quick_phrases'] = 'Rövid kifejezések';
$l['quick_phrases_desc'] = 'Gyors hozzáférés a leggyakrabban szerkesztett nyelvi kifejezésekhez.';
$l['edit_with'] = 'Szerkesztés {1}';
$l['edit_language_variables'] = 'Nyelvi fájlok szerkesztése';
$l['edit_language_variables_desc'] = 'Itt tudod szerkeszteni a különböző nyelvi kifejezéseket.';
$l['edit_properties_desc'] = 'Itt tudod szerkeszteni a nyelvi csomagok tulajdonságait.';
$l['installed_language_packs'] = 'Telepített nyelvi csomagok';
$l['front_end'] = 'Felhasználói felület';
$l['admin_cp'] = 'Adminisztrátori vezérlőpult';
$l['save_language_file'] = 'Nyelvi fájl mentése';
$l['nav_editing_set'] = 'Nyelvi fájl tulajdonságainak szerkesztése';
$l['edit_properties'] = 'Tulajdonságok szerkesztése';
$l['friendly_name'] = 'Csomag neve';
$l['language_in_html'] = 'A nyelvnek megfelelő &lt;html&gt; tag';
$l['charset'] = 'Karakterkódolás';
$l['admin'] = 'Tartalmazza az &ldquo;admin&rdquo; változókat?';
$l['rtl'] = 'Jobbról balra?';
$l['quickphrases_agreement'] = 'Regisztrációs feltételek - Cím';
$l['quickphrases_agreement_1'] = 'Regisztrációs feltételek - 1. Bekezdés';
$l['quickphrases_agreement_2'] = 'Regisztrációs feltételek - 2. Bekezdés';
$l['quickphrases_agreement_3'] = 'Regisztrációs feltételek - 3. Bekezdés';
$l['quickphrases_agreement_4'] = 'Regisztrációs feltételek - 4. Bekezdés';
$l['quickphrases_agreement_5'] = 'Regisztrációs feltételek - 5. Bekezdés';
$l['quickphrases_error_nopermission_guest_1'] = 'Nincs jogosultsága üzenet - 1. Bekezdés';
$l['quickphrases_error_nopermission_guest_2'] = 'Nincs jogosultsága üzenet - 2. Bekezdés';
$l['quickphrases_error_nopermission_guest_3'] = 'Nincs jogosultsága üzenet - 3. Bekezdés';
$l['quickphrases_error_nopermission_guest_4'] = 'Nincs jogosultsága üzenet - 4. Bekezdés';
$l['no_languages'] = 'Nincsenek nyelvek';
$l['no_language_files_front_end'] = 'Nem található nyelvi fájl a felhasználói felülethez.';
$l['no_language_files_admin_cp'] = 'Nem található az adminisztrátori vezérlőpult nyelvi fájl.';
$l['error_invalid_set'] = 'Érvénytelen nyelvi csomag.';
$l['error_invalid_file'] = 'Érvénytelen nyelvi fájl.';
$l['error_cannot_write_to_file'] = 'A fájl írása nem sikerült.  Kérlek ellenőrizd a <a href="http://www.tutorial.hu/chmod-beallitasai/">fájl jogosultságait (CHMOD)</a>, és próbáld újra.';
$l['error_folders_fail'] = 'Probléma lépett fel a nyelvi csomag könyvtárának hozzáférésével. Kérlek ellenőrizd, hogy a könyvtár létezik vagy írható-e.';
$l['alert_note_cannot_write'] = 'Mielőtt szerkesztenéd a fájlt, be kell állítanod a <a href="http://www.tutorial.hu/chmod-beallitasai/">jogosultságokat (CHMOD)</a>, hogy szerver képes legyen írni rá.';
$l['success_langfile_updated'] = 'A nyelvi fájl sikeresen frissítve.';
$l['success_langprops_updated'] = 'A nyelvi fájl tulajdonságai sikeresen frissítve.';
$l['success_quickphrases_updated'] = 'A rövid kifejezések sikeresen frissítve.';
$l['issues'] = 'Eredmények';
$l['phrases'] = 'Szavak';
$l['issues_ok'] = 'Úgy látszik itt minden rendben.';
$l['issues_nothingtocompare'] = 'Nincs mit összehasonlítani.';
$l['issues_warning'] = 'Ennek a fájlnak szüksége lehet a karbantartásodra.
Kérlek bizonyosodj meg, hogy ellenőrizted.';
