<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Thu, 19 Mar 2015 09:25:13 +0000
// --------------------------------------------------------------------------------

$l['smilies'] = 'Hangulatjelek';
$l['manage_smilies'] = 'Hangulatjelek kezelése';
$l['manage_smilies_desc'] = 'Itt tudod szerkeszteni vagy törölni a hangulatjeleidet.';
$l['add_smilie'] = 'Új hangulatjel hozzáadása';
$l['add_smilie_desc'] = 'Itt egy új hangulatjelet tudsz hozzáadni.';
$l['add_multiple_smilies'] = 'Több hangulatjel hozzáadása';
$l['add_multiple_smilies_desc'] = 'Itt egyszerre több új hangulatjelet tudsz hozzáadni.';
$l['edit_smilie'] = 'Hangulatjel szerkesztése';
$l['edit_smilie_desc'] = 'Itt egyenként tudod szerkeszteni a hangulatjeleket.';
$l['mass_edit'] = 'Tömeges szerkesztés';
$l['mass_edit_desc'] = 'Itt szerkesztheted a hangulatjeleidet, akár többet is egyszerre.';
$l['no_smilies'] = 'Jelenleg nincsenek hangulatjelek telepítve a fórumra.';
$l['image'] = 'Hangulatjelek';
$l['name'] = 'Neve';
$l['text_replace'] = 'Kód';
$l['text_replace_desc'] = 'Ezt a szöveget cseréli a hangulatjelre (soronként egyet adj meg).';
$l['image_path'] = 'Kép útvonal';
$l['image_path_desc'] = 'Ez a hangulatjel képének elérési útvonala. Ha különböző témákhoz eltérő hangulatjel képeket akarsz használni, kérlek használd a <strong>{theme}</strong>-et, hogy használhasd az adott téma kép könyvtárát.';
$l['order'] = 'Sorrend';
$l['display_order'] = 'Megjelenítési sorrend';
$l['display_order_desc'] = 'A sorrend ahogyan a hangulatjel a listán megjelenik. Ennek a számnak különbözőnek kell lennie a többitől.';
$l['mass_edit_show_clickable'] = 'Kattintható Hangulatjelek';
$l['show_clickable'] = 'Mutassa a kattintható Hangulatjelek listájában?';
$l['show_clickable_desc'] = 'Ha szeretnéd, hogy a hangulatjel megjelenjen a kis dobozban a hozzászólás szerkesztő mellett akkor jelöld be az \'Igen\' opciót.';
$l['include'] = 'Hozzáad?';
$l['path_to_images'] = 'Elérési útvonala';
$l['path_to_images_desc'] = 'A mappa elérési útvonala melyben a hangulatjelek találhatóak.';
$l['smilie_delete'] = 'Töröl?';
$l['save_smilie'] = 'Hangulatjel mentése';
$l['save_smilies'] = 'Hangulatjelek mentése';
$l['show_smilies'] = 'Hangulatjelek megjelenítése';
$l['reset'] = 'Újraküld';
$l['error_missing_name'] = 'Nem adtál nevet a hangulatjelnek.';
$l['error_missing_text_replacement'] = 'Nem adtad meg a hangulatjel kódját.';
$l['error_missing_path'] = 'Nem adtad meg a hangulatjel elérési útvonalát.';
$l['error_missing_path_multiple'] = 'Nem adtad meg az útvonalat.';
$l['error_missing_order'] = 'Nem adtál meg megjelenítési sorrendet ennek a hangulatjelnek.';
$l['error_duplicate_order'] = 'A hangulatjel megjelenítési sorrendje érvénytelen.';
$l['error_missing_clickable'] = 'Nem jelölted be az \'Igen\' vagy \'Nem\' opciót a "Kattintható hangulatjelek" listája opciónál';
$l['error_no_smilies'] = 'A megadott mappában nem található hangulatjel, vagy pedig a mappában lévő hangulatjelek már hozzá lettek adva a fórumhoz.';
$l['error_no_images'] = 'A megadott mappában nem találhatóak képek.';
$l['error_none_included'] = 'Nem választottál egyetlen hangulatjelet sem.';
$l['error_invalid_path'] = 'Érvénytelen útvonalat adtál meg.';
$l['error_invalid_smilie'] = 'Nincs ilyen hangulatjel.';
$l['success_smilie_added'] = 'A hangulatjel sikeresen hozzáadva.';
$l['success_multiple_smilies_added'] = 'A hangulatjelek sikeresen hozzáadva.';
$l['success_smilie_updated'] = 'A hangulatjel sikeresen frissítve.';
$l['success_multiple_smilies_updated'] = 'A hangulatjelek sikeresen frissítve.';
$l['success_smilie_deleted'] = 'A kijelölt hangulatjelek törlésre kerültek.';
$l['success_mass_edit_updated'] = 'A hangulatjelek sikeresen frissítve.';
$l['confirm_smilie_deletion'] = 'Biztos, hogy törölni szeretnéd ezt a hangulatjelet?';
