<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian (Magyar)
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://community.mybb.com/mods.php?action=view&pid=441
// Compatible version of MyBB : 1810 Béta
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sat, 14 Jan 2017 12:25:35 +0000
// --------------------------------------------------------------------------------

$l['configuration'] = 'Konfiguráció';
$l['bbsettings'] = 'Általános beállítások';
$l['banning'] = 'Kitiltások';
$l['custom_profile_fields'] = 'Egyéni profil mezők';
$l['smilies'] = 'Hangulatjelek';
$l['word_filters'] = 'Szűrő';
$l['mycode'] = 'BB kód';
$l['languages'] = 'Nyelvek';
$l['post_icons'] = 'Üzenet ikonok';
$l['help_documents'] = 'Súgó dokumentum';
$l['plugins'] = 'Bővítmények kezelése';
$l['attachment_types'] = 'Csatolások kezelése';
$l['moderator_tools'] = 'Moderátor eszközök';
$l['spiders_bots'] = 'Keresőrobotok';
$l['calendars'] = 'Naptár kezelése';
$l['warning_system'] = 'Figyelmeztető rendszer';
$l['thread_prefixes'] = 'Téma előtagok';
$l['security_questions'] = 'Biztonsági kérdések';
$l['can_manage_settings'] = 'Kezelheti a beállításokat?';
$l['can_manage_banned_accounts'] = 'Kezelheti a kitiltott felhasználókat?';
$l['can_manage_custom_profile_fields'] = 'Kezelheti az Extra profil mezőket?';
$l['can_manage_smilies'] = 'Kezelheti a hangulatjeleket?';
$l['can_manage_bad_words'] = 'Kezelheti a szűrőket?';
$l['can_manage_custom_mycode'] = 'Kezelheti a BB Kódokat?';
$l['can_manage_language_packs'] = 'Kezelheti a nyelvi csomagokat?';
$l['can_manage_post_icons'] = 'Kezelheti az üzenet ikonokat?';
$l['can_manage_help_documents'] = 'Kezelheti a súgó dokumentumokat?';
$l['can_manage_plugins'] = 'Kezelheti a bővítményeket?';
$l['can_manage_attachment_types'] = 'Kezelheti a csatolás típusokat?';
$l['can_manage_spiders_bots'] = 'Kezelheti a keresőrobotokat?';
$l['can_manage_calendars'] = 'Kezelheti a naptárakat?';
$l['can_manage_warning_system'] = 'Kezelheti a figyelmeztető rendszert?';
$l['can_manage_mod_tools'] = 'Kezelheti a moderátor eszközöket?';
$l['can_manage_thread_prefixes'] = 'Kezelheti a téma előtagokat?';
$l['can_manage_security_questions'] = 'Kezelheti a biztonsági kérdéseket?';
$l['report_reasons'] = 'Jelentés okai';
$l['can_manage_report_reasons'] = 'Kezelheti a jelentés okait?';
