<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 15 Mar 2015 07:22:48 +0000
// --------------------------------------------------------------------------------

$l['banning'] = 'Kitiltás';
$l['banned_ips'] = 'Kitiltott IP-k';
$l['banned_ips_desc'] = 'Itt tudod kezelni azokat az IP-ket, amelyeknek megtiltod a belépést a fórumodra';
$l['banned_accounts'] = 'Kitiltott fiókok';
$l['disallowed_usernames'] = 'Tiltott felhasználónevek';
$l['disallowed_usernames_desc'] = 'Itt tudod kezelni azokat a felhasználóneveket, amelyekkel felhasználók nem regisztrálhatnak. Ez a funkció hasznos arra is, hogy felhasználóneveket foglalj le.';
$l['disallowed_email_addresses'] = 'Tiltott email címek';
$l['disallowed_email_addresses_desc'] = 'Itt tudod kezelni azokat az email címeket, amely címeket nem használhatnak, vagy nem regisztrálhatnak felhasználók.';
$l['banned_ip_addresses'] = 'Kitiltott IP címek';
$l['username'] = 'Felhasználó név';
$l['date_disallowed'] = 'Tiltott dátum';
$l['last_attempted_use'] = 'Utolsó használatba vétel';
$l['email_address'] = 'Email cím';
$l['ip_address'] = 'IP cím';
$l['ban_date'] = 'Kitiltás dátuma';
$l['last_access'] = 'Utolsó belépés';
$l['no_bans'] = 'Jelenleg nincs érvényben kitiltás.';
$l['add_disallowed_username'] = 'Tiltott felhasználónév hozzáadása';
$l['username_desc'] = 'Megjegyzés: Wild card találat indikálásához használd a * -ot';
$l['disallow_username'] = 'Felhasználó név tiltása';
$l['add_disallowed_email_address'] = 'Tiltott email cím hozzáadása';
$l['email_address_desc'] = 'Megjegyzés: Wild card találat indikálásához használd a * -ot';
$l['disallow_email_address'] = 'Email cím tiltása';
$l['ban_an_ip_address'] = 'IP cím kitiltása';
$l['ip_address_desc'] = 'Megjegyzés: IP cím tartomány tiltásához használd a * -ot (Pl.: 127.0.0.*)';
$l['ban_ip_address'] = 'IP cím kitiltása';
$l['error_missing_ban_input'] = 'Nem adtál meg értéket a kitiltáshoz.';
$l['error_invalid_filter'] = 'A megadott szűrő nem létezik.';
$l['error_filter_already_banned'] = 'A megadott szűrő már tiltva.';
$l['success_ip_banned'] = 'Az IP cím sikeresen kitiltva.';
$l['success_username_disallowed'] = 'A felhasználónév sikeresen tiltva lett.';
$l['success_email_disallowed'] = 'Az email cím sikeresen tiltva lett.';
$l['success_ban_deleted'] = 'A megadott kitiltás sikeresen törölve lett.';
$l['confirm_ban_deletion'] = 'Biztos vagy benne, hogy törlöd ezt a kitiltást?';
$l['search_user'] = 'Felhasználó keresése';
