<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian (Magyar)
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://community.mybb.com/mods.php?action=view&pid=441
// Compatible version of MyBB : 1811 Béta
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sat, 29 Jul 2017 16:50:57 +0000
// --------------------------------------------------------------------------------

$l['security_questions'] = 'Biztonsági kérdések';
$l['security_questions_desc'] = 'Itt tudod szerkeszteni és kezelni a  biztonsági kérdéseket, amelyek véletlenszerűen jelennek majd meg a regisztráció során.';
$l['add_new_question'] = 'Új kérdés hozzáadása';
$l['add_new_question_desc'] = 'Adj meg egy kérdést és a hozzá tartozó választ biztonsági kérdésként, amely majd használva lesz a regisztráció során.';
$l['edit_question'] = 'Kérdés szerkesztése';
$l['edit_question_desc'] = 'Itt tudod szerkeszteni a biztonsági kérdést.';
$l['options'] = 'Opciók';
$l['correct'] = 'Helyes';
$l['incorrect'] = 'Helytelen';
$l['disable_question'] = 'Kérdés tiltása';
$l['enable_question'] = 'Kérdés engedélyezése';
$l['delete_question'] = 'Kérdés törlése';
$l['no_security_questions'] = 'Jelenleg nincsenek biztonsági kérdések a fórumodon.';
$l['question'] = 'Kérdés';
$l['question_desc'] = 'Add meg a kérdést, amelyre válaszolni kell a regisztráció során.';
$l['answers'] = 'Válasz(ok)';
$l['answers_desc'] = 'Add meg a választ/válaszokat a fentebb feltett kérdésedre. Kérlek a válaszokat külön sorba írd.';
$l['active'] = 'Aktív';
$l['save_question'] = 'Kérdés mentése';
$l['error_invalid_question'] = 'Egy érvénytelen kérdést választottál.';
$l['error_missing_question'] = 'Nem adtál meg kérdést';
$l['error_missing_answer'] = 'Nem adtál meg egyetlen választ sem erre a kérdésre';
$l['success_question_created'] = 'A kérdés sikeresen létrehozva.';
$l['success_question_updated'] = 'A kérdés sikeresen frissítve.';
$l['success_question_disabled'] = 'A kérdés sikeresen letiltva.';
$l['success_question_enabled'] = 'A kérdés sikeresen engedélyezve.';
$l['success_question_deleted'] = 'A kérdés sikeresen törölve.';
$l['confirm_question_deletion'] = 'Biztosan szeretnéd törölni ezt a kérdést?';
$l['shown'] = 'Mutat???';
