<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian (Magyar)
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://community.mybb.com/mods.php?action=view&pid=441
// Compatible version of MyBB : 1810 Béta
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sat, 14 Jan 2017 12:47:44 +0000
// --------------------------------------------------------------------------------

$l['report_reasons'] = 'Jelentés okai';
$l['report_reasons_desc'] = 'Itt tudod létrehozni és kezelni azon okokat, amelyeket választhatók, amikor a felhasználók jelentenik a tartalmat.';
$l['add_new_reason'] = 'Új ok hozzáadása';
$l['add_new_reason_desc'] = 'Új ok hozzzáadása a listához, amelyből a felhasználók választhatnak, amikor jelentik a tartalmat.';
$l['edit_reason'] = 'Ok szerkesztése';
$l['edit_reason_desc'] = 'Egy ok szerkesztése a listán, amelyből a felhasználók választhatnak, amikor jelentik a tartalmat.';
$l['applies_to'] = 'Alkalmazás a következőkre';
$l['order'] = 'Sorrend';
$l['extra_comment'] = 'Szükséges megjegyzés?';
$l['options'] = 'Beállítások';
$l['delete_reason'] = 'Ok törlése';
$l['no_report_reasons'] = 'Jelenleg nincsenek jelentés okok a fórumban.';
$l['reason_title'] = 'Cím';
$l['reason_title_desc'] = 'Adja meg az ok címét a jelntett tartalomhoz.';
$l['requires_extra'] = 'Szükséges további extra megjegyzés?';
$l['requires_extra_desc'] = 'Szükséges a felhasználónak megadni további megjegyzést, amikor kiválasztja ezt az okot?';
$l['save_reason'] = 'Ok mentése';
$l['content_colon'] = 'Tartalom:';
$l['all_content'] = 'Az összes tartalom';
$l['select_content'] = 'Tartalom kiválasztása';
$l['report_content_'] = 'Egyik sem';
$l['report_content_all'] = 'Az összes';
$l['report_content_post'] = 'Üzenet';
$l['report_content_profile'] = 'Profil';
$l['report_content_reputation'] = 'Hírnév';
$l['report_reason_rules'] = 'Fórum szabályának megszegése';
$l['report_reason_bad'] = 'Nem megfelelő tartalom';
$l['report_reason_spam'] = 'Spam tartalom';
$l['report_reason_wrong'] = 'Rossz fórum';
$l['report_reason_other'] = 'Egyéb';
$l['default_report_reason'] = 'Alapértelmezet';
$l['custom_report_reason'] = 'Egyedi';
$l['update_reasons_order'] = 'Okok sorrendjének frissítése';
$l['error_cannot_modify_reason'] = 'Nem tudod módosítani ezt az okok.';
$l['error_cannot_delete_reason'] = 'Nem tudod törölni ezt az okot.';
$l['error_invalid_reason'] = 'Egy érvéytelen okok választottál ki.';
$l['error_missing_title'] = 'Nem adtad meg az ok címét.';
$l['error_missing_extra'] = 'Nem választotad ki, hogy akarsz-e extra infromációt ehhez az okhoz.';
$l['success_reasons_disporder_updated'] = 'A jelentés okának sorrendje sikeresen frissítve.';
$l['success_reason_created'] = 'Az ok sikeresen létrehozva.';
$l['success_reason_updated'] = 'Az ok sikeresen frissítve.';
$l['success_reason_deleted'] = 'Az ok sikeresen törölve.';
$l['confirm_reason_deletion'] = 'Biztos törölni akarod ezt az okot?';
