<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian (Magyar)
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://community.mybb.com/mods.php?action=view&pid=441
// Compatible version of MyBB : 1810 Béta
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 15 Jan 2017 10:39:11 +0000
// --------------------------------------------------------------------------------

$l['custom_profile_fields'] = 'Egyéni profil mezők';
$l['custom_profile_fields_desc'] = 'Itt szerkesztheted, törölheted vagy kezelheted az egyéni profil mezőket.';
$l['add_profile_field'] = 'Új profil mező hozzáadása';
$l['add_new_profile_field'] = 'Új profil mező hozzáadása';
$l['add_new_profile_field_desc'] = 'Itt létrehozhatsz új profil mezőket.';
$l['edit_profile_field'] = 'Profil mező szerkesztése';
$l['edit_profile_field_desc'] = 'Itt szerkesztheted az egyéni profil mezőket.';
$l['title'] = 'Cím';
$l['short_description'] = 'Rövid leírás';
$l['maximum_length'] = 'Maximális hosszúság';
$l['maximum_length_desc'] = 'A karakterek maximális száma, amelyet megadhatsz. Ez csak a szöveg dobozokra és szöveg mezőkre érvényes.';
$l['field_length'] = 'Mező hosszúság';
$l['field_length_desc'] = 'Itt a mező hosszúságát adhatod meg. Ez csak akkor alkalmazható, ha egyedülálló vagy többszörös választ igénylő mezőt készítesz.';
$l['display_order'] = 'Megjelenítési sorrend';
$l['display_order_desc'] = 'Itt lehet beállítani a sorrendet.';
$l['text'] = 'Szöveg doboz';
$l['textarea'] = 'Szöveg mező';
$l['select'] = 'Lenyíló lista';
$l['multiselect'] = 'Többszörös kiválasztást igénylő legördülő lista';
$l['radio'] = 'Rádiógombok';
$l['checkbox'] = 'Jelölőnégyzetek';
$l['field_type'] = 'Mező típusa';
$l['field_type_desc'] = 'A mező típusának beállítása.';
$l['field_regex'] = 'Reguláris kifejezések';
$l['field_regex_desc'] = 'Adj meg egy reguláris kifejezést, amelynek illeszkednie kell a felhasználói bevitelhez. Bizonyosodj meg róla, hogy a reguláris kifejezés érvényes és biztonságos — nem hajt végre érvényesítést. Hagyd üresen, ha nem használod.<br />
<strong>Például:</strong> ([a-z0-9_\\- ,.+]+)';
$l['selectable_options'] = 'Választható opciók?';
$l['selectable_options_desc'] = 'Kérlek add meg a kiválasztható opciókat, mindegyiket külön sorban, ez csak a \'Lenyíló listák\', \'Jelölőnégyzetek\', és \'Rádiógombok\' típusoknál működik.';
$l['required'] = 'Kötelező?';
$l['required_desc'] = 'Kötelezően ki kell tölteni a regisztráció vagy profil módosítás során? Nincs hatása, ha a mező rejtett, vagy nem módosítható.';
$l['show_on_registration'] = 'Mutassa a regisztrációkor?';
$l['show_on_registration_desc'] = 'Megjelenjen ez a mező a regisztrációs űrlapon? Vedd figyelembe, hogy ez nem érvényes, ha a mező nem szerkeszthető. A mezők, amelyekre szükség van mindig meg fognak jelenni a regisztrációkor.';
$l['display_on_profile'] = 'Megjelenjen a profilon?';
$l['display_on_profile_desc'] = 'Ez a mező megjelenjen a felhasználó profilján? Ez nem vonatkozik az adminisztrátorokra/moderátorokra.';
$l['display_on_postbit'] = 'Megjelenjen a postbit-en? <a href="http://docs.mybb.com/1.6/Postbit/" target="_blank">Mi a postbit</a>';
$l['display_on_postbit_desc'] = 'Ez a mező megjelenjen a felhasználó üzeneteiben?';
$l['viewableby'] = 'Általa megtekinthető';
$l['viewableby_desc'] = 'Válaszd ki azt a csoportot vagy csoportokat, amelyek megnézhetik ezt a profil mezőt.';
$l['editableby'] = 'Általa szerkeszthető';
$l['editableby_desc'] = 'Válaszd ki azt a csoportot vagy csoportokat, amelyek szerkeszthetik ezt a profil mező.';
$l['min_posts_enabled'] = 'Minimum hozzászólás szám?';
$l['min_posts_enabled_desc'] = 'Csak azoknak a felhasználóknak legyen elérhető, akik rendelkeznek egy adott hozzászólás számmal? Ha igen, add meg itt a szükséges hozzászólások számát.';
$l['parser_options'] = 'Feldolgozási beállítások';
$l['parse_allowhtml'] = 'Igen,engedélyezd  a HTML ebben a profil mezőben.';
$l['parse_allowmycode'] = 'Igen, engedélyezd a BB-t ebben a profil mezőben.';
$l['parse_allowsmilies'] = 'Igen, engedélyezd a hangulatjeleket ebben a profil mezőben.';
$l['parse_allowimgcode'] = 'Igen, engedélyezd [img] kódot ebben a profil mezőben.';
$l['parse_allowvideocode'] = 'Igen, engedélyezd [video] kódot ebben a profil mezőben.';
$l['save_profile_field'] = 'Profilmező mentése';
$l['name'] = 'Név';
$l['registration'] = 'Regisztrációkor megjelenjen?';
$l['editable'] = 'Szerkeszthető?';
$l['profile'] = 'Profilon megjelenjen?';
$l['postbit'] = 'Postbiten megjelenjen?';
$l['edit_field'] = 'Mező szerkesztése';
$l['delete_field'] = 'Mező törlése';
$l['no_profile_fields'] = 'Jelenleg nincsenek profil mezők meghatározva a fórumon.';
$l['error_missing_name'] = 'Nem adtad meg ennek az egyedi profil mezőnek a címét';
$l['error_missing_description'] = 'Nem adtál meg leírást ehhez az egyedi profil mezőhöz';
$l['error_invalid_fid'] = 'A kiválasztott profil mező nem létezik.';
$l['success_profile_field_added'] = 'Az egyedi profil mező sikeresen létrehozva.';
$l['success_profile_field_saved'] = 'Az egyedi profil mező sikeresen elmentve.';
$l['success_profile_field_deleted'] = 'A kiválasztott egyedi profil mező sikeresen törölve.';
$l['confirm_profile_field_deletion'] = 'Biztos, hogy törölni szeretnéd ezt a profil mezőt?';
