<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 15 Mar 2015 07:23:24 +0000
// --------------------------------------------------------------------------------

$l['calendars'] = 'Naptárak';
$l['manage_calendars'] = 'Naptárak kezelése';
$l['manage_calendars_desc'] = 'Ebben a szekcióban lehetőséged van a naptárak kezelésére. Ha megváltoztatod a naptárak megjelenítési sorrendjért, akkor bizonyosodj meg róla, hogy elküldted az oldal alján lévő formot.';
$l['add_calendar'] = 'Új naptár hozzáadása';
$l['add_calendar_desc'] = 'Itt tudsz létrehozni új naptárat.';
$l['edit_calendar'] = 'Naptár szerkesztése';
$l['edit_calendar_desc'] = 'Itt tudod szerkeszteni a naptárak beállításait.';
$l['calendar'] = 'Naptár';
$l['order'] = 'Sorrend';
$l['no_calendars'] = 'Jelenleg nincsenek naptárak a fórumodon.';
$l['save_calendar_orders'] = 'Naptár megjelenítési sorrend elmentése';
$l['name'] = 'Név';
$l['display_order'] = 'Megjelenítési sorrend';
$l['week_start'] = 'A hét kezdete';
$l['week_start_desc'] = 'Itt tudod beállítani, hogy melyik naptól kezdődjön a hét ebben a naptárban.';
$l['sunday'] = 'Vasárnap';
$l['monday'] = 'Hétfő';
$l['tuesday'] = 'Kedd';
$l['wednesday'] = 'Szerda';
$l['thursday'] = 'Csütörtök';
$l['friday'] = 'Péntek';
$l['saturday'] = 'Szombat';
$l['event_limit'] = 'Esemény korlát';
$l['event_limit_desc'] = 'Azon elemek száma, amely az adott napi összes esemény linkje előtt jelenjen meg.';
$l['show_birthdays'] = 'Megjelenítse a születésnapokat?';
$l['show_birthdays_desc'] = 'Szeretnéd megjeleníteni a regisztrált felhasználók születésnapját?';
$l['moderate_events'] = 'Új esemény moderálása?';
$l['moderate_events_desc'] = 'Ha ez az opció \'Igen\'-re van állítva, akkor az összes esemény külön lesz moderálva azoktól, amelyek a \'Moderációs sor kihagyása\' engedélyekkel lettek létrehozva.';
$l['allow_html'] = 'HTML engedélyezése az eseményekben?';
$l['allow_mycode'] = 'MyCode engedélyezése az eseményekben?';
$l['allow_img'] = '[IMG] kód engedélyezése az eseményekben?';
$l['allow_video'] = '[VIDEO] kód engedélyezése az eseményekben?';
$l['allow_smilies'] = 'Hangulatjelek engedélyezése az eseményekben?';
$l['save_calendar'] = 'Naptár mentése';
$l['permissions'] = 'Engedélyek';
$l['edit_permissions'] = 'Naptár engedélyek szerkesztése';
$l['calendar_permissions_for'] = 'Naptár engedélyek';
$l['permissions_group'] = 'Csoport';
$l['permissions_view'] = 'Nézet';
$l['permissions_post_events'] = 'Poszt események';
$l['permissions_bypass_moderation'] = 'Moderáció kihagyása';
$l['permissions_moderator'] = 'Moderátori engedélyek';
$l['permissions_all'] = 'Összes?';
$l['permissions_use_group_default'] = 'Csoport használata alapértelmezettként';
$l['save_permissions'] = 'Engedélyek mentése';
$l['error_invalid_calendar'] = 'A megadott naptár nem létezik.';
$l['error_missing_name'] = 'Nem adtál meg nevet ehhez a naptárhoz';
$l['error_missing_order'] = 'Nem adtál meg megjelenítési sorrendet ehhez a naptárhoz';
$l['success_calendar_created'] = 'A naptár sikeresen létrehozva.';
$l['success_calendar_updated'] = 'A naptár sikeresen frissítve.';
$l['success_calendar_permissions_updated'] = 'A naptár engedélyek sikeresen frissítve.';
$l['success_calendar_deleted'] = 'A kiválasztott naptár sikeresen törölve.';
$l['success_calendar_orders_updated'] = 'A naptár megjelenítési sorrendek sikeresen frissítve.';
$l['confirm_calendar_deletion'] = 'Biztos vagy benne, hogy törlöd ezt a naptárat?';
