<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Thu, 19 Mar 2015 10:22:15 +0000
// --------------------------------------------------------------------------------

$l['thread_prefixes'] = 'Téma előtagok';
$l['thread_prefixes_desc'] = 'A téma előtagokkal lehetőséged van olyan előtagokat létrehozni, amelyeket a felhasználók hozzá tudnak csatolni a témáikhoz. A témák ezután szűrhetőek lesznek egy fórumon belül az előtagok segítségével.';
$l['add_new_thread_prefix'] = 'Új téma előtag hozzáadása';
$l['add_new_thread_prefix_desc'] = 'Itt adhatsz hozzá új téma előtagot, megadhatod hol jelenjen meg, mint ahogyan azt is, hogy melyik felhasználói csoport használhatja.';
$l['edit_prefix'] = 'Előtag szerkesztése';
$l['edit_prefix_desc'] = 'Itt szerkesztheted a téma előtagot, és megváltoztathatod a megjelenését, valamint szabályozhatod, hogy hol jelenjen meg és melyik felhasználói csoport használhatja.';
$l['edit_thread_prefix'] = 'Téma előtag szerkesztése';
$l['delete_thread_prefix'] = 'Téma előtag törlése';
$l['prefix_options'] = 'Előtag beállítások';
$l['save_thread_prefix'] = 'Téma előtag mentése';
$l['prefix'] = 'Előtag';
$l['prefix_desc'] = 'Az előtag egyszerű szöveges verziója, ami a választó menükben fog megjelenni.';
$l['display_style'] = 'Stílus megjelenítése';
$l['display_style_desc'] = 'Így fog megjelenni az előtag a téma címek mellett. Használhatsz HTML kódot, vagy egyszerűen használhatod a fenti sima szöveges verziót is.';
$l['available_in_forums'] = 'Elérhető a fórumokban';
$l['available_to_groups'] = 'Elérhető a csoportok számára';
$l['no_thread_prefixes'] = 'A fórumodon nincsenek téma előtagok beállítva.';
$l['confirm_thread_prefix_deletion'] = 'Biztos vagy benne, hogy törlöd ezt a téma előtagokat? Megjegyzés: Az összes egyedi moderációs eszközt frissítened kell törlés után, ami ezt a téma előtagot használja.';
$l['success_thread_prefix_created'] = 'A téma előtag sikeresen létrehozva.';
$l['success_thread_prefix_updated'] = 'A téma előtag sikeresen frissítve.';
$l['success_thread_prefix_deleted'] = 'A téma előtagja sikeresen törölve. Frissítsd az összes egyedi moderációs eszközt, ami ezt az előtagot használja.';
$l['error_missing_prefix'] = 'Írd be a előtagot, amit hozzá szeretnél adni.';
$l['error_missing_display_style'] = 'Adj meg egy megjelenítési stílust ehhez az előtaghoz.';
$l['error_no_forums_selected'] = 'Kérlek válaszd ki azt a fórumot vagy azokat a fórumokat, ahol az előtag elérhető lesz.';
$l['error_no_groups_selected'] = 'Válassz ki egy csoportot, amelyikhez hozzá szeretnéd rendelni ezt az előtagot.';
$l['error_invalid_prefix'] = 'A megadott téma előtagja nem létezik.';
