<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian (Magyar)
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://community.mybb.com/mods.php?action=view&pid=441
// Compatible version of MyBB : 1810 Béta
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sat, 14 Jan 2017 11:23:46 +0000
// --------------------------------------------------------------------------------

$l['attachment_types'] = 'Csatolás típusok';
$l['attachment_types_desc'] = 'Itt tudsz létrehozni és kezelni csatolás típusokat, beállíthatod, hogy az egyes felhasználók milyen fájlokat tudjanak a hozzászólásaikhoz mellékelni.';
$l['add_new_attachment_type'] = 'Új csatolás típus hozzáadása';
$l['add_attachment_type'] = 'Csatolás típus hozzáadása';
$l['add_attachment_type_desc'] = 'Új csatolás típus hozzáadásával a tagok számára lehetővé válik ezen típus csatolása a hozzászólásaikhoz. Lehetőséged van a kiterjesztés, MIME típus, maximum méret beállítására, valamint megjeleníthetsz az egyes csatolás mellett egy kis ikont.';
$l['edit_attachment_type'] = 'Csatolás típus szerkesztése';
$l['edit_attachment_type_desc'] = 'Lehetőséged van a kiterjesztés, MIME típus, maximum méret beállítására, valamint megjeleníthetsz az egyes csatolás mellett egy kis ikont.';
$l['extension'] = 'Kiterjesztés';
$l['maximum_size'] = 'Maximum méret';
$l['no_attachment_types'] = 'Jelenleg nincsenek csatolás típusok a fórumodon.';
$l['name'] = 'Név';
$l['name_desc'] = 'Add meg a csatolmány nevét.';
$l['file_extension'] = 'Fájl kiterjesztés';
$l['file_extension_desc'] = 'Add meg a fájl kiterjesztését, amelyet szeretnél, hogy fel tudjanak tölteni (Ne tegyél pontot a kiterjesztés elé) (Például: txt)';
$l['mime_type'] = 'MIME Típus';
$l['mime_type_desc'] = 'Add meg a MIME típust, amelyet a szerver küld fájlletöltéskor ennél a típusnál (<a href="http://www.webmaster-toolkit.com/mime-types.shtml">Itt egy lista</a>)';
$l['maximum_file_size'] = 'Maximum fájlméret (Kilobyte)';
$l['maximum_file_size_desc'] = 'A maximum feltölthető fájlméret ennél a csatolás típusnál Kilobyte-okban (1 MB = 1024 KB)';
$l['limit_intro'] = 'Bizonyosodj meg róla, hogy a maximum fájlméret az alábbi PHP limitek alatt legyen:';
$l['limit_post_max_size'] = 'Max. poszt méret: {1}';
$l['limit_upload_max_filesize'] = 'Max. feltölthető fájlméret: {1}';
$l['attachment_icon'] = 'Csatolás ikon';
$l['attachment_icon_desc'] = 'Ha meg szeretnél jeleníteni egy kis ikont az adott csatolás típusok mellett, akkor írd be az elérési útvonalát ide. {theme} le lesz cserélve a képpel az adott sablonban, ezáltal megadhatsz téma specifikus csatolás ikonokat is.';
$l['save_attachment_type'] = 'Csatolás típus elmentése';
$l['error_invalid_attachment_type'] = 'Rossz csatolás típust választottál.';
$l['error_missing_mime_type'] = 'Nem adtál meg MIME típust ehhez a csatolás típushoz';
$l['error_missing_extension'] = 'Nem adtál meg fájl kiterjesztést ehhez a csatolás típushoz';
$l['success_attachment_type_created'] = 'A csatolás típus sikeresen létrehozva.';
$l['success_attachment_type_updated'] = 'A csatolás típus sikeresen frissítve.';
$l['success_attachment_type_deleted'] = 'A csatolás típus sikeresen törölve.';
$l['confirm_attachment_type_deletion'] = 'Biztos vagy benne, hogy törlöd ezt a csatolás típust?';
$l['success_activated_attachment_type'] = 'A kiválaszottt csatolmány típus sikeresen aktiválva.';
$l['success_deactivated_attachment_type'] = 'A kiválaszottt csatolmány típus sikeresen tiltva.';
$l['enabled'] = 'Engedélyezed?';
$l['avatar_file'] = 'Profilkép fájl';
$l['avatar_file_desc'] = 'Engedélyezni akarod, hogy ezen csatolmány típus használhtó legyen a profilképekhez?';
$l['available_to_groups'] = 'Csoport(ok) számára elérhető';
$l['available_in_forums'] = 'Fórum(ok)ban elérhető';
