<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Thu, 19 Mar 2015 09:37:02 +0000
// --------------------------------------------------------------------------------

$l['spiders_bots'] = 'Keresőrobotok';
$l['spiders_bots_desc'] = 'Ez a szekció lehetővé teszi, hogy kezeld a <a href=\\"http://hu.wikipedia.org/wiki/Keresőrobot">kereső robotokat</a>, amelyeket a fórumod automatikusan felismer. Ezenkívül azt is láthatod, hogy melyik robot mikor látogatta meg a fórumod.';
$l['add_new_bot'] = 'Új robot hozzáadása';
$l['add_new_bot_desc'] = 'Itt hozzáadhatsz új keresőrobotot melyet szeretnél, hogy a fórumod észleljen.';
$l['edit_bot'] = 'Robot szerkesztése';
$l['edit_bot_desc'] = 'Itt szerkesztheted a felvett robotokat.';
$l['bot'] = 'Robot';
$l['last_visit'] = 'Utolsó látogatás';
$l['no_bots'] = 'Jelenleg nincs hozzáadva kereső robot a fórumodhoz.';
$l['name'] = 'Név';
$l['name_desc'] = 'Add meg a <a href="http://webni.innen.hu/Keres_c5_91robot">kereső robot</a> nevét';
$l['user_agent'] = 'Kliensazonosító';
$l['user_agent_desc'] = 'Itt adhatod meg a robot azonosító kifejezést (részleges pontosság megengedett).';
$l['language_str'] = 'Nyelv';
$l['language_desc'] = 'A robot ezen a nyelven fogja indexelni a fórumot.';
$l['theme'] = 'Sablon';
$l['theme_desc'] = 'A robot ebben a sablonban fogja látni a fórumot.';
$l['user_group'] = 'Felhasználói csoport';
$l['user_group_desc'] = 'Itt választhatod ki, hogy a robot milyen felhasználói csoport tagjaként indexelje a fórumot. Figyelem: Hacsak nem tudod, hogy mit csinálsz, ezt a beállítást hagyd alapértelmezettként (Vendég/Guest)';
$l['save_bot'] = 'Robot mentése';
$l['use_board_default'] = 'Alapértelmezett használata';
$l['error_invalid_bot'] = 'Nincs ilyen robot.';
$l['error_missing_name'] = 'Nem adtad meg a robot nevét';
$l['error_missing_agent'] = 'Nem adtad meg a robot kliensazonosítóját.';
$l['success_bot_created'] = 'A robot sikeresen létrehozva.';
$l['success_bot_updated'] = 'A robot sikeresen frissítve.';
$l['success_bot_deleted'] = 'A kijelölt robot sikeresen törölve.';
$l['confirm_bot_deletion'] = 'Biztos, hogy törölni szeretnéd ezt a robotot?';
