<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 15 Mar 2015 07:23:45 +0000
// --------------------------------------------------------------------------------

$l['help_documents'] = 'Súgó Dokumentum';
$l['add_new_section'] = 'Kategória hozzáadása';
$l['add_new_section_desc'] = 'Itt új súgó kategóriákat tudsz létrehozni.';
$l['add_new_document'] = 'Új dokumentum hozzáadása';
$l['add_new_document_desc'] = 'Itt új súgó dokumentumokat tudsz létrehozni.';
$l['edit_section'] = 'Kategória szerkesztése';
$l['edit_section_desc'] = 'Itt tudod szerkeszteni a súgó kategóriákat.';
$l['edit_document'] = 'Dokumentum szerkesztése';
$l['edit_document_desc'] = 'Itt tudod szerkeszteni a súgó dokumentumokat.';
$l['manage_help_documents'] = 'Dokumentumok kezelése';
$l['manage_help_documents_desc'] = 'Itt tudod kezelni a súgó dokumentumokat.';
$l['title'] = 'Cím';
$l['short_description'] = 'Rövid leírás';
$l['display_order'] = 'Megjelenítési sorrend';
$l['enabled'] = 'Engedélyezve?';
$l['use_translation'] = 'Fordítás használata?';
$l['add_section'] = 'Kategória hozzáadása';
$l['add_document'] = 'Dokumentum hozzáadása';
$l['save_section'] = 'Kategória mentése';
$l['save_document'] = 'Dokumentum mentése';
$l['section'] = 'Kategória';
$l['document'] = 'Dokumentum';
$l['id'] = 'ID';
$l['custom_doc_sec'] = 'Saját dokumentum/kategória';
$l['default_doc_sec'] = 'Alapértelmezett dokumentum/kategória';
$l['no_help_documents'] = 'Jelenleg nincs súgó dokumentum a fórumon.';
$l['section_document'] = 'Kategória / Dokumentum';
$l['error_section_missing_name'] = 'Meg kell adnod a nevét a kategóriának.';
$l['error_section_missing_description'] = 'Meg kell adnod egy rövid leírást a kategóriához.';
$l['error_section_missing_enabled'] = 'Ki kell választanod az \'Igen\'-t vagy \'Nem\'-et az "Engedélyezve?" opcióhoz.';
$l['error_section_missing_translation'] = 'Ki kell választanod az \'Igen\'-t vagy \'Nem\'-et az "Fordítás használata?" opcióhoz.';
$l['error_missing_sid'] = 'Ki kell választani egy kategóriát a dokumentumnak.';
$l['error_document_missing_name'] = 'Meg kell adnod a nevét a dokumentumnak.';
$l['error_document_missing_description'] = 'Meg kell adnod egy rövid leírást a dokumentumhoz.';
$l['error_document_missing_document'] = 'Létre kell hoznod egy dokumentumot.';
$l['error_document_missing_enabled'] = 'Ki kell választanod az \'Igen\'-t vagy \'Nem\'-et az "Engedélyezve?" opcióhoz.';
$l['error_document_missing_translation'] = 'Ki kell választanod az \'Igen\'-t vagy \'Nem\'-et az "Fordítás használata?" opcióhoz.';
$l['error_invalid_sid'] = 'Érvénytelen azonosító.';
$l['error_missing_section_id'] = 'A megadott kategória nem létezik.';
$l['error_missing_hid'] = 'A dokumentum nem létezik.';
$l['success_help_section_added'] = 'A kategória sikeresen hozzáadva.';
$l['success_help_document_added'] = 'A súgó dokumentum sikeresen hozzáadva.';
$l['success_help_section_updated'] = 'A kategória frissítve.';
$l['success_help_document_updated'] = 'A dokumentum frissítve.';
$l['success_section_deleted'] = 'A kijelölt kategória törölve.';
$l['success_document_deleted'] = 'A kijelölt dokumentum törölve.';
$l['confirm_section_deletion'] = 'Biztos, hogy törölni szeretnéd ezt a kategóriát?';
$l['confirm_document_deletion'] = 'Biztos, hogy törölni szeretnéd ezt a dokumentumot?';
