<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian (Magyar)
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://community.mybb.com/mods.php?action=view&pid=441
// Compatible version of MyBB : 1810 Béta
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Mon, 01 May 2017 10:08:52 +0000
// --------------------------------------------------------------------------------

$l['custom_mycode'] = 'Saját BB kódok';
$l['mycode'] = 'BB Kódok';
$l['mycode_desc'] = 'Ez az opció lehetővé teszi, hogy további <a href="http://hu.wikipedia.org/wiki/BBCode" target="_blank">BB kódot</a> adj a fórumodhoz.';
$l['add_new_mycode'] = 'Új BB kód hozzáadása';
$l['add_new_mycode_desc'] = 'Itt új BB kódokat tudsz hozzáadni a fórumodhoz. A BB kód tesztelésére használd a lenti Sandbox opciót.';
$l['edit_mycode_desc'] = 'Itt tudod szerkeszteni a már létrehozott BB kódokat. A BB kód tesztelésére használd a lenti Sandbox opciót.';
$l['title'] = 'Cím';
$l['short_description'] = 'Rövid leírás';
$l['regular_expression'] = 'Szabályos kifejezés ';
$l['regular_expression_desc'] = 'Adj meg egy szabályos kifejezést mely a jellegzetes karakter kombinációját tartalmazza. Győződj meg róla hogy az általad megadott kifejezés szabályos, mert nem kerül ellenőrzésre.';
$l['replacement'] = 'Helyettesítés';
$l['replacement_desc'] = 'Add meg a helyettesítő kifejezést.';
$l['example'] = 'Példa:';
$l['enabled'] = 'Engedélyezve?';
$l['parse_order'] = 'Sorrend';
$l['parse_order_desc'] = 'A BB kódok ilyen sorrendben fognak megjelenni a listán.';
$l['edit_mycode'] = 'BB kód szerkesztése';
$l['activate_mycode'] = 'BB kód aktiválása';
$l['deactivate_mycode'] = 'BB kód deaktiválása';
$l['delete_mycode'] = 'BB kód törlése';
$l['no_mycode'] = 'Jelenleg nincsenek saját BB kódok hozzáadva a fórumodhoz.';
$l['save_mycode'] = 'Mentés';
$l['add_mycode'] = 'Hozzáadás';
$l['changes_not_saved'] = 'A változtatások még nem lettek elmentve.';
$l['sandbox'] = 'Sandbox';
$l['sandbox_desc'] = 'Ezt a mezőt a létrehozott BB kódok kipróbálására, tesztelésére használhatod.';
$l['test_value'] = 'Teszt';
$l['test_value_desc'] = 'Add meg a tesztelni kívánt szöveget.';
$l['result_html'] = 'HTML Eredmény';
$l['result_html_desc'] = 'Ebben a mezőben jelenik meg a HTML kód, melyet a Szabályos kifejezés használ.';
$l['result_actual'] = 'Eredmény';
$l['result_actual_desc'] = 'Az alábbi eredmény mutatja meg a végleges formát miután a HTML hozzárendelődött a kódhoz.';
$l['test'] = 'Tesztel';
$l['error_missing_title'] = 'Nem adtad meg a címet.';
$l['error_missing_regex'] = 'Nem adtál meg szabályos kifejezést.';
$l['error_missing_replacement'] = 'Nem adtál meg helyettesítést.';
$l['error_invalid_mycode'] = 'Nincs ilyen BB kód.';
$l['success_added_mycode'] = 'A BB kód hozzáadva.';
$l['success_deleted_mycode'] = 'A BB kód törölve.';
$l['success_updated_mycode'] = 'A BB kód frissítve.';
$l['success_deactivated_mycode'] = 'A BB kód deaktiválva.';
$l['success_activated_mycode'] = 'A BB kód aktiválva.';
$l['confirm_mycode_deletion'] = 'Biztos, hogy törölni szeretnéd ezt a BB kódot?';
$l['mycode_sandbox_test_error'] = 'Hiba lépett fel a teszt eredmények lekérdezésekor.';
$l['error_regex_already_available'] = 'Már egy létező reguláris kifejezést adtál meg. Kérlek válassz egy másik reguláris kifejezést  ehhez a BB kódhoz.';
