<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 15 Mar 2015 07:21:51 +0000
// --------------------------------------------------------------------------------

$l['bad_words'] = 'Szó szűrők';
$l['edit_bad_word'] = 'Szűrő szerkesztése';
$l['edit_bad_word_desc'] = 'Itt tudod szerkeszteni a szűrőt, és a helyettesítőjét. A \'*\' karakter bármely egyszerű karaktert jelenti (a-zA-Z0-9_).';
$l['bad_word_filters'] = 'Szó szűrők';
$l['bad_word_filters_desc'] = 'Ezzel az eszközzel lehetőséged van szavak, vagy kifejezések kezelésére, amelyek automatikusan lecserélésre kerülnek a fórum hozzászólásaiban. Nagyon hasznos trágár, és egyéb szavak kicserélésére.';
$l['bad_word'] = 'Szó';
$l['bad_word_desc'] = 'Írd be a szót, amit szűrni szeretnél';
$l['bad_word_max'] = 'Egy szűrendő szó nem lehet hosszabb 100 karakternél.';
$l['replacement'] = 'Helyettesítő';
$l['replacement_desc'] = 'Írd be a karaktersorozatot ami felülírja a szűrendő szót (Ha ez üres, akkor csillagok fognak látszódni)';
$l['replacement_word_max'] = 'Helyettesítő szó nem lehet hosszabb 100 karakternél.';
$l['error_replacement_word_invalid'] = 'A helyettesítő szó nem lehet ugyan az, mint a szűrője.';
$l['save_bad_word'] = 'Szűrő mentése';
$l['no_bad_words'] = 'Jelenleg nincs sző szűrő beállítva.';
$l['add_bad_word'] = 'Szűrő hozzáadása';
$l['error_missing_bad_word'] = 'Nem adtál meg szó szűrőt.';
$l['error_invalid_bid'] = 'A megadott szűrő nem létezik.';
$l['error_bad_word_filtered'] = 'A megadott szűrő már létezik.';
$l['success_added_bad_word'] = 'A szűrő sikeresen hozzáadva.';
$l['success_deleted_bad_word'] = 'A szűrő sikeresen törölve.';
$l['success_updated_bad_word'] = 'A szűrő sikeresen frissítve.';
$l['confirm_bad_word_deletion'] = 'Biztos vagy benne, hogy törlöd ezt a szűrőt?';
