<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Wed, 18 Mar 2015 15:23:28 +0000
// --------------------------------------------------------------------------------

$l['post_icons'] = 'Üzenet ikonok';
$l['add_post_icon'] = 'Új üzenet ikon hozzáadása';
$l['add_post_icon_desc'] = 'Itt összesen egy új üzenet ikont tudsz hozzáadni.';
$l['add_multiple_post_icons'] = 'Több üzenet ikon hozzáadása';
$l['add_multiple_post_icons_desc'] = 'Itt egyszerre több új üzenet ikont tudsz hozzáadni.';
$l['edit_post_icon'] = 'Üzenet ikon szerkesztése';
$l['edit_post_icon_desc'] = 'Itt tudod szerkeszteni az ikon adatait.';
$l['manage_post_icons'] = 'Üzenet ikonok kezelése';
$l['manage_post_icons_desc'] = 'Itt tudod szerkeszteni, törölni és kezelni az üzenet ikonjaidat.';
$l['name_desc'] = 'Ez lesz az ikon neve.';
$l['image_path'] = 'Ikon útvonala';
$l['image_path_desc'] = 'Ez lesz az elérési útvonal az üzenet ikonhoz.';
$l['save_post_icon'] = 'Üzenet ikon mentése';
$l['reset'] = 'Visszaállít';
$l['path_to_images'] = 'Képek elérési útvonala';
$l['path_to_images_desc'] = 'Ez a mappa elérési útvonala, ahol az ikonok találhatóak.';
$l['show_post_icons'] = 'Üzenet ikonok megjelenítése';
$l['image'] = 'Kép';
$l['add'] = 'Hozzáad?';
$l['save_post_icons'] = 'Mentés';
$l['no_post_icons'] = 'Jelenleg nincsenek üzenet ikonok a fórumon.';
$l['error_missing_name'] = 'Nem adtad meg a nevét az ikonnak.';
$l['error_missing_path'] = 'Nem adtad meg az elérési útvonalát az ikonnak.';
$l['error_missing_path_multiple'] = 'Nem adtad meg az elérési útvonalat.';
$l['error_invalid_path'] = 'Érvénytelen útvonalat adtál meg.';
$l['error_no_images'] = 'A megadott mappában nincsenek üzenet ikonok, vagy már az összes ikon hozzá lett adva a fórumhoz.';
$l['error_none_included'] = 'Nem választottál ki egyetlen ikont sem.';
$l['error_invalid_post_icon'] = 'Nincs ilyen üzenet ikon.';
$l['success_post_icon_added'] = 'Az üzenet ikon sikeresen hozzáadva.';
$l['success_post_icons_added'] = 'A kiválasztott üzenet ikonok sikeresen hozzáadva.';
$l['success_post_icon_updated'] = 'Az üzenet ikon sikeresen frissítve.';
$l['success_post_icon_deleted'] = 'Az üzenet ikon sikeresen törölve.';
$l['confirm_post_icon_deletion'] = 'Biztos, hogy törölni szeretnéd ezt az üzenet ikont?';
