<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian (Magyar)
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://community.mybb.com/mods.php?action=view&pid=441
// Compatible version of MyBB : 1812 Béta
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Mon, 27 Nov 2017 19:05:47 +0000
// --------------------------------------------------------------------------------

$l['attachments'] = 'Csatolások';
$l['stats'] = 'Statisztika';
$l['find_attachments'] = 'Csatolások keresése';
$l['find_attachments_desc'] = 'Használd a csatolmány(ok) keresőt, amellyel a felhasználók által csatolt fájlok között kereshetsz. Kezd azzal, hogy alább megadsz néhány keresési feltételt. A mezők kitöltése nem kötelező és a csatolmány kereső nem fogja használni a mező értékeit keresési feltételként, ha csak nem tartalmaz a mezők egyike egy értéket.
';
$l['find_orphans'] = 'Árva csatolások keresése';
$l['find_orphans_desc'] = 'Az árva csatolások olyan csatolások, melyek valamilyen oknál fogva hiányoznak az adatbázisból vagy a file rendszerből. Ez az opció segít őket megtalálni és eltávolítani.';
$l['attachment_stats'] = 'Csatolmány statisztika';
$l['attachment_stats_desc'] = 'Itt néhány adatot találhatsz a fórumodon található csatolásokról.';
$l['error_nothing_selected'] = 'Kérlek válassz ki egy vagy több csatolást a törléshez.';
$l['error_no_attachments'] = 'Jelenleg nincsenek csatolások a fórumodon. Mihelyst egy csatolást hozzáadnak a fórumhoz ez a szekció elérhetővé válik számodra.';
$l['error_not_all_removed'] = 'Csak néhány árva csatolások kerültek sikeresen törlésre, a többi csatolást nem sikerült eltávolítani a feltöltési (uploads) mappából.';
$l['error_invalid_username'] = 'A megadott felhasználónév érvénytelen.';
$l['error_invalid_forums'] = 'Egy vagy több fórum, amit kiválasztottál érvénytelen.';
$l['error_no_results'] = 'Nem találtunk csatolást a megadott keresési feltételek alapján.';
$l['error_not_found'] = 'A csatolmány nem található a feltöltési (uploads) mappában.';
$l['error_not_attached'] = 'A csatolmány több mint 24 órája lett feltöltve, de még nem lett hozzá csatolva hozzászóláshoz.';
$l['error_does_not_exist'] = 'A csatolmányhoz tartozó téma vagy hozzászólás nem létezik.';
$l['success_deleted'] = 'A kiválasztott csatolások sikeresen törölve.';
$l['success_orphan_deleted'] = 'A választott árva csatolások sikeresen törölve.';
$l['success_no_orphans'] = 'Jelenleg nincsenek árva csatolások a fórumon.';
$l['confirm_delete'] = 'Biztos, hogy törölni szeretnéd a kiválasztott csatolásokat?';
$l['general_stats'] = 'Általános statisztika';
$l['stats_attachment_stats'] = 'Csatolások - Csatolás statisztika';
$l['num_uploaded'] = '<strong>Feltöltések száma</strong>';
$l['space_used'] = '<strong>Felhasznált tárhely</strong>';
$l['bandwidth_used'] = '<strong>Becsült sávszélesség</strong>';
$l['average_size'] = '<strong>Méret összesen</strong>';
$l['size'] = 'Méret';
$l['posted_by'] = 'Szerző';
$l['thread'] = 'Téma';
$l['downloads'] = 'Letöltések';
$l['date_uploaded'] = 'Feltöltés dátuma';
$l['popular_attachments'] = 'Az 5 legnépszerűbb csatolás';
$l['largest_attachments'] = 'Az 5 legnagyobb csatolás';
$l['users_diskspace'] = 'Az 5 legtöbbet feltöltő tag (file méret szerint)';
$l['username'] = 'Felhasználónév';
$l['total_size'] = 'Teljes méret';
$l['orphan_results'] = 'Árva csatolások keresés - Eredmények';
$l['orphan_attachments_search'] = 'Árva csatolások keresés';
$l['reason_orphaned'] = 'Ok';
$l['reason_not_in_table'] = 'nem található az adatbázis táblában';
$l['reason_file_missing'] = 'Csatolt fájl nem található';
$l['reason_thread_deleted'] = 'Téma törölve';
$l['reason_post_never_made'] = 'Nem volt ilyen hozzászólás';
$l['unknown'] = 'Ismeretlen';
$l['results'] = 'Eredmény';
$l['step1'] = '1 lépés';
$l['step2'] = '2 lépés';
$l['step1of2'] = '1/2 - Fájlrendszer ellenőrzése';
$l['step2of2'] = '2/2 - Adatbázis ellenőrzése';
$l['step1of2_line1'] = 'Kérlek várj, a fájlrendszer vizsgálat alatt áll.';
$l['step2of2_line1'] = 'Kérlek várj, az adatbázis vizsgálat alatt áll.';
$l['step_line2'] = 'Automatikusan átirányítunk a következő lépésre.';
$l['scanning'] = 'Vizsgálat..';
$l['index_find_attachments'] = 'Csatolások - Csatolások keresése';
$l['find_where'] = 'Csatolás keresés...';
$l['name_contains'] = 'Fájlnév, amely tartalmazza';
$l['name_contains_desc'] = 'A keresési feltételek kibővítéséhez használd a: *.[fájl kiterjesztése] karaktert. Példa: *.zip.';
$l['type_contains'] = 'Fájl típus, amely tartalmazza';
$l['forum_is'] = 'Ebben a fórumban keressen';
$l['username_is'] = 'Feltöltő neve, amely tartalmazza';
$l['more_than'] = 'Több mint';
$l['greater_than'] = 'Nagyobb mint';
$l['is_exactly'] = 'Pontosan';
$l['less_than'] = 'Kevesebb mint';
$l['date_posted_is'] = 'Feltöltés dátuma';
$l['days_ago'] = 'nappal ezelőtt';
$l['file_size_is'] = 'Fájlméret';
$l['kb'] = 'KB';
$l['download_count_is'] = 'Letöltések száma';
$l['display_options'] = 'Megjelenítési opciók';
$l['filename'] = 'Fájl neve';
$l['filesize'] = 'Fájl mérete';
$l['download_count'] = 'Letöltések száma';
$l['post_username'] = 'Felhasználónév';
$l['asc'] = 'Növekvő';
$l['desc'] = 'Csökkenő';
$l['sort_results_by'] = 'Rendezési elv';
$l['results_per_page'] = 'Csatolások oldalanként';
$l['in'] = 'szerint';
$l['button_delete_orphans'] = 'Kijelölt árva csatolások törlése';
$l['button_delete_attachments'] = 'Kijelölt csatolások törlése';
$l['button_find_attachments'] = 'Csatolások keresése';
$l['error_count'] = 'Nem lehet eltávolítani a {1} csatolmányt.';
$l['success_count'] = 'A(z) {1} csatolmány sikeresen eltávolítva.';
$l['poster_is'] = 'A feltöltő';
$l['poster_is_either'] = 'Felhasználó vagy Vendég';
$l['poster_is_user'] = 'Csak felhasználók';
$l['poster_is_guest'] = 'Csak vendégek';
