<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sat, 21 Mar 2015 11:50:14 +0000
// --------------------------------------------------------------------------------

$l['forum_announcements'] = 'Fórum közlemények';
$l['forum_announcements_desc'] = 'Itt tudod kezelni a fórumodon található közleményeket. A globális közlemények láthatóak az összes fórumban, míg az Egyedi közlemények csak az adott fórumban lesznek elérhetőek.';
$l['add_announcement'] = 'Közlemény hozzáadása';
$l['add_announcement_desc'] = 'Itt tudsz közleményt hozzáadni egy vagy több fórumhoz.';
$l['update_announcement'] = 'Közlemény mentése';
$l['preview_announcement'] = 'Közlemény előnézete';
$l['update_announcement_desc'] = 'Itt tudod frissíteni a közlemények részleteit.';
$l['start_date_desc'] = 'Ezen a napon és időpontban (GMT szerint) a közlemény meg fog jelenni a kiválasztott fórum(ok)ban.';
$l['end_date_desc'] = 'Ezen a napon és időpontban (GMT szerint) a közlemény nem lesz látható a fórumodon.
Kiválaszthatjuk, a \'Soha\' opció segítségével, hogy soha ne érjen véget ez a közlemény, amíg nem törlöd vagy szerkeszted a közlemény lejárati dátumát.';
$l['forums_to_appear_in_desc'] = 'A közlemény a kijelölt fórum(ok)ban fog megjelenni. A közlemény a kijelölt fórum(ok)ban és annak összes alfórumában is megjelenik majd.';
$l['announcement'] = 'Közlemény';
$l['global_announcements'] = 'Globális közlemények';
$l['no_global_announcements'] = 'Jelenleg nincsenek Globális közlemények.';
$l['no_forums'] = 'Jelenleg egyik fórum sincs beállítva a közlemények megjelenítésére.';
$l['confirm_announcement_deletion'] = 'Biztos, hogy törölni szeretnéd ezt a közleményt?';
$l['success_announcement_deleted'] = 'A kiválasztott közlemény sikeresen törölve.';
$l['success_added_announcement'] = 'A közlemény sikeresen létrehozva.';
$l['success_updated_announcement'] = 'A kiválasztott közlemény sikeresen frissítve.';
$l['error_invalid_announcement'] = 'Kérlek adj meg egy érvényes közleményt.';
$l['error_missing_title'] = 'Nem adtál meg címet.';
$l['error_missing_message'] = 'Nem írtál üzenetet.';
$l['error_missing_forum'] = 'Nem választottál ki fórumot.';
$l['error_invalid_start_date'] = 'A kezdő dátum érvénytelen.';
$l['error_invalid_end_date'] = 'A befejezés dátuma érvénytelen.';
$l['error_end_before_start'] = 'A befejezés dátuma nem lehet a kezdés dátumánál korábbi.';
$l['add_an_announcement'] = 'Közlemény hozzáadása';
$l['update_an_announcement'] = 'Közlemény frissítése';
$l['save_announcement'] = 'Közlemény mentése';
$l['title'] = 'Cím';
$l['start_date'] = 'Kezdés dátuma';
$l['end_date'] = 'Befejezés dátuma';
$l['message'] = 'Közlemény';
$l['forums_to_appear_in'] = 'Melyik fórumban jelenjen meg a közlemény';
$l['allow_html'] = 'HTML engedélyezése?';
$l['allow_mycode'] = 'BB kód engedélyezése?';
$l['allow_smilies'] = 'Hangulatjelek engedélyezése?';
$l['time'] = 'Idő:';
$l['set_time'] = 'Időpont beállítása';
$l['announcement_preview'] = 'Közlemény előnézet';
