<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 22 Mar 2015 08:53:51 +0000
// --------------------------------------------------------------------------------

$l['moderation_queue'] = 'Moderációs sor';
$l['threads'] = 'Témák';
$l['threads_desc'] = 'Itt tudod megnézni és jóváhagyni a moderálásra váró témákat.';
$l['posts'] = 'Hozzászólások';
$l['posts_desc'] = 'Itt tudod megnézni és jóváhagyni a moderálásra váró hozzászólásokat.';
$l['attachments'] = 'Csatolások';
$l['attachments_desc'] = 'Itt tudod megnézni és jóváhagyni a moderálásra váró csatolásokat.';
$l['threads_awaiting_moderation'] = 'Moderációra váró témák';
$l['posts_awaiting_moderation'] = 'Moderációra váró hozzászólások';
$l['attachments_awaiting_moderation'] = 'Moderációra váró csatolások';
$l['error_no_posts'] = 'Jelenleg nincs moderálásra váró hozzászólás.';
$l['error_no_attachments'] = 'Jelenleg nincs moderálásra váró csatolás.';
$l['error_no_threads'] = 'Jelenleg nincs téma, hozzászólás vagy csatolás, amely moderálásra várna.';
$l['success_threads'] = 'A választott témák sikeresen moderálva.';
$l['success_posts'] = 'A választott hozzászólások sikeresen moderálva.';
$l['success_attachments'] = 'A választott csatolások sikeresen moderálva.';
$l['subject'] = 'Tárgy';
$l['author'] = 'Szerző';
$l['posted'] = 'Elküldve';
$l['ignore'] = 'Figyelmen kívül hagy';
$l['approve'] = 'Jóváhagy';
$l['forum'] = 'Fórum:';
$l['thread'] = 'Téma:';
$l['post'] = 'Hozzászólás:';
$l['re'] = 'RE:';
$l['filename'] = 'Fájl név';
$l['uploadedby'] = 'Feltöltötte';
$l['controls'] = 'Vezérlők';
$l['mark_as_ignored'] = 'Megjelölés \'Figyelmen kívül hagyott\'-ként';
$l['mark_as_deleted'] = 'Megjelölés törlésre';
$l['mark_as_approved'] = 'Megjelölés \'Jóváhagyott\'-ként';
$l['perform_action'] = 'Tovább';
