<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 22 Mar 2015 08:54:54 +0000
// --------------------------------------------------------------------------------

$l['forums_and_posts'] = 'Fórumok és hozzászólások';
$l['forum_management'] = 'Fórum kezelés';
$l['forum_announcements'] = 'Fórum közlemények';
$l['moderation_queue'] = 'Moderációs sor';
$l['attachments'] = 'Csatolások';
$l['can_manage_forums'] = 'Kezelheti a fórumokat?';
$l['can_manage_forum_announcements'] = 'Kezelheti a fórumközleményeket?';
$l['can_moderate'] = 'moderálhat hozzászólást, témát, és csatolást?';
$l['can_manage_attachments'] = 'Kezelheti a csatolásokat?';
