<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian (Magyar)
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://community.mybb.com/mods.php?action=view&pid=441
// Compatible version of MyBB : 1812 Béta
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Mon, 27 Nov 2017 19:04:05 +0000
// --------------------------------------------------------------------------------

$l['today'] = 'Ma';
$l['yesterday'] = 'Tegnap';
$l['size_yb'] = 'YB';
$l['size_zb'] = 'ZB';
$l['size_eb'] = 'EB';
$l['size_pb'] = 'PB';
$l['size_tb'] = 'TB';
$l['size_gb'] = 'GB';
$l['size_mb'] = 'MB';
$l['size_kb'] = 'KB';
$l['size_bytes'] = 'byte';
$l['na'] = 'N/A';
$l['mybb_admin_panel'] = 'MyBB admin panel';
$l['mybb_admin_cp'] = 'MyBB Adminisztrátori vezérlőpult';
$l['logged_in_as'] = 'Bejelentkezve mint,';
$l['view_board'] = 'Fórum megtekintése';
$l['logout'] = 'Kijelentkezés';
$l['generated_in'] = 'Generálva {1} (másodperc) alatt <a href="{2}" target="_blank">{3} lekérdezéssel. Memória használat: {4}';
$l['enter_username_and_password'] = '{1} és jelszó megadása a folytatáshoz.';
$l['login_username'] = 'Felhasználónév';
$l['login_email'] = 'email';
$l['login_username_and_password'] = 'felhasználónév/email';
$l['mybb_admin_login'] = 'MyBB Kontroll Panel - Belépés';
$l['return_to_forum'] = 'Vissza a fórumhoz';
$l['please_login'] = 'Kérlek jelentkezz be';
$l['username'] = 'Felhasználónév:';
$l['username1'] = 'Email:';
$l['username2'] = 'Felhasználónév/Email:';
$l['password'] = 'Jelszó:';
$l['secret_pin'] = 'Titkos PIN:';
$l['login'] = 'Bejelentkezés';
$l['lost_password'] = 'Elfelejtetted a jelszavad?';
$l['error_invalid_admin_session'] = 'Érvénytelen adminisztrációs munkamenet.';
$l['error_admin_session_expired'] = 'Az adminisztrációs munkameneted lejárt.';
$l['error_invalid_ip'] = 'Az IP címed nem érvényes.';
$l['error_mybb_admin_lockedout'] = 'Ez a fiók ki lett tiltva.';
$l['error_mybb_admin_lockedout_message'] = 'A fiókod jelenleg ki lett tiltva, miután {1} alkalommal rontottad el a bejelentkezést. Egy e-mailt küldtünk a címedre instrukciókkal, hogy miként tudod újra engedélyezni a fiókodat.';
$l['error_invalid_secret_pin'] = 'Érvénytelen titkos PIN-t adtál meg.';
$l['error_invalid_username'] = 'A megadott felhasználónév érvénytelen.';
$l['error_invalid_uid'] = 'A megadott felhasználó-azonosító érvénytelen.';
$l['error_invalid_token'] = 'A megadott aktivációs kód érvénytelen.';
$l['success_logged_out'] = 'Sikeresen kijelentkeztél.';
$l['error_invalid_username_password'] = '{1} és jelszó páros, amit megadtál érvénytelen.';
$l['confirm_action'] = 'Biztos, hogy el szeretnéd végezni ezt a feladatot?';
$l['home'] = 'Főoldal';
$l['name'] = 'Név';
$l['size'] = 'Méret';
$l['controls'] = 'Vezérlők';
$l['view'] = 'Megtekint';
$l['yes'] = 'Igen';
$l['no'] = 'Nem';
$l['cancel'] = 'Mégsem';
$l['options'] = 'Opciók';
$l['proceed'] = 'Tovább';
$l['ok'] = 'OK';
$l['error'] = 'Hiba';
$l['edit'] = 'Szerkeszt';
$l['never'] = 'Soha';
$l['legend'] = 'Jelmagyarázat';
$l['version'] = 'Verzió';
$l['languagevar'] = 'Nyelv';
$l['use_default'] = 'Alapértelmezett használata';
$l['file'] = 'Fájl';
$l['go'] = 'Tovább';
$l['clear'] = 'Törlés';
$l['unknown'] = 'Ismeretlen';
$l['year'] = 'Év';
$l['year_short'] = 'év';
$l['years'] = 'Év';
$l['years_short'] = 'év';
$l['month'] = 'Hónap';
$l['month_short'] = 'hó';
$l['months'] = 'Hónap';
$l['months_short'] = 'hó';
$l['week'] = 'Hét';
$l['week_short'] = 'hét';
$l['weeks'] = 'Hét';
$l['weeks_short'] = 'hét';
$l['day'] = 'Nap';
$l['day_short'] = 'nap';
$l['days'] = 'Nap';
$l['days_short'] = 'nap';
$l['hour'] = 'Óra';
$l['hour_short'] = 'h';
$l['hours'] = 'Óra';
$l['hours_short'] = 'h';
$l['minute'] = 'Perc';
$l['minute_short'] = 'm';
$l['minutes'] = 'Perc';
$l['minutes_short'] = 'm';
$l['second'] = 'Másodperc';
$l['second_short'] = 's';
$l['seconds'] = 'Másodperc';
$l['seconds_short'] = 's';
$l['permanent'] = 'Állandó';
$l['all_forums'] = 'Összes fórum';
$l['all_groups'] = 'Összes csoport';
$l['select_forums'] = 'Fórum(ok) kiválasztása';
$l['select_groups'] = 'Csoport(ok) kiválasztása';
$l['forums_colon'] = 'Fórumok:';
$l['groups_colon'] = 'Csoportok: </br><span style="font-weight:normal"> Guests = Vendégek;</br> Registered = Regisztrált felhasználók;</br> Super Moderators - Szuper moderátorok;</br> Administrators - Adminisztrátorok;</br> Awaiting Activation = Aktiválásra várók;</br> Moderators = Moderátorok;</br> Banned = Kitiltottak </span>';
$l['none'] = 'Egyik sem';
$l['mybb_acp'] = 'MyBB Adminisztrátori vezérlőpult';
$l['pages'] = 'Oldalak';
$l['previous'] = 'Előző';
$l['page'] = 'Oldal';
$l['next'] = 'Következő';
$l['delete'] = 'Törlés';
$l['reset'] = 'Visszaállít';
$l['and'] = 'és';
$l['on'] = 'Be';
$l['off'] = 'Ki';
$l['alt_enabled'] = 'Engedélyezett';
$l['alt_disabled'] = 'Tiltott';
$l['saved'] = 'Mentett';
$l['rel_in'] = ' -ban/-ben';
$l['rel_ago'] = 'óta';
$l['rel_less_than'] = 'Kevesebb mint ';
$l['rel_time'] = '<span title="{5}{6}">{1}{2} {3} {4}</span>';
$l['rel_minutes_single'] = 'perc';
$l['rel_minutes_plural'] = 'perc';
$l['rel_hours_single'] = 'óra';
$l['rel_hours_plural'] = 'óra';
$l['quote'] = 'Idéz:';
$l['wrote'] = 'Írta:';
$l['code'] = 'Kód:';
$l['php_code'] = 'PHP Kód:';
$l['linkback'] = 'Eredeti hozzászólás';
$l['january'] = 'Január';
$l['february'] = 'Február';
$l['march'] = 'Március';
$l['april'] = 'Április';
$l['may'] = 'Május';
$l['june'] = 'Június';
$l['july'] = 'Július';
$l['august'] = 'Augusztus';
$l['september'] = 'Szeptember';
$l['october'] = 'Október';
$l['november'] = 'November';
$l['december'] = 'December';
$l['access_denied'] = 'Hozzáférés megtagadva';
$l['access_denied_desc'] = 'Nem rendelkezel megfelelő jogosultsággal az adminisztrációs panel ezen részének megtekintéséhez.';
$l['cannot_perform_action_super_admin_general'] = 'Elnézést, mivel nem vagy Szuper Adminisztrátor így ezt a funkciót nem használhatod.<br /><br />Hogy használhasd ezt a funkciót a felhasználói azonosítódat (user ID) hozzá kell adnod a Szuper Adminisztrátorok listájához az inc/config.php fájlban.';
$l['loading_text'] = 'Töltés<br />Kérlek várj...';
$l['timezone_gmt_minus_1200'] = '(GMT -12:00) Marshall Islands';
$l['timezone_gmt_minus_1100'] = '(GMT -11:00) Nome, Midway Island';
$l['timezone_gmt_minus_1000'] = '(GMT -10:00) Hawaii, Papeete';
$l['timezone_gmt_minus_950'] = '(GMT -9:30) Marquesas Islands';
$l['timezone_gmt_minus_900'] = '(GMT -9:00) Alaska';
$l['timezone_gmt_minus_800'] = '(GMT -8:00) Pacific Time';
$l['timezone_gmt_minus_700'] = '(GMT -7:00) Mountain Time';
$l['timezone_gmt_minus_600'] = '(GMT -6:00) Central Time, Mexico City';
$l['timezone_gmt_minus_500'] = '(GMT -5:00) Eastern Time, Bogota, Lima, Quito';
$l['timezone_gmt_minus_450'] = '(GMT -4:30) Caracas';
$l['timezone_gmt_minus_400'] = '(GMT -4:00) Atlantic Time, La Paz, Halifax';
$l['timezone_gmt_minus_350'] = '(GMT -3:30) Newfoundland';
$l['timezone_gmt_minus_300'] = '(GMT -3:00) Brazil, Buenos Aires, Georgetown, Falkland Is.';
$l['timezone_gmt_minus_200'] = '(GMT -2:00) Mid-Atlantic, South Georgia and the South Sandwich Islands';
$l['timezone_gmt_minus_100'] = '(GMT -1:00) Azores, Cape Verde Islands';
$l['timezone_gmt'] = '(GMT) Casablanca, Dublin, Edinburgh, London, Lisbon, Monrovia';
$l['timezone_gmt_100'] = '(GMT +1:00) Budapest, Berlin, Brussels, Copenhagen, Madrid, Paris, Rome, Warsaw';
$l['timezone_gmt_200'] = '(GMT +2:00) Athens, Istanbul, Cairo, Jerusalem, South Africa';
$l['timezone_gmt_300'] = '(GMT +3:00) Kaliningrad, Minsk, Baghdad, Riyadh, Nairobi';
$l['timezone_gmt_350'] = '(GMT +3:30) Tehran';
$l['timezone_gmt_400'] = '(GMT +4:00) Moscow, Abu Dhabi, Baku, Muscat, Tbilisi';
$l['timezone_gmt_450'] = '(GMT +4:30) Kabul';
$l['timezone_gmt_500'] = '(GMT +5:00) Islamabad, Karachi, Tashkent';
$l['timezone_gmt_550'] = '(GMT +5:30) Mumbai, Calcutta, Madras, New Delhi';
$l['timezone_gmt_575'] = '(GMT +5:45) Kathmandu';
$l['timezone_gmt_600'] = '(GMT +6:00) Almaty, Dhakra, Yekaterinburg';
$l['timezone_gmt_650'] = '(GMT +6:30) Yangon';
$l['timezone_gmt_700'] = '(GMT +7:00) Bangkok, Hanoi, Jakarta';
$l['timezone_gmt_800'] = '(GMT +8:00) Beijing, Hong Kong, Perth, Singapore, Taipei, Manila';
$l['timezone_gmt_900'] = '(GMT +9:00) Osaka, Sapporo, Seoul, Tokyo, Irkutsk';
$l['timezone_gmt_950'] = '(GMT +9:30) Adelaide, Darwin';
$l['timezone_gmt_1000'] = '(GMT +10:00) Melbourne, Papua New Guinea, Sydney, Yakutsk';
$l['timezone_gmt_1050'] = '(GMT +10:30) Lord Howe Island';
$l['timezone_gmt_1100'] = '(GMT +11:00) Magadan, New Caledonia, Solomon Islands, Vladivostok';
$l['timezone_gmt_1150'] = '(GMT +11:30) Norfolk Island';
$l['timezone_gmt_1200'] = '(GMT +12:00) Auckland, Wellington, Fiji, Marshall Island';
$l['timezone_gmt_1275'] = '(GMT +12:45) Chatham Islands';
$l['timezone_gmt_1300'] = '(GMT +13:00) Samoa, Tonga, Tokelau';
$l['timezone_gmt_1400'] = '(GMT +14:00) Line Islands';
$l['timezone_gmt_short'] = 'GMT {1}({2})';
$l['confirm_delete_logs'] = 'Törlöd a kijelölt naplózásokat?';
$l['confirm_delete_all_logs'] = 'Összes naplózás törlése?';
$l['selected_logs_deleted'] = 'A kijelölt bejegyzések törölve.';
$l['all_logs_deleted'] = 'Az összes bejegyzés törölve.';
$l['delete_selected'] = 'Kijelöltek törlése';
$l['delete_all'] = 'Összes törlése';
$l['encountered_errors'] = 'A következő hibák merültek fel:';
$l['invalid_post_verify_key'] = 'Hitelesítési hiba történt. Kérlek jelezd, hogy szeretnéd az alábbi akciót:';
$l['invalid_post_verify_key2'] = 'Hitelesítési hiba történt. Kérlek kétszer ellenőrizd, hogy helyesen akarsz az oldalhoz férni.';
$l['unknown_error'] = 'Ismeretlen hiba történt.';
$l['editor_bold'] = 'Félkövér';
$l['editor_italic'] = 'Dőlt';
$l['editor_underline'] = 'Aláhúzott';
$l['editor_strikethrough'] = 'Áthúzott';
$l['editor_subscript'] = 'Alsó index';
$l['editor_superscript'] = 'Felső index';
$l['editor_alignleft'] = 'Balra igazítás';
$l['editor_center'] = 'Középre zárás';
$l['editor_alignright'] = 'Jobbra igazítás';
$l['editor_justify'] = 'Sorkizárása';
$l['editor_fontname'] = 'Betűtípus';
$l['editor_fontsize'] = 'Betűméret';
$l['editor_fontcolor'] = 'Betűszín';
$l['editor_removeformatting'] = 'Formázás eltávolítása';
$l['editor_cut'] = 'Kivágás';
$l['editor_copy'] = 'Másolás';
$l['editor_paste'] = 'Beillesztés';
$l['editor_cutnosupport'] = 'A böngésződ nem támogatja a \'Kivágás\' parancsot. Kérlek használd a Ctrl/Cmd-X billentyűkombinációt.';
$l['editor_copynosupport'] = 'A böngésződ nem támogatja a \'Másolás\' parancsot. Kérlek használd a Ctrl/Cmd-C billentyűkombinációt.';
$l['editor_pastenosupport'] = 'A böngésződ nem támogatja a \'Beillesztés\' parancsot. Kérlek használd a Ctrl/Cmd-V billentyűkombinációt.';
$l['editor_pasteentertext'] = 'Illeszd be a szövegedet a következő mezőbe:';
$l['editor_pastetext'] = 'Szöveg beillesztése';
$l['editor_numlist'] = 'Számozott lista';
$l['editor_bullist'] = 'Felsorolás';
$l['editor_undo'] = 'Visszavonás';
$l['editor_redo'] = 'Ismét';
$l['editor_rows'] = 'Sorok:';
$l['editor_cols'] = 'Oszlopok:';
$l['editor_inserttable'] = 'Táblázat beszúrása';
$l['editor_inserthr'] = 'Vízszintes vonal beszúrása';
$l['editor_code'] = 'Kód';
$l['editor_php'] = 'PHP';
$l['editor_width'] = 'Szélesség (nem kötelező):';
$l['editor_height'] = 'Hosszúság (nem kötelező):';
$l['editor_insertimg'] = 'Egy kép beszúrása';
$l['editor_email'] = 'Email:';
$l['editor_insertemail'] = 'Egy email beszúrása';
$l['editor_url'] = 'URL:';
$l['editor_insertlink'] = 'Link beszúrása';
$l['editor_unlink'] = 'Linkelés megszüntetése';
$l['editor_more'] = 'További';
$l['editor_insertemoticon'] = 'Hangulatjel beszúrása';
$l['editor_videourl'] = 'Videó URL:';
$l['editor_videotype'] = 'Videó Típusa:';
$l['editor_insert'] = 'Beszúrás';
$l['editor_insertyoutubevideo'] = 'YouTube videó beszúrása';
$l['editor_currentdate'] = 'Aktuális dátum beszúrása';
$l['editor_currenttime'] = 'Aktuális idő beszúrása';
$l['editor_print'] = 'Nyomtatás';
$l['editor_viewsource'] = 'Egyszerű szöveg';
$l['editor_description'] = 'Leírás (nem kötelező):';
$l['editor_enterimgurl'] = 'Add meg a kép URLjét:';
$l['editor_enteremail'] = 'Add meg az email címet:';
$l['editor_enterdisplayedtext'] = 'Add meg megjelenítendő szöveget :';
$l['editor_enterurl'] = 'Add meg az URL-t:';
$l['editor_enteryoutubeurl'] = 'Add meg a YouTube videó URL-t vagy az azonosítót:';
$l['editor_insertquote'] = 'Idézet beszúrása';
$l['editor_invalidyoutube'] = 'Érvénytelen YouTube videó';
$l['editor_dailymotion'] = 'Dailymotion';
$l['editor_metacafe'] = 'MetaCafe';
$l['editor_veoh'] = 'Veoh';
$l['editor_vimeo'] = 'Vimeo';
$l['editor_youtube'] = 'Youtube';
$l['editor_facebook'] = 'Facebook';
$l['editor_liveleak'] = 'LiveLeak';
$l['editor_insertvideo'] = 'Videó beszúrása';
$l['editor_maximize'] = 'Teljes méret';
$l['missing_task'] = 'Hiba: Feladat fájl nem létezik';
$l['task_backup_cannot_write_backup'] = 'Hiba: Az adatbázismentés folyamat nem tud írni a backup könyvtárba.';
$l['task_backup_ran'] = 'Az adatbázismentés folyamat sikeresen lefutott.';
$l['task_checktables_ran'] = 'A táblaellenőrző folyamat sikeresen lefutott, sérült táblát nem talált.';
$l['task_checktables_ran_found'] = 'Figyelmeztetés: A táblaellenőrző folyamat sikeresen lefutott és kijavította a {1} táblá(ka)t.';
$l['task_dailycleanup_ran'] = 'A napi takarítási folyamat sikeresen lefutott.';
$l['task_hourlycleanup_ran'] = 'Az óránkénti takarítási folyamat sikeresen lefutott.';
$l['task_logcleanup_ran'] = 'A napló takarítási folyamat sikeresen lefutott és kitörölte a régi naplókat.';
$l['task_promotions_ran'] = 'A promóció folyamat sikeresen lefutott.';
$l['task_threadviews_ran'] = 'A témák áttekintése folyamat sikeresen lefutott.';
$l['task_usercleanup_ran'] = 'A felhasználói takarítási folyamat sikeresen lefutott.';
$l['task_massmail_ran'] = 'A hírlevél folyamat sikeresen lefutott.';
$l['task_userpruning_ran'] = 'A felhasználói takarítási folyamat sikeresen lefutott.';
$l['task_delayedmoderation_ran'] = 'A késleltetett moderációs folyamat sikeresen lefutott.';
$l['task_massmail_ran_errors'] = 'Egy vagy több hiba keletkezett "{1}": 

{2} küldése közben';
$l['task_versioncheck_ran'] = 'A verzió ellenőrző folyamat sikeresen lefutott.';
$l['task_versioncheck_ran_errors'] = 'Nem lehet kapcsolódni a MyBB-hez a verzió ellenőrzéshez.';
$l['task_recachestylesheets_ran'] = 'Újra gyorsítótárazva a {1} stíluslap.';
$l['massmail_username'] = 'Felhasználónév';
$l['email_addr'] = 'Email cím';
$l['board_name'] = 'Fórum neve';
$l['board_url'] = 'Fórum URL';
$l['lockout_unlock'] = 'Admin vezérlőpult feloldása';
$l['enter_username_and_token'] = 'Kérlek add meg a felhasználói neved és az aktivációs kódot a folytatáshoz.';
$l['unlock_token'] = 'Aktivációs kód:';
$l['unlock_account'] = 'Fiók feloldása';
$l['locked_out_subject'] = 'Az adminisztrátori fiók zárolva lett {1} -kor';
$l['locked_out_message'] = '{1},

Az adminisztrátori fiókod {2} zárolva lett {3} elrontott bejelentkezési kísérlet után.

A fiókod feloldásához, kérlek kattints a lent lévő hivatkozásra, vagy másold webböngésződbe.

{4}/{5}/index.php?action=unlock&uid={7}&token={6}

Amennyiben a fenti link nem működik helyesen, kattints az alábbira:

{4}/{5}/index.php?action=unlock

Meg kell adnod a
Felhasználóneved: {1}
Aktivációs kódodat: {6}

Köszönettel,

{2} csapata';
$l['comma'] = ', ';
$l['search_for_a_user'] = 'Felhasználó keresése';
$l['my2fa'] = 'Kétlépcsős azonosítás';
$l['my2fa_failed'] = 'A kód érvénytelen volt, most kiléptetünk';
$l['my2fa_code'] = 'Kérlek add meg a hitelesítési kódot';
$l['my2fa_label'] = 'Hitelesítési kód:';
$l['my2fa_no_codes'] = 'Figyelmeztetés: Az összes helyreállítási kódot használod. Kérlek látogasd meg a<a href="index.php?module=home-preferences&amp;action=recovery_codes">helyreállítási kód lapot</a>, hogy generálj egy új készletet.';
$l['mybb_engine'] = 'MyBB Motor';
$l['enable'] = 'Engedélyez';
$l['disable'] = 'Tilt';
$l['timezone_gmt_850'] = '(GMT +8:30) Pyongyang';
$l['timezone_gmt_875'] = '(GMT +8:45) Eucla';
$l['today_rel'] = '<span title="{1}">Ma</span>';
$l['yesterday_rel'] = '<span title="{1}">Tegnap</span>';
$l['guest'] = 'Vendég';
