<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 22 Mar 2015 10:09:06 +0000
// --------------------------------------------------------------------------------

$l['home'] = 'Főoldal';
$l['dashboard'] = 'Áttekintés';
$l['preferences'] = 'Személyes beállítások';
$l['mybb_credits'] = 'MyBB fejlesztői';
$l['add_new_forum'] = 'Új fórum hozzáadása';
$l['search_for_users'] = 'Felhasználók keresése';
$l['themes'] = 'Téma';
$l['templates'] = 'Sablon kezelő';
$l['plugins'] = 'Bővítmény kezelés';
$l['database_backups'] = 'Adatbázis mentés';
$l['quick_access'] = 'Gyors menü';
$l['online_admins'] = 'Adminok online';
$l['ipaddress'] = 'IP Cím:';
$l['mybb_documentation'] = 'MyBB Dokumentáció';
