<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian (Magyar)
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://community.mybb.com/mods.php?action=view&pid=441
// Compatible version of MyBB : 1811 Béta
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sat, 27 May 2017 05:33:22 +0000
// --------------------------------------------------------------------------------

$l['preferences_and_personal_notes'] = 'Személyes beállítások és személyes feljegyzések';
$l['prefs_and_personal_notes_description'] = 'Itt tudod kezelni az adminisztrációs vezérlőpult beállításaidat, valamint megjegyzéseket is hagyhatsz magadnak.';
$l['preferences'] = 'Személyes beállítások';
$l['global_preferences'] = 'Globális beállítások';
$l['acp_theme'] = 'Adminisztrátori vezérlőpult témája';
$l['select_acp_theme'] = 'Kérlek válaszd ki az adminisztrátori vezérlőpult által használt témát.';
$l['acp_language'] = 'Adminisztrátori vezérlőpult nyelve';
$l['select_acp_language'] = 'Kérlek válassz egy nyelvet, amelyen az adminisztrátori vezérlőpultot szeretnéd használni.';
$l['notes_not_shared'] = 'Ezeket a feljegyzéseket más adminisztrátorok nem látják.';
$l['save_notes_and_prefs'] = 'Személyes megjegyzések és beállítások mentése';
$l['personal_notes'] = 'Személyes megjegyzések';
$l['codemirror'] = 'Code Mirror be- és kikapcsolása';
$l['use_codemirror_desc'] = 'Ez a beállítás lehetővé teszi, hogy kikapcsold a Code Mirror szolgáltatást (ezt használják a sablon és stíluslap szerkesztésénél a szintaxiskiemeléshez). Kapcsold ki a szolgáltatást, ha lassulást veszel észre a fórumodon.';
$l['success_preferences_updated'] = 'A beállítások sikeresen elmentve.';
$l['use_2fa_desc'] = 'Kétlépcsős azonosítás egy módszer, amely megvédi az adminisztrátori fiókodat. Miután engedélyezted, lentebb látni fogsz egy QR kódot, amelyet be kell szkennelned egy alkalmazással <a href="http://docs.mybb.com/1.8/administration/security/2fa/" target="_blank">mint a Google Hitelesítő vagy az Authy</a>. Azok az alkalmazások generálni fognak egy token-t, amely meg kell adni minden belépésnél az adminisztrátori vezérlőpultba.';
$l['my2fa_qr'] = 'Kétlépcsős azonosítási kód';
$l['recovery_codes_desc'] = 'Nézd meg a <a href="index.php?module=home-preferences&amp;action=recovery_codes">helyreállítási kódokat</a>.';
$l['recovery_codes'] = 'Helyreállítási kódok';
$l['recovery_codes_warning'] = '<b>Figyelem:</b> a kódok újra lesznek generálva minden belépésnél és csak egyszer használhatod.';
$l['print_recovery_codes'] = 'Helyreállító kód nyomtatása';
