<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 22 Mar 2015 10:07:34 +0000
// --------------------------------------------------------------------------------

$l['dashboard'] = 'Áttekintés';
$l['dashboard_description'] = 'Ezen az oldalon néhány nagyon fontos statisztikát tekinthetsz meg a fórumoddal kapcsolatban, továbbá üzenetet írhatsz a többi adminisztrátornak.';
$l['mybb_server_stats'] = 'MyBB és szerver statisztika';
$l['forum_stats'] = 'Fórum statisztika';
$l['mybb_version'] = 'MyBB verzió';
$l['threads'] = 'Téma';
$l['new_today'] = 'új a mai napon';
$l['unapproved'] = 'jóváhagyásra vár';
$l['php_version'] = 'PHP Verzió';
$l['posts'] = 'Hozzászólás';
$l['sql_engine'] = 'SQL motor';
$l['users'] = 'Felhasználók';
$l['registered_users'] = 'Regisztrált felhasználó';
$l['active_users'] = 'Aktív felhasználó';
$l['registrations_today'] = 'Regisztráció a mai napon';
$l['awaiting_activation'] = 'felhasználó vár aktiválásra';
$l['server_load'] = 'Szerver terhelés';
$l['attachments'] = 'Csatolás';
$l['used'] = 'felhasznált terület';
$l['reported_posts'] = 'Jelentett hozzászólások';
$l['unread_reports'] = 'Olvasatlan jelentések';
$l['version_check'] = 'Frissítés ellenőrzése';
$l['last_update_check_two_weeks'] = 'Az utolsó <a href="{1}">MyBB verzió ellenőrzést</a> több mint két hete végezted. ';
$l['new_version_available'] = 'Jelenleg ez a verzió fut: {1} <br>A legfrissebb verzió: {2}.';
$l['version_check_description'] = 'Itt tudod ellenőrizni, hogy jelenleg a legfrissebb MyBB példányt használod és megnézheted a legfrissebb közleményeket közvetlenül a MyBB-től.';
$l['latest_mybb_announcements'] = 'Legfrissebb MyBB Közlemények';
$l['no_announcements'] = 'Nincsenek tárolt közlemények. <a href="index.php?module=home&amp;action=version_check">Frissítés ellenőrzése</a>.';
$l['your_version'] = 'A Te verziód';
$l['latest_version'] = 'Legfrissebb verzió';
$l['update_forum'] = 'Kérlek frissítsd a MyBB-t, ehhez látogasd meg a <a href="http://www.mybb.com" target="_blank">MyBB Weboldalát</a>.';
$l['read_more'] = 'Olvasd tovább';
$l['success_up_to_date'] = 'Gratulálunk, a legfrissebb MyBB-t futtatod.';
$l['error_out_of_date'] = 'MyBB példányod elavult.';
$l['error_communication'] = 'Kommunikációs probléma lépett fel a frissítő szerverrel. Kérlek próbáld meg később.';
$l['error_fetch_news'] = 'MyBB-nek nem sikerült letölteni a legutóbbi közleményeket a MyBB weboldalról.';
$l['news_description'] = 'A legfrissebb hírek <a href="http://blog.mybb.com/" target="_blank">MyBB Blog</a>-ról.';
$l['admin_notes_public'] = 'Az alábbi bejegyzéseket minden adminisztrátor láthatja.';
$l['admin_notes'] = 'Jegyzetfüzet';
$l['save_notes'] = 'Bejegyzés mentése';
$l['success_notes_updated'] = 'A jegyzetfüzet sikeresen frissítve.';
