<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 22 Mar 2015 10:02:51 +0000
// --------------------------------------------------------------------------------

$l['mybb_credits'] = 'MyBB fejlesztői/készítői';
$l['mybb_credits_description'] = 'Ők azok, akik idejükkel hozzájárultak, és azon fáradoztak, hogy megalkossák a MyBB-t.';
$l['about_the_team'] = 'A Csapatról';
$l['check_for_updates'] = 'Frissítés ellenőrzése';
$l['error_communication'] = 'Probléma lépett fel a legutolsó készítői lista letöltésekor. Kérlek próbáld meg később.';
$l['no_credits'] = 'Nincs MyBB fejlesztői/készítői lista tárolva. <a href="index.php?module=home-credits&amp;fetch_new=1">Frissítés ellenőrzése</a>.';
$l['success_credits_updated'] = 'A MyBB fejlesztői/készítői lista gyorsítótár sikeresen frissítve.';
