<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Mon, 23 Mar 2015 16:17:16 +0000
// --------------------------------------------------------------------------------

$l['templates_and_style'] = 'Sablonok és stílusok';
$l['themes'] = 'Témák';
$l['templates'] = 'Sablonok';
$l['can_manage_themes'] = 'Kezelheti a témákat?';
$l['can_manage_templates'] = 'Kezelheti a sablonokat?';
