<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Fri, 10 Apr 2015 10:53:53 +0000
// --------------------------------------------------------------------------------

$l['themes'] = 'Témák';
$l['themes_desc'] = 'Itt tudod kezelni a fórumodra telepített témákat. A témák lehetővé teszik, hogy testre szabhasd a fórumod megjelenését. A telepített témákat a lenti táblázatban találod. ';
$l['create_new_theme'] = 'Új téma létrehozása';
$l['create_new_theme_desc'] = 'Itt tudsz létrehozni új témákat az alapértelmezett téma alapján. <strong>Sablonkészletek, stíluslapok <a href="http://hu.wikipedia.org/wiki/CSS">(CSS)</a>, és más egyéb beállítások a szülő témától öröklődnek.</strong>';
$l['import_a_theme'] = 'Egy téma importálása';
$l['import_a_theme_desc'] = 'Itt új témákat tudsz importálni. Importálhatsz témákat a számítógépedről, vagy egy webhelyről URL megadásával.';
$l['edit_stylesheets'] = 'Stíluslapok szerkesztése';
$l['edit_stylesheets_desc'] = 'Itt kezelheted a témád által használt stíluslapokat. A stíluslapokkal <a href="http://hu.wikipedia.org/wiki/CSS">(CSS)</a> határozhatod meg a fórumon megjelenő betűtípusokat, színeket, és egyéb vizuális aspektusait a stílusnak. A témához csatolt stíluslapokat az alábbi táblázatban láthatod.';
$l['add_stylesheet'] = 'Stíluslap hozzáadása';
$l['add_stylesheet_desc'] = 'Itt új stíluslapokat rendelhetsz a témához. Egy stíluslap CSS-t tartalmaz, amely lehetővé teszi, hogy testre szabd ennek a témának a megjelenését. ';
$l['browse_themes'] = 'Témák böngészése';
$l['browse_themes_desc'] = 'Itt böngészhetsz a hivatalos MyBB modifikációk között, amelyek a MyBB verzióddal kompatibilisek.';
$l['browse_all_themes'] = 'Témák keresése';
$l['export_theme'] = 'Téma exportálása';
$l['export_theme_desc'] = 'Itt tudod exportálni a témáidat. Ez az opció különösen hasznos, ha szeretnéd a témáidat másokkal megosztani vagy áthelyezni egy másik fórumra.';
$l['duplicate_theme'] = 'Téma duplikálása';
$l['duplicate_theme_desc'] = 'Itt tudod duplikálni a témáidat. Ez segít, ha ezekből egy másik változatot akarsz fejleszteni.';
$l['colors_manage'] = 'Színek kezelése';
$l['colors_attached_to'] = 'színbeállítások';
$l['colors_setting'] = 'Alap szín';
$l['colors_setting_desc'] = 'Válassz egy színt, melyet ez a téma alapértelmezett színeként használ. A csatolt stíluslapok ezt a színt fogják használni.';
$l['colors_no_color_setting'] = 'A színek nem elérhetőek. Kérlek hozd létre lentebb a színek listáját, hogy használhasd ezt a funkciót.';
$l['colors_add'] = 'Színek kezelése';
$l['colors_add_desc'] = 'A színek listája elérhető ehhez a témához. Lennie kell egy kulcs pár (key=item) színek listájának, például <em>blue=Blue</em>. Új sorral válaszd el az elemeket.';
$l['colors_please_select'] = 'Nincs';
$l['colors_add_edit_desc'] = 'Válassz egy színt, amelyet ehhez a stíluslaphoz csatolsz. Több színt is kiválaszthatsz.';
$l['colors_specific_color'] = 'Egyéni színek';
$l['include_custom_only'] = 'Csak az egyedi módosításokat exportálja?';
$l['include_custom_only_desc'] = 'Alapértelmezésben az összes elem exportálva lesz, ha a "nem" -et választod, akkor csak a módosított elemek kerülnek exportálásra.';
$l['include_templates'] = 'Az exportáláskor csatolja a sablonokat?';
$l['include_templates_desc'] = 'Ha szeretnéd, hogy a saját készítésű sablonokat is exportálja a témával, akkor válaszd az \'Igen\'-t.';
$l['edit_stylesheet_simple_mode'] = 'Stíluslap szerkesztése: Egyszerű módban';
$l['edit_stylesheet_simple_mode_desc'] = 'Itt szerkesztheted a témád stíluslapját. Az Egyszerű mód lehetővé teszi, hogy módosításokat végezz a stíluslapodon minimális CSS ismerettel.';
$l['edit_stylesheet_advanced_mode'] = 'Stíluslap szerkesztése: Fejlett módban';
$l['edit_stylesheet_advanced_mode_desc'] = 'Itt egyszerű fájlként szerkesztheted a stíluslapodat. A stíluslap tartalmát az alábbi szövegmezőben találod.';
$l['theme'] = 'Téma';
$l['num_users'] = '# Felhasználók';
$l['edit_theme'] = 'Téma szerkesztése';
$l['delete_theme'] = 'Téma törlése';
$l['set_as_default'] = 'Beállít alapértelmezettnek';
$l['default_theme'] = 'Alapértelmezett téma';
$l['force_on_users'] = 'Hozzárendelés a tagokhoz';
$l['delete_revert'] = 'Töröl / Visszaállít';
$l['local_file'] = 'Helyi fájl';
$l['url'] = 'URL';
$l['import_from'] = 'Import innen:';
$l['import_from_desc'] = 'Válaszd ki az importálni kívánt fájlt. A fájlt importálhatod a merevlemezedről, vagy egy webhelyről, <a href="http://pcforum.hu/szotar/URL.html">URL</a> megadásával.';
$l['parent_theme'] = 'Szülő téma';
$l['parent_theme_desc'] = 'Válaszd ki azt a Témát, amelynek tulajdonságait szeretnéd ha a most importált Téma örökölné.';
$l['new_name'] = 'Új Név';
$l['new_name_desc'] = 'Az importált Téma új neve. Ha üresen hagyod a Téma fájlban használt nevet fogja megjeleníteni.';
$l['advanced_options'] = 'További opciók';
$l['ignore_version_compatibility'] = 'Verzió kompatibilitás ellenőrzés mellőzése';
$l['ignore_version_compat_desc'] = 'Telepítse a téma fájl-t még akkor is, ha más MyBB verzióval készült?';
$l['import_stylesheets'] = 'Stíluslapok importálása';
$l['import_stylesheets_desc'] = 'Ha a téma saját stíluslapokat tartalmaz, importálja őket?';
$l['import_templates'] = 'Sablonok importálása';
$l['import_templates_desc'] = 'Ha a téma saját sablonokat tartalmaz, importálja őket?';
$l['import_theme'] = 'Téma importálása';
$l['new_name_duplicate_desc'] = 'A duplikált téma új neve.';
$l['duplicate_stylesheets'] = 'Stíluslapok duplikálása';
$l['duplicate_stylesheets_desc'] = 'Ha ez a téma tartalmazz egyéni stíluslapokat legyenek ezek duplikálva?';
$l['duplicate_templates'] = 'Sablonok duplikálása';
$l['duplicate_templates_desc'] = 'Ha ez a téma tartalmazz egyéni stíluslapokat legyenek ezek duplikálva?';
$l['create_a_theme'] = 'Téma létrehozása';
$l['name'] = 'Név';
$l['name_desc'] = 'Adj meg egy nevet az új témának.';
$l['display_order'] = 'Sorrend';
$l['edit_theme_properties'] = 'Téma tulajdonságainak szerkesztése';
$l['name_desc_edit'] = 'Add meg a téma nevét.';
$l['allowed_user_groups'] = 'Engedélyezett felhasználói csoportok';
$l['allowed_user_groups_desc'] = 'Határozd meg, hogy melyik felhasználó csoport használhatja ezt a témát. Ha az \'Összes csoport\' opciót választod az felülírja az összes előző beállítást. A CTRL gomb lenyomásával több csoportot is kiválaszthatsz.';
$l['all_user_groups'] = 'Összes csoport';
$l['template_set'] = 'Sablon kategória';
$l['template_set_desc'] = 'Add meg a téma által használandó sablon kategóriát. a választott sablon fogja definiálni a jelölőnyelvet (HTML).';
$l['editor_theme'] = 'Szerkesztő Típusa';
$l['editor_theme_desc'] = 'Itt választhatod ki a MyCode szerkesztő felületét. A szerkesztő stílusok a <strong>jscripts/editor_themes</strong> mappában találhatóak.';
$l['img_directory'] = 'Kép mappa';
$l['img_directory_desc'] = 'A gyökérkönyvtár a képekhez melyeket ez a téma használ. Figyelem! Ez csak a téma által használt képek mappája, nem azoké a képeké amelyeket a stíluslapokon határozol meg.';
$l['logo'] = 'Fórum Logó';
$l['logo_desc'] = 'A logó fájl elérési útvonala (ez a logó jelenik meg minden oldal tetején).';
$l['table_spacing'] = 'Táblázat térköz ';
$l['table_spacing_desc'] = 'A táblázat celláinak belső margójának szélessége <a href="http://hu.wikipedia.org/wiki/Pixel">pixel</a>ben megadva. Ez a HTML <em><a href="http://www.tutorial.hu/tablazatok/">cellpadding</a></em> paraméterének felel meg.';
$l['inner_border'] = 'Belső táblázat vonal vastagsága';
$l['inner_border_desc'] = 'Ennek az opciónak a segítségével a cellák közötti távolság állítható be, pixelben. Ez a HTML <em><a href="http://www.tutorial.hu/tablazatok/">cellspacing</a></em> paraméterének felel meg.';
$l['save_theme_properties'] = 'Téma mentése';
$l['save_stylesheet_order'] = 'Stíluslap sorrend mentése';
$l['background'] = 'Háttér';
$l['extra_css_atribs'] = 'Extra CSS Attribútumok';
$l['color'] = 'Szín';
$l['width'] = 'Szélesség';
$l['text_decoration'] = 'Szöveg dekoráció pl. aláhúzott';
$l['font_family'] = 'Betűtípus';
$l['font_size'] = 'Betűméret';
$l['font_style'] = 'Betűstílus';
$l['font_weight'] = 'Betű vastagság';
$l['stylesheets'] = 'Stíluslapok';
$l['inherited_from'] = 'Öröklött ebből:';
$l['attached_to'] = 'Hozzárendelve';
$l['attached_to_nothing'] = 'Attached to nothing???';
$l['attached_to_desc'] = 'Hozzárendelhetsz egy stíluslapot globálisan vagy egyénileg egy fájlhoz.';
$l['actions'] = 'actions???';
$l['of'] = 'of???';
$l['attached_to_all_pages'] = 'Az összes oldalhoz csatolva';
$l['properties'] = 'Tulajdonságok';
$l['edit_style'] = 'CSS szerkesztése';
$l['stylesheets_in'] = 'Stíluslapok a következőben:';
$l['stylesheet_properties'] = 'Stíluslap tulajdonságok';
$l['stylesheet_inherited_default'] = 'Ez a stíluslap jelenleg a következőből öröklődik: {1}. Bármilyen változtatás megszakítja a folyamatot.';
$l['stylesheet_inherited'] = 'Ez a stíluslap jelenleg a következőből öröklődik: {1}. Bármilyen változtatás megszakítja a folyamatot. Szerkeszd a stíluslapot itt: {1}, hogy megtartsd az öröklődést.';
$l['globally'] = 'Globálisan';
$l['specific_files'] = 'Egy bizonyos fájlhoz';
$l['specific_actions'] = 'Egy bizonyos művelet';
$l['specific_actions_desc'] = 'A műveleteket vesszővel kell elválasztani';
$l['file'] = 'Fájl';
$l['add_another'] = 'Másik hozzáadása';
$l['edit_stylesheet_properties_for'] = 'Stíluslap tulajdonságok szerkesztése: ';
$l['file_name'] = 'Fájl neve';
$l['file_name_desc'] = 'A stíluslap neve, mely általában <strong>[.css]</strong> kiterjesztéssel végződik.';
$l['save_stylesheet_properties'] = 'Stíluslap mentése';
$l['saved'] = 'Elmentve';
$l['editing'] = 'Szerkesztés';
$l['selector'] = 'Válassz: ';
$l['save_changes'] = 'Változások mentése';
$l['save_changes_and_close'] = 'Változások mentése és bezárás';
$l['save_changes_js'] = 'Szeretnéd először menteni a változtatásaidat?';
$l['delete_confirm_js'] = 'Biztos, hogy törölni szeretnéd?';
$l['import_stylesheet_from'] = 'Importálás egy másik stíluslapból';
$l['write_own'] = 'Saját tartalom hozzáadása';
$l['save_stylesheet'] = 'Stíluslap mentése';
$l['add_stylesheet_to'] = 'Stíluslap hozzáadása a következőhöz: ';
$l['full_stylesheet_for'] = 'Teljes stíluslap a';
$l['recommended_themes_for_mybb'] = 'Ajánlott MyBB témák {1} verzióhoz';
$l['browse_results_for_mybb'] = 'Keresési eredmények a MyBB {1} -ra';
$l['search_for_themes'] = 'Témák keresése';
$l['search'] = 'Keresés';
$l['download'] = 'Letöltés';
$l['created_by'] = 'Készítette';
$l['error_invalid_stylesheet'] = 'Érvénytelen stíluslapot választottál.';
$l['error_invalid_theme'] = 'Érvénytelen témát választottál.';
$l['error_missing_name'] = 'Kérlek add meg a téma nevét.';
$l['error_missing_url'] = 'Kérlek add meg az importálandó téma URL-ét.';
$l['error_theme_already_exists'] = 'Már van ilyen téma. Kérlek adj meg egy új nevet.';
$l['error_theme_security_problem'] = 'Lehetséges biztonsági hiba a témában. Nem lett importálva. Vedd fel a kapcsolatot a készítőjével vagy a MyBB Group-pal segítségért.';
$l['error_local_file'] = 'Nem sikerült megnyitni a fájlt. Van ilyen fájl? Kérlek ellenőrizd le és próbáld újra.';
$l['error_uploadfailed'] = 'Feltöltés sikertelen. Kérlek próbáld újra.';
$l['error_uploadfailed_detail'] = 'Hiba részletei: ';
$l['error_uploadfailed_php1'] = 'PHP hiba: A feltöltött fájl mérete meghaladta a php.ini-ben beállított upload_max_filesize méretét. Kérlek lépj kapcsolatba a fórum adminisztrátorával';
$l['error_uploadfailed_php2'] = 'A feltöltött fájl mérete meghaladta a megengedett fájl méretet.';
$l['error_uploadfailed_php3'] = 'A fájl csak részlegesen került feltöltésre.';
$l['error_uploadfailed_php4'] = 'Sikertelen feltöltés.';
$l['error_uploadfailed_php6'] = 'PHP hiba: Egy ideiglenes könyvtár hiányzik. Lépj kapcsolatba a fórum adminisztrátorával.';
$l['error_uploadfailed_php7'] = 'PHP hiba: Nem sikerült a lemezre a fájl lemezre írása. Lépj kapcsolatba a fórum adminisztrátorával..';
$l['error_uploadfailed_phpx'] = 'PHP hiba kód: {1}. Lépj kapcsolatba a fórum adminisztrátorával.';
$l['error_uploadfailed_lost'] = 'A fájl nem található a szerveren.';
$l['error_uploadfailed_nocontents'] = 'A MyBB nem találta meg a feltöltött fájlt. Kérlek ellenőrizd, hogy a fájl biztosan feltöltésre került és nem sérült e.';
$l['error_invalid_version'] = 'Ez a téma a MyBB egy másik verziójához készült. Kérlek pipáld ki a "Verzió kompatibilitás ellenőrzés mellőzése" opciót, hogy ne jelenjen meg ez a hiba üzenet.';
$l['error_missing_stylesheet_name'] = 'Kérlek add meg a stíluslap nevét.';
$l['error_missing_stylesheet_extension'] = 'Ennek a stíluslapnak helyes fájlkiterjesztéssel kell végződnie, mint például: {1}<em>.css</em>';
$l['error_invalid_parent_theme'] = 'A választott szülő téma nem létezik. Kérlek válassz egy érvényes szülő témát.';
$l['error_invalid_templateset'] = 'A választott sablon kategória nem létezik. Kérlek válassz egy érvényes sablon kategóriát.';
$l['error_invalid_editortheme'] = 'A választott szerkesztő téma nem létezik. Kérlek válassz egy érvényes szerkesztő  témát.';
$l['error_inheriting_stylesheets'] = 'Nem törölheted ezt a témát mert más témák még használják a stíluslapját.';
$l['error_cannot_parse'] = 'A MyBB nem tudja olvasni ezt a stíluslapot az egyszerű szerkesztőben. Ehhez a fejlett szerkesztőt kell használnod.';
$l['error_communication_problem'] = 'Probléma lépett fel a MyBB téma szerverrel való kapcsolatfelvétel közben. Kérlek próbáld újra pár perc múlva.';
$l['error_no_results_found'] = 'Nincs találta a megadott kulcsszavakra.';
$l['error_no_color_picked'] = 'Nem lett meghatározva melyik szín legyen csatolva ehhez a stíluslaphoz.';
$l['error_no_display_order'] = 'Hiba található a stíluslap megjelenítési sorrendjében. Kérlek frissítsd az oldalt és próbáld újra.';
$l['success_duplicated_theme'] = 'A kiválasztott téma sikeresen duplikálva.';
$l['success_imported_theme'] = 'A választott téma importálva.';
$l['success_theme_created'] = 'A stílus létrehozva.';
$l['success_theme_deleted'] = 'A kijelölt téma törölve';
$l['success_stylesheet_properties_updated'] = 'A kijelölt stíluslap tulajdonságai frissítve.';
$l['success_stylesheet_updated'] = 'A kijelölt téma sikeresen frissítve.';
$l['success_stylesheet_deleted'] = 'A kijelölt stíluslap törölve/visszaállítva.';
$l['success_theme_set_default'] = 'A kijelölt téma most már alapértelmezett.';
$l['success_theme_forced'] = 'Az összes felhasználó hozzárendelve a kijelölt témához.';
$l['success_theme_properties_updated'] = 'A kijelölt téma tulajdonságai frissítve.';
$l['success_stylesheet_added'] = 'A stíluslap sikeresen létrehozva.';
$l['success_stylesheet_order_updated'] = 'A stíluslapok megjelenítésének sorrendje sikeresen frissítve.';
$l['confirm_theme_deletion'] = 'Biztos, hogy törölni szeretnéd ezt a témát?';
$l['confirm_stylesheet_deletion'] = 'Biztos, hogy törölni/visszaállítani szeretnéd ezt a stíluslapot?';
$l['confirm_theme_forced'] = 'Biztos, hogy azt szeretnéd, hogy minden felhasználó ezt a témát használja?';
$l['theme_info_fetch_error'] = 'Hiba lépett fel a stílus információ lekérdezésekor.';
$l['theme_info_save_error'] = 'Hiba lépett fel a stílus információ mentésekor.';
$l['saving'] = 'Mentés...';
