<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian (Magyar)
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://community.mybb.com/mods.php?action=view&pid=441
// Compatible version of MyBB : 1810 Béta
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 15 Jan 2017 09:44:52 +0000
// --------------------------------------------------------------------------------

$l['template_sets'] = 'Sablon készletek';
$l['template_set'] = 'Sablon készlet';
$l['templates'] = '{1}  sablonok';
$l['manage_template_sets'] = 'Sablonkészletek kezelése';
$l['manage_template_sets_desc'] = 'Itt tudod kezelni a sablonkészletek, megtekinteni a sablonok, melyek használják ezeket a beállításokat és elkezdheted személyre szabni a fórumod kinézetét.';
$l['add_set'] = 'Készlet hozzáadása';
$l['add_set_desc'] = 'Itt tudsz készíteni egy új sablonkészletet. A fórum az új kategóriát a \'Fő MyBB témák\' = \'Master MyBB templates\' alapján hozza létre, így szerkesztheted azt anélkül, hogy más sablonokban végeznél módosításokat.';
$l['add_template'] = 'Sablon hozzáadása';
$l['add_template_desc'] = 'Itt tudsz sablon darabkákat létrehozni, melyeket hozzáadhatsz meglévő sablon kategóriákhoz.';
$l['add_template_group'] = 'Sabloncsoport hozzáadása';
$l['add_template_group_desc'] = 'Adj hozzá egy sabloncsoportot, hogy összegyűjtsd a sablonokat.';
$l['search_replace'] = 'Keresés/csere';
$l['search_replace_desc'] = 'Ez az eszköz lehetővé teszi, hogy keresést végezhess sablon címekre vagy sablonokra, melyek egy bizonyos szöveget tartalmaznak.';
$l['find_updated'] = 'Frissített sablonok keresése';
$l['find_updated_desc'] = 'Ez az opció lehetővé teszi, hogy frissítéseket keress a MyBB sablonjaidhoz.';
$l['edit_template'] = 'Sablon szerkesztése';
$l['editing_template'] = 'Sablon szerkesztése: {1}';
$l['edit_template_desc'] = 'Itt tudod szerkeszteni a sablon kódját, címét és kategóriáját.';
$l['edit_set'] = 'Készlet szerkesztése';
$l['edit_set_desc'] = 'Itt tudod a kategória címét megváltoztatni.';
$l['manage_templates'] = 'Sablonok kezelése';
$l['manage_templates_desc'] = 'Itt tudod szerkeszteni ennek a sablonnak a részeit. A szerkesztéshez klikkelj a sablon nevére, vagy az \'Opciók => Szerkesztés\' menüpontra.';
$l['diff_report'] = 'Analizálás';
$l['diff_report_desc'] = 'Ez az opció lefuttat egy összehasonlítást a sablonok között, és pontosan megmutatja, hogy milyen változtatás történt a saját sablonod és a legfrissebb \'Master copy\' között.';
$l['title'] = 'Cím';
$l['save'] = 'Mentés';
$l['search_for'] = 'Ezt keresse';
$l['replace_with'] = 'Cseréli erre (nem kötelező)';
$l['reset'] = 'Visszaállít';
$l['find_templates'] = 'Sablonok keresése';
$l['find_and_replace'] = 'Keres és lecserél';
$l['search_template_names'] = 'Sablon nevek keresés';
$l['ungrouped_templates'] = 'Csoportosítatlan sablonok';
$l['search_noneset'] = 'Nem adtad meg a keresendő szót.';
$l['search_results'] = 'Sablon keresés eredménye';
$l['search_header'] = 'A következő keresése: "{1}", itt: {2}';
$l['search_updated'] = 'Frissítve {1}';
$l['search_found'] = 'Megtalálva {1}';
$l['search_created_custom'] = 'Egyedi sablon létrehozva: {1}';
$l['search_edit'] = 'szerkeszt';
$l['search_change_original'] = 'eredeti megváltoztatása';
$l['search_noresults'] = 'Nem találtunk sablont mely a következőket tartalmazná: \'<strong>{1}</strong>\'';
$l['search_noresults_title'] = 'Nem találtunk sablont a következő címmel: \'<strong>{1}</strong>\'';
$l['default_templates'] = 'Alapértelmezett sablonok';
$l['edit_template_breadcrumb'] = 'Sablon szerkesztése: ';
$l['global_templates'] = 'Általános sablonok';
$l['master_templates'] = 'Fő (Master) sablonok';
$l['not_used_by_any_themes'] = 'Nincs használatban';
$l['used_by'] = 'Használja: ';
$l['used_by_all_themes'] = 'Az össze téma használja';
$l['expand_templates'] = 'Sablonok kibontása';
$l['edit_template_set'] = 'Sablon kategória szerkesztése';
$l['delete_template_set'] = 'Sablon kategória törlése';
$l['empty_template_set'] = '<em>Nincsenek sablonok ebben a készletben.</em>';
$l['inline_edit'] = 'Soros szerkesztés';
$l['full_edit'] = 'Teljes szerkesztés';
$l['revert_to_orig'] = 'Visszaállít';
$l['delete_template'] = 'Sablon törlése';
$l['edit_in'] = 'Szerkesztés';
$l['group_calendar'] = 'Naptár';
$l['group_forumdisplay'] = 'Fórum megjelenítés';
$l['group_index'] = 'Index oldal';
$l['group_error'] = 'Hibaüzenet';
$l['group_memberlist'] = 'Tagok listája';
$l['group_multipage'] = 'Több oldalas lapozás';
$l['group_private'] = 'Privát üzenetek';
$l['group_portal'] = 'Portál';
$l['group_postbit'] = 'Post Bit???';
$l['group_posticons'] = 'Post Icon???';
$l['group_showthread'] = 'Téma megjelenítése';
$l['group_usercp'] = 'Felhasználói vezérlőpult';
$l['group_online'] = 'Ki van jelen';
$l['group_forumbit'] = 'Forum Bit???';
$l['group_editpost'] = 'Hozzászólás szerkesztése';
$l['group_forumjump'] = 'Fórum ugrás';
$l['group_moderation'] = 'Moderáció';
$l['group_nav'] = 'Navigáció';
$l['group_search'] = 'Keresés';
$l['group_showteam'] = 'Fórum csapat megjelenítése';
$l['group_reputation'] = 'Értékelés';
$l['group_newthread'] = 'Új téma';
$l['group_newreply'] = 'Új válasz';
$l['group_member'] = 'Tag';
$l['group_warning'] = 'Figyelmeztetési rendszer';
$l['group_global'] = 'Általános';
$l['group_header'] = 'Fejléc';
$l['group_managegroup'] = 'Csoport kezelése';
$l['group_misc'] = 'Egyebek';
$l['group_modcp'] = 'Moderátor vezérlőpult';
$l['group_announcement'] = 'Közlemény';
$l['group_polls'] = 'Szavazás';
$l['group_post'] = 'Hozzászólás';
$l['group_printthread'] = 'Téma nyomtatása';
$l['group_report'] = 'Jelentés';
$l['group_smilieinsert'] = 'Hangulatjel beszúró';
$l['group_stats'] = 'Statisztikák';
$l['group_xmlhttp'] = 'XMLHTTP';
$l['group_footer'] = 'Lábléc';
$l['group_video'] = 'Video MyCode';
$l['group_sendthread'] = 'Téma küldése';
$l['expand'] = 'Kibont';
$l['collapse'] = 'Bezár';
$l['save_continue'] = 'Mentés és a szerkesztés folytatása';
$l['save_close'] = 'Mentés és visszalép a listához';
$l['template_name'] = 'Sablon neve';
$l['template_name_desc'] = 'Sablon neve. Ha ezt megváltoztatod az alapértelmezett sablonon, akkor az új név alatt lesz elmentve.';
$l['template_set_desc'] = 'Melyik kategóriába kerüljön ez a sablon darabka?';
$l['template_group_prefix'] = 'Sabloncsoport előtag';
$l['template_group_prefix_desc'] = 'Az előtag neve, amelyen a sablonokat csoportosítod. Ez már nem lehet egy létező előtag neve. Például, ha már csoportosítva vannak a sablonok a <em>hello_world</em>, <em>hello_foobar</em> és <em>hello_foo</em> előtag néven, akkor ide a <strong>hello</strong>-t írd.';
$l['template_group_title'] = 'Sabloncsoport címe';
$l['template_group_title_desc'] = 'A csoport előtagjának címe. Ez fog megjelenni a sablon listába. Például, ha a miénk <em>hello</em> a sabloncsoport neve, akkor ide a <strong>Hello</strong>-t írd be.';
$l['edit_template_group'] = 'Sabloncsoport szerkesztése';
$l['editing_template_group'] = 'Sabloncsoport szerkesztése: {1}';
$l['delete_template_group'] = 'Sabloncsoport törlése';
$l['save_template_group'] = 'Sabloncsoport mentése';
$l['templates_the_same'] = 'A két sablon amelyet választottál egy és ugyanaz, így nem lehet őket összehasonlítani.';
$l['master_updated_ins'] = 'A változtatások melyeket az előző verzióban eszközöltél ki lesznek emelve így.';
$l['master_updated_del'] = 'A változtatások, melyeket a sablonokban eszközöltél ki lesznek emelve így.';
$l['template_diff_analysis'] = 'Sablon különbségek megjelenítése';
$l['search_names_header'] = 'Sablon nevének keresése mely a következőket tartalmazza: "{1}"';
$l['updated_template_welcome1'] = '<b>Szerkesztés</b> - Ez az opció lehetővé teszi, hogy módosítsd ennek a kategóriának a sablonjait.';
$l['updated_template_welcome2'] = '<b>Visszaállít</b> - Ez az opció visszaállít minden módosítást amit eddig végeztél a sablonon.';
$l['updated_template_welcome3'] = '<b>Analizálás</b> - Ez az opció lefuttat egy összehasonlítást a sablonok között, és pontosan megmutatja, hogy milyen változtatás történt a saját sablonod és a legfrissebb \'Master copy\' között.';
$l['no_global_templates'] = 'Jelenleg nincsenek \'általános sablonok\'.';
$l['no_updated_templates'] = 'Jelenleg nincsenek frissített sablonok.';
$l['confirm_template_set_deletion'] = 'Biztos, hogy törölni szeretnéd ezt a sablon kategóriát?';
$l['confirm_template_group_delete'] = 'Biztos, hogy törölni szeretnéd ezt a sabloncsoportot? Ez a művelet nem törli a sablonokat a csoportból.';
$l['confirm_template_deletion'] = 'Biztos, hogy törölni szeretnéd ezt a sablont?';
$l['confirm_template_revertion'] = 'Biztos, hogy vissza szeretnéd állítani ezt a sablont?';
$l['error_security_problem'] = 'Lehetséges biztonsági hiba a sablonban. Nézd át a módosításokat, vagy vedd fel a kapcsolatot a MyBB Group-pal segítségért.';
$l['error_missing_input'] = 'Kérlek győződj meg róla, hogy minden információ rendelkezésedre áll ahhoz, hogy sikeresen szerkeszd ezt a sablont (tid és sid)';
$l['error_already_exists'] = 'Ez a cím már foglalt. Kérlek válassz egy másik címet.';
$l['error_invalid_template'] = 'Kérlek válassz egy érvényes sablont.';
$l['error_missing_set_title'] = 'Kérlek válassz egy sablon kategória címet.';
$l['error_invalid_input'] = 'Kérlek győződj meg arról, hogy a megfelelő sablon kategória azonosítót használod.';
$l['error_invalid_set'] = 'Kérlek válassz egy érvényes sablon kategóriát.';
$l['error_invalid_template_set'] = 'Érvénytelen sablon kategória.';
$l['error_themes_attached_template_set'] = 'Ez a kategória nem törölhető mivel stílusok vannak hozzárendelve.';
$l['error_missing_group_prefix'] = 'Kérlek adj meg egy előtagot a sabloncsoportnak.';
$l['error_missing_group_title'] = 'Kérlek adj meg egy címet a sabloncsoportnak.';
$l['error_duplicate_group_prefix'] = 'A sabloncsoport már létezik ezzel az előtaggal. Kérlek adj meg egy másik előtagot.';
$l['error_missing_template_group'] = 'A sabloncsoport nem található.';
$l['error_default_template_group'] = 'Nem tudod szerkeszteni vagy eltávolítani az alapértelmezett sabloncsoportot.';
$l['success_template_saved'] = 'A kijelölt sablon elmentve.';
$l['success_template_deleted'] = 'A kijelölt sablon törölve.';
$l['success_template_reverted'] = 'A kijelölt sablon visszaállítva.';
$l['success_template_set_saved'] = 'A kijelölt sablon kategória elmentve.';
$l['success_template_set_deleted'] = 'A kijelölt sablon kategória törölve.';
$l['success_template_group_saved'] = 'A kiválasztott sabloncsoport sikeresen elmentve.';
$l['success_template_group_deleted'] = 'A kiválasztott sabloncsoport sikeresen törölve.';
$l['group_mycode'] = 'MyCode';
$l['error_invalid_group_title'] = 'Mint az aláhúzásjelet (_), melyeket használunk, mint határoló/elválasztó tiltottak a sablon csoport előtagokban. Kérlek válassz másikat. ';
