<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian (Magyar)
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://community.mybb.com/mods.php?action=view&pid=441
// Compatible version of MyBB : 1812 Béta
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Mon, 27 Nov 2017 19:06:29 +0000
// --------------------------------------------------------------------------------

$l['mod_logs'] = 'Moderátor naplók';
$l['mod_logs_desc'] = 'Itt megtekintheted, törölheted, vagy kereshetsz a moderátor naplókban. Ezek a naplók tartalmazzák a felhsználók (saját téma/hozzászólás törlése stb.), valamint a moderátorok tevékenységét.';
$l['prune_mod_logs'] = 'Moderátor naplók törlése';
$l['prune_mod_logs_desc'] = 'Itt tudod törölni a moderátor naplókat előre meghatározott kritériumok alapján.';
$l['no_modlogs'] = 'Nem találtam naplót a megadott kritérium alapján.';
$l['username'] = 'Felhasználónév';
$l['date'] = 'Dátum';
$l['action'] = 'Tevékenység';
$l['information'] = 'Információ';
$l['ipaddress'] = 'IP Cím';
$l['forum'] = 'Fórum:';
$l['thread'] = 'Téma:';
$l['post'] = 'Hozzászólás:';
$l['user_info'] = 'Felhasználó:';
$l['announcement'] = 'Közlemény:';
$l['filter_moderator_logs'] = 'Napló szűrő';
$l['forum_moderator'] = 'Fórum moderátor:';
$l['sort_by'] = 'Rendezési elv:';
$l['results_per_page'] = 'Eredmények oldalanként:';
$l['all_moderators'] = 'Összes moderátor';
$l['older_than'] = 'Régebbi mint ';
$l['forum_name'] = 'Fórum neve';
$l['thread_subject'] = 'Téma címe';
$l['asc'] = 'Növekvő';
$l['desc'] = 'Csökkenő';
$l['in'] = 'szerint';
$l['order'] = 'sorrend';
$l['days'] = 'nap';
$l['prune_moderator_logs'] = 'Moderátor napló törlése';
$l['date_range'] = 'Időintervallum:';
$l['success_pruned_mod_logs'] = 'A moderátor napló sikeresen törölve.';
$l['note_logs_locked'] = 'Biztonsági okok miatt a 24 óránál korábbi naplók nem távolítható el.';
$l['na_deleted'] = 'N/A - törölve';
