<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian (Magyar)
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://community.mybb.com/mods.php?action=view&pid=441
// Compatible version of MyBB : 1810 Béta
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 15 Jan 2017 10:20:37 +0000
// --------------------------------------------------------------------------------

$l['file_verification'] = 'Fájl hitelesítés';
$l['checking'] = 'Ellenőrzés...';
$l['file_verification_message'] = 'Ez a folyamat minden alapértelmezett MyBB fájl érvényességét ellenőrizni fogja. Nyomj Igen-t a folytatáshoz. <br /> <small>Figyelmeztetünk, hogy ez a folyamat nem tud különbséget tenni egyedi módosítások és hibás fájlok közt. Ezért óvatosnak kell lenned a "Hibás" megjelölést kapó fájlok visszaállításánál.</small>';
$l['error_communication'] = 'Probléma történt a MyBB szerverrel való kommunikáció során. Kérlek próbáld újra néhány perc múlva.';
$l['file'] = 'Fájl';
$l['no_corrupt_files_found'] = 'Gratulálok! Nincs hibás fájl a rendszerben.';
$l['found_problems'] = 'Talált problémák';
$l['no_problems_found'] = 'Nem találtam problémát';
$l['changed'] = 'Változott';
$l['missing'] = 'Hiányzó';
$l['status'] = 'Állapot';
