<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Fri, 10 Apr 2015 11:22:06 +0000
// --------------------------------------------------------------------------------

$l['task_manager'] = 'Ütemezett feladat kezelő';
$l['add_new_task'] = 'Új feladat hozzáadása';
$l['add_new_task_desc'] = 'Itt új ütemezett feladatokat tudsz létrehozni, melyek automatikusan futnak a fórumon.';
$l['edit_task'] = 'Feladat szerkesztése';
$l['edit_task_desc'] = 'Itt a már létrehozott feladatokat és azok beállításait tudod szerkeszteni.';
$l['task_logs'] = 'Feladat naplók';
$l['view_task_logs'] = 'Naplók megtekintése';
$l['view_task_logs_desc'] = 'Ha a naplózás engedélyezve van, akkor a lefutott feladatokról és az esetlegesen felmerülő hibákról itt kapsz értesítést.';
$l['scheduled_tasks'] = 'Ütemezett feladatok';
$l['scheduled_tasks_desc'] = 'Itt tudod kezelni az ütemezett feladatokat a fórumodon. Feladat futtatásához klikkelj a jobb oldali opciók ikonra.';
$l['title'] = 'Cím';
$l['short_description'] = 'Rövid leírás';
$l['task_file'] = 'Feladat fájl';
$l['task_file_desc'] = 'Válaszd ki a fájlt, amelyet szeretnéd, hogy ez a feladat futtasson.';
$l['time_minutes'] = 'Időpont: Perc';
$l['time_minutes_desc'] = 'Vesszővel válaszd el, ha több percet szeretnél megadni. Írj \'*\'-ot ha azt szeretnéd, hogy ez a feladat minden percben lefusson.';
$l['time_hours'] = 'Időpont: Óra';
$l['time_hours_desc'] = 'Vesszővel válaszd el, ha több órát szeretnél megadni. Írj \'*\'-ot ha azt szeretnéd, hogy ez a feladat minden órában lefusson.';
$l['time_days_of_month'] = 'Időpont: Napok';
$l['time_days_of_month_desc'] = 'Vesszővel válaszd el, ha több napot szeretnél megadni. Írj \'*\'-ot ha azt szeretnéd, hogy ez a feladat minden nap lefusson, vagy válassz egy napot a lenti listából.';
$l['every_weekday'] = 'Minden hétköznap';
$l['sunday'] = 'Vasárnap';
$l['monday'] = 'Hétfő';
$l['tuesday'] = 'Kedd';
$l['wednesday'] = 'Szerda';
$l['thursday'] = 'Csütörtök';
$l['friday'] = 'Péntek';
$l['saturday'] = 'Szombat';
$l['time_weekdays'] = 'Időpont: Hétköznapok';
$l['time_weekdays_desc'] = 'Válaszd ki, hogy melyik hétköznap fusson ez a feladat. A CTRL billentyű nyomva tartásával több napot is kiválaszthatsz.';
$l['every_month'] = 'Minden hónapban';
$l['time_months'] = 'Időpont: Hónapok';
$l['time_months_desc'] = 'Válaszd ki, hogy melyik hónapban fusson ez a feladat. A CTRL billentyű nyomva tartásával több hónapot is kiválaszthatsz.';
$l['enabled'] = 'Feladat engedélyezve?';
$l['enable_logging'] = 'Naplózás engedélyezése?';
$l['save_task'] = 'Mentés';
$l['task'] = 'Feladat';
$l['date'] = 'Dátum';
$l['data'] = 'Infó';
$l['no_task_logs'] = 'Jelenleg nincsenek feladat naplók.';
$l['next_run'] = 'Következő futtatás';
$l['run_task_now'] = 'Futtatás most';
$l['disable_task'] = 'Feladat letiltása';
$l['run_task'] = 'Feladat futtatása';
$l['enable_task'] = 'Feladat engedélyezése';
$l['delete_task'] = 'Feladat törlése';
$l['error_invalid_task'] = 'A feladat nem létezik.';
$l['error_missing_title'] = 'Nem adtál címet a feladatnak.';
$l['error_missing_description'] = 'nem adtál meg leírást a feladathoz.';
$l['error_invalid_task_file'] = 'A feladat amelyet választottál nem létezik.';
$l['error_invalid_minute'] = 'A perc amit megadtál nem érvényes.';
$l['error_invalid_hour'] = 'Az óra amit megadtál nem érvényes.';
$l['error_invalid_day'] = 'A nap amit megadtál nem érvényes.';
$l['error_invalid_weekday'] = 'A hétköznap amit választottál nem érvényes';
$l['error_invalid_month'] = 'A hónap amit választottál nem érvényes.';
$l['success_task_created'] = 'A feladat sikeresen létrehozva.';
$l['success_task_updated'] = 'A feladat sikeresen frissítve.';
$l['success_task_deleted'] = 'A feladat sikeresen törölve.';
$l['success_task_enabled'] = 'A feladat engedélyezve.';
$l['success_task_disabled'] = 'A feladat letiltva.';
$l['success_task_run'] = 'A feladat sikeresen lefuttatva.';
$l['confirm_task_deletion'] = 'Biztos, hogy törölni szeretnéd ezt a feladatot?';
$l['confirm_task_enable'] = '<strong>FIGYELMEZTETÉS:</strong> Egy olyan feladatot akarsz engedélyezni, amelyet <a href="http://wiki.hup.hu/index.php/Cron">cron</a>-on keresztül szoktak futtatni. (További információért kérlek olvasd át a <a href="http://docs.mybb.com/Help-Task_System.html" target="_blank">MyBB dokumentáció</a>-t. Tovább?';
$l['no_tasks'] = 'Jelen pillanatban nincsenek feladatok a fórumodban.';
