<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Fri, 10 Apr 2015 11:15:29 +0000
// --------------------------------------------------------------------------------

$l['tools_and_maintenance'] = 'Eszközök és karbantartás';
$l['maintenance'] = 'Karbantartás';
$l['logs'] = 'Naplózás';
$l['system_health'] = 'Rendszer áttekintés';
$l['cache_manager'] = 'Gyorsítótár kezelés';
$l['task_manager'] = 'Ütemezett feladatok';
$l['recount_and_rebuild'] = 'Számlálók frissítése';
$l['view_php_info'] = 'PHP információ';
$l['database_backups'] = 'Adatbázis mentés';
$l['optimize_database'] = 'Adatbázis optimalizálás';
$l['file_verification'] = 'Fájl hitelesítés';
$l['administrator_log'] = 'Admin naplózás';
$l['moderator_log'] = 'Moderátor naplózás';
$l['user_email_log'] = 'Tag email naplózás';
$l['system_mail_log'] = 'Rendszer email naplózás';
$l['user_warning_log'] = 'Figyelmeztetés naplózás';
$l['spam_log'] = 'Spam naplózás';
$l['statistics'] = 'Statisztika';
$l['can_access_system_health'] = 'Hozzáférhet a rendszer áttekintéshez?';
$l['can_manage_cache'] = 'Hozzáférhet a gyorsítótárhoz?';
$l['can_manage_tasks'] = 'Hozzáférhet az ütemezett feladatokhoz?';
$l['can_manage_db_backup'] = 'Hozzáférhet az adatbázismentéshez?';
$l['can_optimize_db'] = 'Kezelheti az adatbázis optimalizálást?';
$l['can_recount_and_rebuild'] = 'Frissítheti a számlálókat?';
$l['can_manage_admin_logs'] = 'Hozzáférhet az \'Admin naplózás\'-hoz?';
$l['can_manage_mod_logs'] = 'Hozzáférhet az \'Moderátor naplózás\'-hoz?';
$l['can_manage_user_mail_log'] = 'Hozzáférhet az \'Tag email naplózás\'-hoz?';
$l['can_manage_system_mail_log'] = 'Hozzáférhet az \'Rendszer email naplózás\'-hoz?';
$l['can_manage_user_warning_log'] = 'Hozzáférhet az \'Figyelmeztetés naplózás\'-hoz?';
$l['can_manage_spam_log'] = 'Kezelheti a spam naplókat?';
$l['can_view_php_info'] = 'Megtekintheti a PHP információt?';
$l['can_manage_file_verification'] = 'Hozzáférhet a fájl hitelesítéshez?';
$l['can_view_statistics'] = 'Megtekintheti a statisztikákat?';
