<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Fri, 10 Apr 2015 11:15:47 +0000
// --------------------------------------------------------------------------------

$l['optimize_database'] = 'Adatbázis optimalizálás';
$l['table_selection'] = 'Tábla kiválasztása';
$l['tables_select_desc'] = 'Itt kiválaszthatod az adatbázis táblákat melyeken a feladatot el szeretnéd végezni. A CTRL billentyű nyomva tartásával több táblát is kiválaszthatsz.';
$l['select_all'] = 'Összes kiválasztása';
$l['deselect_all'] = 'Kiválasztás megszüntetése';
$l['select_forum_tables'] = 'Fórum táblák kiválasztása';
$l['optimize_selected_tables'] = 'Adatbázis táblák optimalizálása';
$l['error_no_tables_selected'] = 'Nem választottál ki egy táblát sem.';
$l['success_tables_optimized'] = 'A táblák optimalizálása sikeresen befejeződött.';
