<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Fri, 10 Apr 2015 11:21:34 +0000
// --------------------------------------------------------------------------------

$l['system_health'] = 'Rendszer';
$l['system_health_desc'] = 'Itt áttekinthetsz néhány fontosabb információt a rendszeredről.';
$l['utf8_conversion'] = 'UTF-8 konvertálás';
$l['utf8_conversion_desc'] = 'Egy adatbázis táblát konvertálsz UTF-8 formátumba. Ez a művelet akár több órát is igénybe vehet, a fórumod és a tábla méretétől függően. A művelet végrehajtása után visszairányítunk a főoldalra.';
$l['utf8_conversion_desc2'] = 'Ez az eszköz ellenőrzi az adatbázis táblákat, hogy azok UTF-8 formátumban vannak-e, és lehetővé teszi a konvertálásukat, ha nem.';
$l['convert_all'] = 'Összes konvertálása';
$l['converting_to_utf8'] = 'A MyBB jelenleg "{1}" adatbázis táblát konvertál UTF-8 formátumba {2} formátumból.';
$l['convert_to_utf8'] = 'Konvertálni akarsz "{1}" adatbázistáblát UTF-8 formátumba {2} formátumból.';
$l['convert_all_to_utf'] = 'Az összes adatbázistáblát akarod konvertálni UTF-8 formátumból {1} formátumba.';
$l['convert_all_to_utf8mb4'] = 'Az ÖSSZES táblát 4-Byte UTF-8 Unicode kódolásba akarod konvertálni {1} kódolásból.';
$l['converting_to_utf8mb4'] = 'A MyBB "{1}" táblát konvertál 4-Byte UTF-8 Unicode kódolásba {2} kódolásból.';
$l['please_wait'] = 'Kérlek várj...';
$l['converting_table'] = 'Tábla konvertálása:';
$l['convert_table'] = 'Tábla konvertálása';
$l['convert_tables'] = 'Összes tábla konvertálása';
$l['convert_database_table'] = 'Adatbázis tábla konvertálása';
$l['convert_database_tables'] = 'Összes adatbázistábla konvertálása';
$l['table'] = 'Tábla';
$l['status_utf8'] = 'UTF-8 státusz';
$l['status_utf8mb4'] = '4-Byte UTF-8 támogatás<br />(MySQL 5.5.3, vagy újabb szükséges)';
$l['not_available'] = 'Nem elérhető';
$l['all_tables'] = 'Minden tábla';
$l['convert_now'] = 'Konvertál';
$l['totals'] = 'Összesítés';
$l['attachments'] = 'Csatolások';
$l['total_database_size'] = 'Teljes adatbázis méret';
$l['attachment_space_used'] = 'Csatolások által elfoglalt terület';
$l['total_cache_size'] = 'Teljes Cache Méret';
$l['estimated_attachment_bandwidth_usage'] = 'Becsült csatolás sávszélesség használat';
$l['max_upload_post_size'] = 'Max. feltöltés / hozzászólás méret';
$l['average_attachment_size'] = 'Átlagos csatolás méret';
$l['stats'] = 'Statisztika';
$l['task'] = 'Feladat';
$l['run_time'] = 'Futtatás időpontja';
$l['next_3_tasks'] = 'Következő 3 feladat';
$l['no_tasks'] = 'Jelenleg nincs futó feladat.';
$l['backup_time'] = 'Mentés időpontja';
$l['no_backups'] = 'Jelenleg nincs adatbázis mentés';
$l['existing_db_backups'] = 'Meglévő adatbázis mentések';
$l['writable'] = 'Írható';
$l['not_writable'] = 'Nem írható';
$l['please_chmod_777'] = 'Kérlek állítsd a CHMOD-ot 777-re.';
$l['chmod_info'] = 'Kérlek módosítsd a CHMOD beállításokat a megadottak szerint. További információkért a CHMOD-al kapcsolatban, látogasd meg ezt a linket: ';
$l['file'] = 'File';
$l['location'] = 'Hely';
$l['settings_file'] = 'Beállítási fájl (settings.php)';
$l['config_file'] = 'Konfigurációs fájl (config.php)';
$l['file_upload_dir'] = 'Fájl feltöltés mappa';
$l['avatar_upload_dir'] = 'Avatar feltöltés mappa';
$l['language_files'] = 'Nyelvi fájlok';
$l['backup_dir'] = 'Adatbázis mentések';
$l['cache_dir'] = 'Cache mappa';
$l['themes_dir'] = 'Témák mappája';
$l['chmod_files_and_dirs'] = 'Fájlok és mappák CHMOD beállításai';
$l['notice_process_long_time'] = 'Ez a művelet akár több órát is igénybe vehet, a fórumod és a tábla méretétől függően. <strong>Nagyon ajánlott adatbázis mentést készíteni, mivel a művelet nem vonható vissza.</strong>';
$l['notice_mb4_warning'] = 'A 4-Byte UTF-8 támogatáshoz MySQL 5.5.3 vagy újabb kell. Nem tudod importálni az adatbázisod más MySQL verzióval.';
$l['check_templates'] = 'Sablonok ellenőrzése';
$l['check_templates_desc'] = 'Az összes telepített sablonok átellenőrzése az ismert biztonsági hibák alapján.';
$l['check_templates_title'] = 'Sablon biztonság ellenőrzése';
$l['check_templates_info'] = 'Ez a folyamat ellenőrizni fogja a sablonjaidat a biztonsági problémákat keresve, amelyek befolyásolhatják a fórumodat és a szervert amelyen fut a fórum. Ez eltarthat egy ideig, ha sok sablont telepítettél.
<br /><br />A folyamat elindításához kattints az alább lévő \'Tovább\' gombra.';
$l['check_templates_info_desc'] = 'Az alábbi sablonokban ismert biztonsági probléma található. Kérlek nézd át ezeket.';
$l['full_edit'] = 'Teljes szerkesztés';
$l['error_chmod'] = 'a szükséges fájlok és/vagy mappák közül nem rendelkezik megfelelő CHMOD beállításokkal.';
$l['error_invalid_table'] = 'A megadott tábla nem létezik.';
$l['error_db_encoding_not_set'] = 'A jelenlegi MyBB beállításaid nem teszik lehetővé, hogy használd ezt az eszközt. További információért kérlek látogasd meg ezt az oldalt: <a href="http://docs.mybb.com/Utf8_setup.html">MyBB dokumentáció</a>.';
$l['error_not_supported'] = 'Jelenlegi adatbázisod nem támogatja a MyBB UTF-8 konverterét.';
$l['error_invalid_input'] = 'Probléma lépett fel a sablonok ellenőrzése során. Kérlek próbáld meg újra vagy segítséghez lépj kapcsolatba a MyBB Csoporttal.';
$l['error_master_templates_altered'] = 'A Master Sablonokat megváltoztatták. A segítséghez kérlek lépj kapcsolatba a MyBB Csoporttal, hogy hogyan változtatták meg ezeket.';
$l['error_utf8mb4_version'] = 'Ez a MySQL verzió nem támogatja a 4-Byte UTF-8 kódolást.';
$l['warning_multiple_encodings'] = 'Nem ajánlott több különböző kódolás használata az adatbázisban. Váratlan problémákat vagy MySQL hibákat okozhat.';
$l['warning_utf8mb4_config'] = 'A teljes 4-Byte UTF-8 támogatáshoz módosítanod kell a <i>$config[\'database\'][\'encoding\'] = \'utf8\';</i> beállítást <i>$config[\'database\'][\'encoding\'] = \'utf8mb4\';</i>-re az inc/config.php fájlban.';
$l['success_templates_checked'] = 'Sablonok sikeresen ellenőrizve - nem található biztonsági probléma!';
$l['success_all_tables_already_converted'] = 'Táblák konvertálása megtörtént, vagy már egyébként is UTF-8 formátumban voltak.';
$l['success_table_converted'] = 'A kiválasztott tábla "{1}" UTF-8 konvertálása sikeresen megtörtént.';
$l['success_chmod'] = 'Az összes szükséges fájl és mappa megfelelő CHMOD beállításokkal rendelkezik.';
