<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Fri, 10 Apr 2015 11:13:17 +0000
// --------------------------------------------------------------------------------

$l['system_email_log'] = 'Rendszer email naplózás';
$l['system_email_log_desc'] = 'A MyBB által elküldött, majd hiba miatt visszaérkezett emaileket találhatod itt. Ez a funkció különösen hasznos bizonyos SMTP beállítási hibák azonosítására.';
$l['prune_system_email_log'] = 'Naplózás törlése';
$l['filter_system_email_log'] = 'Naplózás szűrése';
$l['close_window'] = 'Ablak bezárása';
$l['user_email_log_viewer'] = 'Felhasználói email napló megjelenítő';
$l['smtp_code'] = 'SMTP kód:';
$l['smtp_server_response'] = 'SMTP szerver válasz:';
$l['to'] = 'Címzett';
$l['from'] = 'Feladó';
$l['subject'] = 'Tárgy';
$l['date'] = 'Dátum';
$l['email'] = 'Email';
$l['date_sent'] = 'Elküldés időpontja';
$l['error_message'] = 'Hibaüzenet';
$l['fine'] = 'Keresés Find???';
$l['no_logs'] = 'Jelenleg nincs bejegyzés.';
$l['subject_contains'] = 'A tárgy tartalmazza:';
$l['error_message_contains'] = 'A hiba üzenet tartalmazza:';
$l['to_address_contains'] = 'A címzett címe tartalmazza:';
$l['from_address_contains'] = 'A feladó címe tartalmazza:';
$l['find_emails_to_addr'] = 'Az erre a címre elküldött levelek keresése.';
