<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Fri, 10 Apr 2015 11:25:18 +0000
// --------------------------------------------------------------------------------

$l['warning_logs'] = 'Figyelmeztetés naplózás';
$l['warning_logs_desc'] = 'Itt tudod megtekinteni a kiadott figyelmeztetések listáját.';
$l['warned_user'] = 'Figyelmeztetett felhasználó';
$l['warning'] = 'Figyelmeztetés';
$l['date_issued'] = 'Dátum';
$l['expires'] = 'Lejár';
$l['expiry_date'] = 'Lejár';
$l['issued_date'] = 'Kelt';
$l['issued_by'] = 'Adta';
$l['details'] = 'Részletek';
$l['filter_warning_logs'] = 'Napló szűrő';
$l['filter_warned_user'] = 'Figyelmeztetett felhasználó:';
$l['filter_issued_by'] = 'Figyelmeztetést adta:';
$l['filter_reason'] = 'Részletek:';
$l['sort_by'] = 'Rendezési elv:';
$l['results_per_page'] = 'Eredmények száma oldalanként:';
$l['view'] = 'Megtekint';
$l['no_warning_logs'] = 'Jelenleg nincsenek figyelmeztetési naplók.';
$l['revoked'] = 'Visszavonva ';
$l['post'] = 'Hozzászólás';
$l['asc'] = 'Növekvő';
$l['desc'] = 'Csökkenő';
$l['in'] = ' szerint';
$l['order'] = ' sorrend';
$l['warning_details'] = 'Figyelmeztetés részletei';
$l['warning_note'] = 'Adminisztratív feljegyzések';
$l['already_expired'] = 'Lejárt';
$l['warning_revoked'] = 'Visszavont';
$l['warning_active'] = 'Aktív';
$l['error_invalid_warning'] = 'Érvénytelen figyelmeztetés.';
$l['revoke_warning'] = 'Figyelmeztetés visszavonása';
$l['revoke_warning_desc'] = 'A figyelmeztetés visszavonásához add meg annak okát.';
$l['reason'] = 'Ok:';
$l['warning_is_revoked'] = 'A figyelmeztetés visszavonva';
$l['revoked_by'] = 'Visszavonta:';
$l['date_revoked'] = 'Visszavonás dátuma:';
$l['error_already_revoked'] = 'A figyelmeztetés már vissza lett vonva.';
$l['error_no_revoke_reason'] = 'Nem írtál okot, hogy miért szeretnéd visszavonni a figyelmeztetést.';
$l['redirect_warning_revoked'] = 'A figyelmeztetés visszavonva, és a felhasználó figyelmeztetési pontjait csökkentettük.';
