<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Fri, 10 Apr 2015 11:06:06 +0000
// --------------------------------------------------------------------------------

$l['cache'] = 'Gyorsítótár:';
$l['cache_manager'] = 'Gyorsítótár kezelés';
$l['cache_manager_description'] = 'Itt tudod kezelni a <a href="http://wiki.hup.hu/index.php/Cache">gyorsítótárat</a>, mely a MyBB optimalizálásának egy módja.';
$l['rebuild_cache'] = 'A gyorsítótár újraépítése';
$l['reload_cache'] = 'A gyorsítótár újratöltés';
$l['rebuild_reload_all'] = '(Minden újraépítése és újratöltése)';
$l['error_cannot_rebuild'] = 'Ez a gyorsítótár nem újraépíthető.';
$l['error_empty_cache'] = 'A gyorsítótár üres.';
$l['error_incorrect_cache'] = 'Érvénytelen gyorsítótár lett megadva.';
$l['error_no_cache_specified'] = 'Nem adtál meg gyorsítótárat.';
$l['success_cache_rebuilt'] = 'A gyorsítótár sikeresen újraépítve.';
$l['success_cache_reloaded'] = 'A gyorsítótár sikeresen újratöltve.';
