<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Fri, 10 Apr 2015 11:13:57 +0000
// --------------------------------------------------------------------------------

$l['user_email_log'] = 'Tag email naplózás';
$l['user_email_log_desc'] = 'Minden egyes email, melyet a felhasználók küldenek egymásnak, (beleértve a "A téma küldése egy barátnak" opciót is) naplózásra kerül. Itt utánajárhatsz annak is, ha valamelyik felhasználó visszaél ezzel a funkcióval.';
$l['prune_user_email_log'] = 'Naplózás törlése';
$l['close_window'] = 'Ablak bezárása';
$l['user_email_log_viewer'] = 'Felhasználó Email Log Néző';
$l['to'] = 'Címzett';
$l['from'] = 'Feladó';
$l['ip_address'] = 'IP Cím';
$l['subject'] = 'Tárgy';
$l['date'] = 'Dátum';
$l['email'] = 'Email';
$l['date_sent'] = 'Elküldés dátuma';
$l['deleted'] = 'Törölve';
$l['sent_using_send_thread_feature'] = 'Elküldve a "A téma küldése egy barátnak" funkcióval.';
$l['thread'] = 'Téma:';
$l['find_emails_by_user'] = 'A felhasználó által küldött levelek keresése';
$l['find'] = 'Keresés Find???';
$l['deleted_user'] = 'Törölt felhasználó';
$l['email_sent_to_user'] = 'Email elküldve a felhasználónak';
$l['email_sent_using_contact_form'] = 'Email elküldve a kapcsolati űrlapot használva';
$l['no_logs'] = 'Jelenleg nincs bejegyzés.';
$l['filter_user_email_log'] = 'Naplózás szűrése';
$l['username_is'] = 'Felhasználónév';
$l['email_contains'] = 'Email cím tartalmazza';
$l['subject_contains'] = 'Tárgy tartalmazza';
$l['find_emails_to_user'] = 'A feladónak küldött összes email megkeresése';
$l['error_invalid_user'] = 'A megadott felhasználónév nem létezik.';
