<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian (Magyar)
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://community.mybb.com/mods.php?action=view&pid=441
// Compatible version of MyBB : 1812 Béta
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sat, 29 Jul 2017 16:54:31 +0000
// --------------------------------------------------------------------------------

$l['spam_logs'] = 'Spam naplók';
$l['spam_logs_desc'] = 'Itt megtekintheted a spam szűrő által blokkolt felhasználókat.';
$l['prune_spam_logs'] = 'Spam naplók tisztítás';
$l['prune_spam_logs_desc'] = 'Itt tudod megtisztítani a spam naplókat a meghatározott feltételek alapján.';
$l['spam_username'] = 'Felhasználónév';
$l['spam_email'] = 'Email cím';
$l['spam_ip'] = 'IP cím';
$l['spam_date'] = 'Dátum';
$l['spam_confidence'] = 'Confidence/Megbízható';
$l['no_spam_logs'] = 'Eddig egyetlen felhasználó sem lett blokkolva a spam szűrő által.';
$l['success_pruned_spam_logs'] = 'Spam naplók sikeresen megtisztítva.';
$l['note_logs_locked'] = 'Biztonsági okok miatt a 24 óránál korábbi naplók nem távolítható el.';
$l['all_usernames'] = 'Összes felhasználó';
$l['all_emails'] = ' Összes email cím';
$l['date_range'] = 'Dátumtartomány:';
$l['days'] = 'nap';
$l['filter_spam_logs'] = 'Spam naplók szűrése';
$l['asc'] = 'Növekvő';
$l['desc'] = 'Csökkenő';
$l['in'] = 'szerint';
$l['order'] = 'sorrend';
$l['sort_by'] = 'Rendezés elv:';
$l['results_per_page'] = 'Eredmények oldalanként';
$l['search_ip_on_sfs'] = 'IP keresése a Stop Forum Spam-en';
$l['search'] = 'Keresés';
