<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Fri, 10 Apr 2015 11:20:34 +0000
// --------------------------------------------------------------------------------

$l['statistics'] = 'Statisztika';
$l['overall_statistics'] = 'Áttekintés';
$l['overall_statistics_desc'] = 'Itt tudsz áttekintő statisztikákat nézni a fórumodról. Minden idő UTC-ben van megadva.';
$l['date_range'] = 'Időintervallum';
$l['date'] = 'Dátum';
$l['users'] = 'Felhasználók';
$l['threads'] = 'Témák';
$l['posts'] = 'Hozzászólások';
$l['from'] = 'Ettől';
$l['to'] = 'eddig';
$l['increase'] = 'Növekedés';
$l['no_change'] = 'Nincs változás';
$l['decrease'] = 'Csökkenés';
$l['error_no_results_found_for_criteria'] = 'Nem találtunk eredményeket a megadott időintervallumra. Kérlek próbálj más időintervallumot.';
$l['error_no_statistics_available_yet'] = 'Elnézést, jelenleg egyetlen statisztika sem érhető el a fórumodról.';
