<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Fri, 10 Apr 2015 11:16:50 +0000
// --------------------------------------------------------------------------------

$l['recount_rebuild'] = 'Számlálók frissítése';
$l['recount_rebuild_desc'] = 'Itt tudod újraszámlálni a fórumod adatait és javítani a szinkronizációs hibákat.';
$l['data_per_page'] = 'Adatok száma ciklusonként';
$l['recount_stats'] = 'Statisztika újraépítése';
$l['recount_stats_desc'] = 'Ez az opció újraépíti és frissíti a statisztikát a fórum kezdőoldalán és a statisztika oldalon.';
$l['recount_reputation'] = 'Hírnév újraszámolása';
$l['recount_reputation_desc'] = 'Ez az opció újraszámolja a hírnevet minden egyes felhasználónál.';
$l['recount_warning'] = 'Figyelmeztetési pontok újraszámolása';
$l['recount_warning_desc'] = 'Ez az opció újraszámolja az aktív figyelmeztetési pontokat minden egyes felhasználónál.';
$l['recount_private_messages'] = 'Privát üzenetek újraszámolása';
$l['recount_private_messages_desc'] = 'Ez az opció újraszámolja a privát üzenet számlálót minden egyes felhasználónál.';
$l['recount_referrals'] = 'Ajánlások újraszámolása';
$l['recount_referrals_desc'] = 'Ez az opció újraszámolja az ajánlás számlálót minden egyes felhasználónál.';
$l['recount_thread_ratings'] = 'Téma értékelések újraszámolása';
$l['recount_thread_ratings_desc'] = 'Ez az opció újraszámolja az értékelést minden egyes témánál.';
$l['rebuild_forum_counters'] = 'Számlálók újraépítése';
$l['rebuild_forum_counters_desc'] = 'Ezzel a funkcióval újraszámolhatod a számlálókat, valamint a fórumok utolsó hozzászólásai is frissítésre kerülnek, hogy a helyes értékeket mutassák.';
$l['rebuild_thread_counters'] = 'Témák újraépítése';
$l['rebuild_thread_counters_desc'] = 'Ezzel a funkcióval újraszámolhatod a téma számlálókat, valamint a témák is frissítésre kerülnek, hogy a helyes értékeket mutassák.';
$l['rebuild_poll_counters'] = 'Szavazat számlálók újraépítése';
$l['rebuild_poll_counters_desc'] = 'Ez a funkció frissíteni fogja a szavazat számlálókat és az összes szavazatokat minden egyes szavazásnál, hogy a helyes értékeket mutassák.';
$l['recount_user_posts'] = 'Hozzászólások újraépítése';
$l['recount_user_posts_desc'] = 'Ezzel a funkcióval újraszámolhatod a felhasználók hozzászólásait az adatbázisban található hozzászólások száma alapján, hogy a helyes értékeket mutassák.';
$l['recount_user_threads'] = 'Felhasználó téma számok újraszámolása';
$l['recount_user_threads_desc'] = 'Ez a funkció frissíteni fogja a téma számot minden egyes felhasználónál az adatbázisban aktuálisan tárolt adatok alapján és a fórumokat amelyeknél a téma számláló tiltva lett.';
$l['rebuild_attachment_thumbs'] = 'Csatolás kicsinyítések újraépítése';
$l['rebuild_attachment_thumbs_desc'] = 'Ezzel a funkcióval újraépítheted a csatolás kicsinyítéseket, hogy azok biztosan a megadott szélesség, magasság adatok szerint legyenek megjelenítve.';
$l['success_rebuilt_forum_counters'] = 'Számlálók sikeresen újraépítve.';
$l['success_rebuilt_thread_counters'] = 'Témák sikeresen újraépítve.';
$l['success_rebuilt_poll_counters'] = 'Szavazat számlálók sikeresen újraépítve.';
$l['success_rebuilt_user_post_counters'] = 'A felhasználói üzenetek száma sikeresen újraszámolva.';
$l['success_rebuilt_user_thread_counters'] = 'A felhasználó témák számlálás sikeresen újraszámolva.';
$l['success_rebuilt_attachment_thumbnails'] = 'A csatolás kicsinyítések újraépítve.';
$l['success_rebuilt_forum_stats'] = 'A fórum statisztika újraépítve.';
$l['success_rebuilt_reputation'] = 'A felhasználó hírnév sikeresen újraépítve.';
$l['success_rebuilt_warning'] = 'A felhasználó figyelmeztetési pontok sikeresen újraépítve.';
$l['success_rebuilt_private_messages'] = 'A felhasználó privát üzenet számlálás sikeresen újraszámolva.';
$l['success_rebuilt_referral'] = 'A felhasználói ajánlás számláló sikeresen újraszámolva.';
$l['success_rebuilt_thread_ratings'] = 'A téma értékelés sikeresen újraszámolva.';
$l['confirm_proceed_rebuild'] = 'Klikk a "Tovább" gombra a folytatáshoz.';
$l['automatically_redirecting'] = 'Automatikusan átirányítunk...';
