<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Fri, 10 Apr 2015 11:03:31 +0000
// --------------------------------------------------------------------------------

$l['database_backups'] = 'Adatbázis mentések';
$l['database_backups_desc'] = 'Itt találhatsz egy listát a jelenleg a webszerver MyBB Backups mappájában tárolt adatbázis mentésekről.';
$l['new_database_backup'] = 'Új adatbázis mentés';
$l['new_backup'] = 'Új mentés';
$l['new_backup_desc'] = 'Itt tudsz mentést készíteni az adatbázisodról.';
$l['backups'] = 'Mentések';
$l['existing_database_backups'] = 'Korábbi adatbázis mentések';
$l['backup_saved_to'] = 'Az elmentett adatbázis az alábbi helyre került:';
$l['download'] = 'Letöltés';
$l['table_selection'] = 'Tábla választás';
$l['backup_options'] = 'Mentési Opciók';
$l['table_select_desc'] = 'Válaszd ki azokat a táblákat melyekről mentést szeretnél készíteni. A CTRL billentyű nyomva tartásával több táblát is kiválaszthatsz.';
$l['select_all'] = 'Összes kijelölése';
$l['deselect_all'] = 'Kijelölés megszüntetése';
$l['select_forum_tables'] = 'Fórum táblák kiválasztása';
$l['file_type'] = 'Fájl típus';
$l['file_type_desc'] = 'Válaszd ki a fájl típusát melybe menteni szeretnéd az adatbázist.';
$l['gzip_compressed'] = 'GZIP Tömörített';
$l['plain_text'] = 'Egyszerű szöveg';
$l['save_method'] = 'Mentési eljárás';
$l['save_method_desc'] = 'Itt tudod megadni, hogy a mentett adatbázist letöltöd saját gépre vagy a szerveren tárolod.';
$l['backup_directory'] = 'Backup mappa (tárolás a szerveren)';
$l['backup_contents'] = 'Mentés tartalma';
$l['backup_contents_desc'] = 'Válaszd ki, hogy milyen információ kerüljön a mentett fájlba.';
$l['structure_and_data'] = 'Szerkezet és adat';
$l['structure_only'] = 'Csak a szerkezet';
$l['data_only'] = 'Csak adat';
$l['analyze_and_optimize'] = 'Táblák optimalizálása és elemzése';
$l['analyze_and_optimize_desc'] = 'Szeretnéd, hogy elemezze és optimalizálja a kiválasztott táblákat?';
$l['perform_backup'] = 'Mentés';
$l['backup_filename'] = 'Mentett fájl neve';
$l['file_size'] = 'Fájl méret';
$l['creation_date'] = 'Létrehozva';
$l['no_backups'] = 'Jelenleg nincs adatbázis mentés.';
$l['error_file_not_specified'] = 'nem adtad meg az adatbázist a letöltéshez.';
$l['error_invalid_backup'] = 'A megadott fájl érvénytelen vagy nem létezik.';
$l['error_backup_doesnt_exist'] = 'Nincs ilyen adatbázis mentés';
$l['error_backup_not_deleted'] = 'A mentés nem lett törölve.';
$l['error_tables_not_selected'] = 'Nem választottál ki egyetlen táblát sem.';
$l['error_no_zlib'] = 'A zlib library nincs engedélyezve - Nem tudsz GZIP tömörített mentést készíteni.';
$l['alert_not_writable'] = 'A backups mappa (az adminisztráción belül) nem írható. Nem tudsz mentést készíteni a szerverre.';
$l['confirm_backup_deletion'] = 'Biztos, hogy törölni szeretnéd ezt a mentést?';
$l['success_backup_deleted'] = 'A mentés sikeresen törölve.';
$l['success_backup_created'] = 'A mentés sikeresen létrehozva.';
