<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian (Magyar)
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://community.mybb.com/mods.php?action=view&pid=441
// Compatible version of MyBB : 1810 Béta
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sat, 14 Jan 2017 11:59:42 +0000
// --------------------------------------------------------------------------------

$l['users'] = 'Felhasználók';
$l['search_for_user'] = 'Felhasználó keresése';
$l['browse_users'] = 'Felhasználók';
$l['browse_users_desc'] = 'Az alábbiakban láthatod a fórumodon regisztrált felhasználókat. Hogy a felhasználókat a fórum milyen formában jelenítse meg, saját magad tudod beállítani. A testreszabáshoz kattints a \'Megjelenítés\' gombra.';
$l['find_users'] = 'Keresés';
$l['find_users_desc'] = 'Itt tudsz a fórumodon regisztrált felhasználók között keresni.';
$l['create_user'] = 'Új felhasználó létrehozása';
$l['create_user_desc'] = 'Itt tudsz létrehozni új felhasználót.';
$l['merge_users'] = 'Felhasználók egyesítése';
$l['merge_users_desc'] = 'Itt két felhasználó regisztrációját tudod egyesíteni. A "Forrás Felhasználó" lesz beleolvasztva a "Cél Felhasználó"-ba, és ezzel <strong>csak</strong> a Cél Felhasználó regisztrációja marad meg. A Forrás Felhasználó hozzászólásai, témái, privát üzenetei, naptár eseményei stb. hozzáadódnak a Cél Felhasználó fiókjához.<br /><span style="font-size: 15px;"><b>MEGJEGYZÉS: Ez a folyamat később nem vonható vissza!!!</b></span>';
$l['edit_user'] = 'Felhasználó szerkesztése';
$l['edit_user_desc'] = 'Itt tudod a felhasználó profilját, beállításait, aláírását szerkeszteni; valamint láthatsz egy általános statisztikát a felhasználóról.';
$l['show_referrers'] = 'Ajánló megjelenítése';
$l['show_referrers_desc'] = 'A keresésed eredményét lentebb láthatod. Az eredményeket megnézheted táblázatos vagy névjegykártya stílusú nézetben.';
$l['show_ip_addresses'] = 'IP cím megjelenítése';
$l['show_ip_addresses_desc'] = 'A regisztrációnál használt IP címet és a hozzászólás írásakor használt IP címet az alábbi táblázatban tekintheted meg. ';
$l['manage_users'] = 'Felhasználók kezelése';
$l['manage_users_desc'] = 'A mindennapi feladatokat egyszerűbben elvégezhetjük, ha a felhasználókat egységben kezeljük.';
$l['inline_edit'] = 'Soros felhasználói moderáció:';
$l['inline_activate'] = 'Felhasználó(k) aktiválása';
$l['inline_ban'] = 'Felhasználók kitiltása';
$l['inline_usergroup'] = 'A felhasználó(k) csoportjának megváltoztatása';
$l['inline_delete'] = 'Felhasználó(k) törlése';
$l['inline_prune'] = 'Felhasználók hozzászólásainak megtisztítása/törlése';
$l['inline_activated'] = '{1} felhasználó sikeren aktiválva.';
$l['inline_activated_more'] = '<small>{1} felhasználó, akit kiválasztottál, már aktiválva van.</small>';
$l['inline_activated_failed'] = 'Már az összes felhasználó aktiválva van, akit kiválasztottál.';
$l['ban_time'] = 'Kitiltás időtartama <em>*</em>';
$l['ban_reason'] = 'Kitiltása oka';
$l['mass_ban'] = 'Több felhasználó kitiltása';
$l['important'] = 'Fontos';
$l['mass_ban_info'] = 'Ez a művelet {1} felhasználót fog érinteni. Csak akkor folytasd, ha biztosan ezt szeretnéd tenni.';
$l['ban_users'] = 'Felhasználók kitiltása';
$l['users_banned'] = '{1} felhasználó ki lett tiltva';
$l['confirm_multilift'] = 'Biztosan ki szeretnéd tiltani a kiválasztott felhasználó(t)?';
$l['success_ban_lifted'] = 'A kiválasztott felhasználó(k), {1} kitiltása eltávolítva.';
$l['edit_ban'] = 'Kitiltása szerkesztés';
$l['lift_bans'] = 'Kitiltások feloldása';
$l['confirm_multidelete'] = 'Biztosan törölni szeretnéd a kiválasztott felhasználót/felhasználókat: {1}? Nem vonható vissza.';
$l['users_deleted'] = '{1} felhasználó(k) törölve.';
$l['mass_prune_info'] = 'Ez a művelet {1} felhasználót érint. Ha folytatod, akkor eltávolítja az összes felhasználó hozzászólásait, ami régebbi a megadott dátumnál.<br /><br /><strong>Vedd figyelembe, hogy ha bármely felhasználó hozzászólása egy adott téma első hozzászólása, akkor a teljes téma eltávolítása fog kerülni.</strong>';
$l['mass_prune_posts'] = 'Több hozzászólás megtisztítása';
$l['manual_date'] = 'Adj meg egy időt';
$l['relative_date'] = 'Vagy válassz törlési opciót';
$l['multi_selected_dates'] = 'A kézi dátum megadást és a beállított opciót is választottad. Kérlek válassz a kézi dátum megadás vagy a beállított opció egyike közül.';
$l['incorrect_date'] = 'A dátum amit megadtál érvénytelen. Kérlek adj meg egy dátumot vagy hagyd üresen és válassz a beállított opció közül.';
$l['prune_complete'] = 'A tisztítás sikeresen teljesítve.';
$l['prune_fail'] = 'Nem találtunk a kiválasztott felhasználó(k)hoz tartozó hozzászólást. Nincsenek hozzászólások amit megtisztíthatnánk.';
$l['no_prune_option'] = 'Kérlek adj meg egy dátumot vagy válassz egy opciót a folytatáshoz.';
$l['prune_posts'] = 'Hozzászólások tisztítása';
$l['delete_posts'] = 'Hozzászólások törlése';
$l['usergroup_info'] = 'A következő művelet hatással lesz {1} felhasználóra. Az alábbi beállítások közül választva felülírod a kiválasztott felhasználó(k) elsődleges / további / megjelenített csoportját.';
$l['mass_usergroups'] = 'Csoportos felhasználói csoport módosítás';
$l['success_mass_usergroups'] = 'A felhasználó(k) frissítése sikeres.';
$l['alter_usergroups'] = 'Változások mentése';
$l['no_usergroup_changed'] = 'A kiválasztott felhasználók egyikének sem lehet módosítani a felhasználói csoportjait.';
$l['no_set_option'] = 'Nem lett kiválasztva érvényes beállított dátum. Kérlek válassz egy lehetőséget a legördülő menüből vagy kézzel adj meg egy dátumot.';
$l['select_an_option'] = '(Válassz egy lehetőséget)';
$l['month_1'] = 'Január';
$l['month_2'] = 'Február';
$l['month_3'] = 'Március';
$l['month_4'] = 'Április';
$l['month_5'] = 'Május';
$l['month_6'] = 'Június';
$l['month_7'] = 'Július';
$l['month_8'] = 'Augusztus';
$l['month_9'] = 'Szeptember';
$l['month_10'] = 'Október';
$l['month_11'] = 'November';
$l['month_12'] = 'December';
$l['option_1'] = 'Egy hónapnál idősebb';
$l['option_2'] = 'Három hónapnál idősebb';
$l['option_3'] = 'Hat hónapnál idősebb';
$l['option_4'] = 'Egy évnél idősebb';
$l['option_5'] = '18 hónapnál idősebb';
$l['option_6'] = 'Két évnél idősebb';
$l['error_avatartoobig'] = 'Nem változtathatod meg az avatarodat, mivel az új avatar mérete túl nagy. A maximum avatar méret: {1}x{2} (szélesség x magasság)';
$l['error_invalidavatarurl'] = 'Az avatar URL-e érvénytelen.';
$l['error_invalid_user'] = 'Érvénytelen felhasználót választottál.';
$l['error_no_perms_super_admin'] = 'Nincs jogosultságod a felhasználó szerkesztéséhez.';
$l['error_invalid_user_source'] = 'A megadott forrás felhasználó nem létezik.';
$l['error_invalid_user_destination'] = 'A cél felhasználó nem létezik';
$l['error_cannot_merge_same_account'] = 'A forrás és a cél felhasználónak különbözőnek kell lennie.';
$l['error_no_users_found'] = 'Nem találtunk felhasználót a megadott keresési feltételek alapján.';
$l['error_invalid_admin_view'] = 'Érvénytelen adminisztrációs megjelenítést választottál.';
$l['error_missing_view_title'] = 'Nem adtál meg címet a megjelenítésnek.';
$l['error_no_view_fields'] = 'Nem választottál ki egyetlen mezőt sem a megjelenítésre.';
$l['error_invalid_view_perpage'] = 'Érvénytelen adatot választottál';
$l['error_invalid_view_sortby'] = 'Érvénytelen mezőt választottál';
$l['error_invalid_view_sortorder'] = 'Érvénytelen rendezési elvet választottál';
$l['error_invalid_view_delete'] = 'Érvénytelen adminisztrációs megjelenítést választottál.';
$l['error_cannot_delete_view'] = 'Legalább 1 adminisztrációs nézetnek kell lennie.';
$l['error_inline_no_users_selected'] = 'Nem választottál ki felhasználó(kat)t. Válassz ki felhasználó(ka)t, és próbáld újra.';
$l['error_cannot_delete_user'] = 'Ez a felhasználó nem törölhető.';
$l['error_no_referred_users'] = 'A kiválasztott felhasználónak nincsenek ajánlott felhasználói.';
$l['user_deletion_confirmation'] = 'Biztos, hogy törölni szeretnéd ezt a felhasználót?';
$l['success_coppa_activated'] = 'A COPPA felhasználó aktiválva.';
$l['success_activated'] = 'A kiválasztott felhasználó aktiválva.';
$l['success_user_created'] = 'A felhasználó sikeresen létrehozva.';
$l['success_user_updated'] = 'A felhasználó sikeresen frissítve.';
$l['success_user_deleted'] = 'A felhasználó törölve.';
$l['success_merged'] = 'sikeresen összevonva';
$l['succuss_view_set_as_default'] = 'Az adminisztrációs megjelenítés beállítva alapértelmezettként.';
$l['success_view_created'] = 'Az adminisztrációs megjelenítés létrehozva.';
$l['success_view_updated'] = 'Az adminisztrációs megjelenítés frissítve.';
$l['success_view_deleted'] = 'Az adminisztrációs megjelenítés törölve.';
$l['confirm_view_deletion'] = 'Biztos, hogy törölni szeretnéd a kiválasztott megjelenítést?';
$l['warning_coppa_user'] = '<p class="alert"><strong>Figyelmeztetés: </strong> A felhasználó COPPA hitelesítésre vár. <a href="index.php?module=user-users&amp;action=activate_user&amp;uid={1}">Felhasználó aktiválása</a></p>';
$l['required_profile_info'] = 'Szükséges profil információk';
$l['password'] = 'Jelszó';
$l['confirm_password'] = 'Jelszó megerősítése';
$l['email_address'] = 'Email cím';
$l['use_primary_user_group'] = 'Elsődleges csoport használata';
$l['primary_user_group'] = 'Elsődleges felhasználói csoport';
$l['additional_user_groups'] = 'További felhasználói csoportok';
$l['additional_user_groups_desc'] = 'Használd a CTRL billentyűt több csoport kiválasztásához.
<p style="font-weight: bold; line-height: 5%">Administrators = Adminisztrátorok</p>
<p style="font-weight: bold; line-height: 5%">Awaiting Activation = Aktiválásra várók</p>
<p style="font-weight: bold; line-height: 5%">Banned = Kitiltott</p>
<p style="font-weight: bold; line-height: 5%">Moderators = Moderátorok</p>
<p style="font-weight: bold; line-height: 5%">Registered = Regisztrált</p>
<p style="font-weight: bold; line-height: 5%">Super Moderators = Szuper Moderátorok</p>';
$l['display_user_group'] = 'Megjelenített csoport';
$l['save_user'] = 'Felhasználó Mentése';
$l['overview'] = 'Áttekintés';
$l['profile'] = 'Profil';
$l['account_settings'] = 'Beállítások';
$l['signature'] = 'Aláírás';
$l['avatar'] = 'Avatar';
$l['mod_options'] = 'Moderátor opciók';
$l['general_account_stats'] = 'Általános statisztika';
$l['local_time'] = 'Helyi idő';
$l['local_time_format'] = '{1} at {2}';
$l['posts'] = 'Hozzászólások';
$l['age'] = 'Kor';
$l['posts_per_day'] = 'Hozzászólások naponta';
$l['percent_of_total_posts'] = 'Összes hozzászólás %-a';
$l['user_overview'] = 'Áttekintés';
$l['new_password'] = 'Új jelszó';
$l['new_password_desc'] = 'Csak akkor szükséges megadni, ha megváltoztatod';
$l['confirm_new_password'] = 'Új jelszó megerősítése';
$l['optional_profile_info'] = 'Egyéb profil információk';
$l['custom_user_title'] = 'Becenév';
$l['custom_user_title_desc'] = 'Ha üresen hagyod a csoport címét fogja használni';
$l['website'] = 'Weboldal';
$l['icq_number'] = 'ICQ';
$l['aim_handle'] = 'AIM';
$l['yahoo_messanger_handle'] = 'Yahoo! Messenger';
$l['skype_handle'] = 'Skype kezelés';
$l['google_handle'] = 'Google Talk kezelés';
$l['birthday'] = 'Születési idő';
$l['away_information'] = 'Távolléti információk';
$l['away_status'] = 'Távollét állapota:';
$l['away_status_desc'] = 'Itt megadhatod, hogy \'Távol vagy\' vagy \'Elérhető vagy\'-e a fórumon.';
$l['im_away'] = 'Távol vagyok';
$l['im_here'] = 'Elérhető vagyok';
$l['away_reason'] = 'Távollét oka:';
$l['away_reason_desc'] = 'A távollét rövid leírása (max. 200 karakter).';
$l['return_date'] = 'Visszatérés dátuma:';
$l['return_date_desc'] = 'Ha tudod mikor jössz vissza, itt megadhatod a visszatérésed dátumát.';
$l['error_acp_return_date_past'] = 'A visszatérés dátuma nem lehet a mai napnál korábbi!';
$l['hide_from_whos_online'] = 'Elrejtés az online listáról';
$l['login_cookies_privacy'] = 'Bejelentkezés, sütik és biztonság';
$l['recieve_admin_emails'] = 'Emailek fogadása adminisztrátoroktól';
$l['hide_email_from_others'] = 'Email cím elrejtése a többi felhasználó elől';
$l['recieve_pms_from_others'] = 'Privát Üzenetek fogadása a felhasználóktól';
$l['recieve_pms_from_buddy'] = 'Privát Üzenetek fogadása csak a barátlistán lévőktől';
$l['alert_new_pms'] = 'Értesítés privát üzenet érkezésekor';
$l['email_notify_new_pms'] = 'Email értesítés Privát Üzenet érkezésekor';
$l['buddy_requests_pm'] = 'PÜ értesítés  fogadása új baráti felkérésről';
$l['buddy_requests_auto'] = 'Baráti felkérések automatikus elfogadása (ha a fenti jelölőnégyzet be van pipálva egy tájékoztató PÜ-t küldünk az új baráti felkérésről)';
$l['default_thread_subscription_mode'] = 'Alapértelmezett téma feliratkozás';
$l['do_not_subscribe'] = 'Nincs feliratkozás';
$l['no_email_notification'] = 'Nincs email értesítés';
$l['instant_email_notification'] = 'Azonnali email értesítés';
$l['messaging_and_notification'] = 'Üzenetek és értesítések';
$l['use_default'] = 'Alapértelmezett használata';
$l['date_format'] = 'Dátum formátum';
$l['time_format'] = 'Idő formátum';
$l['time_zone'] = 'Időzóna';
$l['daylight_savings_time_correction'] = 'Nyári/téli időszámítás engedélyezése';
$l['automatically_detect'] = 'DST beállítások automatikus észlelése';
$l['always_use_dst_correction'] = 'Mindig használja a DST korrekciót';
$l['never_use_dst_correction'] = 'Ne használja a DST korrekciót';
$l['date_and_time_options'] = 'Dátum és idő beállítások';
$l['show_threads_last_day'] = 'Témák megjelenítése tegnapról';
$l['show_threads_last_5_days'] = 'Témák megjelenítése az elmúlt 5 napból';
$l['show_threads_last_10_days'] = 'Témák megjelenítése az elmúlt 10 napból';
$l['show_threads_last_20_days'] = 'Témák megjelenítése az elmúlt 20 napból';
$l['show_threads_last_50_days'] = 'Témák megjelenítése az elmúlt 50 napból';
$l['show_threads_last_75_days'] = 'Témák megjelenítése az elmúlt 75 napból';
$l['show_threads_last_100_days'] = 'Témák megjelenítése az elmúlt 100 napból';
$l['show_threads_last_year'] = 'Témák megjelenítése a múlt évből';
$l['show_all_threads'] = 'Összes téma megjelenítése';
$l['threads_per_page'] = 'Témák száma egy oldalon';
$l['default_thread_age_view'] = 'Alapértelmezett téma nézet';
$l['forum_display_options'] = 'Fórum megjelenítés opciók';
$l['show_classic_postbit'] = 'A hozzászólások megjelenítése klasszikus módban';
$l['display_images'] = 'Képek megjelenítése a hozzászólásokban';
$l['display_videos'] = 'Videók megjelenítése a hozzászólásokban';
$l['display_users_sigs'] = 'A felhasználó aláírásának megjelenítése a hozzászólásaiban';
$l['display_users_avatars'] = 'A felhasználó avatarának megjelenítése a hozzászólásaiban';
$l['show_quick_reply'] = 'Gyors válasz megjelenítése a téma alján';
$l['posts_per_page'] = 'Hozzászólások száma egy oldalon';
$l['default_thread_view_mode'] = 'Alapértelmezett téma nézet';
$l['linear_mode'] = 'Lineáris Mód';
$l['threaded_mode'] = 'Rétegezett Mód';
$l['thread_view_options'] = 'Téma megjelenítési módok';
$l['show_redirect'] = 'Visszairányító ablak megjelenítése';
$l['show_code_buttons'] = 'BB kód formázási lehetőségek megjelenítése';
$l['source_editor'] = 'A szerkesztő \'egyszerű szöveg\' módba kapcsolása alapértelmezettként';
$l['theme'] = 'Téma';
$l['board_language'] = 'Fórum nyelve';
$l['other_options'] = 'Egyéb opciók';
$l['signature_desc'] = 'Formázás opciók: BB Kódok: {1}, hangulatjelek??? are {2}, IMG kód: {3}, HTML: {4}';
$l['enable_sig_in_all_posts'] = 'Aláírás engedélyezése a hozzászólásokban';
$l['disable_sig_in_all_posts'] = 'Aláírás kikapcsolása a hozzászólásokban';
$l['do_nothing'] = 'Ne változtassa meg az aláírás beállításait';
$l['signature_preferences'] = 'Aláírás Preferenciák';
$l['suspend_sig'] = 'Aláírás Felfüggesztése';
$l['suspend_sig_box'] = 'A felhasználó aláírásának felfüggesztése';
$l['suspend_sig_perm'] = '<small>Véglegesen felfüggesztve.</small>';
$l['suspend_sig_info'] = 'Ha egy aláírás fel van függesztve, akkor a felhasználó nem tudja szerkeszteni, és nem jelenik meg a profiljában és a hozzászólásaiban sem';
$l['suspend_sig_extend'] = '<small>Adj meg egy új időpontot, hogy megváltoztasd a felfüggesztés idejét, vagy vedd ki a jelölést az opció mellől, hogy eltávolítsd a felfüggesztést.</small>';
$l['suspend_expire_info'] = '<small>Lejár: <span style="color: {2};">{1}</span></small>';
$l['suspend_never_expire'] = '<small>{1} felfüggesztése soha nem jár le (véglegesen felfüggesztve).</small>';
$l['suspend_sig_error'] = 'Érvénytelen időt adtál meg a felhasználó aláírásának felfüggesztéséhez. Adj meg érvényes időt.';
$l['moderate_posts'] = 'Hozzászólások moderálása';
$l['moderate_posts_info'] = 'Azon új hozzászólások moderálása, amelyet {1} készített.';
$l['moderate_for'] = 'Moderál:';
$l['moderated_perm'] = '<p><small>Tartósan moderálva.<br />Adj meg egy új időpontot alul, hogy megváltoztasd, vagy vedd ki a jelölést az opció mellől, hogy eltávolítsd ezt a moderációt.</small></p>';
$l['moderate_length'] = '<p><small>Moderálva eddig: <span style="color: {2};">{1}</span>.<br />Adj meg egy új időpontot alul, hogy megváltoztasd, vagy vedd ki a jelölést az opció mellől, hogy eltávolítsd ezt a moderációt.</small></p>';
$l['suspend_posts'] = 'Hozzászólások felfüggesztése';
$l['suspend_posts_info'] = '{1} felfüggesztése. Nem írhat hozzászólást.';
$l['suspend_for'] = 'Felfüggeszt:';
$l['suspended_perm'] = '<p><small>Tartósan felfüggesztve.<br />Adj meg egy új időpontot alul, hogy megváltoztasd, vagy vedd ki a jelölést az opció mellől, hogy eltávolítsd ezt a felfüggesztést.</small></p>';
$l['suspend_length'] = '<p><small>Felfüggesztve eddig:<span style="color: {2};">{1}</span>.<br />Adj meg egy új időpontot alul, hogy megváltoztasd, vagy vedd ki a jelölést az opció mellől, hogy eltávolítsd ezt a felfüggesztést.</small></p>';
$l['suspendsignature_error'] = 'Kiválasztottad, hogy felfüggeszted ennek a felhasználónak az aláírását, de nem adtál meg érvényes időtartamot. Adj meg érvényes időt a folytatáshoz, vagy vedd ki a jelölést az opció mellől a törléshez.';
$l['moderateposting_error'] = 'Kiválasztottad, hogy moderálod ennek a felhasználónak a hozzászólásait, de nem adtál meg érvényes időtartamot. Adj meg érvényes időt a folytatáshoz, vagy vedd ki a jelölést az opció mellől a törléshez.';
$l['suspendposting_error'] = 'Kiválasztottad, hogy felfüggeszted ennek a felhasználónak a hozzászólásait, de nem adtál meg érvényes időtartamot.';
$l['suspendmoderate_error'] = 'Kiválasztottad, hogy felfüggeszted és moderálod ennek a felhasználónak a hozzászólásait. Egyszerre egy típusú moderációt válassz.';
$l['expire_length'] = 'Felfüggesztés időtartama:';
$l['expire_hours'] = 'órák';
$l['expire_days'] = 'napok';
$l['expire_weeks'] = 'hetek';
$l['expire_months'] = 'hónapok';
$l['expire_never'] = 'Soha nem jár le';
$l['expire_permanent'] = 'Tartós';
$l['username'] = 'Felhasználónév';
$l['email'] = 'Email';
$l['primary_group'] = 'Elsődleges csoport';
$l['additional_groups'] = 'További csoportok';
$l['registered'] = 'Regisztrált';
$l['last_active'] = 'Utoljára aktív';
$l['post_count'] = 'Hozzászólások';
$l['thread_count'] = 'Téma számláló';
$l['reputation'] = 'Értékelés';
$l['warning_level'] = 'Figyelmeztetési szint';
$l['registration_ip'] = 'Regisztrációs IP';
$l['last_known_ip'] = 'Utolsó ismert IP cím';
$l['registration_date'] = 'Regisztrált';
$l['info_on_ip'] = 'Információ erről az IP címről';
$l['current_avatar'] = 'Jelenleg használt avatar';
$l['user_current_using_uploaded_avatar'] = 'Ez a felhasználó jelenleg feltöltött avatart használ.';
$l['user_currently_using_remote_avatar'] = 'Ez a felhasználó jelenleg egy linkelt avatart használ.';
$l['max_dimensions_are'] = 'Avatar maximum méretek:';
$l['avatar_max_size'] = 'Avatar fájl maximális mérete:';
$l['remove_avatar'] = 'Jelenleg használt avatar eltávolítása?';
$l['avatar_desc'] = 'Itt kezelheted a felhasználó avatarát. Az avatarok kis egyedi képek, melyeket a felhasználók választhatnak meg, és amelyek megjelennek a nevük mellett a hozzászólásokban.';
$l['avatar_auto_resize'] = 'Ha az avatar mérete túl nagy, azt automatikusan átméretezzük.';
$l['attempt_to_auto_resize'] = 'Avatar átméretezése hogy ha túl nagy?';
$l['specify_custom_avatar'] = 'Saját avatar hozzáadása';
$l['upload_avatar'] = 'Avatar feltöltése';
$l['or_specify_avatar_url'] = 'vagy add meg a külső avatar URL-ét:';
$l['user_notes'] = 'Felhasználói jegyzetek';
$l['ip_addresses'] = 'IP címek';
$l['ip_address'] = 'IP cím';
$l['show_users_regged_with_ip'] = 'Felhasználó megjelenítése aki ezzel az IP címmel regisztrált.';
$l['show_users_posted_with_ip'] = 'Felhasználó megjelenítése aki ezzel az IP címmel küldött hozzászólást.';
$l['ban_ip'] = 'IP cím kitiltása';
$l['ip_address_for'] = 'IP cím';
$l['source_account'] = 'Forrás Felhasználó';
$l['source_account_desc'] = 'Ez a felhasználó lesz egyesítve a Cél felhasználóval. Ez a felhasználó el lesz távolítva az eljárás után.';
$l['destination_account'] = 'Cél Felhasználó';
$l['destination_account_desc'] = 'Ezzel a felhasználóval lesz a Forrás Felhasználó egyesítve. Ez a felhasználó fog megmaradni.';
$l['merge_user_accounts'] = 'Egyesít';
$l['display_options'] = 'Megjelenítési opciók';
$l['ascending'] = 'Emelkedő';
$l['descending'] = 'Csökkenő';
$l['sort_results_by'] = 'Eredmények csoportosítása: ';
$l['in'] = 'szerint';
$l['results_per_page'] = 'Eredmények száma egy oldalon';
$l['display_results_as'] = 'Megjelenítési opciók';
$l['business_card'] = 'Kártya';
$l['views'] = 'Megjelenítés';
$l['views_desc'] = 'A Megjelenítés kezelő lehetővé teszi, hogy különböző megjelenítési módokat hozhass létre. A különböző megjelenítési módok hasznosak lehetnek, pl. jelentések létrehozásához.';
$l['manage_views'] = 'Megjelenítés Kezelő';
$l['none'] = 'None???';
$l['search'] = 'Keresés';
$l['view_profile'] = 'Profil megtekintése';
$l['edit_profile_and_settings'] = 'Profil szerkesztése és beállítások';
$l['ban_user'] = 'Felhasználó kitiltása';
$l['approve_coppa_user'] = 'COPPA felhasználó aktiválása';
$l['approve_user'] = 'Felhasználó aktiválása';
$l['delete_user'] = 'Felhasználó törlése';
$l['show_referred_users'] = 'Ajánló megjelenítése';
$l['show_attachments'] = 'Csatolások megjelenítése';
$l['table_view'] = 'Táblázat';
$l['card_view'] = 'Kártya';
$l['find_users_where'] = 'Keresés az alábbi szempontok alapján...';
$l['username_contains'] = 'A felhasználónév tartalmazza:';
$l['email_address_contains'] = 'Az email címe tartalmazza:';
$l['is_member_of_groups'] = 'A felhasználó tagja az alábbi csoportok valamelyikének?';
$l['website_contains'] = 'A weboldalának címe tartalmazza:';
$l['icq_number_contains'] = 'Az ICQ tartalmazza:';
$l['aim_handle_contains'] = 'Az AIM tartalmazza:';
$l['yahoo_contains'] = 'A Yahoo! címe tartalmazza:';
$l['skype_contains'] = 'A Skype tartalmazza:';
$l['google_contains'] = 'A Google Talk tartalmazza:';
$l['signature_contains'] = 'Az aláírása tartalmazza:';
$l['user_title_contains'] = 'A beceneve tartalmazza:';
$l['greater_than'] = 'több mint';
$l['is_exactly'] = 'pontosan';
$l['less_than'] = 'kevesebb mint';
$l['post_count_is'] = 'A hozzászólásainak száma:';
$l['thread_count_is'] = 'A téma számláló???:';
$l['reg_ip_matches'] = 'A regisztrációs IP címe tartalmazza:';
$l['wildcard'] = '* an IP byte wild card: 1.2.*.*';
$l['posted_with_ip'] = 'Hozzászólást írt az alábbi IP címmel:';
$l['custom_profile_fields_match'] = 'Egyedi profil mező egyezések';
$l['is_not_blank'] = ' nem üres';
$l['or'] = 'vagy';
$l['reg_in_x_days'] = 'Regisztrációjának ideje az utolsó';
$l['days'] = 'nap';
$l['view'] = 'Megjelenítés';
$l['create_new_view'] = 'Új Megjelenítés Létrehozása';
$l['create_new_view_desc'] = 'Itt tudsz új megjelenítést hozzáadni ehhez a szekcióhoz. Megadhatod, hogy melyik mező jelenjen meg, a keresési kritériumokat, valamint a rendezési elvet.';
$l['view_manager'] = 'Megjelenítés Kezelő';
$l['set_as_default_view'] = 'Beállítás alapértelmezettként?';
$l['enabled'] = 'Engedélyezve';
$l['disabled'] = 'Letiltva';
$l['fields_to_show'] = 'Mezők kiválasztása';
$l['fields_to_show_desc'] = 'Kérlek válaszd ki a mezőt amelyet szeretnél megjeleníteni. (Katt a mezőre és húzd át a másik oldalra.)';
$l['edit_view'] = 'Megjelenítés szerkesztése';
$l['edit_view_desc'] = 'Megjelenítés szerkesztésekor meghatározhatod, hogy melyik mezők, és milyen keresési kritériumok jelenjenek meg.';
$l['private'] = 'Privát';
$l['private_desc'] = 'Ez a megjelenítés csak számodra lesz látható';
$l['public'] = 'Publikus';
$l['public_desc'] = 'A többi adminisztrátor is láthatja ezt a megjelenítést';
$l['visibility'] = 'Láthatóság';
$l['save_view'] = 'Mentés';
$l['created_by'] = 'Létrehozta';
$l['default'] = 'Alapértelmezett';
$l['this_is_a_view'] = 'Ez egy {1} nézet';
$l['set_as_default'] = 'Beállítás alapértelmezettként';
$l['delete_view'] = 'Megjelenítés törlése';
$l['default_view_desc'] = 'A MyBB által létrehozott alapértelmezett megjelenítés. nem lehet szerkeszteni vagy eltávolítani.';
$l['public_view_desc'] = 'Publikus megjelenítés, látható minden adminisztrátor számára.';
$l['private_view_desc'] = 'Privát megjelenítés, csak a számodra lesz látható.';
$l['table'] = 'Táblázat';
$l['title'] = 'Cím';
$l['view_title_1'] = 'Összes felhasználó';
$l['emailsubject_activateaccount'] = 'Fiók aktiválása {1}-n';
$l['email_adminactivateaccount'] = '{1},

Az adminisztrátor aktiválta a fórum a fiókodat a(z) {2}-n.

A folytatáshoz kérlek látogass el a következő címre

{3}

A regisztrált azonosító adatokkal tudsz majd belépni.



Köszönettel,

{2} csapata';
$l['ipaddress_misc_info'] = 'Egyéb információ a \'{1}\'-ról/ről';
$l['ipaddress_host_name'] = 'Hoszt név';
$l['ipaddress_location'] = 'GeoIP hely';
$l['lift_ban'] = 'Kitiltás feloldása';
$l['error_remote_avatar_not_allowed'] = 'A távoli profilkép URL-je a fórum adminisztrátora által tilva lett.';
