<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Fri, 10 Apr 2015 11:28:28 +0000
// --------------------------------------------------------------------------------

$l['user_titles'] = 'Felhasználói rangok';
$l['user_titles_desc'] = 'Ez az opció lehetővé teszi, hogy meghatározott felhasználói rangokat adj a felhasználóknak a hozzászólásaik száma alapján.';
$l['add_new_user_title'] = 'Új felhasználói rang';
$l['add_new_user_title_desc'] = 'Itt tudsz új felhasználói rangokat készíteni. <i>Figyelem: Ez itt <strong>nem </strong> az <u><a href="index.php?module=user-group_promotions">előléptetés rendszer.</a></u></i>';
$l['error_missing_title'] = 'Nem adtál címet a rangnak.';
$l['error_missing_posts'] = 'Nem adtad meg a hozzászólások minimális számát.';
$l['error_cannot_have_same_posts'] = 'A hozzászólások minimális száma nem egyezhet meg más felhasználói ranghoz megadottal';
$l['error_invalid_user_title'] = 'Érvénytelen felhasználói rangot adtál meg.';
$l['success_user_title_created'] = 'Az új felhasználói rang létrehozva.';
$l['success_user_title_updated'] = 'A felhasználói rang frissítve.';
$l['success_user_title_deleted'] = 'A felhasználói rang törölve.';
$l['title_to_assign'] = 'Cím';
$l['title_to_assign_desc'] = 'Ez a cím fog megjelenni a felhasználó neve alatt, abban az esetben ha nem állított be saját becenevet.';
$l['minimum_posts'] = 'Minimum hozzászólás';
$l['minimum_posts_desc'] = 'A minimum hozzászólás szám, ami ahhoz szükséges, hogy a felhasználó elnyerje ezt a címet.';
$l['number_of_stars'] = 'Csillagok száma';
$l['number_of_stars_desc'] = 'Itt állíthatod be, hogy ehhez a felhasználói ranghoz hány csillag tartozzon. 0-ra állítva nem lesznek csillagok megjelenítve.';
$l['star_image'] = 'Csillag képe';
$l['star_image_desc'] = 'Itt adhatod meg a csillag kép fájljaihoz tartozó útvonalat. Ha üres akkor a csoportnak megfelelő kép fájlt fogja megjeleníteni.';
$l['save_user_title'] = 'Mentés';
$l['edit_user_title'] = 'Szerkesztés';
$l['edit_user_title_desc'] = 'Itt tudod szerkeszteni a felhasználói rangokat.';
$l['user_title_deletion_confirmation'] = 'Biztos, hogy törölni szeretnéd ezt a felhasználói rangot?';
$l['manage_user_titles'] = 'Felhasználói rangok Kezelése';
$l['user_title'] = 'Felhasználói Rang';
$l['no_user_titles'] = 'Jelenleg nincsenek felhasználói rangok meghatározva.';
