<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Fri, 10 Apr 2015 11:26:11 +0000
// --------------------------------------------------------------------------------

$l['banning'] = 'Kitiltás';
$l['banned_accounts'] = 'Felhasználók';
$l['banned_accounts_desc'] = 'Itt tudsz kitiltani felhasználókat. A kitiltott felhasználók nem fogják tudni használni a fórumot.';
$l['ban_a_user'] = 'Felhasználó kitiltása';
$l['ban_a_user_desc'] = 'Itt tudsz felhasználókat kitiltani a fórumodról.';
$l['edit_ban'] = 'Kitiltás szerkesztése';
$l['edit_ban_desc'] = 'Itt tudod szerkeszteni a kitiltás okát és időtartamát.';
$l['banned_ips'] = 'Kitiltott IP címek';
$l['disallowed_usernames'] = 'Tiltott nevek';
$l['disallowed_email_addresses'] = 'Tiltott email címek';
$l['error_invalid_ban'] = 'Érvénytelen kitiltást választottál.';
$l['error_invalid_username'] = 'A megadott felhasználónév érvénytelen vagy nem létezik.';
$l['error_no_perm_to_ban'] = 'Nem rendelkezel megfelelő jogosultsággal a felhasználó kitiltásához.';
$l['error_already_banned'] = 'A felhasználó már egy kitiltott csoporthoz tartozik.';
$l['error_ban_self'] = 'Magadat nem tudod kitiltani.';
$l['error_no_reason'] = 'Nem adtad meg a kitiltás okát.';
$l['success_ban_lifted'] = 'A kitiltás felfüggesztve.';
$l['success_banned'] = 'A választott felhasználó kitiltva..';
$l['success_ban_updated'] = 'A kitiltás frissítve.';
$l['success_pruned'] = 'A kiválasztott felhasználó hozzászólásai és témái sikeresen törölve.';
$l['confirm_lift_ban'] = 'Biztos, hogy fel akarod függeszteni ezt a kitiltást?';
$l['confirm_prune'] = 'Biztos, hogy szeretnéd törölni a felhasználó összes hozzászólását és témáját?';
$l['ban_username'] = 'Felhasználónév <em>*</em>';
$l['autocomplete_enabled'] = 'Automatikus kitöltés engedélyezett';
$l['ban_reason'] = 'Kitiltás oka';
$l['ban_group'] = 'Kitiltott csoport <em>*</em>';
$l['ban_group_desc'] = 'A felhasználó kitiltásához a felhasználót át kell mozgatni egy erre megfelelően létrehozott csoportba.';
$l['ban_time'] = 'Kitiltás időtartama <em>*</em>';
$l['user'] = 'Felhasználó';
$l['moderation'] = 'Moderáció';
$l['ban_lifts_on'] = 'Kitiltás megszűnik';
$l['time_left'] = 'Hátralévő idő';
$l['permenantly'] = 'végleges kitiltás';
$l['na'] = 'N/A';
$l['for'] = 'for ';
$l['bannedby_x_on_x'] = '<strong>{1}</strong><br /><small>Kitiltotta: {2} Dátum: {3} {4}</small>';
$l['lift'] = 'Felfüggeszt';
$l['no_banned_users'] = 'Jelenleg nincsenek kitiltott felhasználók.';
$l['prune_threads_and_posts'] = 'Témák és hozzászólások törlése';
$l['ban_user'] = 'Kitilt';
$l['update_ban'] = 'Frissít';
$l['search_user'] = 'Felhasználó keresése';
