<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian (Magyar)
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://community.mybb.com/mods.php?action=view&pid=441
// Compatible version of MyBB : 1810 Béta
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sat, 14 Jan 2017 12:00:45 +0000
// --------------------------------------------------------------------------------

$l['users_and_groups'] = 'Tagok és csoportok';
$l['users'] = 'Felhasználók';
$l['groups'] = 'Csoportok';
$l['user_titles'] = 'Felhasználói rangok';
$l['banning'] = 'Kitiltás';
$l['admin_permissions'] = 'Admin engedélyek';
$l['mass_mail'] = 'Csoportos email';
$l['group_promotions'] = 'Csoport előléptetés';
$l['can_manage_users'] = 'Kezelheti a felhasználókat?';
$l['can_manage_user_groups'] = 'Kezelheti a felhasználói csoportokat?';
$l['can_manage_user_titles'] = 'Kezelheti a felhasználói rangokat?';
$l['can_manage_user_bans'] = 'Használhatja a \'Kitiltás\' opciót?';
$l['can_manage_admin_permissions'] = 'Használhat admin jogokat?';
$l['can_send_mass_mail'] = 'Küldhet csoportos email-t?';
$l['can_manage_group_promotions'] = 'Kezelheti a \'Csoport előléptetés\' opciót?';
$l['awaiting_activation'] = 'Aktiválásra vár';
$l['can_manage_awaiting_activation'] = 'Kezelheti az aktiválásra várókat?';
