<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Fri, 10 Apr 2015 11:28:03 +0000
// --------------------------------------------------------------------------------

$l['mass_mail'] = 'Csoportos email';
$l['mass_mail_queue'] = 'Csoportos email';
$l['mass_mail_queue_desc'] = 'Itt tudod kezelni a jelenlegi, vagy későbbi levelezésedet. ';
$l['create_mass_mail'] = 'Csoportos email készítése';
$l['create_mass_mail_desc'] = 'Itt új csoportos emailt tudsz készíteni.';
$l['mass_mail_archive'] = 'Csoportos email archívum';
$l['mass_mail_archive_desc'] = 'Itt tudod megtekinteni a már elküldött levelek naplózását.';
$l['edit_mass_mail'] = 'Csoportos email szerkesztése';
$l['edit_mass_mail_desc'] = 'Itt tudod szerkeszteni a csoportos email beállításait.';
$l['send_mass_mail'] = 'Csoportos email küldése';
$l['email_addr'] = 'Email cím';
$l['board_name'] = 'Weboldal neve';
$l['board_url'] = 'Weboldal URL';
$l['personalize_message'] = 'Üzenet testreszabása:';
$l['message_settings'] = 'Üzenet beállításai';
$l['subject'] = 'Tárgy';
$l['subject_desc'] = 'Kérlek add meg az üzenet tárgyát.';
$l['send_via_email'] = 'Küldés email-ként';
$l['send_via_pm'] = 'Küldés privát üzenetként';
$l['message_type'] = 'Üzenet típusa';
$l['deliver_immediately'] = 'Azonnali kézbesítés';
$l['deliver_specific'] = 'Kézbesítés egy meghatározott időpontban';
$l['delivery_date'] = 'Kézbesítés időpontja';
$l['delivery_date_desc'] = 'Kérlek add meg, hogy mikor szeretnéd kézbesíteni az üzeneteket.';
$l['per_page'] = 'Oldalanként';
$l['per_page_desc'] = 'Egyszerre elküldhető üzenetek száma.';
$l['plain_text_only'] = 'Csak szöveges üzenet';
$l['html_only'] = 'Csak HTML';
$l['html_and_plain_text'] = 'HTML és szöveges üzenet';
$l['message_format'] = 'Üzenet Formátuma';
$l['define_html_message'] = 'HTML Üzenet összeállítása';
$l['define_html_message_desc'] = 'Add meg az üzenet HTML verzióját';
$l['auto_gen_plain_text'] = 'Szöveges verzió automatikus generálása';
$l['define_text_version'] = 'Szöveges verzió összeállítása';
$l['define_text_version_desc'] = 'Az üzenet szöveges verziójának megadása';
$l['define_the_recipients'] = 'Címzett feltételek megadása';
$l['username_contains'] = 'A felhasználónév tartalmazza...';
$l['email_addr_contains'] = 'Email címe tartalmazza...';
$l['members_of'] = 'Az alábbi csoportok tagja...';
$l['greater_than'] = 'nagyobb mint';
$l['is_exactly'] = 'pontosan';
$l['less_than'] = 'kevesebb mint';
$l['more_than'] = 'több mint';
$l['post_count_is'] = 'Hozzászólásainak száma';
$l['hours'] = 'Óra';
$l['days'] = 'Nap';
$l['weeks'] = 'Hét';
$l['months'] = 'Hónap';
$l['years'] = 'Év';
$l['ago'] = 'óta';
$l['user_last_active'] = 'A felhasználó utoljára volt aktív';
$l['user_registered'] = 'A felhasználó regisztrált';
$l['save_mass_mail'] = 'Mentés';
$l['step_four'] = '4. lépés';
$l['delivery_method'] = 'Küldés módja';
$l['private_message'] = 'Privát üzenet';
$l['email'] = 'Email';
$l['message'] = 'Üzenet';
$l['text_based'] = 'Szöveges';
$l['preview'] = 'Előnézet';
$l['mass_mail_preview'] = 'Csoportos email előnézete';
$l['html_based'] = 'HTML alapú';
$l['total_recipients'] = 'Összes címzett';
$l['change_recipient_conds'] = 'Címzett feltételek módosítása';
$l['review_message'] = 'Üzenet áttekintése';
$l['define_delivery_date'] = 'Kézbesítés időpontjának megadása';
$l['schedule_for_delivery'] = 'Küldés';
$l['username'] = 'Felhasználónév';
$l['step_three'] = '3. lépés';
$l['next_step'] = 'Következő lépés';
$l['step_two'] = '2. lépés';
$l['review_text_version'] = 'Szöveges verzió áttekintése';
$l['review_text_version_desc'] = 'Kérlek tekintsd át az automatikusan létrehozott szöveges verziót.';
$l['step_one'] = '1. lépés';
$l['status'] = 'Állapot';
$l['recipients'] = 'Címzettek';
$l['delivered'] = 'Kézbesítve';
$l['canceled'] = 'Megszakítva';
$l['resend'] = 'Újraküld';
$l['no_archived_messages'] = 'Nincs elküldött vagy megszakított levelezési listád.';
$l['draft'] = 'Vázlat';
$l['queued'] = 'Függőben';
$l['delivering'] = 'Elküldés alatt';
$l['na'] = 'N/A';
$l['mass_mail_cancel_confirmation'] = 'Biztos, hogy megakarod szakítani a lista küldését?';
$l['no_unsent_messages'] = 'Jelenleg nincs el nem küldött, függőben lévő, vagy jelenleg elküldés alatt álló levelezési listád.';
$l['error_invalid_mid'] = 'Érvénytelen levelezési listát választottál.';
$l['error_only_in_future'] = 'A jövőben csak tömeges levelet küldhetsz.';
$l['error_no_users'] = 'A megadott keresési feltételek alapján nem találtunk ilyen felhasználót. Kérlek bővítsd a keresést és próbálkozz újra.';
$l['error_missing_plain_text'] = 'Nem adtad meg a szöveges verzióját az üzenetnek.';
$l['error_missing_subject'] = 'Nem adtad meg a üzenet tárgyát.';
$l['error_missing_message'] = 'Nem adtál meg üzenetet.';
$l['error_missing_html'] = 'Nem adtad meg a HTML verzióját az üzenetnek.';
$l['error_delete_invalid_mid'] = 'Érvénytelen levelező listát választottál a törléshez.';
$l['success_mass_mail_saved'] = 'A csoportos email sikeresen elmentve.';
$l['success_mass_mail_deleted'] = 'A kijelölt csoportos email törölve.';
$l['success_mass_mail_resent'] = 'A csoportos email elmentve. Tekintsd meg lejjebb.';
$l['success_mass_mail_canceled'] = 'A csoportos email elküldése megszakítva.';
$l['mass_mail_deletion_confirmation'] = 'Biztos, hogy törölni szeretnéd ezt a csoportos emailt?';
