<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian (Magyar)
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://community.mybb.com/mods.php?action=view&pid=441
// Compatible version of MyBB : 1810 Béta
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Mon, 01 May 2017 10:02:06 +0000
// --------------------------------------------------------------------------------

$l['awaiting_activation'] = 'Aktiválásra vár';
$l['awaiting_activation_desc'] = 'Itt lehet kezelni azon felhasználókat, akik aktiválásra várnak. Kérlek jegyezd meg, azon felhasználó aki email aktiválásra vár, nem szükséges az emailen keresztül jóváhagynia a regisztrációját, ha itt aktiválásra kerül a felhasználó.';
$l['manage_awaiting_activation'] = 'Aktiválásra vár kezelése';
$l['no_users_awaiting_activation'] = 'Jelenleg nincsen(ek) aktiválásra váró felhasznál(ók).';
$l['username'] = 'Felhasználónév';
$l['registered'] = 'Regisztrált';
$l['last_active'] = 'Utoljára aktív';
$l['email'] = 'Email';
$l['ipaddress'] = 'IP cím';
$l['type'] = 'Típus';
$l['email_activation'] = 'Email aktiválásra vár';
$l['administrator_activation'] = 'Adminisztrátori aktiválásra vár';
$l['admin_activation_coppa'] = 'Adminisztrátori aktiválásra vár (COPPA)';
$l['activate_users'] = 'Felhasználó(k) aktiválása';
$l['delete_users'] = 'Felhasználó(k) törlése';
$l['confirm_activate_users'] = 'Biztos, hogy aktiválni akarod a kiválasztott felhasználó(ka)t?';
$l['confirm_delete_users'] = 'Biztos, hogy törölni akarod a kiválasztott felhasználó(ka)t?';
$l['no_users_selected'] = 'Nem választotál ki felhasználó(ka)t';
$l['success_users_deleted'] = 'A kiválasztott felhasználó(k) törölve.';
$l['success_users_activated'] = 'A kiválasztott felhasználó(k) aktiválva.';
$l['emailsubject_activateaccount'] = '{1} fiók aktiválása';
$l['email_adminactivateaccount'] = '{1},

Az adminisztrátot aktiválta a fiókodat a {2} fórumon.

A folytatáshoz kérlek látogass el az alábbi linkre

{3}

A regisztrációkor megadott adatokkal léphetsz be.

Köszönettel, 
{2} Csapata';
