<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian (Magyar)
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://community.mybb.com/mods.php?action=view&pid=441
// Compatible version of MyBB : 1813 Béta
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Sun, 10 Dec 2017 09:54:57 +0000
// --------------------------------------------------------------------------------

$l['user_groups'] = 'Felhasználói csoportok';
$l['manage_user_groups'] = 'Csoportok kezelése';
$l['manage_user_groups_desc'] = 'Itt tudod a fórumodon létrehozott felhasználói csoportokat kezelni. A fórum vezetők csoportjainak a \'Fórum vezetők\' oldalon való megjelenítését is tudod itt kezelni. Ha az értéket "0"-ra állítod a nevek ABC sorrendben jelennek majd meg.</br>
<p style="font-weight: bold; line-height: 5%">Guests = Vendégek</p>Az alapértelmezett csoport, hogy az összes látogató így legyen megjelölve amíg be nem lép.
<p style="font-weight: bold; line-height: 5%">Registered = Regisztrált</p>A regisztráció után az összes felhasználó alapértelmezettként ebbe a csoportba kerül.
<p style="font-weight: bold; line-height: 5%">Super Moderators = Szuper Moderátorok</p>Ezen felhasználók bármelyik fórumot moderálhatják.
<p style="font-weight: bold; line-height: 5%">Administrators = Adminisztrátorok</p>Ebbe a csoportba tartozik az összes adminisztrátor.
<p style="font-weight: bold; line-height: 5%">Awaiting Activation = Aktiválásra várók</p>A felhasználók akik még nem aktiválták a fiókjukat az emaillel vagy manuálisan nem aktiválták őket.
<p style="font-weight: bold; line-height: 5%">Moderators = Moderátorok</p>Ezen felhasználók a meghatározott fórumokat moderálják.
<p style="font-weight: bold; line-height: 5%">Banned = Kitiltott</p>Az alapértelmezett felhasználói csoport, amelybe a tagok kerülnek amikor kitiltják őket.';
$l['add_user_group'] = 'Új csoport létrehozása';
$l['add_user_group_desc'] = 'Itt tudsz új csoportot hozzáadni a fórumhoz, és jogosultságokat is tudsz másolni másik fórumból.';
$l['group_join_requests'] = 'Csatlakozási kérelem';
$l['group_join_requests_desc'] = 'Lentebb látható azon felhasználóknak a listája, akik csatlakozni szeretnének ehhez a felhasználói csoporthoz. A kérelmeket jóváhagyhatod vagy elutasíthatod.';
$l['manage_group_leaders'] = 'Csoport vezetők kezelése';
$l['manage_group_leaders_desc'] = 'Itt tudod kezelni a csoport vezetőit. Attól függően, hogy milyen jogosultságokat adtál neki, a vezető kezelheti a csoporthoz tartozó felhasználókat, valamint a csatlakozási kérelmeket.';
$l['edit_user_group'] = 'Csoport szerkesztése';
$l['edit_user_group_desc'] = 'Itt tudod szerkeszteni a felhasználói csoportokat.';
$l['edit_group_leader'] = 'Csoport vezető szerkesztése';
$l['edit_group_leader_desc'] = 'Itt tudod beállítani a csoport vezető jogosultságait.';
$l['group_leaders'] = 'Csoport vezetők';
$l['delete_group'] = 'Csoport törlése';
$l['edit_group'] = 'Csoport szerkesztése';
$l['no_groups'] = 'Jelenleg nincsenek csoportok létrehozva a fórumon.';
$l['join_requests'] = 'Csatlakozási kérelem moderálása';
$l['update_groups_order'] = 'Csoport sorrend frissítése';
$l['reset'] = 'Visszaállít';
$l['number_of_users'] = 'Felhasználók száma';
$l['order'] = 'Sorrend';
$l['group'] = 'Csoport';
$l['custom_user_group'] = 'Saját felhasználói csoport';
$l['default_user_group'] = 'Alapértelmezett felhasználói csoport';
$l['join_requests_for'] = 'Csatlakozási kérelem a következő csoporthoz:';
$l['users'] = 'Felhasználók';
$l['reason'] = 'Ok';
$l['date_requested'] = 'Dátum';
$l['approve'] = 'Jóváhagy';
$l['deny'] = 'Elutasít';
$l['approve_selected_requests'] = 'Választott kérelmek jóváhagyása';
$l['deny_selected_requests'] = 'Választott kérelmek elutasítása';
$l['group_leaders_for'] = 'A következő csoport vezetői:';
$l['can_manage_members'] = 'Kezelheti a tagokat?';
$l['can_manage_join_requests'] = 'Kezelheti a csatlakozási kérelmeket?';
$l['can_invite_members'] = 'Kezelheti a meghívott tagokat?';
$l['user'] = 'Felhasználó';
$l['can_manage_group_members'] = 'Kezelheti a csoport felhasználóit?';
$l['can_manage_group_members_desc'] = 'Állítsd ezt az opciót \'Igen\'-re, ha azt szeretnéd, hogy ez a felhasználó kezelhesse a csoport tagjait.';
$l['can_manage_group_join_requests'] = 'Kezelheti a csoportos kérelmeket?';
$l['can_manage_group_join_requests_desc'] = 'Elfogadhatja vagy visszautasíthatja ez a felhasználó az új tagsági kérelmeket ehhez a csoporthoz?';
$l['can_invite_group_members'] = 'Kezelheti a meghívott csoport tagokat';
$l['can_invite_group_members_desc'] = 'Meghívhat új tagokat ez a felhasználó, hogy csatlakozzanak ehhez a csoporthoz?';
$l['add_group_leader'] = 'Vezető hozzáadása a következő csoporthoz:';
$l['save_group_leader'] = 'Mentés';
$l['edit_leader'] = 'Vezető szerkesztése:';
$l['title'] = 'Cím';
$l['short_description'] = 'Rövid leírás';
$l['username_style'] = 'Felhasználónév stílus';
$l['username_style_desc'] = 'Itt egy stílust tudsz a felhasználónévhez hozzáadni amely megkülönbözteti az ehhez a csoporthoz tartozó felhasználókat.  <strong>Használd a {username} tag-et.</strong>';
$l['user_title'] = 'Csoport becenév';
$l['user_title_desc'] = 'Ha nem adsz meg semmit, akkor a felhasználó rangját jeleníti meg, egyébként pedig amit ide beírsz.';
$l['do_not_copy_permissions'] = 'Ne másoljon jogosultságokat másik csoportból.';
$l['copy_permissions_from'] = 'Jogosultságok másolása...';
$l['copy_permissions_from_desc'] = 'Ha szeretnéd másolhatsz fórum és csoport jogosultságokat ide. Válassz egy csoportot a másoláshoz.';
$l['save_user_group'] = 'Mentés';
$l['list_users'] = 'Tagok Listázása';
$l['general'] = 'Általános';
$l['forums_posts'] = 'Fórumok és hozzászólások';
$l['users_permissions'] = 'Tagok és jogosultságok';
$l['misc'] = 'Egyéb';
$l['mod_cp'] = 'Moderátori vezérlőpult';
$l['stars'] = '# Csillagok';
$l['star_image'] = 'Csillag képe';
$l['user_stars'] = 'Csillagok száma';
$l['user_stars_desc'] = 'Ha megadod a csillag kép elérési útvonalát és számát akkor ez fog megjelenni. Ha különböző csillag képeket akarsz használni különböző témával, akkor használd a <strong>{theme}</strong> tag-et.';
$l['group_image'] = 'Csoport képe';
$l['group_image_desc'] = 'Itt tudsz beállítani egy külön képet a csoportnak, ami a hozzászólásokban jelenik meg. Kérlek használd a <strong>{lang}</strong> tag-et, amennyiben vannak lefordított csoport képek.';
$l['general_options'] = 'Általános Beállítások';
$l['member_list'] = 'Igen, jelenítse meg ennek a csoportnak a felhasználóit a tagok listáján';
$l['forum_team'] = 'Igen, mutassa ezt a csoportot a \'fórum vezetők\' oldalon.';
$l['is_banned_group'] = 'Igen, ez egy kitiltott csoport.<br /><small>Ha ez a csoport \'kitiltott\' felhasználói csoport, a felhasználók kitiltásra kerülnek ebben a csoportban.</small>';
$l['publicly_joinable_options'] = 'Csatlakozási Opciók';
$l['user_joinable'] = 'Igen, a felhasználók szabadon csatlakozhatnak vagy elhagyhatják a csoportot.';
$l['moderate_join_requests'] = 'Igen, minden csatlakozási kérelem először moderálásra kerül.<br /><small>Users must be able to freely join and leave this group for this to take effect.</small>';
$l['invite_only'] = 'Igen, ehhez a csoporthoz a felhasználó csak meghívóval tud csatlakozni.<br /><small>Users must be able to freely join and leave this group for this to take effect.</small>';
$l['can_set_as_display_group'] = 'Igen, felhasználók megjeleníthetik a csoportot.<br /><small>Ha ezt az opciót igen-re állítod, a felhasználók megjeleníthetik a csoportot rangjukként stb.</small>';
$l['moderation_administration_options'] = 'Moderációs/Adminisztrációs Opciók';
$l['is_super_mod'] = 'Igen, ehhez a csoporthoz tartozó felhasználók Szuper Moderátorok';
$l['can_access_mod_cp'] = 'Igen, ehhez a csoporthoz tartozó felhasználók hozzáférhetnek a Moderációs vezérlőpulthoz';
$l['can_access_admin_cp'] = 'Igen, ehhez a csoporthoz tartozó felhasználók hozzáférhetnek az Adminisztrátori vezérlőpulthoz';
$l['viewing_options'] = 'Megjelenítés';
$l['can_view_board'] = 'Megtekintheti az oldalt?';
$l['can_view_threads'] = 'Megtekintheti a témákat?';
$l['can_search_forums'] = 'Kereshet a fórumokban?';
$l['can_view_profiles'] = 'Megtekintheti a profilokat?';
$l['can_download_attachments'] = 'Letölthet csatolásokat?';
$l['can_view_board_closed'] = 'Megnézheti a fórumot, ha zárva van?';
$l['posting_rating_options'] = 'Hozzászólás/értékelés opciók';
$l['can_post_threads'] = 'Indíthat témát?';
$l['can_post_replies'] = 'Válaszolhat?';
$l['can_rate_threads'] = 'Értékelhet témákat?';
$l['moderation_options'] = 'Moderációs beállítások';
$l['mod_new_posts'] = 'Moderálhat új hozzászólásokat?';
$l['mod_new_threads'] = 'Moderálhat új témákat?';
$l['mod_new_attachments'] = 'Moderálhat új csatolmányokat?';
$l['mod_after_edit'] = 'Moderálhat szerkesztett hozzászólásokat?';
$l['poll_options'] = 'Szavazás opciók';
$l['max_posts_per_day'] = 'Maximális üzenet naponként';
$l['max_posts_per_day_desc'] = 'Itt adhatod meg, hogy hány hozzászólás engedélyezett felhasználónként naponta. Ha 0 akkor nincs limit.';
$l['can_post_polls'] = 'Indíthat szavazást?';
$l['can_vote_polls'] = 'Szavazhat?';
$l['can_undo_votes'] = 'Visszavonhat szavazatokat a szavazásokból?';
$l['attachment_options'] = 'Csatolás opciók';
$l['can_post_attachments'] = 'Csatolást adhat hozzászólásokhoz?';
$l['attach_quota'] = 'Csatolási limit:';
$l['attach_quota_desc'] = 'Itt adhatod meg, hogy a csoport összesen mennyi csatolást tölthet fel. Ha 0 akkor nincs limit.';
$l['editing_deleting_options'] = 'Szerkesztés/Törlés opciók';
$l['can_edit_posts'] = 'Szerkesztheti a saját hozzászólásait?';
$l['can_delete_posts'] = 'Törölheti a saját hozzászólásait?';
$l['can_delete_threads'] = 'Törölheti a saját témáit?';
$l['can_edit_attachments'] = 'Frissítheti a saját csatolásait?';
$l['account_management'] = 'Engedélyek - Fiók kezelés';
$l['edit_time_limit'] = 'Szerkesztési idő limit';
$l['edit_time_limit_desc'] = 'A percek száma amíg a általános felhasználók nem szerkeszthetik a saját hozzászólásaikat (ha van jogosultságuk). Ha 0 akkor nincs limit.';
$l['can_be_reported'] = 'Jelenthet?';
$l['can_access_usercp'] = 'Hozzáférhet a felhasználók Kezelőpultjához?';
$l['can_change_username'] = 'Megváltoztathatja a felhasználónevet?';
$l['can_change_website'] = 'Megváltoztathatja a weboldalt?';
$l['can_use_usertitles'] = 'Használhat becenevet?';
$l['can_upload_avatars'] = 'Feltölthet avatart?';
$l['can_use_signature'] = 'Hozzáadhat aláírást?';
$l['can_use_signature_posts'] = 'Hozzáadhat aláírást x hozzászólás után?';
$l['required_posts'] = 'Minimum hozzászólás az aláírás hozzáadásához:';
$l['required_posts_desc'] = 'Megadhatod, mennyi hozzászólásnak kell lennie ahhoz, hogy hozzáadhasson aláírást.';
$l['uses_no_follow'] = 'Aláírás linkekben engedélyezze a nofollow tag-et?';
$l['reputation_system'] = 'Értékelés rendszer';
$l['can_use_pms'] = 'Használhatja a privát üzenet szolgáltatást?';
$l['can_send_pms'] = 'Küldhet privát üzenetet?';
$l['can_track_pms'] = 'Privát üzenet visszaigazolás használata?';
$l['can_deny_reciept'] = 'Privát üzenet visszaigazolás megtagadás lehetősége?';
$l['can_override_pms'] = 'Küldhet privát üzeneteket még akkor is, ha a címzett tiltotta őket?';
$l['message_quota'] = 'Privát üzenet limit:';
$l['message_quota_desc'] = 'Itt adhatod meg, hogy a csoport tagjai mennyi PÜ-t tárolhatnak. Ha üres akkor nincs limit.';
$l['max_recipients'] = 'Üzenetenkénti címzettek maximális száma:';
$l['max_recipients_desc'] = 'Címzettek maximális száma. Ha üres akkor a felhasználó akárhány címzettnek küldhet egyszerre üzenetet.';
$l['show_reputations'] = 'Az ebbe a csoportba tartozó felhasználók értékelésének megjelenítése?';
$l['can_give_reputation'] = 'Adhat értékelést felhasználóknak?';
$l['points_to_award_take'] = 'Adható/elvehető pontok száma:';
$l['points_to_award_take_desc'] = 'Itt meg kell adnod egy összeget, hogy mennyi pont kerüljön jóváírásra vagy levonásra, ha a csoport felhasználói használják az  Értékelés opciót.';
$l['max_reputations_daily'] = 'Új értékelések naponta:';
$l['max_reputations_daily_desc'] = 'Itt határozhatod meg, hogy hányszor használhassa egy felhasználó az értékelés rendszert egy nap. 0-ra állítva nincs limit.';
$l['max_reputations_perthread'] = 'Értékelés hozzáadása témánként:';
$l['max_reputations_perthread_desc'] = 'Amikor az \'Értékelés hozzáadása témánként\' engedélyezve van, be tudod állítani a maximálisan adható értékelések számát, amelyet a csoport felhasználói ugyan annak a felhasználónak tudnak adni ugyan abban a témán belül. Írd be a lenti mezőbe ennek számát. Korlátlan számú értékelés adáshoz (ugyanannak a felhasználónak, ugyanazon témán belül) írj be 0 -át.';
$l['max_reputations_peruser'] = 'Értékelés hozzáadása felhasználónként:';
$l['max_reputations_peruser_desc'] = 'Hasonlóan az \'Hírnév adása témánként\'-hoz beállíthatsz egy maximum értékelés adás értéket, amelyet az ebben a csoportban lévő felhasználó adhat egy napon belül ugyan annak a felhasználónak. Korlátlan számú értékelés adásához (ugyanannak a felhasználónak) írj be 0-át.';
$l['warning_system'] = 'Figyelmeztető rendszer';
$l['can_send_warnings'] = 'Küldhet figyelmeztetést felhasználóknak?';
$l['can_receive_warnings'] = 'Kaphat figyelmeztetést felhasználóktól?';
$l['warnings_per_day'] = 'Maximum figyelmeztetések egy nap:';
$l['private_messaging'] = 'Privát üzenő rendszer';
$l['calendar'] = 'Naptár';
$l['can_view_calendar'] = 'Megtekintheti a naptárat?';
$l['can_post_events'] = 'Publikus eseményt adhat a naptárhoz?';
$l['can_bypass_event_moderation'] = 'Figyelmen kívül hagyhatja a publikus esemény moderációs sort?';
$l['can_moderate_events'] = 'Moderálhat publikus eseményeket?';
$l['whos_online'] = 'Ki van jelen';
$l['can_view_whos_online'] = 'Megtekintheti, hogy ki van jelen?';
$l['can_view_invisible'] = 'Rejtett felhasználókat is megtekintheti?';
$l['can_view_ips'] = 'Megtekintheti az Online felhasználók IP címét?';
$l['can_view_member_list'] = 'Megtekintheti a felhasználók listáját?';
$l['show_in_birthday_list'] = 'Megjelenhet a születésnap listán?';
$l['can_email_users'] = 'Küldhet témát barátoknak, és emailt felhasználóknak?';
$l['can_email_users_override'] = 'Küldhet emailt még akkor is, ha szerepel a mellőzöttek listáján????';
$l['max_emails_per_day'] = 'Maximum email naponta:';
$l['max_emails_per_day_desc'] = 'Az emailek maximum száma, melyeket a felhasználók küldhetnek az \'Email küldése felhasználóknak\' és a \'Téma elküldése egy barátnak\' opcióval.';
$l['email_flood_time'] = 'Email flood ideje:';
$l['email_flood_time_desc'] = 'A percek száma amíg egy felhasználónak várnia kell míg elküld egy másik emailt. Ha 0-a akkor nincs várakozási idő.';
$l['forum_post_options'] = 'Fórumok és Hozzászólások';
$l['user_options'] = 'Felhasználók';
$l['can_manage_announce'] = 'Kezelheti a közleményeket?<br /><small>Kérlek jegyezd meg, hogy a fórum moderátorokat hozzá kell rendelni legalább egy fórumhoz, hogy kezelhesse a közleményeket.</small>';
$l['can_manage_mod_queue'] = 'Kezelheti a moderációs sort?<br /><small>Kérlek jegyezd meg, hogy a fórum moderátorokat hozzá kell rendelni legalább egy fórumhoz, hogy kezelhesse a moderációs sort.</small>';
$l['can_manage_reported_content'] = 'Kezelheti a jelentett tartalmat?<br /><small>Kérlek jegyezd meg, hogy a fórum moderátorokat hozzá kell rendelni legalább egy fórumhoz, hogy kezelhesse a jelentett tartalmat.</small>';
$l['can_view_mod_logs'] = 'Megnézheti a moderátori naplókat?<br /><small>Kérlek jegyezd meg, hogy a fórum moderátorokat hozzá kell rendelni legalább egy fórumhoz, hogy megnézhesse a moderátori naplókat.</small>';
$l['can_edit_profiles'] = 'Szerkesztheti a profilokat?<br /><small>Kérlek jegyezd meg, hogy a fórum moderátorok nem szerkeszthetik a szuper moderátorok vagy adminisztrátorok profilját függetlenül ettől az engedélytől.</small>';
$l['can_ban_users'] = 'Kitilthat felhasználókat?<br /><small>Kérlek jegyezd meg, hogy a fórum moderátorok nem tilthatják ki a szuper moderátorokat vagy adminisztrátorokat függetlenül ettől az engedélytől.</small>';
$l['can_view_warnlogs'] = 'Megnézheti a figyelmeztetési naplókat?';
$l['can_use_ipsearch'] = 'Használhatja az IP cím keresést?';
$l['outstanding_join_request'] = 'kezelésre váró csatlakozási kérelem.';
$l['no_join_requests'] = 'Jelenleg nincs kezelésre váró csatlakozási kérelem.';
$l['no_assigned_leaders'] = 'Még nem adtál vezetőt ehhez a csoporthoz. A vezető hozzáadásához töltsd ki az alábbi űrlapot.';
$l['error_missing_title'] = 'Nem adtad meg a nevét az új felhasználói csoportnak.';
$l['error_invalid_user_group'] = 'Érvénytelen felhasználói csoportot választottál.';
$l['error_invalid_join_request'] = 'Érvénytelen csatlakozási kérelmet választottál.';
$l['error_invalid_username'] = 'A megadott felhasználónév érvénytelen.';
$l['error_already_leader'] = 'A felhasználó már vezetője ennek a csoportnak.';
$l['error_invalid_group_leader'] = 'Érvénytelen csoport vezetőt adtál meg.';
$l['error_missing_namestyle_username'] = 'A felhasználónév stílusnak tartalmaznia kell a következőt: {username}';
$l['error_disallowed_namestyle_username'] = 'Nem használhatsz scriptet, meta vagy base tag-eket a felhasználónév stílusban.';
$l['error_default_group_delete'] = 'Az alapértelmezett csoportok nem törölhetőek';
$l['error_cannot_have_both_types'] = 'Nem csatlakozhat olyan csoporthoz, amely egyszerre moderált és csak meghívóval lehet a csoporthoz csatlakozni.Kérlek az egyiket vagy a másikat válaszd.???';
$l['success_group_created'] = 'Az új felhasználói csoport létrehozva.';
$l['success_group_updated'] = 'A felhasználói csoport frissítve.';
$l['success_group_deleted'] = 'A felhasználói csoport törölve.';
$l['success_groups_disporder_updated'] = 'A felhasználói csoport megjelenítési sorrendje frissítve.';
$l['success_join_request_approved'] = 'A csatlakozási kérelem jóváhagyva. A felhasználó most már a csoport tagja.';
$l['success_join_request_denied'] = 'A csatlakozási kérelem elutasítva.';
$l['success_selected_requests_approved'] = 'A csatlakozási kérelem jóváhagyva. A felhasználó most már a csoport tagja.';
$l['success_selected_requests_denied'] = 'A csatlakozási kérelem elutasítva.';
$l['success_user_made_leader'] = 'hozzáadva a csoporthoz mint vezető';
$l['success_group_leader_updated'] = 'A csoport vezető adatai frissítve.';
$l['success_group_leader_deleted'] = 'A felhasználó eltávolítva a csoport vezető listáról.';
$l['confirm_group_deletion'] = 'Biztos, hogy törölni szeretnéd ezt a felhasználói csoportot?';
$l['confirm_group_leader_deletion'] = 'Biztos, hogy törölni szeretnéd ezt a csoport vezetőt?';
$l['can_delete_own_reputation'] = 'Törölheti saját adott hírneveit?';
$l['make_user_member'] = 'Taggá teszed a felhasználót?';
$l['make_user_member_desc'] = 'Hozzá legyen adva ez a felhasználó, mint ennek a csoportnak a tagja, ha már ők megteték?';
$l['can_view_deletion_notices'] = 'Megnézheti a törlési közleményeket?';
$l['success_group_created_duplicate_title'] = 'Az új felhasználói csoport sikeresen létrehozva. Kérlek vedd figyelembe, hogy több felhasználói csoport van a "{1}" néven.';
$l['success_group_updated_duplicate_title'] = 'A kiválasztott felhasználói csoport sikeresen frissítve. Kérlek vedd figyelembe, hogy több felhasználói csoport van a "{1}" néven.';
