<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Hungarian
// Author of the language pack : Sz.Gábor
// Language pack translators website : http://forum.rkalltablets.info
// Compatible version of MyBB : 1804
// Last edited in MyBB Editor by : Sz.Gábor
// Last edited date : Fri, 10 Apr 2015 11:25:43 +0000
// --------------------------------------------------------------------------------

$l['admin_permissions'] = 'Admin jogosultságok';
$l['user_permissions'] = 'Felhasználói jogosultságok';
$l['user_permissions_desc'] = 'Itt tudod kezelni az adminisztrátori jogosultságokat felhasználónként. Ezzel az opcióval megakadályozhatod, hogy egyes adminisztrátorok hozzáférjenek az adminisztrációs panel bizonyos részeihez.';
$l['group_permissions'] = 'Csoportos Jogosultságok';
$l['group_permissions_desc'] = 'Az adminisztrátor jogokat csoportokra is ki lehet terjeszteni.';
$l['default_permissions'] = 'Alapértelmezett jogosultságok';
$l['default_permissions_desc'] = 'Az alapértelmezett jogosultságok azokra vonatkoznak akik nem rendelkeznek külön meghatározott jogosultságokkal, vagy a jogosultságuk nem öröklődik egy másik csoportból.h';
$l['admin_permissions_updated'] = 'Az admin jogosultságok frissítve.';
$l['revoke_permissions'] = 'Jogok visszavonása';
$l['edit_permissions'] = 'Jogok szerkesztése';
$l['set_permissions'] = 'Jogok beállítása';
$l['edit_permissions_desc'] = 'Itt részletesen be tudod állítani a jogosultságokat.';
$l['update_permissions'] = 'Jogok frissítése';
$l['view_log'] = 'Napló megtekintése';
$l['permissions_type_group'] = 'Jogosultság típusa ennek a csoportnak';
$l['permissions_type_user'] = 'Jogosultság típusa ennek a felhasználónak';
$l['no_group_perms'] = 'Jelenleg nincsenek csoportos jogok beállítva.';
$l['no_user_perms'] = 'Jelenleg nincsenek felhasználói jogosultságok beállítva.';
$l['edit_user'] = 'Felhasználói profil szerkesztése';
$l['using_individual_perms'] = 'Egyéni jogosultságok használata';
$l['using_custom_perms'] = 'Szokásos jogosultságok használata';
$l['using_group_perms'] = 'Csoportos jogosultságok használata';
$l['using_default_perms'] = 'Alapértelmezett jogosultságok használata';
$l['last_active'] = 'Utoljára aktív';
$l['user'] = 'Felhasználó';
$l['edit_group'] = 'Csoport szerkesztése';
$l['default'] = 'Alapértelmezett';
$l['group'] = 'Csoport';
$l['error_super_admin'] = '???Ez a művelet nem engedélyezett. A módosítani kívánt felhasználó Szuper Adminisztrátor.<br /><br />A művelet végrehajtásához a felhasználói azonosítódat hozzá kell adnod a Szuper adminisztrátori listához az inc/config.php fájlban.';
$l['error_delete_no_uid'] = 'Nem adtad meg az azonosítót.';
$l['error_delete_invalid_uid'] = 'Nem adtál meg érvényes azonosítót';
$l['success_perms_deleted'] = 'A Jogosultság sikeresen visszavonva.';
$l['confirm_perms_deletion'] = 'Biztos, hogy vissza szeretnéd vonni ezt a jogosultságot?';
$l['confirm_perms_deletion2'] = 'Biztos, hogy vissza szeretnéd vonni a felhasználó jogosultságait?';
